### ISSUE TITLE
layered chart loosing x-axis sort order

### ISSUE THREAD

**Issue by afonit** [vega/vega-lite#3566] opened 2018-03-22 13:46 UTC
I am bringing this issue over from altair:
https://github.com/altair-viz/altair/issues/549

the x axis should be sorted as
'3_weeks_prior', '3_weeks_post', '6_weeks_prior',
        '6_weeks_post', '9_weeks_prior', '9_weeks_post'

In the single plot example - that happens, but then `in the layered plot` it **swaps the prior and post positions**.

Please let me know if there is a better way to link to an example than just pasting a wall of text in here.
Here is the non layered working example:

![image](https://user-images.githubusercontent.com/1798497/37773957-591f1dd4-2db5-11e8-8bde-c4958149f3af.png)

```json
{
  "config": {
    "view": {
      "width": 400,
      "height": 300
    }
  },
  "mark": "bar",
  "data": {
    "values": [
      {
        "actual_color": "#58D68D",
        "location": "ab14",
        "m_color": 0,
        "m_sorting": 0,
        "period": "3_weeks_prior",
        "period_after": "3_weeks_post",
        "rate": 0.051948,
        "size": 3,
        "size_after": 3
      },
      {
        "actual_color": "#58D68D",
        "location": "ab14",
        "m_color": 0,
        "m_sorting": 1,
        "period": "3_weeks_post",
        "period_after": "",
        "rate": 0.012821,
        "size": 3,
        "size_after": ""
      },
      {
        "actual_color": "#F5B041",
        "location": "ab14",
        "m_color": 1,
        "m_sorting": 2,
        "period": "6_weeks_prior",
        "period_after": "6_weeks_post",
        "rate": 0.01633,
        "size": 6,
        "size_after": 6
      },
      {
        "actual_color": "#F5B041",
        "location": "ab14",
        "m_color": 1,
        "m_sorting": 3,
        "period": "6_weeks_post",
        "period_after": "",
        "rate": 0.090129,
        "size": 6,
        "size_after": ""
      },
      {
        "actual_color": "#D7DF01",
        "location": "ab14",
        "m_color": 2,
        "m_sorting": 4,
        "period": "9_weeks_prior",
        "period_after": "9_weeks_post",
        "rate": 0.100279,
        "size": 9,
        "size_after": 6
      },
      {
        "actual_color": "#D7DF01",
        "location": "ab14",
        "m_color": 2,
        "m_sorting": 5,
        "period": "9_weeks_post",
        "period_after": "",
        "rate": 0.016212,
        "size": 6,
        "size_after": ""
      }
    ]
  },
  "encoding": {
    "color": {
      "type": "nominal",
      "field": "actual_color",
      "legend": null
    },
    "x": {
      "type": "nominal",
      "axis": {
        "labelAngle": -45
      },
      "field": "period",
      "sort": {
        "op": "sum",
        "field": "m_sorting"
      }
    },
    "y": {
      "type": "quantitative",
      "axis": {
        "format": "%"
      },
      "field": "rate"
    }
  },
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json"
}
```

When I put in more layers the x-axis sort does not seem to be respected.
![image](https://user-images.githubusercontent.com/1798497/37774031-80cc3b3c-2db5-11e8-9d1d-f1be1bb573d6.png)

```json
{
  "config": {
    "view": {
      "width": 400,
      "height": 300
    }
  },
  "layer": [
    {
      "mark": "bar",
      "data": {
        "values": [
          {
            "actual_color": "#58D68D",
            "location": "ab14",
            "m_color": 0,
            "m_sorting": 0,
            "period": "3_weeks_prior",
            "period_after": "3_weeks_post",
            "rate": 0.051948,
            "size": 3,
            "size_after": 3
          },
          {
            "actual_color": "#58D68D",
            "location": "ab14",
            "m_color": 0,
            "m_sorting": 1,
            "period": "3_weeks_post",
            "period_after": "",
            "rate": 0.012821,
            "size": 3,
            "size_after": ""
          },
          {
            "actual_color": "#F5B041",
            "location": "ab14",
            "m_color": 1,
            "m_sorting": 2,
            "period": "6_weeks_prior",
            "period_after": "6_weeks_post",
            "rate": 0.01633,
            "size": 6,
            "size_after": 6
          },
          {
            "actual_color": "#F5B041",
            "location": "ab14",
            "m_color": 1,
            "m_sorting": 3,
            "period": "6_weeks_post",
            "period_after": "",
            "rate": 0.090129,
            "size": 6,
            "size_after": ""
          },
          {
            "actual_color": "#D7DF01",
            "location": "ab14",
            "m_color": 2,
            "m_sorting": 4,
            "period": "9_weeks_prior",
            "period_after": "9_weeks_post",
            "rate": 0.100279,
            "size": 9,
            "size_after": 6
          },
          {
            "actual_color": "#D7DF01",
            "location": "ab14",
            "m_color": 2,
            "m_sorting": 5,
            "period": "9_weeks_post",
            "period_after": "",
            "rate": 0.016212,
            "size": 6,
            "size_after": ""
          }
        ]
      },
      "encoding": {
        "color": {
          "type": "nominal",
          "field": "actual_color",
          "legend": null
        },
        "x": {
          "type": "nominal",
          "axis": {
            "labelAngle": -45
          },
          "field": "period",
          "sort": {
            "op": "sum",
            "field": "m_sorting"
          }
        },
        "y": {
          "type": "quantitative",
          "axis": {
            "format": "%"
          },
          "field": "rate"
        }
      }
    },
    {
      "mark": {
        "type": "line",
        "color": "black"
      },
      "data": {
        "values": [
          {
            "actual_color": "#58D68D",
            "location": "ab14",
            "m_color": 0,
            "m_sorting": 0,
            "period": "3_weeks_prior",
            "period_after": "3_weeks_post",
            "rate": 0.051948,
            "size": 3,
            "size_after": 3
          },
          {
            "actual_color": "#58D68D",
            "location": "ab14",
            "m_color": 0,
            "m_sorting": 1,
            "period": "3_weeks_post",
            "period_after": "",
            "rate": 0.012821,
            "size": 3,
            "size_after": ""
          },
          {
            "actual_color": "#F5B041",
            "location": "ab14",
            "m_color": 1,
            "m_sorting": 2,
            "period": "6_weeks_prior",
            "period_after": "6_weeks_post",
            "rate": 0.01633,
            "size": 6,
            "size_after": 6
          },
          {
            "actual_color": "#F5B041",
            "location": "ab14",
            "m_color": 1,
            "m_sorting": 3,
            "period": "6_weeks_post",
            "period_after": "",
            "rate": 0.090129,
            "size": 6,
            "size_after": ""
          },
          {
            "actual_color": "#D7DF01",
            "location": "ab14",
            "m_color": 2,
            "m_sorting": 4,
            "period": "9_weeks_prior",
            "period_after": "9_weeks_post",
            "rate": 0.100279,
            "size": 9,
            "size_after": 6
          },
          {
            "actual_color": "#D7DF01",
            "location": "ab14",
            "m_color": 2,
            "m_sorting": 5,
            "period": "9_weeks_post",
            "period_after": "",
            "rate": 0.016212,
            "size": 6,
            "size_after": ""
          }
        ]
      },
      "encoding": {
        "detail": {
          "type": "quantitative",
          "field": "m_color"
        },
        "x": {
          "type": "ordinal",
          "axis": {
            "grid": false,
            "labelAngle": -45
          },
          "field": "period",
          "sort": {
            "op": "sum",
            "field": "m_sorting"
          }
        },
        "y": {
          "type": "quantitative",
          "axis": {
            "grid": false,
            "title": "# Months in data"
          },
          "field": "size"
        }
      }
    },
    {
      "mark": {
        "type": "point",
        "color": "black"
      },
      "data": {
        "values": [
          {
            "actual_color": "#58D68D",
            "location": "ab14",
            "m_color": 0,
            "m_sorting": 0,
            "period": "3_weeks_prior",
            "period_after": "3_weeks_post",
            "rate": 0.051948,
            "size": 3,
            "size_after": 3
          },
          {
            "actual_color": "#58D68D",
            "location": "ab14",
            "m_color": 0,
            "m_sorting": 1,
            "period": "3_weeks_post",
            "period_after": "",
            "rate": 0.012821,
            "size": 3,
            "size_after": ""
          },
          {
            "actual_color": "#F5B041",
            "location": "ab14",
            "m_color": 1,
            "m_sorting": 2,
            "period": "6_weeks_prior",
            "period_after": "6_weeks_post",
            "rate": 0.01633,
            "size": 6,
            "size_after": 6
          },
          {
            "actual_color": "#F5B041",
            "location": "ab14",
            "m_color": 1,
            "m_sorting": 3,
            "period": "6_weeks_post",
            "period_after": "",
            "rate": 0.090129,
            "size": 6,
            "size_after": ""
          },
          {
            "actual_color": "#D7DF01",
            "location": "ab14",
            "m_color": 2,
            "m_sorting": 4,
            "period": "9_weeks_prior",
            "period_after": "9_weeks_post",
            "rate": 0.100279,
            "size": 9,
            "size_after": 6
          },
          {
            "actual_color": "#D7DF01",
            "location": "ab14",
            "m_color": 2,
            "m_sorting": 5,
            "period": "9_weeks_post",
            "period_after": "",
            "rate": 0.016212,
            "size": 6,
            "size_after": ""
          }
        ]
      },
      "encoding": {
        "detail": {
          "type": "quantitative",
          "field": "m_color"
        },
        "size": {
          "value": 207
        },
        "x": {
          "type": "ordinal",
          "axis": {
            "grid": false,
            "labelAngle": -45
          },
          "field": "period",
          "sort": {
            "op": "sum",
            "field": "m_sorting"
          }
        },
        "y": {
          "type": "quantitative",
          "axis": {
            "grid": false,
            "title": "# Months in data"
          },
          "field": "size"
        }
      }
    }
  ],
  "resolve": {
    "scale": {
      "y": "independent",
      "x": "shared",
      "color": "shared"
    }
  },
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json"
}
```

**Comment by kanitw** [comment] 2018-03-22 15:16
Could you please use some editor (e.g., VSCode or our online vega editor) to re-format the JSON and add back ticks?  (Pasting code in this form is very hard to read.)

**Comment by afonit** [comment] 2018-03-22 15:34
@kanitw thanks for answering my question of:
"Please let me know if there is a better way to link to an example than just pasting a wall of text in here."
I did paste this from the vega editor online, I also added the ```json ``` (backticks?).
Please let me know if this is what you were looking for. (I just edited my first post)

**Comment by kanitw** [comment] 2018-03-22 19:47
I think this is a duplicate of https://github.com/vega/vega-lite/issues/2177, but I'll let @domoritz double check before closing.

**Comment by domoritz** [comment] 2018-03-22 19:50
Yes, it's the same issue. Sorting by the sum of a field will not work in Vega-Lite because of a limitation in Vega.

**Closed** 2018-03-22 20:13 UTC
