### ISSUE TITLE
Any way to bind a mark property value to a selection?

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega-lite#3570] opened 2018-03-25 23:20 UTC
I am trying to set the opacity of a mark based on the value of an input range slider [0-1]. I know this is fairly straightforward in Vega, but is there a way to do this in Vega-Lite?

**Comment by kanitw** [comment] 2018-03-26 00:27
Yeah, we want to make this easy in Vega-Lite too, but there is no easy to map signal values to mark properties / encoding channel yet. 

I think this is a duplicate of https://github.com/vega/vega-lite/issues/3338 so I'll close this for now.   Feel free to reopen if you disagree.

**Closed by kanitw** 2018-03-26 00:27 UTC
