### ISSUE TITLE
Legends occupying more space in the Chart Area.

### ISSUE THREAD

**Issue by jerinjjose** [vega/vega-lite#6384] opened 2020-04-21 06:23 UTC
When There are more Legends to be displayed in the Chart. It is taking more area and the Chart becomes very less area using. 

I am wondering if any way to specify the Legend Area width and Height So that if the number of legends is more means, it can create a scroll bar and scrollable within that specific area. So Chart Size always remains the same. 

Please find the attachment for the More Info. 

![488ce8cf-65e2-4f37-8f6f-553d08f34eb6](https://user-images.githubusercontent.com/10355174/79831922-fe82c380-83c5-11ea-9eaf-a1a1b66bfbf6.png)

Note: I am using Angular for vegalite & Using Vega Embed I am rendering.

**Comment by domoritz** [comment] 2020-04-21 17:43
I think this is a feature request. By design, Vega renders to a canvas or SVG and therefore we cannot have scroll areas. We would need to change Vega to support multiple outputs that can be laid out in HTML. Since we would need support in Vega, I'm closing the feature request here.

**Comment by domoritz** [comment] 2020-04-21 17:43
Marked as blocked by necessary Vega changes.

**Closed by domoritz** 2020-04-21 17:43 UTC
Labels: Feature Request :raising_hand_woman:

**Comment by sfc-gh-tteixeira** [comment] 2025-12-12 20:48
Would it be possible to do something like [this](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAGyUAVhDYA7EABoQAEzjQATjRyZ289AEEABMNlxDsJOsyGA7nRiGk5hhExsEhmG00AvOZiRBQw02QUEkJkEzKLI4WWVzGEtrJjhBNhtDOkpFEGIoOSgkTDQAbVA7ZXo0AHYABjqleBoyLDQAZgalHUwotBAAJSR490MAEWKnADNvQwBGBsMAYTYGWUxNNVzlSbRQCDgARwY4qDg9kFdktEbLtxw0ACYG26QIfoPDgH0aZRAAX3+3XUwwgM3UCDKoCKgigDHCmHO6AA5Cs1hsAJ6GZGGADUhgAFDtMAwEJRPj8EgBSeYNACUuTe-QK6PUGIBCmhgThCKRICm6W8ROKpPJR0phgItLqDKUTPQOgQ5yBXNh8OKfJBIwQBNlIHleUCJwBAF0lMh1ABrC6YDE4Pk4Ng0da5KY0MJwP6oDYnIEgU5sZTOsgXAAeFzdaS9IEV526dr5x2GPWKNFIuR6fXQABUaErDABlREPP3s1CgSOCaPEI1xmMJ-pJ9Z0VPp7p0LODYbKUYANVrHJABXS6gjNCjzNW6zZGYb6Fk7mdgVyMTiXtk8MEfrcoR0D1Q5X546rk9Z7JVR4n6BrgmNSnByBK6EojympsBnJAlWqqHqt2arRPgArLcxDjjYFyuOobCWnyGygjglhxCUfrEig5aXEcJyyGckEBFYNxKK4bD7gsrzvOgq7xJSALblqYLeJCB6qjyGr9KiU6YtieKGMSopUcoNFyhRQ6cTO-xmv6OGBsGYZjleIACUJ9b2o2DDJi2OhtvqoY0BRG5hERMJIqAPbIM6ZSNAsklarEZRAQof4mh+IBlqZIpMbctqqegTYplpdZILp+mbkZgQmSo7hIBZB78HMChzM5LnhBicCjsxIAWtaGHeXyUA0OoUB9ERNA+EiZFKCRSD5baaBzH6AZBrIIYYcO3jySe6AstO7JKAJaAGVufqISCCAUYeshIEq-RKYh8hEWkcBQE+oC5f0zqIuoN65I1wbjSA4aSX47hoFMgQHH6TDOtG0Dhe8EkXllNpzjGcChiUcrCGQeiKXAUwfSo4aoAs97+AWpXlfVSi7c1NpvStl6daJZ6Dm16WgDexroJE1XWoCD02WooTphht1ZtCoTtegEBJOonq0f8QA), instead?

Try dragging the legend side to side.

Edit: Actually I'm posting [here](https://github.com/vega/vega/issues/2334#issuecomment-3648121492). Seems like a better place to follow up on this!
