### ISSUE TITLE
header labelOrient bottom does not place labels below chart

### ISSUE THREAD

**Issue by MakoSDV** [vega/vega-lite#6938] opened 2020-10-07 16:47 UTC
Setting "labelOrient" to "bottom" in the "header" for a "column" shifts the labels below the top of the chart instead of below the entire chart.

Tested using the online [Vega Editor](https://vega.github.io/editor/#/edited): Vega 5.17.0, Vega-Lite 4.16.8, Vega-Tooltip 0.24.2, Editor 0.89.0

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {"url": "data/population.json"},
  "transform": [
    {"filter": "datum.year == 2000"},
    {"calculate": "datum.sex == 2 ? 'Female' : 'Male'", "as": "gender"}
  ],
  "width": {"step": 12},
  "mark": "bar",
  "encoding": {
    "column": {
      "field": "age",
      "type": "ordinal",
      "spacing": 10,
      "header": {"titleOrient": "bottom", "labelOrient": "bottom"}
    },
    "y": {
      "aggregate": "sum",
      "field": "people",
      "title": "population",
      "axis": {"grid": false}
    },
    "x": {"field": "gender", "axis": {"title": ""}},
    "color": {"field": "gender", "scale": {"range": ["#675193", "#ca8861"]}}
  },
  "config": {"view": {"stroke": "transparent"}, "axis": {"domainWidth": 1}}
}
```
![image](https://user-images.githubusercontent.com/26930776/95361809-31991080-089b-11eb-827b-e46bb3df0e91.png)

**Comment by kanitw** [comment] 2021-01-04 09:19
Duplicate of https://github.com/vega/vega-lite/issues/6960

**Closed by kanitw** 2021-01-04 09:19 UTC
Labels: Bug :bug:
