### ISSUE TITLE
`rule` marks do not appear to align perfectly with tick marks

### ISSUE THREAD

**Issue by g3o2** [vega/vega-lite#3429] opened 2018-03-01 15:08 UTC
If, in this [example](https://vega.github.io/vega-lite/examples/bar_aggregate.html), the `bar` mark is replaced by `rule`, the tick mark does not align with the rule.

```javascript
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A bar chart showing the US population distribution of age groups in 2000.",
  "data": { "url": "data/population.json"},
  "transform": [{"filter": "datum.year == 2000"}],
  "mark": "rule",
  "encoding": {
    "y": {
      "field": "age", "type": "ordinal",
      "scale": {"rangeStep": 17}
    },
    "x": {
      "aggregate": "sum", "field": "people", "type": "quantitative",
      "axis": {"title": "population"}
    }
  }
}
```

![image](https://user-images.githubusercontent.com/12123506/36851226-0b40341a-1d69-11e8-9d26-0c82a05a2fd2.png)

For this particular graph, the working solution to this issue is to use the `bar` mark instead with the `size` encoding channel set to a small value. However, it is probably not a general workaround.

```javascript
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A bar chart showing the US population distribution of age groups in 2000.",
  "data": { "url": "data/population.json"},
  "transform": [{"filter": "datum.year == 2000"}],
  "mark": "bar",
  "encoding": {
    "y": {
      "field": "age", "type": "ordinal",
      "scale": {"rangeStep": 17}
    },
    "x": {
      "aggregate": "sum", "field": "people", "type": "quantitative",
      "axis": {"title": "population"}
    },
    "size": { "value": 1 }
  }
}
```

![image](https://user-images.githubusercontent.com/12123506/36851754-49acb6be-1d6a-11e8-8952-d7ed35fd7ec8.png)

**Comment by domoritz** [comment] 2018-03-01 19:42
@g3o2 Good catch. Could you look at the generated Vega and see what we should generate differently?

**Comment by g3o2** [comment] 2018-03-02 16:48
After some analysis, I think that the following changes make a difference for this particular example:
* use `scale.type: band` instead of `scale.type: point` for the y scale;
* add `"band": 0.5` to the y encoding channel.

Nonetheless, the result is much better though not 100%.

![image](https://user-images.githubusercontent.com/12123506/36910605-878af3f6-1e41-11e8-8bb2-c8ff9dcd6a7b.png)

**Comment by kanitw** [comment] 2018-03-04 04:11
This is weird. 

cc: @jheer --  I wonder if you have any idea why rule is off by 1-pixel for point scale.  (Is it a vega bug?)

**Comment by jheer** [comment] 2018-03-05 17:37
The discrepancy is primariy a result of differences between stroked and filled shapes. Axis ticks are stroked, and so by default are "off" by 0.5. The [ViewLayout](https://github.com/vega/vega-view-transforms/blob/master/src/ViewLayout.js#L239) operator compensates by biasing axis groups by 0.5 pixels so that the ticks fall _within_ a pixel rather than on a pixel _boundary_, thus also better aligning with filled shapes.

In this case, the point scale operates independently. If Vega-Lite emits a y encoding channel `offset` of 0.5 then things should be brought back into harmony. However, this does not work in this situation because the default `tickRound: true` config option causes the axis ticks to be rounded to the nearest pixel by default, but the point scale does not do this for the plotted rule marks. Setting `tickRound: false` in the config (or, setting `round: true` for the y-scale) and adding the 0.5 offset will cause everything to align.

I know this is annoying, but after much experimentation in the past couple years this setup still seems to provide the best default behavior for a range of Vega charts...

**Comment by kanitw** [comment] 2018-03-05 18:20
@jheer Thanks for your explanation.  

I see.  Another possible easy solution for Vega-Lite is to make `band` scale the default scale for rule instead of `point`.  (It's a bit weird to use band, but the result is better.  So I wonder it we should just do that.)

**Comment by domoritz** [comment] 2018-03-05 18:38
What happens if we set the size of a tick with a band scale (I know it's not a good idea but it is possible).

**Comment by kanitw** [comment] 2018-03-05 18:56
> What happens if we set the size of a tick with a band scale (I know it's not a good idea but it is possible).

"tick" here in this issue is axis tick, not the tick mark?

**Comment by domoritz** [comment] 2018-03-05 19:01
Sorry, I meant size of rules.

**Comment by kanitw** [comment] 2018-03-05 19:08
The problem is not the size, but rather the x/y position.

**Comment by g3o2** [comment] 2018-03-06 07:23
Yet, another (design) solution in this special case is to drop the axis tick marks. Certainly not satisfactory for fiends of tick marks but still a perfectly aesthetic and valid solution.

**Comment by kanitw** [comment] 2018-03-10 16:09
@jheer @domoritz Any objection if I make band scale the default scale for rule instead of point. 
(It should solve this problem.)

**Comment by jheer** [comment] 2018-03-10 21:32
Not that I can think of.

**Comment by kanitw** [comment] 2018-03-11 05:14
Fixed in https://github.com/vega/vega-lite/pull/3508

**Closed by kanitw** 2018-03-11 05:14 UTC
