### ISSUE TITLE
The zoomable scatterplot only zooms in one direction. 

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#3347] opened 2018-02-01 18:36 UTC
See https://vega.github.io/vega-lite/examples/interactive_splom.html

![zoom](https://user-images.githubusercontent.com/589034/35696230-ca38c9c0-073b-11e8-98ab-5112631c95e2.gif)

**Comment by domoritz** [comment] 2018-02-01 18:37
CC @jakevdp

**Comment by arvind** [comment] 2018-02-01 19:01
Duplicate of #3321.

**Closed by arvind** 2018-02-01 19:01 UTC
Labels: Bug
