### ISSUE TITLE
Implements `visible` encoding channel

### ISSUE THREAD

**Issue by christophe-petitjean** [vega/vega-lite#5875] opened 2020-02-08 23:57 UTC
I look everywhere but I didn't find something about this. 

My use case : make marks visible or not depending on condition/field.

I know I can add an `opacity` channel and configure a scale on it (by default opacity scale doesn't go to 0) to do this but then I can't use `opacity` for something else. I think `opacity` and `visible` channels should coexist.

**Comment by domoritz** [comment] 2020-02-09 00:06
Can you set the opacity to 0 for data you want to hide and otherwise scale it?

**Comment by domoritz** [comment] 2020-02-09 00:08
Can we close this as a duplicate of https://github.com/vega/vega/issues/1539? I think we need support in Vega first before we add a new channel to Vega-Lite.

**Comment by jakevdp** [comment] 2020-02-09 01:32
You can make the opacity encoding conditioned on data values using https://vega.github.io/vega-lite/docs/condition.html

**Comment by domoritz** [comment] 2020-02-09 16:51
I'm going to close this issue until we have some clarity about what's needed and whether we need changes from the Vega side.

**Closed by domoritz** 2020-02-09 16:51 UTC
Labels: Feature Request :raising_hand_woman:

**Comment by christophe-petitjean** [comment] 2020-02-09 18:45
Yes, it's probably the road to go (add a condition on opacity channel) but it seems a little hacky for me :) Thanks for your answers!

**Comment by domoritz** [comment] 2020-02-09 20:33
I'm happy to consider the addition of a new channel but I first want to know whether filter is sufficient and what the design space looks like.

**Comment by kanitw** [comment] 2020-02-10 19:23
In any case, we better do this in Vega first anyway.
