### ISSUE TITLE
Setting axis.translate causes axes to not align with data

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#6030] opened 2020-03-07 14:58 UTC
Setting ``axis.translate`` causes data to no longer align with the axis ([vega editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4zEgN1gGwK4FMBnFMAbXQA8SBGAXwBo1IrUAmWgXQfCgFtYATgGsSkAA4B7AJYA7eJHo9I+GQGMJ0WQHMSoCBGa6e+qPACeY-KICOuWHKmJ4UjFcUmDAMyn5s0UVTuHpCEqjhWqOjQEvyyJKTUjKwcjJAyUqoRYJ44hPi0xmDcJpBmRh6mFlmQtvbOTi5uhV4+fgEKzVCh4bowMbBxqAlJKVDpmSQ52HkFJrNFQZDqMt46kYWYPgDuvYTwAhJCWTK42NjF+pCwFFKEABq9+-aE2AhZ1AAMFwbXtwCajwEz1e8CyAFpPvMCrQgA)):
```json
{
  "data": {"values": [{"x": 1}, {"x": 2}]},
  "mark": "point",
  "encoding": {
    "x": {
      "type": "quantitative",
      "field": "x",
      "scale": {"domain": [1, 2], "nice": false}
    },
    "y": {
      "type": "quantitative",
      "field": "x",
      "scale": {"domain": [1, 2], "nice": false}
    }
  },
  "config": {
    "view": {"stroke": null},
    "axisX": {"translate": 10},
    "axisY": {"translate": -10}
  }
}
```
![visualization - 2020-03-07T065708 149](https://user-images.githubusercontent.com/781659/76145721-e129ae00-6040-11ea-88c1-75f826ff028c.png)

I would expect x-axis translation to be vertical, and y-axis translation to be horizontal, so that the data still aligns with the axis.

**Comment by kanitw** [comment] 2020-03-07 18:33
This property is designed to align stroked line with the pixel grid, so a reasonable value is usually just either `0.5` or `0`.  So I think this is working as intended. 

There is also the `offset` property, which is probably for the following purpose: 

> I would expect x-axis translation to be vertical, and y-axis translation to be horizontal, so that the data still aligns with the axis.

I do think that these two names aren't descriptive about their differences, but I also don't have a better idea / think it's worth introducing a breaking change. Thus, I'll close this for now. 



If you have a suggestion how the behavior should be changed, please file an issue in Vega since this is directly a Vega property and VL does nothing special about it.

**Closed by kanitw** 2020-03-07 18:33 UTC
Labels: Bug :bug:

**Comment by jakevdp** [comment] 2020-03-07 19:25
Ah, thanks for the clarification
