### ISSUE TITLE
Stacking spec does not render correctly against vega master

### ISSUE THREAD

**Issue by mprudhom** [vega/vega-lite#1162] opened 2016-02-20 21:36 UTC
I don't know what the policy is on tracking the vega master branch, but vega-lite specs that use stacking don't appear to be rendering properly.

The vega spec `stacked.vg.json` produced with:

```
./bin/vl2vg -p examples/specs/stacked_bar_v.json > stacked.vg.json
```

Renders correctly when using the version of vega in vega-lite's `node_modules`:

```
./node_modules/vega/bin/vg2png stacked.vg.json > stacked1.png
```

appears as:

![stacked1](https://cloud.githubusercontent.com/assets/659086/13199168/c1dc0480-d7eb-11e5-9ed9-01897e31ea0a.png)

But when using the vega master (assuming it is checked out in the parent dir):

```
../vega/bin/vg2png /tmp/stacked_bar_v.vg.json > stacked2.png
```

appears as:

![stacked](https://cloud.githubusercontent.com/assets/659086/13199170/fa6ad07e-d7eb-11e5-9d1f-32b69758bf9c.png)

**Comment by arvind** [comment] 2016-02-20 22:10
@mprudhom, I don't happen to have a version of vega-lite master checked out currently. Do you mind including the `stacked.vg.json` spec generated above?

**Comment by mprudhom** [comment] 2016-02-20 22:12
Here you go:

```json
{
    "width": 1,
    "height": 1,
    "padding": "auto",
    "data": [
        {
            "name": "source",
            "url": "data/barley.json",
            "format": {
                "type": "json",
                "parse": {
                    "yield": "number"
                }
            },
            "transform": [
                {
                    "type": "filter",
                    "test": "datum.yield!==null"
                }
            ]
        },
        {
            "name": "summary",
            "source": "source",
            "transform": [
                {
                    "type": "aggregate",
                    "groupby": [
                        "variety",
                        "site"
                    ],
                    "summarize": {
                        "yield": [
                            "sum"
                        ]
                    }
                }
            ]
        },
        {
            "name": "stacked_scale",
            "source": "summary",
            "transform": [
                {
                    "type": "aggregate",
                    "groupby": [
                        "variety"
                    ],
                    "summarize": [
                        {
                            "ops": [
                                "sum"
                            ],
                            "field": "sum_yield"
                        }
                    ]
                }
            ]
        },
        {
            "name": "layout",
            "source": "summary",
            "transform": [
                {
                    "type": "aggregate",
                    "summarize": [
                        {
                            "field": "variety",
                            "ops": [
                                "distinct"
                            ]
                        }
                    ]
                },
                {
                    "type": "formula",
                    "field": "cellWidth",
                    "expr": "(datum.distinct_variety + 1) * 21"
                },
                {
                    "type": "formula",
                    "field": "cellHeight",
                    "expr": "200"
                },
                {
                    "type": "formula",
                    "field": "width",
                    "expr": "(datum.distinct_variety + 1) * 21"
                },
                {
                    "type": "formula",
                    "field": "height",
                    "expr": "200"
                }
            ]
        }
    ],
    "marks": [
        {
            "name": "root",
            "type": "group",
            "from": {
                "data": "layout"
            },
            "properties": {
                "update": {
                    "width": {
                        "field": "width"
                    },
                    "height": {
                        "field": "height"
                    }
                }
            },
            "marks": [
                {
                    "type": "rect",
                    "from": {
                        "data": "summary",
                        "transform": [
                            {
                                "type": "stack",
                                "groupby": [
                                    "variety"
                                ],
                                "field": "sum_yield",
                                "sortby": [
                                    "-site"
                                ],
                                "output": {
                                    "start": "sum_yield_start",
                                    "end": "sum_yield_end"
                                }
                            }
                        ]
                    },
                    "properties": {
                        "update": {
                            "xc": {
                                "scale": "x",
                                "field": "variety"
                            },
                            "width": {
                                "value": 20
                            },
                            "y": {
                                "scale": "y",
                                "field": "sum_yield_start"
                            },
                            "y2": {
                                "scale": "y",
                                "field": "sum_yield_end"
                            },
                            "strokeWidth": {
                                "value": 2
                            },
                            "fill": {
                                "scale": "color",
                                "field": "site"
                            }
                        }
                    }
                }
            ],
            "scales": [
                {
                    "name": "x",
                    "type": "ordinal",
                    "domain": {
                        "data": "summary",
                        "field": "variety",
                        "sort": true
                    },
                    "bandWidth": 21,
                    "round": true,
                    "padding": 1,
                    "points": true
                },
                {
                    "name": "y",
                    "type": "linear",
                    "domain": {
                        "data": "stacked_scale",
                        "field": "sum_sum_yield"
                    },
                    "rangeMin": 200,
                    "rangeMax": 0,
                    "round": true,
                    "nice": true,
                    "zero": true
                },
                {
                    "name": "color",
                    "type": "ordinal",
                    "domain": {
                        "data": "summary",
                        "field": "site",
                        "sort": true
                    },
                    "range": "category10"
                }
            ],
            "axes": [
                {
                    "type": "x",
                    "scale": "x",
                    "grid": false,
                    "ticks": 5,
                    "title": "variety",
                    "properties": {
                        "axis": {},
                        "labels": {
                            "text": {
                                "template": "{{ datum.data | truncate:25}}"
                            },
                            "angle": {
                                "value": 270
                            },
                            "align": {
                                "value": "right"
                            },
                            "baseline": {
                                "value": "middle"
                            }
                        }
                    }
                },
                {
                    "type": "y",
                    "scale": "y",
                    "format": "s",
                    "grid": true,
                    "layer": "back",
                    "title": "SUM(yield)",
                    "properties": {
                        "axis": {},
                        "labels": {}
                    }
                }
            ],
            "legends": [
                {
                    "fill": "color",
                    "title": "site",
                    "properties": {
                        "symbols": {
                            "shape": {
                                "value": "square"
                            },
                            "strokeWidth": {
                                "value": 0
                            }
                        }
                    }
                }
            ]
        }
    ]
}
```

**Comment by arvind** [comment] 2016-02-20 22:15
Thanks! The issue is that Vega-Lite is still outputting a `bandWidth` for scales. We'd recently agreed on renaming that property to `bandSize`. This change has landed in Vega's master (vega/vega@683a364) and I believe is forthcoming in Vega-Lite.

**Comment by kanitw** [comment] 2016-02-21 03:56
We already fixed this in ad0a375092d8912df69078e3dd7b024d502bccdc.   So maybe you don't have the latest Vega-Lite version.  If you still see this problem with the current master, please re-open this issue.

**Closed by kanitw** 2016-02-21 03:56 UTC

**Comment by mprudhom** [comment] 2016-02-21 14:27
You're right; updating fixed the issue. Apologies for the spurious issue.

**Comment by domoritz** [comment] 2016-02-21 19:55
We try to keep the master versions compatible with each other. The latest released version should also be compatible.
