### ISSUE TITLE
Sorting unexpectedly breaks with layered / composite marks

### ISSUE THREAD

**Issue by jheer** [vega/vega-lite#6892] opened 2020-09-22 17:54 UTC
1. Consider this [example spec](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICCNsRpwIUmfIC+SzNqSyIAMzbaEaANqgXNQZhw2voAnnBI2gAUqpgMCF4A5ABKcILhEHAABAAianAJALoAlJkAfAC8mQCMAJw1AKyZAGRNmWER0WpxiSlpSBk5eYUlADyVAEwADFWTza0x3QkA6u6CygDuNMpZAOLabBAQhZkAhJWyDIKCc5kL8curG1u7+4fHI9VwNTd3iQCySEk7kyOzgsm0+QKp3Olz0dlAUCQgiglzy+l+D10T22INeRyh-FuXXuAAV9soGFBMOxZJkAEIMZRkOCYQqKED9fRkth+TAgGwFJTIbQAa30ODYNFkfKUYKgbGUUrIaFAAA8VSA-KllFz9rz2ZgQjg4PoAI4MJzU9TU0jspCqmgQDVuDxqfSQfl2EAhZ3mNb6AFA7QgsEQg1Gk3odyK2RI9kybR8zQgNg4fQIcLyJRa-3obn6pTRoLoixQMEx5U2KtKTbKehoABsk0mNiAA)
2. Change the mark type to "boxplot", resulting in this [new spec](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICCNsRpwIUmfIC+SzNqSyIAMzbaEaANqgXNQZhw2voAnnBI2gAUqpgMCF4A5ABKcILhEHAABAAianAJALoAlJkAfAC8mQCMAJw1AKyZAGRNmWER0WpxiSlpSBk5eYUlADyVAEwADFWTza0x3QkA6u6CygDuNMpZAOLabBAQhZkAhJWyDIKCc5kL8curG1u7+4fHI9VwNTd3iQCySEk7kyOzgsm0+QKp3Olz0dlAUCQgiglzy+l+D10T22INeRyh-FuXXuAAV9soGFBMOxZJkAEIMZRkOCYQqKED9fRkth+TAgGwFJTIbQAa30TDYAA8cII2HylGCoGxlDRZGQ0KBJRqQH5UsoufteezMCEcHB9ABHBhOanqamkdlISU0CDatweNT6SD8uwgEJu8xrfQAoHaEFgiHG03m9DuFWyJHsmTaPmaEBsHD6BDheRKXVB9Dco1KONBdEWKBg+Pqmy1pSbZT0NAANkmkxsQA)
3. The sorting on the new spec is now broken.

In general we can't sort when combining layers with disparate data sets, but with a little thought shouldn't we be able to sort layered plots where each layer is either a variant of the same source data OR a source data and some annotation layers that do not have to participate in the scale domain? Short of a clever automatic solution, could we consider some way to indicate that one layer / data set should drive the scale domain(s) and the others can be ignored?

(Apologies if this happens to be a duplicate of a known bug...)

**Comment by domoritz** [comment] 2020-09-22 19:03
I'll mark this as a duplicate of https://github.com/vega/vega-lite/issues/5486 (or https://github.com/vega/vega-lite/issues/5404), assign the issue to myself, and bump the priority. The problem of sorting comes up very often so yes, we should find a fix for the common cases where we can sort: https://github.com/vega/vega-lite/issues/5048. 

I recently rewrote the optimizer code (https://github.com/vega/vega-lite/pull/6787) so we can easily write more optimizers that may be able to merge the dataflows for different scale domain sources.

**Closed by domoritz** 2020-09-22 19:03 UTC
Labels: Bug :bug:
