### ISSUE TITLE
Custom sorting order does not work for columns in grouped bar charts

### ISSUE THREAD

**Issue by andreipoe** [vega/vega-lite#5484] opened 2019-10-23 17:38 UTC
I'm trying to apply a custom ordering to the columns of a grouped bar chart. Setting `sort` to either `ascending` or `descending` works as expected, but providing an array of labels doesn't.

For example, take the [sample Altair grouped bar chart](https://altair-viz.github.io/gallery/grouped_bar_chart.html) and add custom sorting to the columns using `"sort": ["Waseca", "Duluth"]` ([editor link](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjMSA3ZApgO6baRHIAmALgBakAsADEwDRS0Fq3WkDMLAL7tIAWwCGAJwDWpHNViwANtWQAHUvACuSpYOHgolcdXFzI8caIKlIx0wFomATj4FoBABzQ+AVgBG-gBMlAwAjC4M0Ij+AGxhfJ7unhH+kAYQYlKyWJD+UpCshpAE8HCUyPDoWKAQmXBKsJLm1ACeaja58LCileJKhVAoBEqUtq0EBRl1MMpaovAt7Z1Q3b2WAyLDo7YAzsjUNiK7TbxYANqQAOriu+5mIgAiOlp0kAC605kAHksdtk0KhtBpBtmNchMpkU6lBWn8VpAAI5acTwVSmVS4I5QcSoVCSAioEwI3bzEFg8aEHaCQzTSAAEl20E4ElsPGoal2GAA9NysUSAHSoA60LT+AXIWDcpks8R8wniBxKA4EPl8AUMAVMAUAKxOi2hRhMtwI1F2ckMmXsipcbg83j8gRC4Ui0TiCSS0BSTDSF0tdVqMJm+0OtgAqvBkFjJCHWmAAGJSUSFf0wvBSQhtWwAWVRzK0kmQD1TM0hzSwYVcYUNQdhVPBYCCAHYS18AyXMiGETc7tBi7XMrgM6a4blc2VRYX+wPIGXSJW+NWO3WRg2GJ4BZ5YtuW7W2xBA7XIF2c01C+aa0H04WRzm85OiymB7DJuWwAul8-Z-XSM2NXwAIYVtLwPZdjxVWwAGFJEUaRdgUA0wKHG8szHe8C0fEDS1fecqywzJWh-LA+GcAVXAAvhgJLQ8rxPXIAHFJFRSgwAAJXENQqAvJDh1QqBx3zKcnxnOcKzwsDCNXfggjI7dYl3IN92wMC6KgZ4lFeeh8KgZDM1Hfj0KE7TZxwsTF2MySdiwIIN2cOSFJhJSaLTVTIAjKMCBjA440TSRk2M3TbwYpRxH8GDEK-UT33EyKiLABh1SYOTYio2scFcnt7hBQK+MgeiQrChAQSij8REshtfF8AUgic8DQzHM9kAvHTeP0vKCvC4rTOi8yVysxsNybeynJUiDcmg2D4KKgLWtsfLQs6izutKiS4sSAUEgo1Kg2c4MxqgRjmLYjiuOEo8cra+bCoikTlpikS4qCUjNoA7aYXS-bIHUzTstm4KFuml8CjM6s+obJ6BWSpsRq-Vz3OjWMEyTM6rwu2wAGUh3gE5TBRtMSvuo9yv4KqXsovcsN2ztPsyvs8ZmNHckx1EcenIm7vM1apKwBgmwFCjXop6jRvq-jGu4r9GagZnsdgXGluBnrPwe7nGyqoadze9tYc+ibYDghD6cHP7pax1mjaBt8Vti1XmA1eytdAnXRbypj4BY9jOMoCWZylyAZfNhWrcJq9ies0iocdshXO+t4RD9gO5YeS3cN679VaCdWYZnOHIwR7ykb8i3rz02wADURixXgg9T5WibW0jnCjj6Xdp5OS6CqAK6UKuusV0qwdIXxtSCAXatc7Nxd+lC2u73uyo50H0-6oJYg2sfKZFhE9YN6aeJn8vK9NYuCc5m3+vCfmBebre5rdj2Tu94u-bn4+a5BizHsS6+hbSuqEVjlpFqB9civ2rinD+g9rJrz4NnI8ucPJeTaIXfy+9S65AACoEn8MgE+i9P6qz4GvXwyVm7-1sG3ae6CoBYIIDgvuwc05hzALEdUngKLj0+pPSQ54qGd0gLQ+hC9+54SgfFdUGt5JwNorrGC+spo3XOibAR2DcHvyVgQi+a9yKC0UpvZ2CJDru2Ol7H2SiQE0NUXgkRZ8VYr1IpIhydROEu0AXw3Kgi1EQI0WIgCZEN7CwMeGPOnlEa+VQZLZRAA5WAAp4q+CbNYxhddQ5xQStVB2v8drkNyJQ+O0TYnxMScI5JZU4q+A3GEFxCJuG8PyRYyAMS4kMASQw2uZSM6DWkS5WRk1DYzQaU0opST2lcwvlVSOWT3q3wYvfExp0BnUMaYUlpxSJL4LGQ2PgMkwiZL0dRHJakXhx2AUsoZqy2mQOXls9UsRul7RdvDUJBdwnPwKc02IQQRkf02fwNeKUpkBkOdcE0dN6lnJWZ8y5PjrmkFiOrHc1TTw8Kau4tq5yoUlPab47URDEX6Jzr0+R-S0H8IxV89R1s7Frg3CQuSN8gmzKOp7BZpLcrku+Ro351lNQ6KAoCg8wK3HgrJZCil3iB6wuspU+51NHkhKQT5ZGiz+EAAVJjUBCu7TlVL66EJko4hlhLW6grZqjZR6qTBarGJSkO+M0m0tIQK5SjKxYorMeahplrNXMR1Xa0sj1SJbk1s6lu285G7wNKctVGrrXQslcwy+dyCXwM+kYh+pi3letjb621ti9X9T4JqJxEAkW5GFdG3K3q41Yqucw7ZsqoAIPzsg15Kr2UrKbL4P1+bUkZ01JM-Zf8MqmrRbYc5Xb42iKlfFNejiy1urqZW9Fnbu21phcwoIMlk0HNcjvBRY7cgTrXRK6dibNRVJTTIl26b5lP3bSu5pk680pPtarSsAoS1gAXV9Y5QCO4dqfSekyNil71sSslRtwKnmKpQVmpZVwmpwGxpUMAQzEg9tfQGwhpFyZDp2jMqAeS2VtUQ0yBA+x4BocKRhl9miKobk8Ea1NLtamoofRQpDFHUPoc8Jh+jv5SIMD2Y5K9PSXb7pJZEhpZHkOUeo3E2j6zQMCZ5kGkTzixMPMMXMll96SOcfIyhqjvH+PcrAEW+2Ib8PTNdb+jSccDO5K48ZhTFm+N0fM4uSGzHr0Ihg2E5VTmDITgwma-GHMgiqcbNo3z4nuyjo42hULRllOMKi159UwnrOicCcampU8kshcEphNLqcMvny2ZqPF244vaaghGg9RXIACQfOF7CNiKvUukrJHLmm8ssZ08yx+Hq0x+1a2FntXWC3gx2T-Gz2t8u2GFcFlrhlSuRUi9FrdAo6XyTq3K-zCrAtF2a1dRaZWzLTb7YWteTHQ3ArycuuaHVAYgfSx0wtfMmwBOHVwwrz3-rXSndsz7WzSa-YI3ZyTe9pNLPO7D26nXttr12X10tWnDt32G5ms7r3FGhy2+ZsImoEpbQezHP9h6Dr45B1FsRmdNzDUx02z6AWXlBbh-wxO8tLs9Wu2+lefMydFrISO3s7cE5myTnTsH-BaVQYnoV1bPP2sESJ5VkmWp5u5bSoRyAMOCdjeUarqb23tSsPJwtp2S2mXGL06NhmJvpe8828j4n-ydf9b13ZlbXPcqm7zQL7DK8ZKjyt7rqHtuoDs9bZz32yiwFm-M6vTcYuaaJcB13I+4D3vlbl8RYXP62PNQA7PHPsvfGMch7Z6PBvGtSYTw0pPQfovbK1E663Lq6+3od-B-hLe+cLmDwRNaYevcY93Z9CtZfD49zfqe0HDOZLZakSz6Dx2OendW545Pmvw4d-R9+ymj3M+z8wVY9dw+C-xVIuH2BJ+lfuupyouhXi89XZv8JyGNfFuDYa30ojuYksrvq3uZpfOwhHt7lHv-nbhmqyv7m1KAUPq4CPgzhbhPsflPq4lTiKh4pfovvTjOgIJDIrmzpvnHtvogeOisq0mAfvjFv+IBOniahLi-ucnQYQV-mHsXgDuflABwcUlwWIukr4BRAwGQRJg3kAZ6hCs0nQSgaDl5tVpgZIUNvbiNv3oBsMvQd1mJFZvthTtPrgVnssvIUIR-vzjfjttDOvs2s8pQREk3nIbOhSooWgTOozntl+j+k9vwWYa4ZXjOgwMWrwc-ngY+oEVfqgV-rYQNn5gAcSjIcboMmKnvnoRZtqGIVAZPj7j3rppoc1hyroTNrhGRCwQAiYf4cUcIZ4TJL4GocEogidk4cATGlarmu4dthuElEfo0bkolqttWp0W7h9l5mvEwKoY-v9uEaYcMdqtEUvsEeqDVHYUSpGloW1PMTal0SnlVPfnhpHrXrAQdAUbjkMTmgsbsQwanoaqGvrn7s4e0T6lcaMfnl5mEPzBprkTAQkbkLHkqlQU8dobzGutcRkQIBURQmfn7MekEYmp8avPitgQVrMdUauvCWkpqAcf0VAIbpsTQUBukaUcRHNjkVgXkSca7DjggcCZEaCcSTdg2GEPsVMSictlUbCRiYsUQZunzDVnEZSX8THhQYCa0bIfwrJtxiZjRh5uCSSe5gdqzqwVlM1lKa5qZiUUyUPJUt8RSb8fFsinUqtuqfJpqfKdqTzHzGjoYV3lTMqeGoAUbk7jJi5mabKYyYLuDuUfcXZr3oUSaW6Txh6VqV6b+BbnqbifZj9GqUGTKYpnKW8Z-inrhqof6O8LSCAIIEAA)). The specified column order will not be respected:

![image](https://user-images.githubusercontent.com/6793243/67419334-6ea1bf80-f5c4-11e9-80a0-cb8a29363233.png)

**Comment by kanitw** [comment] 2019-12-03 23:33
This is a duplicate of https://github.com/vega/vega-lite/issues/5366

**Closed by kanitw** 2019-12-03 23:33 UTC
Labels: Bug :bug:
