### ISSUE TITLE
Make charts more accessible

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#4244] opened 2018-11-05 18:11 UTC
It would be nice if we could make charts more accessible to users with vision deficiencies. SVG supports aria tags and there are some suggestions for accessibility in https://css-tricks.com/accessible-svgs/#article-header-id-14. Unfortunately, this approach won't work for canvas but we should do our best for SVGs. 

Open questions
* What should we annotate? Can we reuse the tooltip code to make marks accessible? 
* Do we need to add something to Vega?
* What about tab order and other accessibility features?

**Comment by ganeshpatro321** [comment] 2019-05-12 04:38
Regarding this issue:
* We should exactly know what are the marks we would like to annotate or improve accessibility.
* I think we have to make changes in Vega for this feature 

@domoritz could you brief more information regarding this issue.

**Comment by domoritz** [comment] 2019-05-27 17:01
ToDo

* Take an existing Vega spec and manually add annotations
* Get feedback on the annotated spec
* Update Vega to either automatically add the annotations or allow users to set them. We probably need to modify the Vega SVG renderer and parser. 
* Update Vega-Lite to generate appropriate Vega specifications.

**Comment by ganeshpatro321** [comment] 2019-05-27 17:39
Yeah, I was thinking exactly the same. Have to figure out where to add annotations in the spec. Again that will vary according to specs.

**Comment by syntagmatic** [comment] 2019-12-05 21:57
This is a beginner but related question: is it possible to add custom attributes to an element?

For example, how could one add the `tabindex` or `role` attributes to elements in a visualization? I am trying to take an existing Vega spec and improve its behavior with a screen reader.

**Comment by domoritz** [comment] 2019-12-06 00:18
Vega does support custom attributes. The tricky bit is that you also need to support it in the renderer and the Browser Canvas API does not have a support for tabindex.

**Comment by domoritz** [comment] 2020-01-27 05:41
I'm adding basic support for tab index and aria labels in https://github.com/vega/vega/pull/2343. 

@syntagmatic Can you explain how you would use role? I don't see any role that works for Vega charts.

**Comment by syntagmatic** [comment] 2020-01-29 03:07
Thanks @domoritz, that looks great. Actually I don't think there would be many common use-cases for `role`, that doesn't seem necessary.

Another consideration would be making `aria-hidden` available for tick labels, legends or other text elements that should be ignored by a screen reader.

**Comment by domoritz** [comment] 2020-01-29 06:52
As far as I can see, voice over already skips them. Have you tried another screen reader? 

Do you want to send a pull request to add support for aria hidden?

**Comment by syntagmatic** [comment] 2020-01-29 08:02
Here's a screenshot of the accessibility tree from this [vega-lite line chart bl.ock](https://bl.ocks.org/domoritz/raw/3823557eaf8df548f1271cddccc58aa3/) which exhibits the behavior. Those `GenericContainer` elements are all the text fields of the legends/ticks.

<img width="1545" alt="Screen Shot 2020-01-28 at 11 41 03 PM" src="https://user-images.githubusercontent.com/156229/73336816-b53c3100-4227-11ea-9007-ab9f16f51cea.png">

The ordering the reader takes for the first chart is:

- "AAPL" -> "AMZN" -> "IBM" -> "MSFT"
- "Symbol" (the legend title)
- "2000" -> "2001" -> "2002".... (the X axis values, even visibly hidden ones like 2001)
- "Time" (the X axis title)
- "0" -> "50"... -> "250"
- "Price" (the Y axis title)

The problem is this ordering just feels jumbled. Legend/axis items are read before titles and it's hard to make sense of what the text means in the first place.

I confirmed that the macOS VoiceOver follows that path, here's a screenshot of that happening:

<img width="655" alt="Screen Shot 2020-01-28 at 11 43 37 PM" src="https://user-images.githubusercontent.com/156229/73336966-1ebc3f80-4228-11ea-82e2-da88b12ce2e9.png">

Hiding them from the reader with `aria-hidden` is one possible solution, but let me do a bit more reading on it. I'll take a closer look at vega/vega#2343 tomorrow.

Thanks again for your efforts here, it's greatly appreciated.

**Comment by domoritz** [comment] 2020-01-29 19:01
I see. I think we should hide axis and legend elements and instead create some understandable representation such as "X axis shows price between 0 and 550", "Y axis shows time from 2000 to 2010".

**Comment by domoritz** [comment] 2020-01-30 01:09
Also, I didn't know about the accessibility feature in Chrome. That's super neat.

**Comment by majornista** [comment] 2020-02-12 16:03
> I'm adding basic support for tab index and aria labels in [vega/vega#2343](https://github.com/vega/vega/pull/2343).
> 
> @syntagmatic Can you explain how you would use role? I don't see any role that works for Vega charts.

`role` could be as simple as defining a `<g>` element as a `button`, to provide an affordance to a screen reader user for drilling down into the individual data points. For example, in the stock chart above, a user could focus the trend line for AAPL, "closing stock price for AAPL from years 2000 to 2010, button", then click the "button" to drill in to inspect individual data points, changing the `role` of the container to `grid`, and allowing the user to navigate through the individual data points like a data table. WAI-ARIA 1.1 also has the [`aria-roledescription`](https://www.w3.org/TR/wai-aria-1.1/#aria-roledescription) attribute that allows a user to provide a localized string to describe an element's `role`.

Ideally we'd be able to provide a deeper understanding of the data to a blind user, that's closer to what  data visualization, as an accessibility tool for making sense of data, provides to a sighted user. 

It starts with being able to add WAI-ARIA attributes to provide labeling and structure for regions and data points within the data vizualization.

**Comment by domoritz** [comment] 2020-02-12 16:30
> role could be as simple as defining a <g> element as a button, to provide an affordance to a screen reader user for drilling down into the individual data points. For example, in the stock chart above, a user could focus the trend line for AAPL, "closing stock price for AAPL from years 2000 to 2010, button", then click the "button" to drill in to inspect individual data points, changing the role of the container to grid, and allowing the user to navigate through the individual data points like a data table. WAI-ARIA 1.1 also has the aria-roledescription attribute that allows a user to provide a localized string to describe an element's role.

This sounds great. Could you explain whether it's enough to just mark the group element as a button or whether more code is needed to e.g. expand dom nodes on click? I'm not sure whether just supporting role is enough here and I'm wary of adding another encoding when it doesn't give us benefits yet.

**Comment by majornista** [comment] 2020-02-12 17:22
> This sounds great. Could you explain whether it's enough to just mark the group element as a button or whether more code is needed to e.g. expand dom nodes on click? I'm not sure whether just supporting role is enough here and I'm wary of adding another encoding when it doesn't give us benefits yet.

For keyboard/screen reader accessibility, we would need to handle events like `onFocus/onBlur`, `onKeyDown/onKeyUp`, and `onClick` for focusable elements with role and tabIndex="0". For example, when a datapoint receives focus we would want to render some custom indication of focus and perhaps display the tooltip for the datapoint, as we do on mouseover.

**Comment by majornista** [comment] 2020-02-12 17:30
> Vega does support custom attributes. The tricky bit is that you also need to support it in the renderer and the Browser Canvas API does not have a support for tabindex.

Browser support for the Canvas shadow DOM would be complicated, and maybe not ideal. One use case where rendering using Canvas is often preferred over SVG is when there are multiple visualizations on a single web page, like for a dashboard. Canvas is quicker to render than the same number of SVG elements. But with appropriate alternative text for the Canvas element, an affordance could be provided to re-render the data visualization in SVG, allowing keyboard/screenreader interaction and inspection.

**Comment by domoritz** [comment] 2020-02-12 17:47
Thanks for the explanation. For the MVP, I'll focus on labels and tabindex and keep the rest for the future when we have a better idea of what's the best way to make data accessible.

**Comment by syntagmatic** [comment] 2020-02-12 19:18
I agree that labels/tabindex seem like a "good enough" solution for now.

There are some W3C SVG Accessibility/Navigation brainstorming notes that are worth looking at in the future for ideas on more complex screen reader and keyboard navigation.

https://www.w3.org/wiki/SVG_Accessibility/Navigation#Amelia.27s_Proposal_.26_Related_Brainstorming

A Vega(-lite) interaction grammar could be a great way to specify the desired behavior without implementing the low-level key event handlers and imperative state management that the WAI-ARIA authoring practices demonstrate. Example:

https://www.w3.org/TR/wai-aria-practices-1.1/examples/grid/dataGrids.html
https://www.w3.org/TR/wai-aria-practices-1.1/examples/grid/js/dataGrid.js

**Comment by majornista** [comment] 2020-02-13 17:40
Mark items already support keyboard event handlers (see: https://vega.github.io/vega/docs/event-streams/#supported-event-types), but they are of no use because a mark cannot accept keyboard focus.  because it doesn't support `tabindex`. Assuming Vega gets support for `tabIndex`, if an item can accept focus and can trigger mouse or keyboard events, it is interactive and should communicate to the user and assistive technology what it is and what it can do. For this you need to support more WAI-ARIA attributes than just `aria-label` and `tabindex`. Also, if an element can receive focus, Vega should support `focus` and `blur` event handlers.

**Comment by domoritz** [comment] 2020-02-13 18:31
Sounds good. Let's get aria labels and tabindex into Vega and in a follow up pull request add support for more properties.

**Comment by domoritz** [comment] 2020-04-03 17:55
Done in https://github.com/vega/vega-lite/pull/6185

**Closed** 2020-04-19 16:03 UTC
Labels: Area - Visual Encoding, Feature Request :raising_hand_woman:, P2, RFC / Discussion :speech_balloon:
