### ISSUE TITLE
Empty="all" does not count as selection for logical "and"

### ISSUE THREAD

**Issue by arvind** [vega/vega-lite#3593] opened 2018-04-03 00:24 UTC
From @zanarmstrong in vega/vega#1216

> Steps to reproduce: 
> 
> Go to this Observable: 
> https://beta.observablehq.com/@zanarmstrong/vega-lite-interaction
> 
> Click on "1982". You'll see this. This is surprising. By clicking on 1982, now none of the years are selected and all the points in the scatterplot are grey. But, it looks like all the countries are selected because they're all still colored.
> 
> ![qyj1e0r7bei](https://user-images.githubusercontent.com/7397271/38221990-3bdea178-3697-11e8-8564-02bc187c36fa.png)
> 
> If you then right click on "USA", "Japan" and "Europe", you'll see the following.
> 
> ![nygexgf24lb](https://user-images.githubusercontent.com/7397271/38222025-6ebc622e-3697-11e8-93d5-be8671495f4d.png)
> 
> I would have expected to see the latter image in both cases. In both cases, I've selected the year "1982" and I would expect all of the countries of origin to be selected (either because I've selected them all by selecting nothing... or because I've selected them all manually by right-clicking). 
> 
> ---
> The two key things that seem to be happening are that: 
> 
> 1 - I'm using "empty=all" 
> 2 - Selection is based on a logical and
> 
> Somehow the empty=all doesn't seem to count for the logical "and"

**Comment by zanarmstrong** [comment] 2018-04-03 00:44
Thanks for looking into it! And, for opening the issue in the right place :).

**Comment by zanarmstrong** [comment] 2021-07-19 23:26
Looks like this has been fixed (confirmed by @Fil). 

Thanks for fixing it! 

Am closing the bug.

**Comment by zanarmstrong** [comment] 2021-07-19 23:28
I guess I can't close it since I'm just a commenter (that makes sense). Anyway, it looks good :). You are welcome to close. Thank you!

**Comment by domoritz** [comment] 2021-07-19 23:30
🎉

**Closed** 2021-07-19 23:30 UTC
Labels: Area - Interaction

**Comment by Fil** [comment] 2021-07-20 10:25
Here's a fork of @zan's notebook upgraded to Vega@5 https://observablehq.com/d/d1d081e3f7840b68
