### ISSUE TITLE
Inversion of ordinal brush looks funky

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#2315] opened 2017-04-29 06:10 UTC
![brush](https://cloud.githubusercontent.com/assets/589034/25553429/a052b3aa-2c67-11e7-8c6b-5b306c17a0d7.gif)

Spec:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"url": "data/europe_world_bank.csv"},
  "hconcat": [
    {
      "mark": "bar",
      "height": 700,
       "selection": {
        "brush": {"type": "interval", "encodings": ["y"]}
      },
      "encoding": {
        "y": {
          "field": "Country",
          "type": "ordinal",
          "sort": {
            "op": "min",
            "field": "Population_ages_15_64_of_total",
            "order": "descending"
          }
        },
        "x": {
          "field": "Population_ages_15_64_of_total",
          "type": "quantitative"
        },
        "color": {
          "condition": {"selection": "!brush", "value": "steelblue"},
          "value": "goldenrod"
        }
      }
    },
    {
      "mark": "bar",
      "height": 700,
      "selection": {
        "brush": {"type": "interval", "encodings": ["y"]}
      },
      "encoding": {
        "y": {
          "field": "Country",
          "type": "ordinal",
          "sort": {
            "op": "min",
            "field": "Population_ages_65_and_above_of_total",
            "order": "descending"
          }
        },
        "x": {
          "field": "Population_ages_65_and_above_of_total",
          "type": "quantitative"
        },
        "color": {
          "condition": {"selection": "!brush", "value": "steelblue"},
          "value": "goldenrod"
        }
      }
    },
    {
      "mark": "point",
      "width": 260,
      "height": 260,
      "selection": {"brush": {"type": "interval"}},
      "encoding": {
        "y": {
          "field": "Population_ages_15_64_of_total",
          "type": "quantitative",
          "scale": {"zero": false}
        },
        "x": {
          "field": "Population_ages_65_and_above_of_total",
          "type": "quantitative",
          "scale": {"zero": false}
        },
        "color": {
          "condition": {"selection": "!brush", "value": "steelblue"},
          "value": "goldenrod"
        }
      }
    }
  ]
}
```

Data: https://gist.github.com/domoritz/c52e1ff798f325533d04f1c6d7b8fd83

**Comment by arvind** [comment] 2017-04-29 06:19
Duplicate of #2148.

**Comment by domoritz** [comment] 2017-04-29 06:30
Hmm, not sure whether this is a duplicate. 

We seem to be using a band scale for this chart and as far as I understand #2148 is a problem because of point scales

```json
{
              "name": "concat_0_y",
              "type": "band",
              "domain": {
                "data": "data_0",
                "field": "Country",
                "sort": {
                  "op": "min",
                  "field": "Population_ages_15_64_of_total"
                }
              },
              "range": [700,0],
              "round": true,
              "paddingInner": 0.1,
              "paddingOuter": 0.05,
              "reverse": true
            }
```

**Comment by domoritz** [comment] 2017-04-29 19:00
I think this issue may be different because the scale is already a band scale.

**Comment by arvind** [comment] 2017-04-29 19:02
I think the underlying issue in both bug reports is how we represent the state of interval selections over ordinal data (rather than specific scale types). Will leave this report open, however, as a second useful example to test an eventual solution against.

**Comment by domoritz** [comment] 2017-05-17 18:56
cc @danyelf

**Comment by kanitw** [comment] 2017-06-06 03:19
This now works correctly in #2377

**Closed by kanitw** 2017-06-06 03:19 UTC
