### ISSUE TITLE
Line with Points blows up timeFormat in transform calculate

### ISSUE THREAD

**Issue by king612** [vega/vega-lite#3730] opened 2018-05-10 11:29 UTC
I believe this is a bug.

When adding point: true to a line mark, if the x channel is a date it can no longer be used in a tooltip with a calculate transform to format the date.  Removing point: true in the line mark allows the timeFormat() of the temporal x channel values to display correctly.

The code below is adapted from the Overview-Detail interaction example.  If you hover over the points on the bottom chart (the Overview), you'll see the blown date in the tooltip.  If you remove point: true, the tooltip will render correctly.  This would seem to be a bug.  I am using the latest version of vega-lite.

Thanks,
John K.

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",

  "data": {"url": "data/sp500.csv"},

  "vconcat": [
    {
      "width": 480,
      "mark": "area",
      "encoding": {
        "x": {
          "field": "date",
          "type": "temporal",
          "scale": {"domain": {"selection": "brush"}},
          "axis": {"title": ""}
        },
        "y": {"field": "price", "type": "quantitative"},
        "tooltip": [
              {"field": "date", "type": "temporal"},
              {"field": "price", "type": "quantitative"}
        ]
      }
    },
    {
      "width": 480,
      "height": 60,
      "layer": [
        {
          "mark": {"type": "line", "interpolate": "monotone"},
          "selection": {"brush": {"type": "interval", "encodings": ["x"]}},
          "encoding": {
            "x": {
              "field": "date",
              "type": "temporal",
              "axis": {"format": "%Y"}
            },
            "y": {
              "field": "price",
              "type": "quantitative",
              "axis": {"tickCount": 3, "grid": false}
            }
          }
        },
        {
          "mark": {"type": "line", "point": true},
          "transform": [{
            "calculate": 
    "timeFormat(datum.date, '%-m/%-d/%y')", "as": "formattedDate"
          }],
          "encoding": {
            "x": {
              "field": "date",
              "type": "temporal",
              "axis": {"format": "%Y"}
            },
            "y": {
              "field": "price",
              "type": "quantitative",
              "axis": {"tickCount": 3, "grid": false}
            },
            "tooltip": 
              {"field": "formattedDate", "type": "nominal"}
            
          }
        }
      ]
    }
  ]
}```

**Comment by domoritz** [comment] 2018-05-10 20:27
As a side note to avoid confusion:

> If you remove point: true, the tooltip will render correctly

The date is always the same, though no matter where you ask for the tooltip.

**Comment by domoritz** [comment] 2018-05-10 20:29
Simpler examples.

Doesn't work (but works if we change the marktype to "point"). 

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"url": "data/sp500.csv"},
  "layer": [
    {
      "mark": {"type": "line", "point": true},
      "transform": [
        {
          "calculate": "timeFormat(datum.date, '%-m/%-d/%y')",
          "as": "formattedDate"
        }
      ],
      "encoding": {
        "x": {"field": "date", "type": "temporal", "axis": {"format": "%Y"}},
        "y": {
          "field": "price",
          "type": "quantitative",
          "axis": {"tickCount": 3, "grid": false}
        },
        "tooltip": {"field": "formattedDate", "type": "nominal"}
      }
    }
  ]
}
```

**Comment by king612** [comment] 2018-05-10 20:37
Thank you for the response.  Yes, I just solved it by adding the points in a separate layer, as shown on the excellent doc pages, but it clearly looks like something is awry under the covers.  Just thought I'd report it.  I was also using monotonic smoothing, but that didn't seem to affect it one way or the other.

**Comment by domoritz** [comment] 2018-05-10 20:38
The problem is that we don't parse the `date` field as a date before we try to format it. We cannot infer this automatically so I'd say we need to expect users to write 

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {
    "url": "data/sp500.csv",
    "format": {
      "parse": {
        "date": "date"
      }
    }
  },
  "layer": [
    {
      "mark": {"type": "line", "point": true},
      "transform": [
        {
          "calculate": "timeFormat(datum.date, '%-m/%-d/%y')",
          "as": "formattedDate"
        }
      ],
      "encoding": {
        "x": {"field": "date", "type": "temporal", "axis": {"format": "%Y"}},
        "y": {
          "field": "price",
          "type": "quantitative",
          "axis": {"tickCount": 3, "grid": false}
        },
        "tooltip": {"field": "formattedDate", "type": "nominal"}
      }
    }
  ]
}
```

or 

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {
    "url": "data/sp500.csv"
  },
  "layer": [
    {
      "mark": {"type": "line", "point": true},
      "transform": [
        {
          "calculate": "timeFormat(toDate(datum.date), '%-m/%-d/%y')",
          "as": "formattedDate"
        }
      ],
      "encoding": {
        "x": {"field": "date", "type": "temporal", "axis": {"format": "%Y"}},
        "y": {
          "field": "price",
          "type": "quantitative",
          "axis": {"tickCount": 3, "grid": false}
        },
        "tooltip": {"field": "formattedDate", "type": "nominal"}
      }
    }
  ]
}
```

I agree that this is not satisfying but I think it makes sense because the user wrote their own expression. 

A different way to write the spec is the following:

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"url": "data/sp500.csv"},
  "layer": [
    {
      "mark": {"type": "line", "point": true},
      "encoding": {
        "x": {"field": "date", "type": "temporal", "axis": {"format": "%Y"}},
        "y": {
          "field": "price",
          "type": "quantitative",
          "axis": {"tickCount": 3, "grid": false}
        },
        "tooltip": {
          "field": "datum.date",
          "type": "temporal",
          "format": "%-m/%-d/%y"
        }
      }
    }
  ]
}
```

Right now, the tooltip is on the line but I think we could change that in the normalizer @kanitw, right?

**Comment by king612** [comment] 2018-05-10 20:53
Those are cleaner solutions for sure.  Actually, what got me started on this was that I couldn't get the array form of tooltip to work.  The form where the tooltip formats into nice little table (e.g., to show multiple fields).  I have not been able to reproduce this issue outside of my app's spec (which I can't post) on the Vega Editor.  On my machine, the array form of tooltip always renders as '[object Object]'  If you have any thoughts on that I'd love to hear them.  That's why I was trying to build a string out of multiple fields in the first place.

Where is toDate() documented?

Thanks,
John K.

**Comment by domoritz** [comment] 2018-05-10 20:58
> Where is toDate() documented?

https://vega.github.io/vega/docs/expressions/

**Comment by domoritz** [comment] 2018-05-11 21:11
Let's see how this works in Vega 4 and then decide.

**Comment by domoritz** [comment] 2020-01-09 00:52
https://github.com/vega/vega-lite/issues/3730#issuecomment-388175826 works now. Closing.

**Closed by domoritz** 2020-01-09 00:52 UTC
Labels: Area - Data & Transform, Area - Visual Encoding
