### ISSUE TITLE
Selection projection broken for aggregate plot

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#5126] opened 2019-06-28 22:05 UTC
For example, in this [spec](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATZAgBOjQnh4qckAIJh26XWCTW8YWIm4B3RkupgWyMAFUAymCE3ISsYuhGymCajLB4+uyskUpg3ABmYOjUPtS63KzEYO5gAEwADBV0ahqQmhGYOMBQrLpi2Fr1pMGh4cnyiioAvuoQkPHoSrBp3Lqo7QDawJBpjGJ4yLrttRGsqHQAnsjWYAC8J6UVZZCDALrqNbDIYsjwye1Lj8+v72P7hMhbWDuajPNRQZBKeDcGIeWALSAADzBkH2kBug2GIBqGF0AGstlZNiNwZDocD3hpRqjGpSIFAVk9NFssgDVFA8H8AaYZjD0G1iXSoAg+VywEtdBNsv51oR2gBGADsg1pmMFiIpgtGWVywnWgN2yIZYiZpn+IVBbN+-y2AEdWBMjHgIowqNVNVB0AjYj9HaDTSEws7lNcVQKoCF0PBmNSxZAoUoYm9GpBPi8k0KnmnkRQ+axRXLhlAc2I8+0ynRpMqIMrlUA).

clicking a bar leads to 

```
ERROR TypeError: Cannot read property '0' of undefined
    at d (selectionTest.js:25)
    at Object.f [as vlSelectionTest] (selectionTest.js:92)
    at Object.eval (eval at r (expression.js:9), <anonymous>:3:122)
    at Encode.js:72
    at Array.forEach (<anonymous>)
    at t.a (visitArray.js:9)
    at a.s.visit (Pulse.js:390)
    at o.Object.transform (Encode.js:71)
    at o.a.evaluate (Transform.js:57)
    at o.a.run (Transform.js:33) 

```

**Comment by domoritz** [comment] 2019-12-03 01:36
@kanitw @arvind This issue is marked as P1. Do we need to fix this or decrease the priority?

**Comment by arvind** [comment] 2021-01-06 19:44
As of Vega 5.17.1, Vega-Lite 4.17.0, this spec appears to be working as intended. 
![Kapture 2021-01-06 at 14 43 53](https://user-images.githubusercontent.com/42262/103813154-9e07e500-502d-11eb-9328-71e861a531fc.gif)

**Closed by arvind** 2021-01-06 19:44 UTC
Labels: Area - Interaction, Bug :bug:, P3
