### ISSUE TITLE
Color and fill scales are not merged

### ISSUE THREAD

**Issue by marcprux** [vega/vega-lite#5262] opened 2019-08-04 20:26 UTC
As mentioned in issue #5186, the https://vega.github.io/vega-lite/examples/interactive_multi_line_label.html example uses a different color scale for the line mark than it does for the text annotation marks.

Observe at the following screenshot that the "IBM" line is green, but the text annotation for the stock price (88.7) is red.

<img width="939" alt="60922127-1095da00-a26a-11e9-8a2c-181f0a54fe95" src="https://user-images.githubusercontent.com/659086/62428841-afe1ac00-b706-11e9-8e63-02e8d8694c73.png">

Hiding the legend (which was the solution to #5186) doesn't change this bug, it just makes it less obvious.

**Comment by kanitw** [comment] 2019-08-04 22:52
Hi,

which version are you seeing this?

This is what I see from the online (latest) version:

![image](https://user-images.githubusercontent.com/111269/62430309-d59f8e80-b6cf-11e9-997d-5cc8159e86a5.png)

**Comment by domoritz** [comment] 2019-08-05 06:59
Which is incorrect. See how the colors of the text are not the same as the line.

**Comment by domoritz** [comment] 2019-08-05 15:30
I [simplified the example](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATdHkw5QECJFYAnMdi070fPN3gBrWHXiwKajUYBm3ExjwWDQyM8AE9CZAtIFzd1IKNCdBNYCP0POMhtPBTLLMg0iABfNKLC2KgAd0ZNFgsADgAGerLIFEZqfAsAFkbmsXQQ5BMLAG00wKDIZCV4bk1GJWoA-MNIAA8AyE9GZDFNSMyI1ShQ8Mis1EIfdHMCsrioEI2tnb2cSEITRnhD47DsyAAjqx0Eo8MwdIwqJBbssjDMxD4nttdpFYCFUOxuOYjpATv8lNxUPNrtDljD7pA+gMhjhhuN0hgTPZIhIlBEyap6RNkmJkPAwcolvcJn12DshcKJnjUfNqLz3JKJmzEshYP4cHgTKxkHdFZBBW9UNxWMluFQhrrJZNprNZbARrDhWs8orDABdS1OtCEUKRAlsl2KkrC8lOxnMt6Xeb+T1GKYzOYLCVW7gJeDMR6pV1w5RzAUqLPZow8vn5lnoMXYx0UijXbUWACM1cModdkFrYnrOHqzeD9z7LbdxV1XOOJhBsG8vgdktHEy2YiyNLAc-SJf5PALUFF4t7joHEA9y0p-UGI1X1oTsuTTqyq3VK+bwT+kSBILBujBUNj6WeKMjnzfIGkqtk66yFm20pvOclzjlWRabMirw5OyrqgRSmaPghUFQG+oLgl+hxPlAf7Ie8gGoUGP45giy6rlKL5vASRJKCS1ErKRqLopi8HZpSNBTMhSisGIYh7iBP6QOGN4UjhuLIPeCp6tcbRbvxngxs2GTgWAACs7EZJhIi6fuZJDi24BDkUQA) and found that if we use color encoding instead of fill, the colors are right. 

<img width="186" alt="Screen Shot 2019-08-05 at 5 29 08 PM" src="https://user-images.githubusercontent.com/589034/62476085-a27bfe80-b7a6-11e9-8391-5b4d657ebaf1.png">
<img width="182" alt="Screen Shot 2019-08-05 at 5 29 02 PM" src="https://user-images.githubusercontent.com/589034/62476086-a27bfe80-b7a6-11e9-9dc0-2c84160dbba4.png">

**Comment by domoritz** [comment] 2019-08-05 15:38
The issue is that we are generating two scales. One for color, one for fill. 

@kanitw shouldn't we be merging them? 

The fix for the spec is to use color rather than fill. I sent https://github.com/vega/vega-lite/pull/5265 as a fix for the example.

**Comment by kanitw** [comment] 2019-08-05 16:09
> @kanitw shouldn't we be merging them?

I don't think there is a good solution here given that we don't know when should we merge.

If we say we merge color scales that act as fill, then we would be wrong for cases where users use line stroke and text fill.  (And vice versa.)

Given that users should generally either use only color, or mix fill and stroke -- I think this is a "wontfix" to me.  

If anyone has a case that couldn't be fixed with a such workaround, please feel free to provide an example and re-open the issue.

**Closed by kanitw** 2019-08-05 16:09 UTC
Labels: Bug :bug:, wontfix
