### ISSUE TITLE
Density visualizations with group by are not stacking correctly

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#6624] opened 2020-06-15 16:55 UTC
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAdxoATemjEAGbUvg0yWNAEZdStUkwpUoBgCdBaEJesEoSexCkz5AXyVkewBrZ084FCVMeyRZCAAzNnsENABtUETBNTSQABEaCBxBJChEOFlMRRAACSSIOBw2ZTh7EABdJSQIHIQIiAcyiqriJEEGOHaA0DVyiDoAT2cRsYmlMns2BhwmRdRUkF6ugd6htr8OkHKoNjUaWTI0UAAPR5B4mjgspdHxqsx5nATdAARwYsUwdCsNFIIACIF2GQ+X3QMziCz+AKBIFB4MhEJhSgg1igoXQAC8WmxYUproIkq93p9suhDv17INKlFMc5ZGwEHdRrC-H4gA)

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "width": 400,
  "height": 100,
  "data": {
    "url": "data/cars.json"
  },
  "mark": "area",
  "transform": [
    {
      "fold": ["Displacement", "Horsepower"],
      "as": ["measurement", "value"]
    },
    {
      "density": "value",
      "groupby": ["measurement"]
    }
  ],
  "encoding": {
    "x": {"field": "value", "type": "quantitative"},
    "y": {"field": "density", "type": "quantitative", "stack": "zero"},
    "color": {"field": "measurement", "type": "nominal"}
  }
}
```

![image](https://user-images.githubusercontent.com/589034/84685025-5fbea300-aeee-11ea-83b6-a4dde7b37f3b.png)

**Comment by domoritz** [comment] 2020-06-15 16:58
The issue is that we use impute to fill in missing densities as 0 but the densities are not signed.

**Comment by joelostblom** [comment] 2024-04-02 00:39
This is currently working as intended, so I'm closing the issue. I believe it was solved in https://github.com/vega/vega-lite/pull/9106

![image](https://github.com/vega/vega-lite/assets/4560057/99915472-b06b-419f-a985-6898dfb78879)

**Closed by joelostblom** 2024-04-02 00:39 UTC
Labels: Bug :bug:, P3
