### ISSUE TITLE
Wrong UTC / Local time interpretation

### ISSUE THREAD

**Issue by iliatimofeev** [vega/vega-lite#4091] opened 2018-07-27 20:02 UTC
```json
{
  
  "layer": [
    { 
      "mark": {"type": "point", "color": "#3366cc"},
      "encoding": {
        "x": {"type": "ordinal", "field": "date", "timeUnit": "date"},
        "y": {"type": "ordinal", "field": "date", "timeUnit": "hours"}
      }
    },
    {
      "mark": {"type": "point", "color": "#dc3912", "shape": "square"},
      "encoding": {
        "x": {"type": "ordinal", "field": "date", "timeUnit": "date"},
        "y": {"type": "ordinal", "field": "date", "timeUnit": "utchours"}
      }
    }
  ],
  "data": {
    "values": [
      {"date": "2018-02-01"},
      {"date": "2018-02-02 00:00"},
      {"date": "2018-02-03 00:00 UTC"},
      {"date": "2018-02-04 00:00Z"}
    ]
  },
  "$schema": "https://vega.github.io/schema/vega-lite/v2.6.0.json"
}
```
![visualization 27](https://user-images.githubusercontent.com/11561581/43343896-9be27996-91f0-11e8-9057-c00347e6918d.png)

I have UTC+3 so expected:
![visualization 29](https://user-images.githubusercontent.com/11561581/43344742-7ee16890-91f3-11e8-90cc-cf8314578269.png)

as

```json
{
  
  "layer": [
    { 
      "mark": {"type": "point", "color": "#3366cc"},
      "encoding": {
        "x": {"type": "ordinal", "field": "date", "timeUnit": "date"},
        "y": {"type": "ordinal", "field": "local"}
      }
    },
    {
      "mark": {"type": "point", "color": "#dc3912", "shape": "square"},
      "encoding": {
        "x": {"type": "ordinal", "field": "date", "timeUnit": "date"},
        "y": {"type": "ordinal", "field": "UTC"}
      }
    }
  ],
  "data": {
    "values": [
      {"date": "2018-02-01" ,"local":0,"UTC":21},
      {"date": "2018-02-02 00:00","local":0,"UTC":21},
      {"date": "2018-02-03 00:00 UTC", "local":3,"UTC":0},
      {"date": "2018-02-04 00:00Z","local":3,"UTC":0}
    ]
  },
  "$schema": "https://vega.github.io/schema/vega-lite/v2.6.0.json"
}
```

**Comment by domoritz** [comment] 2018-07-27 20:52
If you're using UTC, you should use the UTC time units: https://vega.github.io/vega-lite/docs/timeunit.html#utc

**Comment by iliatimofeev** [comment] 2018-07-27 21:06
Well I read it twice, I can't find any mention why I can't show UTC or local depending on what I put in data.
only warning about double conversion on `scale` but I don't use it.
>Do not use UTC time unit and the UTC scale type at the same time since that will cause Vega-Lite to shift the output time twice.

The only issue I can see that "2018-02-01" is interpreted as UTC, but i believe that it should be local and if it is ISO than it has to be local if it is not ISO it has to be local accoding to documentation
![visualization 32](https://user-images.githubusercontent.com/11561581/43346374-881bd4bc-91f9-11e8-97ff-25a3029e442a.png)

**Comment by domoritz** [comment] 2018-07-27 21:18
Except that JavaScript interprets strings in a particular way: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse

Thanks for the. We will look at these and see what we can do from the Vega-Lite and Vega side.

**Comment by ijlyttle** [comment] 2018-07-27 21:38
I don't know if this is the same issue or a separate issue (happy to file a different one if need be) 

My issue is with how the tooltip is not parsing to UTC as I would expect. (or I'm doing something wrong).

Here it is, in action: https://bl.ocks.org/ijlyttle/84ce12ce2c1093070f645a2bae3b8fa0

The spec:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "Tooltip issue",
  "data": {
    "values": [
      {
        "date": "2018-01-01",
        "interval_start_utc": "2018-01-01T00:00:00Z",
        "interval_end_utc": "2018-01-02T00:00:00Z",
        "value": 0.0932
      },
      {
        "date": "2018-01-02",
        "interval_start_utc": "2018-01-02T00:00:00Z",
        "interval_end_utc": "2018-01-03T00:00:00Z",
        "value": 0.4407
      },
      {
        "date": "2018-01-03",
        "interval_start_utc": "2018-01-03T00:00:00Z",
        "interval_end_utc": "2018-01-04T00:00:00Z",
        "value": 0.4625
      },
      {
        "date": "2018-01-04",
        "interval_start_utc": "2018-01-04T00:00:00Z",
        "interval_end_utc": "2018-01-05T00:00:00Z",
        "value": 0.3028
      },
      {
        "date": "2018-01-05",
        "interval_start_utc": "2018-01-05T00:00:00Z",
        "interval_end_utc": "2018-01-06T00:00:00Z",
        "value": 0.3285
      },
      {
        "date": "2018-01-06",
        "interval_start_utc": "2018-01-06T00:00:00Z",
        "interval_end_utc": "2018-01-07T00:00:00Z",
        "value": 0.15
      },
      {
        "date": "2018-01-07",
        "interval_start_utc": "2018-01-07T00:00:00Z",
        "interval_end_utc": "2018-01-08T00:00:00Z",
        "value": 0.2946
      }
    ]
  },
  "mark": "rect",
  "encoding": {
    "x": {
      "field": "interval_start_utc",
      "scale": {
        "type": "utc"
      },
      "title": "date",
      "type": "temporal"
    },
    "x2": {
      "field": "interval_end_utc",
      "type": "temporal"
    },
    "color": {
      "field": "value",
      "type": "quantitative"
    },
    "tooltip": [
      {
        "field": "date",
        "type": "temporal",
        "format": "%Y-%m-%d"
      },
      {
        "field": "value",
        "type": "quantitative"
      }
    ]
  }
}
```

**Comment by jakevdp** [comment] 2018-07-27 21:40
Copying a comment from slack to get it here. I also initially expected the same as you, but it turns out the current behavior (shown in the left-most plot) is consistent with the documented behavior of javascript date parsing (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse)

> The date time string may be in a simplified ISO 8601 format. For example, "2011-10-10" (just date) or "2011-10-10T14:48:00" (date and time) can be passed and parsed. Where the string is ISO 8601 date only, the UTC time zone is used to interpret arguments. If the string is date and time in ISO 8601 format, it will be treated as local.

When you use an ISO fragment, it it treated as UTC, while a full ISO string is treated as local time.

So the question I suppose is whether this is a big enough problem that it should be bypassed by creating a custom date parser.

**Comment by iliatimofeev** [comment] 2018-07-27 21:44
vega
```json
{
  "$schema": "https://vega.github.io/schema/vega/v3.json",
  "autosize": "pad",
  "padding": 5,
  "data": [
    {
      "name": "table",
      "values": [
        {"date": "2018-02-01", "local": 0, "UTC": 21},
        {"date": "2018-02-02 00:00", "local": 0, "UTC": 21},
        {"date": "2018-02-03 00:00 UTC", "local": 3, "UTC": 0},
        {"date": "2018-02-04 00:00Z", "local": 3, "UTC": 0}
      ],
      "transform": [
        {"type": "formula", "expr": "toDate(datum['date'])", "as": "timestamp"},
      {"type": "formula", "expr": "hours(datum['timestamp'])", "as": "hrs"},
      {"type": "formula", "expr": "utchours(datum['timestamp'])", "as": "utchrs"},
      {"type": "formula", "expr": "date(datum['timestamp'])", "as": "day"}
      ]
    }
  ],
    
 
  "marks": [
    {
      "name": "layer_0_marks",
      "type": "symbol",
      "style": ["point"],
      "from": {"data": "table"},
      "encode": {
        "update": {
          "opacity": {"value": 0.7},
          "fill": {"value": "transparent"},
          "stroke": {"value": "#3366cc"},
          "x": {"scale": "x", "field": "day"},
          "y": {"scale": "y", "field": "hrs"}
        }
      }
    },
    {
      "name": "layer_1_marks",
      "type": "symbol",
      "style": ["point"],
      "from": {"data": "table"},
      "encode": {
        "update": {
          "opacity": {"value": 0.7},
          "shape": {"value": "square"},
          "fill": {"value": "transparent"},
          "stroke": {"value": "#dc3912"},
          "x": {"scale": "x", "field": "day"},
          "y": {"scale": "y", "field": "utchrs"}
        }
      }
    }
  ],
  "scales": [
    {
      "name": "x",
      "type": "point",
      "domain": {
        "fields": [
          {"data": "table", "field": "day"}
        ],
        "sort": true
      },
      "range": {"step": 22},
      "padding": 0.5
    },
    {
      "name": "y",
      "type": "point",
      "domain": {
        "fields": [
          {"data": "table", "field": "hrs"},
          {"data": "table", "field": "utchrs"}
        ],
        "sort": true
      },
      "range": {"step": 22},
      "padding": 0.5
    }
  ],
  "axes": [
    {
      "scale": "x",
      "orient": "top",
      "grid": false,
      "title": "date",
      "labelOverlap": true,
      "encode": {
        "labels": {
          "update": {
            "text": {"signal": "format(datum.value, ',')"},
            "angle": {"value": 270},
            "align": {"value": "left"},
            "baseline": {"value": "middle"}
          }
        }
      },
      "zindex": 1
    },
    {
      "scale": "y",
      "orient": "left",
      "grid": false,
      "title": "local, UTC",
      "labelOverlap": true,
      "zindex": 1
    }
  ]
}
```
![visualization 33](https://user-images.githubusercontent.com/11561581/43347760-6dc0e3e0-91ff-11e8-8f18-2f5e36579c01.png)

**Comment by jakevdp** [comment] 2018-07-27 21:45
@ijlyttle

The issue is that ``"2018-01-01"`` is parsed as UTC. If you want it to be parsed as local time, then you can use ``"2018-01-01T00:00:00"``.

**Comment by ijlyttle** [comment] 2018-07-27 21:50
@jakevdp In this case, I want to keep everything as UTC so that the rendering is insensitive to the browser's time-zone. I found a fix, the tooltip encoding can accept a UTC scale.

**Comment by jakevdp** [comment] 2018-07-27 21:52
My preferred solution for Altair is to try to keep everything local, because by default vega/vega-lite renders in local time. I'd rather have the default just work than require users to manually flag all outputs as UTC every time they use temporal data.

**Comment by iliatimofeev** [comment] 2018-07-27 22:31
In fact it is the same issue https://github.com/vega/vega-lite/issues/4044 I just found it, sorry for doubling issue.

**Comment by domoritz** [comment] 2018-07-27 22:32
Also https://github.com/vega/vega-lite/pull/4094

**Comment by kanitw** [comment] 2019-06-08 05:20
Since it's the same as https://github.com/vega/vega-lite/issues/4044 and https://github.com/vega/vega-lite/issues/4044 is a wontfix, I'll close this too. 

Please feel free to reopen if you have a suggestion for better solution.

**Closed by kanitw** 2019-06-08 05:20 UTC
Labels: Bug :bug:, Enhancement :tada:
