### ISSUE TITLE
Fix domains of scales with filtered domains

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#4513] opened 2019-01-30 20:51 UTC
With Vega-Lite selections, we can filter data to match a selection. However, this causes scales to jump uncontrollably inhibiting users ability to make comparisons. It would be nice to have a way to fix scale domain to their initial domain. 

requested by @jheer

**Comment by kanitw** [comment] 2019-02-24 06:56
One possible hack that could work for now is to add another layer for the unfiltered data with opacity = 0.  Obviously allowing this without a hack is probably useful

**Comment by arvind** [comment] 2019-06-07 17:53
Duplicate of #4327.

**Closed by arvind** 2019-06-07 17:53 UTC
Labels: Feature Request :raising_hand_woman:, P0 – Critical :fire:
