### ISSUE TITLE
Sorting not working (potential bug)

### ISSUE THREAD

**Issue by Alcampopiano** [vega/vega-lite#4075] opened 2018-07-23 18:26 UTC
## this sorts nicely:
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.4.3.json",
  "config": {
    "axis": {
      "labelFontSize": 20,
      "titleFontSize": 20
    },
    "legend": {
      "labelFontSize": 20,
      "legendTitle": "asdf",
      "symbolSize": 100,
      "titleFontSize": 20
    },
    "scale": {
      "bandPaddingInner": 0.5
    },
    "style": {
      "bar": {
        "size": 20
      }
    }
  },
  "encoding": {
    "color": {
      "legend": {
        "title": "help"
      }
    },
    "x": {
      "axis": {
        "title": "options"
      },
      "scale": {
        "paddingInner": 0.5,
        "paddingOuter": 0.5
      }
    },
    "y": {
      "axis": {
        "title": "percentage of students"
      }
    }
  },
  "height": 300,
  "layer": [
    {
      "data": {
        "values": [
          {
            "Options": "personal interests",
            "Percentage of Students": 47,
            "nums": 934
          },
          {
            "Options": "visits to or from colleges/universities/workplaces",
            "Percentage of Students": 15,
            "nums": 296
          },
          {
            "Options": "exploration on the internet",
            "Percentage of Students": 8,
            "nums": 165
          },
          {
            "Options": "presentations - guest speakers",
            "Percentage of Students": 5,
            "nums": 100
          },
          {
            "Options": "volunteering",
            "Percentage of Students": 4,
            "nums": 88
          },
          {
            "Options": "information sessions",
            "Percentage of Students": 4,
            "nums": 83
          },
          {
            "Options": "leadership opportunities",
            "Percentage of Students": 3,
            "nums": 65
          },
          {
            "Options": "myblueprint - ipp",
            "Percentage of Students": 3,
            "nums": 59
          }
        ]
      },
      "encoding": {
        "color": {
          "field": "Options",
          "legend": null,
          "type": "nominal"
        },
        "x": {
          "field": "Percentage of Students",
          "type": "quantitative"
        },
        "y": {
          "field": "Options",
          "sort": {
            "field": "Percentage of Students",
            "op": "count",
            "order": "ascending"
          },
          "type": "nominal"
        }
      },
      "height": 300,
      "mark": {
        "size": 20,
        "type": "bar"
      },
      "width": 1000
    },
    {
      "data": {
        "values": [
          {
            "Options": "personal interests",
            "Percentage of Students": 47,
            "nums": 934
          },
          {
            "Options": "visits to or from colleges/universities/workplaces",
            "Percentage of Students": 15,
            "nums": 296
          },
          {
            "Options": "exploration on the internet",
            "Percentage of Students": 8,
            "nums": 165
          },
          {
            "Options": "presentations - guest speakers",
            "Percentage of Students": 5,
            "nums": 100
          },
          {
            "Options": "volunteering",
            "Percentage of Students": 4,
            "nums": 88
          },
          {
            "Options": "information sessions",
            "Percentage of Students": 4,
            "nums": 83
          },
          {
            "Options": "leadership opportunities",
            "Percentage of Students": 3,
            "nums": 65
          },
          {
            "Options": "myblueprint - ipp",
            "Percentage of Students": 3,
            "nums": 59
          }
        ]
      },
      "encoding": {
        "text": {
          "field": "Percentage of Students",
          "type": "quantitative"
        },
        "x": {
          "field": "Percentage of Students",
          "type": "quantitative"
        },
        "y": {
          "field": "Options",
          "sort": {
            "field": "Percentage of Students",
            "op": "count",
            "order": "ascending"
          },
          "type": "nominal"
        }
      },
      "height": 300,
      "mark": {
        "align": "left",
        "baseline": "middle",
        "dx": 5,
        "size": 20,
        "type": "text"
      },
      "width": 1000
    }
  ],
  "width": 400
}
```

## this does not seem to sort (and I think it is the same as the last example but with different data

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.4.3.json",
  "config": {
    "axis": {
      "labelFontSize": 20,
      "titleFontSize": 20
    },
    "legend": {
      "labelFontSize": 20,
      "legendTitle": "asdf",
      "symbolSize": 100,
      "titleFontSize": 20
    },
    "scale": {
      "bandPaddingInner": 0.5
    },
    "style": {
      "bar": {
        "size": 20
      }
    }
  },
  "encoding": {
    "color": {
      "legend": {
        "title": "help"
      }
    },
    "x": {
      "axis": {
        "title": "options"
      },
      "scale": {
        "paddingInner": 0.5,
        "paddingOuter": 0.5
      }
    },
    "y": {
      "axis": {
        "title": "percentage of students"
      }
    }
  },
  "height": 300,
  "layer": [
    {
      "data": {
        "values": [
          {
            "Options": "Never",
            "Percentage of Students": 10
          },
          {
            "Options": "Once a month",
            "Percentage of Students": 8
          },
          {
            "Options": "Once a week",
            "Percentage of Students": 2
          },
          {
            "Options": "Once a year",
            "Percentage of Students": 30
          },
          {
            "Options": "Once every few months",
            "Percentage of Students": 30
          },
          {
            "Options": "Twice a year",
            "Percentage of Students": 19
          }
        ]
      },
      "encoding": {
        "color": {
          "field": "Options",
          "legend": null,
          "type": "nominal"
        },
        "x": {
          "field": "Percentage of Students",
          "type": "quantitative"
        },
        "y": {
          "field": "Options",
          "sort": {
            "field": "Options",
            "op": "mean",
            "order": "ascending"
          },
          "type": "nominal"
        }
      },
      "height": 300,
      "mark": {
        "size": 20,
        "type": "bar"
      },
      "width": 1000
    },
    {
      "data": {
        "values": [
          {
            "Options": "Never",
            "Percentage of Students": 10
          },
          {
            "Options": "Once a month",
            "Percentage of Students": 8
          },
          {
            "Options": "Once a week",
            "Percentage of Students": 2
          },
          {
            "Options": "Once a year",
            "Percentage of Students": 30
          },
          {
            "Options": "Once every few months",
            "Percentage of Students": 30
          },
          {
            "Options": "Twice a year",
            "Percentage of Students": 19
          }
        ]
      },
      "encoding": {
        "text": {
          "field": "Percentage of Students",
          "type": "quantitative"
        },
        "x": {
          "field": "Percentage of Students",
          "type": "quantitative"
        },
        "y": {
          "field": "Options",
          "sort": {
            "field": "Percentage of Students",
            "op": "count",
            "order": "ascending"
          },
          "type": "nominal"
        }
      },
      "height": 300,
      "mark": {
        "align": "left",
        "baseline": "middle",
        "dx": 5,
        "size": 20,
        "type": "text"
      },
      "width": 1000
    }
  ],
  "width": 400
}
```

**Comment by Alcampopiano** [comment] 2018-07-23 18:52
Perhaps it has something to do with the fact that there is no aggregate needed (since the data are already aggregated beforehand). Unsure how to use the required `op` option in that case.

**Comment by domoritz** [comment] 2018-07-23 20:02
What are you trying to sort by? Can you create a smaller example that demonstrates the bug? Note that Vega-Lite does not always support sorting layers by something other than count aggregates. This will be improved in Vega-Lite 3. Could you try it and see whether it fixes this issue?

**Comment by Alcampopiano** [comment] 2018-07-23 20:07
I am trying to sort the categorical variables in the bar chart by the quantitative values of each bar. Here is a smaller example (I'm not sure I can make it that much smaller unfortunately):

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.4.3.json",
  "layer": [
    {
      "data": {
        "values": [
          {"Percentage of Students": 62, "num": 1256, "vari": "excited"},
          {"Percentage of Students": 11, "num": 238, "vari": "confident"},
          {"Percentage of Students": 8, "num": 167, "vari": "worried"},
          {"Percentage of Students": 14, "num": 296, "vari": "not sure"}
        ]
      },
      "encoding": {
        "color": {"field": "vari", "legend": null, "type": "nominal"},
        "x": {
          "field": "vari",
          "sort": ["excited", "not sure", "confident", "worried"],
          "type": "nominal"
        },
        "y": {"field": "Percentage of Students", "type": "quantitative"}
      },
      "mark": {"type": "bar"}
    },
    {
      "data": {
        "values": [
          {"Percentage of Students": 62, "num": 1256, "vari": "excited"},
          {"Percentage of Students": 11, "num": 238, "vari": "confident"},
          {"Percentage of Students": 8, "num": 167, "vari": "worried"},
          {"Percentage of Students": 14, "num": 296, "vari": "not sure"}
        ]
      },
      "encoding": {
        "text": {"field": "Percentage of Students", "type": "quantitative"},
        "x": {
          "field": "vari",
          "sort": ["excited", "not sure", "confident", "worried"],
          "type": "nominal"
        },
        "y": {"field": "Percentage of Students", "type": "quantitative"}
      },
      "mark": {"type": "text"}
    }
  ]
}
```

**Comment by domoritz** [comment] 2018-07-23 20:13
Duplicate of https://github.com/vega/vega-lite/issues/3710 and https://github.com/vega/vega-lite/issues/3153

**Closed by domoritz** 2018-07-23 20:13 UTC

**Comment by Alcampopiano** [comment] 2018-07-23 20:35
Eureka (until a permanent fix is released).

If you explicitly order the data values first and then set the usual sort options (`op...field...order`), the data will be sorted; at least this is what you can see in this example. Note that the `ascending` option works in the opposite way. But hey, at least the data are sorted.

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.4.3.json",
  "layer": [
    {
      "data": {
        "values": [
          {"Percentage of Students": 62, "num": 1256, "vari": "excited"},
          {"Percentage of Students": 14, "num": 238, "vari": "confident"},
          {"Percentage of Students": 11, "num": 167, "vari": "worried"},
          {"Percentage of Students": 8, "num": 296, "vari": "not sure"}
        ]
      },
      "encoding": {
        "color": {"field": "vari", "legend": null, "type": "nominal"},
        "x": {
          "field": "vari",
          "sort": {"op": "count", "field": "Percentage of Students", "order": "ascending"},
          "type": "nominal"
        },
        "y": {"field": "Percentage of Students", "type": "quantitative"}
      },
      "mark": {"type": "bar"}
    },
    {
      "data": {
        "values": [
          {"Percentage of Students": 62, "num": 1256, "vari": "excited"},
          {"Percentage of Students": 14, "num": 238, "vari": "confident"},
          {"Percentage of Students": 11, "num": 167, "vari": "worried"},
          {"Percentage of Students": 8, "num": 296, "vari": "not sure"}
        ]
      },
      "encoding": {
        "text": {"field": "Percentage of Students", "type": "quantitative"},
        "x": {
          "field": "vari",
          "sort": {"op": "count", "field": "Percentage of Students", "order": "ascending"},
          "type": "nominal"
        },
        "y": {"field": "Percentage of Students", "type": "quantitative"}
      },
      "mark": {"type": "text"}
    }
  ]
}
```

**Comment by domoritz** [comment] 2018-07-23 20:38
Thank you for posting this @Alcampopiano!
