### ISSUE TITLE
Sorting values on a color legend.

### ISSUE THREAD

**Issue by yhoonkim** [vega/vega-lite#2069] opened 2017-04-03 00:06 UTC
I'd like to sort nominal values on color channel.
First I drew this,
```json
{
    "$schema": "https://vega.github.io/schema/vega-lite/v2.0.json",
    "data": {"url": "https://vega.github.io/vega-datasets/data/cars.json"},
    "mark": "bar",
    "encoding": {
      "x": {
        "field": "*",
        "type": "quantitative",
        "aggregate": "count"
      },
      "y": {
        "field": "Origin",
        "type": "nominal",
        "sort": {"field": "*","order": "descending","op": "count"}
      },
      "color": {
        "field": "Origin",
        "type": "nominal",
        "sort": {"field": "*","order": "ascending","op": "count"}
      }
    }
  }
```
Result : 

![vega 14](https://cloud.githubusercontent.com/assets/6269456/24592137/3d6f7328-17c6-11e7-9cc3-be88e48ea814.png)

Then I sorted with this spec with expecting to change an order of values on the color legend (USA->Japan -> Europe). 
```
{
    "$schema": "https://vega.github.io/schema/vega-lite/v2.0.json",
    "data": {"url": "https://vega.github.io/vega-datasets/data/cars.json"},
    "mark": "bar",
    "encoding": {
      "x": {
        "field": "*",
        "type": "quantitative",
        "aggregate": "count"
      },
      "y": {
        "field": "Origin",
        "type": "nominal",
        "sort": {"field": "*","order": "descending","op": "count"}
      },
      "color": {
        "field": "Origin",
        "type": "nominal",
        "sort": {"field": "*","order": "ascending","op": "count"}
      }
    }
  }
```
Result : 
![vega 13](https://cloud.githubusercontent.com/assets/6269456/24592090/28de9e76-17c5-11e7-89ec-12407a2f87a1.png)

Hope to know how to sort values on legend and whether it is intended to change color values when sorting color channel.

**Comment by kanitw** [comment] 2017-04-04 17:32
@yhoonkim I just checked, this looks like a Vega bug.  Could you please help file a bug in Vega?

**Comment by yhoonkim** [comment] 2017-04-04 17:38
@kanitw Sure! To make clear, the different background color is not an issue. (I made that change.)

**Comment by kanitw** [comment] 2017-04-05 04:24
Sure.  The problem is that reverse make Vega scale uses the end of category 10 instead of correctly reversing the domain.  Once you file a bug in Vega, please also close this issue.

**Comment by yhoonkim** [comment] 2017-04-05 19:46
@kanitw 
It turns out [`reverse` is intended to flip all colors.](https://github.com/vega/vega/issues/770#issuecomment-291971323)

Given this, does this issue is still closed?

**Comment by kanitw** [comment] 2017-04-05 20:28
Seems like the solution is that we can modify our scale code to output sort's `order` instead of using the `reverse` property like this: https://github.com/vega/vega/issues/770#issuecomment-291986630.

**Closed** 2017-05-29 23:28 UTC
