### ISSUE TITLE
`config.axisX.labelAngle` has no effect (or re-open issue #2751)

### ISSUE THREAD

**Issue by g3o2** [vega/vega-lite#3050] opened 2017-09-30 15:16 UTC
See  #2751 with the current vega-lite rc3 version.

**Comment by domoritz** [comment] 2017-09-30 17:39
This seems to be a regression of https://github.com/vega/vega-lite/issues/2683.

**Comment by domoritz** [comment] 2017-09-30 18:08
Fixed in https://github.com/vega/vega-lite/pull/3031, I believe.

**Closed by domoritz** 2017-09-30 18:08 UTC
