### ISSUE TITLE
Sorting by nominal field fails in some circumstances

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#6064] opened 2020-03-11 03:02 UTC
This specification does not show the expected sort order in the y axis ([vega editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4yghSA3WAbArgKYDOKYA2uBhMNnmQIwA0UusARobmZAIKQBfJlWq0c3VACYWkNpwlQAQoOHUadBQGYZcrj34CRYALpUhVSAFtYAJwDWPdrciqohAHYBjAPbQAlu4A5mToGJAAHiGQAGZ+XNA84i5Q8ACeAA6EPACO+LDu8H6IhVhZ5tSQqVGx8Yn0MmmZPN42-u71UMQt8NVxuAmoshx6AuVhPrgtvbWDutwNGVmD7t6WAfSGEIYCQA)):
```json
{
  "data": {
    "values": [
      {"val": 1, "label": "A"},
      {"val": 2, "label": "B"},
      {"val": 3, "label": "A"}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "val", "type": "quantitative"},
    "y": {"field": "val", "type": "ordinal", "sort": {"field": "label"}},
    "color": {"field": "label", "type": "nominal"}
  }
}
```
![visualization - 2020-03-10T173712 567](https://user-images.githubusercontent.com/781659/76370954-cb90de80-62f5-11ea-98e7-4315df2dc7d5.png)

This bug only shows up with a specific combination of features; for example, the sort works correctly when doing any of the following:

- Removing the ``x`` encoding ([vega editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4yghSA3WAbArgKYDOKYA2uBhMNnmQIwA0UusARobmZAIKQBfJlWq0c3VACYWkNpwlQAQoOHUadBQGYZcrj34CRYALpUhVSAFtYAJwDWPdrciqohAHYBjAPbQAlu4A5mToGJAAniGQAGZ+XNA84i5Q8OEADoQ83jb+7vQyxNnwUbHxPLrcAubUkD642SVxuAmoshx6MqkZPO7elgH0hhCGAkA)):
   ![visualization - 2020-03-10T195507 073](https://user-images.githubusercontent.com/781659/76377794-10724080-6309-11ea-94c7-02f4337d970a.png)

- Removing the ``color`` encoding ([vega editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4yghSA3WAbArgKYDOKYA2uBhMNnmQIwA0UusARobmZAIKQBfJlWq0c3VACYWkNpwlQAQoOHUadBQGYZcrj34CRYALpUhVSAFtYAJwDWPdrciqohAHYBjAPbQAlu4A5mToGJAAHiGQAGZ+XNA84i5Q8ACeAA6EPACO+LDu8H6IhVhZ5tSQqVGx8Yn0MmmZPN42-u71UMQt8NVxuAmoshx6AoYQhgJAA)):
   ![visualization - 2020-03-10T195425 246](https://user-images.githubusercontent.com/781659/76377762-f89abc80-6308-11ea-93b9-fb249f806d2e.png)

- Sorting by numeric rather than string data ([vega editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4yghSA3WAbArgKYDOKYA2uBhMNnmQIwA0UusARobowL5NXVaObqgBMLSG04iwovgIxD6qAMwSpXXgoC6VeZgC2sAE4BrMpHYnI-TIQB2AYwD20AJb2A5mXQZIADx9IADM3LmgLYRsoeABPAAdCCwBHfFh7eDdETKwk-T9YoNDwyPoJOMSLZ2N3ezKoYmr4IrDcCNRJDk0efMwXXGqWko6NbnKEpI77ZwMPeh49EB4gA))
:
   ![visualization - 2020-03-10T195719 328](https://user-images.githubusercontent.com/781659/76377957-6cd56000-6309-11ea-9cc5-d30422e5a9e7.png)

First noticed in https://stackoverflow.com/questions/60626992/sorting-based-on-the-alt-color-field-in-altair/60627255

**Comment by domoritz** [comment] 2020-03-11 04:14
The issue is that we apply `sum` aggregation to the label.

<img width="454" alt="Screen Shot 2020-03-10 at 21 14 01" src="https://user-images.githubusercontent.com/589034/76381910-17eb1700-6314-11ea-9717-5851b7805ab8.png">

**Comment by domoritz** [comment] 2020-03-11 04:16
We do apply sum because the bars are stacked but in this case we are not aggregating the stacked field.

**Comment by domoritz** [comment] 2020-03-11 04:32
Fixed in https://github.com/vega/vega-lite/pull/6065 by disabling the smartness to use sum for stacked charts.

**Comment by domoritz** [comment] 2020-03-12 01:59
Actually fixed in https://github.com/vega/vega-lite/issues/6064

**Closed** 2020-03-12 05:35 UTC
Labels: Bug :bug:, P2
