### ISSUE TITLE
LegendLayout schema is empty

### ISSUE THREAD

**Issue by marcprux** [vega/vega-lite#6240] opened 2020-04-02 12:42 UTC
VL 4.9.0's schema's (https://github.com/vega/schema/blob/master/vega-lite/v4.9.0.json#L10787) `LegendLayout` def is not being generated, and `LegendConfig.layout` is an odd `not` construct:

```json
    "layout": {
        "description": "Legend orient group layout parameters.",
          "not": {
        }
```

The last schema to have the `layout` property defined correctly was 4.1.1 (https://github.com/vega/schema/blob/master/vega-lite/v4.1.1.json#L9515): 

```json
        "layout": {
          "$ref": "#/definitions/LegendLayout",
          "description": "Legend orient group layout parameters."
        }
```

So it would seem that this issue was introduced around 4.2.0.

**Comment by marcprux** [comment] 2020-04-02 12:49
This may have something to do with `export interface LegendLayout extends BaseLegendLayout` in https://github.com/vega/vega/blob/eced44eb31fc4d64d36b165a360430fee450ad9e/packages/vega-typings/types/spec/config.d.ts#L451 

If I manually remove `extends BaseLegendLayout` and re-generate the typings, it does generate a ref:

```shell

marc@bix vega-lite % yarn schema && grep --after-context=3 'layout": ' build/vega-lite-schema.json
yarn run v1.22.4
$ mkdir -p build && ts-json-schema-generator -f tsconfig.json -p src/index.ts -t TopLevelSpec --no-type-check --no-ref-encode > build/vega-lite-schema.json && yarn renameschema && cp build/vega-lite-schema.json site/_data/
$ scripts/rename-schema.sh
✨  Done in 4.15s.
        "layout": {
          "$ref": "#/definitions/LegendLayout",
          "description": "Legend orient group layout parameters."
        },
```

**Comment by marcprux** [comment] 2020-04-02 12:54
If I rename `BaseLegendLayout.offset` to `BaseLegendLayout.offsetXXX` in `config.d.ts`, then the `LegendLayout` ref is generated successfully. Perhaps the typescript generator doesn't like the property name `offset`, or it is conflicting with another `offset` property somewhere?

**Comment by marcprux** [comment] 2020-04-02 13:04
Perhaps related to https://github.com/vega/ts-json-schema-generator/issues/344 ? It should be noted that the schema is generated fine with `margin?: number | SignalRef`, but fails with `offset?: number | SignalRef`, so it seems like the keyword `offset` is conflicting with something.

**Comment by marcprux** [comment] 2020-04-02 13:16
Changing `offset?: number | SignalRef` to `offset?: boolean | SignalRef` also results in the schema being generated correctly, but `offset?: number` fails, as does `offset?: someTypeThatIsAliasedToNumber`.

**Comment by marcprux** [comment] 2020-04-02 13:43
If I edit `type NumericValueRef` in `encode.d.ts` to change `offset?: number | NumericValueRef` to `offsetXXX?: number | NumericValueRef`, then the `LegendLayout` is generated successfully with its `offset?: number | SignalRef` property. So perhaps there is conflict between `NumericValueRef.offset` and `BaseLegendLayout.offset`.

**Comment by domoritz** [comment] 2020-04-02 17:46
Looks like the schema generator is doing the right thing. Layout is `never` and `not: {}` reflects that. 

<img width="1020" alt="Screen Shot 2020-04-02 at 10 46 15" src="https://user-images.githubusercontent.com/589034/78281219-34234380-74cf-11ea-9be2-0619aa8f0d15.png">

**Comment by domoritz** [comment] 2020-04-02 17:59
Small example to reproduce the issue. 

```ts
export type LegendConfig2 = ExcludeMappedValueRefButKeepSignal<{
  layout?: LegendLayout;
}>;

export const config: LegendConfig2 = {
  layout: 1
};
```

You are right, @marcprux, the issue is somewhere in the `NumericValueRef`.that we use in ExcludeMappedValueRefButKeepSignal.

**Comment by domoritz** [comment] 2020-04-02 18:03
I found one issue. We should not even have to use `ExcludeMappedValueRefButKeepSignal` here since `VgLegendConfig` should not support value refs in the first place. Let's fix that and see whether this solved the issue.

**Comment by domoritz** [comment] 2020-04-02 18:26
Thanks for the investigation. It really helped me find the core of the issue. 

Fixed in https://github.com/vega/vega-lite/pull/6242

**Closed by domoritz** 2020-04-02 18:26 UTC
Labels: Bug :bug:
