### ISSUE TITLE
Support valid value for order indicating not to order input data

### ISSUE THREAD

**Issue by willium** [vega/vega-lite#3300] opened 2018-01-24 06:36 UTC
Sometimes a user may not want a line to default order their data. This might be a rare occurrence, but when it happens there's no easy way to vega to respect the indexed order of the data. I propose a
```"order": "index"```
or similar, alongside "ascending" and "descending"

**Comment by domoritz** [comment] 2018-01-24 07:22
This should be covered by `order: null`. Do you have an example where this does not work?

**Comment by kanitw** [comment] 2018-01-24 17:44
Duplicate of https://github.com/vega/vega-lite/issues/1020

**Closed by kanitw** 2018-01-24 17:44 UTC
