### ISSUE TITLE
Initial interval selection `{"empty": "all"}` on VConcatChart with temporal field is empty

### ISSUE THREAD

**Issue by jnj16180340** [vega/vega-lite#6742] opened 2020-07-17 20:42 UTC
This one renders fine, but an empty selection renders as "none" even though {"empty":"all"} is set.       

It seems to show up in these circumstances although I haven't worked out the exact combination:
- LookupTransform on data
- Selection on temporal X axis
- Selection on one VConcat element sets the domain on a different VConcat element

The `time_parse` transformation doesn't seem to affect it, e.g. replacing all the datetime strings with integer timestamps shows the same behavior.       

Does anyone know of a workaround, or a way to dynamically set the initial selection to data bounds? This is normally used with named datasets, but I inlined the data for this example.      

[In Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAHJQCMlAFYQ2AOxAAaEEgaY2EGgC84aUFBWYkNZRDQgcSACb3LZdSABOcPYbSY3DOBqYAJ44RugAZnQgAL4apsqRLqigxDRwAO7GIPGYlgxsDBAAEnA0ZFhoAMwADNVxZnkFEADqNPb0aGK10bEg9kjmWcpICGF9AwJIcADsTACcMgCsc4sycFAAbJWrTOFIMkhIAExi4VAylVArizEa-eYQcJjWyePm-GJMR9OSc2LbkmqSEW9nCGw202q9jEi2qTEW0zWcyYcGqaAA2qAAPptGwAUQAHqE3DRRspMFixNNXEgoABHLG5UZoDbVSjVI53CaPCnDZnoI61VmVLEAJQYykWWJkvzmrjggm07GUjNJYVZ7JkG0WGjgynsqv5IEFgv41WmZskAAJqmJUDIZKhKtaAIIAWVckUEcCxXjCkiOMmm00WRyOix1IGgSCsWIQLxk1UkAY00dj8fjaFW1TmdSjUBjEEZbHMghZMjm005UfMbgpTLGJuqZotSZtlXtjsq0yt7tu2Nx6EJxLV5Mpkhp9MN6rZHK5DyeWL5jdqockYol0skCPlityKmnLNnR2duv1h4FHOb5stNsWqEWGwfMl7Ho0Xp9frQiY2YhWkg2CsZFTAt0wTP8NjmEDCzjCBM1QI5czEYD8xgnRS06LpE1TWt6zVGwmxbW9bQfJ9YVffsQBxex8SJOASTJCkxA2ScGQbI92Wre4kB5JcRhXao1w3FUZUWCddT3ZULw1Dkjg2M8DXYy9TRvNtBIfe8xDECj3xob1fQMMIZEDbcNmTRDpmgsDv0kB15NQsD4MDb4xCsot0KQMsnTmSpcxwpA6wvY0ryItS7QjVB-go2IBxooc6IYvUmJuDRaTY-DUBkrjuUXZcCKFQThJkaVcyOXclQPJSZK1KCQD1RSMuClTW2taon2YyK5itAAFN8QA-AzvFQOY-l8iNARQtMi3gi4YWrKbYPgyo7PshaPK8rTAMkfzAqUprrxau9Iva61eso6jaJHRjKTEVjpOPeceNy-j8ra6oRXFZRphK6oZHK-cVSq2ctRQ+qgsI1TWumSKjhhnq+oGr9hqTd7tlhbaHOmhNvnNNzFpeSpuyWPH1s6X8wx2vCjQhw62phyKXzOmKqMHEBh3o0cmMqO6gc4x7eLyy83o+iUNh+tEJIqwGMuqyRKgU8GQshm05lQWpvPhz09M-Qy0AA1ZpjMuTVtArHvxNSbTfxqpphqDG1pLTzOh8xDKcV5riMkNXqidU6PWiABdR7+CmWYFmWVZ1i2HY9gOY5TnOS5rgxUAXQ8FAH1+HNajzF0XmUBhBEEDQACFuoASTQRCqUskAADFmiKD01fZSo5JzjuO66ezRQAFSryg5kQ2qAGVzH1AL7DdAAtTpk0oRZKhhDRe-CNAC6LjQLviq6kspalmbTuAM+7bOO40POWUocEZW3E5ll+8FqzLyuEKrbD68b5u2SDINO87i4Gg+7fkqJQNuCwNBjxjP0NwU9Z6oCrEcMBJxa6r2-OycOS9wRbEFP8EMW9Wbs0SmOKklEj4Z1WDKQUOcL4vAkE-MQgJuwQnBLaSML8q5Dw2NWBuTc0A-yXoCf+OdBTyxAMAhCbIfL2SgRPWBM8WSLzAYBVBa9MrskXt2VYcxuFtzkisAhcU2YJU5vvMh6cqiVmzDQkAl8nSyB8rKH4gZtjZ3YRXKoJ4jgY14d-WQdlhEiNskA-ub8wFiVrrImBcCswBjARWFeajQHBh8o+N6rJAIGJZkYohpjSGHwsZlACFYbF2KQe9EMYhjaBi1OaeyHD7QRzzL4-h7IAwjQ6Z0kakhkIhKqKArBkYomTwUQgrolAsKuRAGghClATwIhQXg4MVSULb2MbvEhB81Cp0KVqZMNRai0PXoXYuIAGnbEYShFpLc2G5kCTnSMEikHJl-JA8e0TRmMOkIvZe0y1Eb1OWs3J11GHmOPlUYylRWSlLoZQKskFHHanejmGUpcPFv0DM0r+rSLiE3ubUasEiLgTN+kM95Iz4GIOQVSRJrSRpbCftMXMkFDYpmyZdDmIKJwFPBQhaOiYYVVAmWGWE0wuhaIdIvNFr9EJyR4diluJwRr4o5GIp5SCtjbDedAiliiBkqNpbM0+ZkdERiDCeaOhiOXEKYty7ZtjCknguNQw5tiCbXzDITGqxlKxLFeWc9Fbc2612uT-BEvkuldJQk86YUhvGj3JfI+BYkkHLVqjM0BpLjLbh8rac0CJ7JApMVysFGdEQ6OhbnF4SCVhVhWN2KF2pCbSqrkvZaGhQ3sm1AKwJiZHmhMJlIHp1ZhlJrQGKtkkzDVyCHn2uSy0ES5h+IWwhxa96gp5RnIMWxISursQCltTp-g0s-nwm5CJd34u3H02Z5kpmjpiZFeePzIwzIPeynenL10sU3VUSCMpz5uqzGA3yWkVjIW8XglCDTviYo7Qqn+XRliRs6UGG9xLlo5m1XIx9VK24npmXIK8UKvUQhqDIRhtci0bKYj++15CqhVNsoBspcKvWAiY7NCMUqA0yq4fKs9bJjYqtReI0JYYJkBhkYmx9TblFob+QPLUYrloVmE4vHRVrP02spHRnZvLINpMFfYgCUml620Es6bxYjzleJ8Qh2QWcUOdLZTG6+I0xEPtGSm+J6a1E1pBg6bcSZtRVNtlp9ZX6SF6Ydbyrhv5jOgIrM6ZiSwUvcO44ek8-wrkOYFUy5zI1Hw3sHQGLVIAvOUvGVOxT9pB6ZJhO9X+JxJCIgi8C79pbx0QZ7UctWWXIIU1PX4jk4JCsdOYjemtywMaVbnt8per61E-ikEKWaOifIOlqtRqLyUusITmICF1VahUrCC78ACXjgxaiy+-LFgm2nJhVcmdDAyl4Jp1WOhBEn8OqPQYmOaxls5VOQgidra6SE3F-TDbYlaTuRTmbbQCDoUco4hFl-j8GHsUYWCqsyU2pGw+wx8+BcmoUKZmRIZaWdWHLDDH+VZq6aOUih-RwpbczJCL3dW6+zjl3JlDKlhTtm272YezmTJ43uFTdjW3BJFWZPebiWmw1zzWQ9NzI+YUtsqNM92yz-bXRbJc76883y70qmCSdWK9xr8LiAlqp2lFPbhFaRK6A2Ds3FdVcnb9KZMykGIiYwiCj3iH6G3B8zmE+3WQrDufDvMMG-jBixyNi143Dttym4PGUnnvfzYXot6d7IVW-XKztnTWl9tQvMixl4GxB4Z9+M-dFsGP6dorKGDPyxXtgJzGSz7uGfsoOL0GP8EHzQ1IWL5SP+uq-Q6pIBLoxmJBqcFCksM5pIS1ST3K1POLKH4uWoS8TUjVgjvz5lJR5O-sPgmcHoPYfIQnln5X260Pti+rrwPFFtoa7I9SUPSDW8X3xbmMnDHGw1xlxAzZTm0zlTXlwD0bwB3-y218irFfzyXfzZ15WdG2BdT6xnURG3H+FtGjkNh33RSWBWHuxG23AK2c1lHdzmTO2J11TGV9wo1VzmUWGYl+EqRNUBAxgrywJjxzErGM0TyoKqWl2G1aQtxd0CRPwHk2y90H0+WfSL1qy2yHTbXGm8RPB6UwJBW5g-zakAm-3UUrBDEEgdEWT-FuzgzkJuVslhHxUATExATAWQkiUvzwxH20NkBqGsIuBzGuxqCmREJMMNyqTcOM0WFkCR0Ji0lsJSNt04T32cMQ0FAzxf08MkXqxAIV3UNJ2vwNVqwbzmgWXM2NgDEZxyQhy5kNxqCZUsJnQ5AozairGcReSALs1AJ-ltHj0CXBGgLbWkxKNiQQL8wHm1ADE2iEOzBGmMPXVMJwIzj-CXgIKA1vRhAjEOz2OWCZTd142-CaQGIwVqAz1kIkUHUQgdDYK+wnRJS4Nq0Dwo24TklBxzCQxWJIVMIDl6EKHolGEGFeEQBRHsAAHkcAAYXhQBaQ4SshTAEAcBtY4o9hBBHhdQnAdA3A0BMTsS6oiQ2A6wfA-AAgowCg3AoAwhCS4Beh7A2B0hlBBA2AHA65tYAA5F6dAfoCAGAJgdk2BVwaMb0OuRE0kquHoDQYgeIAsTAFOfqWkJ4LINwZkrISIBUIxObQIEIMYOkBgGMXIcwXIUgGIXoDwJQQQc014MUsIUAAkGwAUgKOAGiDQIIGwSwewOAUIfUJKC01MUIKALIPUUwJwZQJIEwNgNk-E14LUwQHU-PaCb0IYGgWkgkzyIkrgRAMYHAQQHiZAVwQwdUzMrEhkvU0IGwZQNgBASwJ2XoHQGM3IHATUtIRMmwbiAWF6SssYGsus4YMsXoJ0+M9soxX0XCQ8FMh0voWsiwVQO0hUdYAGZ0pcqAPE1GW4EAZQdMukrMykkstgMsx4RstUAAVR3MVPQCCGPjcAQDMBgHuDgBgGpLgjyEwE8FcGCCrPQA-NRNJIbI9KyCQAJBoHhP6lJOQCvJADAS3ITKMWAWnKyEPOPIrJAG-INKNPJDoAGBoHNJlIwFKHKCvNhA0GQDcAAGssgcA2BLArzfB-BeybBhBlAjBGy3BCxwhIKlTwh1SEAshuIhheS3gBBPhvhfh-gxIgQQQwQIQoRGt4REQ4BkRUQ4KxyXh0QawAoqYjB+ZnpmQg4QAKK4BPT0ALpeg2S2AKKGBWyzLcRmYeIbAJztKpzshPIoBC4BgxgGxuoApHgAAKe4BgBASgCASchsNQAAcgAFIABNfgaKhABK+wK0aK8uVAaKt0DKkeVKnASKgAShiEMvSDaA6HtBzhlNADDLYAjKjOyBjKlNHO1JsF1NQlTNeB3IzNQHpJAm4DzILLghQA0BQu6v3MbP1OrNrPrKHMCDYGbJoFstAHgs7Jyl5B7PQomvQH7Omq3JHKWrHKcrCpcvYiQo6t3NQuGvoiPNGvLNPNGAvKiGvNvPvPJEfK8pfIYDcDfILg-OsCYt-MQBoo4pmpAFMoRNAvAq4rvIGBsFgt6GWvQEQrapnJGvpPGp-JAENONJwrNLYt6HgDKAqAfDzHIqoteBorovJMYo2oxpYrYtTDXJXMXO9HXNJM3PBNROCBsE8jLDPHDOcA0pACdMMqtJjNtJADIDZKYCdn+pADovomIAbNPMwHavQrVCtEeBZrxK-I4qsChv4tQExH6j4oEomCEqNG4g+C+B+FGikuBFBHBEhGhFhEUqRBRDRHhvUoxC0t2nwj0rWoMo0GMtMvZQsrmuststDvtUcrMqOt9uZDiHcs8o-JsB8r8rgECoGGCtCvCrVCirioSqSuipSrSoyqyuipyuirysKuZggBGHzKMk7kDg0BKvaBgG-AqsBKAA)

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.8.1.json",
  "autosize": {
    "contains": "padding",
    "resize": true,
    "type": "fit"
  },
  "config": {
    "view": {
      "continuousHeight": 300,
      "continuousWidth": 400
    }
  },
  "data": {
    "name": "data-ae7b915951ec6351bfa1aa24fc13c955"
  },
  "datasets": {
    "data-4b278943580a5df6670d450b571e9be0": [
      {
        "_id": "Experiment_47",
        "acq_time": 60.02,
        "dataset_name": "200603_Run5_1899",
        "elution_time": 60.0165,
        "end_time": "2020-07-08 04:11:38 AM",
        "file_size": 8217752255,
        "scans_ms": 10882,
        "scans_msms": 51090,
        "scans_total": 61972,
        "start_time": "2020-07-08 03:11:37 AM"
      },
      {
        "_id": "Experiment_48",
        "acq_time": 60.02,
        "dataset_name": "200528_Run_1857",
        "elution_time": 60.0238,
        "end_time": "2020-07-08 05:56:51 AM",
        "file_size": 10649586191,
        "scans_ms": 14969,
        "scans_msms": 29041,
        "scans_total": 44010,
        "start_time": "2020-07-08 04:56:50 AM"
      },
      {
        "_id": "Experiment_46",
        "acq_time": 60.02,
        "dataset_name": "200528_Run_1858",
        "elution_time": 60.0226,
        "end_time": "2020-07-08 05:55:44 AM",
        "file_size": 12185688297,
        "scans_ms": 18116,
        "scans_msms": 21274,
        "scans_total": 39390,
        "start_time": "2020-07-08 04:55:43 AM"
      },
      {
        "_id": "Experiment_45",
        "acq_time": 60.02,
        "dataset_name": "200605_Run1_1902",
        "elution_time": 60.0169,
        "end_time": "2020-07-08 06:46:49 PM",
        "file_size": 9943955801,
        "scans_ms": 13452,
        "scans_msms": 31166,
        "scans_total": 44618,
        "start_time": "2020-07-08 05:46:48 PM"
      },
      {
        "_id": "Experiment_44",
        "acq_time": 60.02,
        "dataset_name": "200603_Run7_1901",
        "elution_time": 60.0161,
        "end_time": "2020-07-08 07:42:42 PM",
        "file_size": 9080335508,
        "scans_ms": 12707,
        "scans_msms": 33715,
        "scans_total": 46422,
        "start_time": "2020-07-08 06:42:41 PM"
      },
      {
        "_id": "Experiment_43",
        "acq_time": 60.02,
        "dataset_name": "200603_Run6_1900",
        "elution_time": 60.0183,
        "end_time": "2020-07-08 09:00:39 PM",
        "file_size": 8651768266,
        "scans_ms": 12021,
        "scans_msms": 37308,
        "scans_total": 49329,
        "start_time": "2020-07-08 08:00:38 PM"
      }
    ],
    "data-ae7b915951ec6351bfa1aa24fc13c955": [
      {
        "Area": 58909000,
        "As": null,
        "BPI": 29477,
        "FWHM": 0.032600000000000406,
        "RT": 2.9299,
        "StandardMZ": 488.5345,
        "Tf": null,
        "_id": "Experiment_47"
      },
      {
        "Area": 370900000,
        "As": 6.661885245901662,
        "BPI": 27210,
        "FWHM": 0.1717000000000013,
        "RT": 13.3291,
        "StandardMZ": 722.3247,
        "Tf": 1.0915346663204375,
        "_id": "Experiment_47"
      },
      {
        "Area": 511820000,
        "As": 4.662480376766045,
        "BPI": 29262,
        "FWHM": 0.13480000000000203,
        "RT": 20.936,
        "StandardMZ": 653.3617,
        "Tf": 6.0533751962322695,
        "_id": "Experiment_47"
      },
      {
        "Area": 397510000,
        "As": 3.1938997821350905,
        "BPI": 32328,
        "FWHM": 0.11160000000000281,
        "RT": 27.3587,
        "StandardMZ": 582.319,
        "Tf": 3.779356060606195,
        "_id": "Experiment_47"
      },
      {
        "Area": 68619000,
        "As": 2.037542662116076,
        "BPI": 15950,
        "FWHM": 0.08299999999999841,
        "RT": 33.3465,
        "StandardMZ": 740.4014,
        "Tf": 2.235724743777421,
        "_id": "Experiment_47"
      },
      {
        "Area": 16883000,
        "As": null,
        "BPI": 35481,
        "FWHM": 0.04590000000000005,
        "RT": 2.8864,
        "StandardMZ": 488.5345,
        "Tf": null,
        "_id": "Experiment_48"
      },
      {
        "Area": 312360000,
        "As": 4.726993865030918,
        "BPI": 27210,
        "FWHM": 0.1333000000000002,
        "RT": 13.4015,
        "StandardMZ": 722.3247,
        "Tf": 0.9963662790697682,
        "_id": "Experiment_48"
      },
      {
        "Area": 263510000,
        "As": 3.422507403751153,
        "BPI": 29262,
        "FWHM": 0.24990000000000023,
        "RT": 22.6335,
        "StandardMZ": 653.3617,
        "Tf": 2.3706896551723635,
        "_id": "Experiment_48"
      },
      {
        "Area": 231320000,
        "As": 3.6223316912971564,
        "BPI": 32327,
        "FWHM": 0.1573999999999991,
        "RT": 27.8289,
        "StandardMZ": 582.319,
        "Tf": 3.0151285930407576,
        "_id": "Experiment_48"
      },
      {
        "Area": 71966000,
        "As": 2.95729537366533,
        "BPI": 23431,
        "FWHM": 0.06510000000000105,
        "RT": 33.8842,
        "StandardMZ": 740.4014,
        "Tf": 1.9210526315790786,
        "_id": "Experiment_48"
      },
      {
        "Area": 17637000,
        "As": null,
        "BPI": 34347,
        "FWHM": 0.057700000000000085,
        "RT": 2.8824,
        "StandardMZ": 488.5345,
        "Tf": null,
        "_id": "Experiment_46"
      },
      {
        "Area": 369180000,
        "As": 5.339449541284371,
        "BPI": 27210,
        "FWHM": 0.14059999999999917,
        "RT": 13.3109,
        "StandardMZ": 722.3247,
        "Tf": 1.0203633167301487,
        "_id": "Experiment_46"
      },
      {
        "Area": 342810000,
        "As": 2.7331804281345553,
        "BPI": 29262,
        "FWHM": 0.2660000000000018,
        "RT": 22.4826,
        "StandardMZ": 653.3617,
        "Tf": 2.1674311926605396,
        "_id": "Experiment_46"
      },
      {
        "Area": 284560000,
        "As": 3.8682634730538283,
        "BPI": 32328,
        "FWHM": 0.18909999999999982,
        "RT": 27.6993,
        "StandardMZ": 582.319,
        "Tf": 2.9161118508654273,
        "_id": "Experiment_46"
      },
      {
        "Area": 92664000,
        "As": 3.1938461538462555,
        "BPI": 23431,
        "FWHM": 0.10079999999999956,
        "RT": 33.8235,
        "StandardMZ": 740.4014,
        "Tf": 1.9619450317124871,
        "_id": "Experiment_46"
      },
      {
        "Area": 74121000,
        "As": 0.0,
        "BPI": 26922,
        "FWHM": 0.026699999999999946,
        "RT": 2.9598,
        "StandardMZ": 488.5345,
        "Tf": 106.80061349693119,
        "_id": "Experiment_45"
      },
      {
        "Area": 298020000,
        "As": 3.9511889862327716,
        "BPI": 27210,
        "FWHM": 0.08880000000000088,
        "RT": 13.3349,
        "StandardMZ": 722.3247,
        "Tf": 1.1045212090424157,
        "_id": "Experiment_45"
      },
      {
        "Area": 423560000,
        "As": 4.273611111111167,
        "BPI": 29262,
        "FWHM": 0.14910000000000068,
        "RT": 20.9356,
        "StandardMZ": 653.3617,
        "Tf": 4.318906605922491,
        "_id": "Experiment_45"
      },
      {
        "Area": 326880000,
        "As": 2.6782786885246117,
        "BPI": 32328,
        "FWHM": 0.09619999999999962,
        "RT": 27.3219,
        "StandardMZ": 582.319,
        "Tf": 2.860849056603737,
        "_id": "Experiment_45"
      },
      {
        "Area": 40818000,
        "As": 2.839034205231745,
        "BPI": 13809,
        "FWHM": 0.0911000000000044,
        "RT": 33.2728,
        "StandardMZ": 740.4014,
        "Tf": 2.7142857142859076,
        "_id": "Experiment_45"
      },
      {
        "Area": 60959000,
        "As": 0.0,
        "BPI": 29477,
        "FWHM": 0.023699999999999832,
        "RT": 2.9183,
        "StandardMZ": 488.5345,
        "Tf": 1.0000000000000135,
        "_id": "Experiment_44"
      },
      {
        "Area": 368820000,
        "As": 6.999999999999892,
        "BPI": 27210,
        "FWHM": 0.19529999999999959,
        "RT": 13.3095,
        "StandardMZ": 722.3247,
        "Tf": 1.1749412072119139,
        "_id": "Experiment_44"
      },
      {
        "Area": 476140000,
        "As": 4.192207792207709,
        "BPI": 29262,
        "FWHM": 0.15110000000000312,
        "RT": 20.9512,
        "StandardMZ": 653.3617,
        "Tf": 5.442857142857023,
        "_id": "Experiment_44"
      },
      {
        "Area": 359710000,
        "As": 2.09104477611935,
        "BPI": 32328,
        "FWHM": 0.12259999999999849,
        "RT": 27.3382,
        "StandardMZ": 582.319,
        "Tf": 2.9910447761193972,
        "_id": "Experiment_44"
      },
      {
        "Area": 38352000,
        "As": 1.971854304635769,
        "BPI": 15950,
        "FWHM": 0.08579999999999899,
        "RT": 33.2951,
        "StandardMZ": 740.4014,
        "Tf": 2.254689754689808,
        "_id": "Experiment_44"
      },
      {
        "Area": 60997000,
        "As": 0.0,
        "BPI": 14262,
        "FWHM": 0.03410000000000002,
        "RT": 2.9318,
        "StandardMZ": 488.5345,
        "Tf": 119.88343558282384,
        "_id": "Experiment_43"
      },
      {
        "Area": 306610000,
        "As": 6.97750511247449,
        "BPI": 27210,
        "FWHM": 0.08150000000000013,
        "RT": 13.3417,
        "StandardMZ": 722.3247,
        "Tf": 1.1309771309771304,
        "_id": "Experiment_43"
      },
      {
        "Area": 442500000,
        "As": 5.173633440514405,
        "BPI": 29262,
        "FWHM": 0.14209999999999923,
        "RT": 20.9628,
        "StandardMZ": 653.3617,
        "Tf": 6.452572347266821,
        "_id": "Experiment_43"
      },
      {
        "Area": 430790000,
        "As": 1.902140672782886,
        "BPI": 32328,
        "FWHM": 0.10490000000000066,
        "RT": 27.3436,
        "StandardMZ": 582.319,
        "Tf": 2.658244680851099,
        "_id": "Experiment_43"
      },
      {
        "Area": 49342000,
        "As": 2.8455598455597944,
        "BPI": 15950,
        "FWHM": 0.09009999999999962,
        "RT": 33.2911,
        "StandardMZ": 740.4014,
        "Tf": 2.714622641509405,
        "_id": "Experiment_43"
      }
    ]
  },
  "usermeta": {
    "embedOptions": {
      "actions": {
        "compiled": false,
        "editor": false,
        "export": true,
        "source": false
      },
      "downloadFileName": "dashboard",
      "scaleFactor": 2
    }
  },
  "vconcat": [
    {
      "facet": {
        "row": {
          "field": "StandardMZ",
          "type": "quantitative"
        }
      },
      "resolve": {
        "scale": {
          "x": "shared",
          "y": "independent"
        }
      },
      "spec": {
        "encoding": {
          "color": {
            "field": "StandardMZ",
            "scale": {
              "nice": false,
              "scheme": "plasma",
              "zero": false
            },
            "type": "nominal"
          },
          "tooltip": {
            "field": "dataset_name",
            "type": "nominal"
          },
          "x": {
            "field": "_start_time",
            "scale": {
              "domain": {
                "selection": "selector033"
              },
              "nice": false,
              "zero": false
            },
            "timeUnit": "yearmonthdatehoursminutes",
            "type": "temporal"
          },
          "y": {
            "axis": {
              "format": ".3"
            },
            "field": "RT",
            "scale": {
              "zero": false
            },
            "type": "quantitative"
          }
        },
        "height": 50,
        "mark": {
          "point": true,
          "type": "line"
        },
        "transform": [
          {
            "from": {
              "data": {
                "name": "data-4b278943580a5df6670d450b571e9be0"
              },
              "fields": [
                "start_time",
                "dataset_name"
              ],
              "key": "_id"
            },
            "lookup": "_id"
          },
          {
            "as": "_start_time",
            "calculate": "timeParse(datum.start_time,'%Y-%m-%d %I:%M:%S %p')"
          }
        ],
        "width": 1000
      }
    },
    {
      "encoding": {
        "color": {
          "field": "StandardMZ",
          "scale": {
            "nice": false,
            "scheme": "plasma",
            "zero": false
          },
          "type": "nominal"
        },
        "tooltip": {
          "field": "dataset_name",
          "type": "nominal"
        },
        "x": {
          "field": "_start_time",
          "scale": {
            "nice": false,
            "zero": false
          },
          "timeUnit": "yearmonthdatehoursminutes",
          "type": "temporal"
        },
        "y": {
          "axis": {
            "format": ".3"
          },
          "field": "RT",
          "scale": {
            "zero": false
          },
          "type": "quantitative"
        }
      },
      "height": 50,
      "mark": {
        "point": true,
        "type": "line"
      },
      "selection": {
        "selector033": {
          "empty": "all",
          "encodings": [
            "x"
          ],
          "resolve": "global",
          "type": "interval"
        }
      },
      "title": "time selector",
      "transform": [
        {
          "from": {
            "data": {
              "name": "data-4b278943580a5df6670d450b571e9be0"
            },
            "fields": [
              "start_time",
              "dataset_name"
            ],
            "key": "_id"
          },
          "lookup": "_id"
        },
        {
          "as": "_start_time",
          "calculate": "timeParse(datum.start_time,'%Y-%m-%d %I:%M:%S %p')"
        },
        {
          "sample": 100000
        }
      ],
      "width": 1000
    }
  ]
}
```

**Comment by arvind** [comment] 2021-01-06 19:22
Hi @jnj16180340, thanks for filing this issue. I'm not sure what the desired behavior is here — do you mind describing further? As far as I can tell, the spec you've posted is working as intended. You can initialize a selection by specifying an `"init"` property like so: 

```
"init": {
            "x": [{"year": 2020, "month": "jul", "date": 8, "hours": 5, "minutes": 30}, {"year": 2020, "month": "jul", "date": 8, "hours": 8, "minutes": 30}]
          }
```

**Comment by domoritz** [comment] 2021-04-28 19:39
Closing since we did not get a response for a request for clarification.

**Closed by domoritz** 2021-04-28 19:39 UTC
Labels: Area - Interaction, Need Clarification :grey_question:
