### ISSUE TITLE
4.0.0.beta-12: strange definition names

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#5603] opened 2019-11-30 20:31 UTC
The 4.0.0-beta.12 release has some strange definition names; for example:
```
"ConditionalAxisProperty<(alias-724931800-67988-68103-724931800-0-208413<(def-alias-981995915-6039-6088-981995915-0-10466|undefined)870796116,undefined>870796116|null)>"
```

https://github.com/vega/schema/blob/master/vega-lite/v4.0.0-beta.12.json#L2968

It happens more than once: the string ``"724931800-67988"``, for example, appears 108 times in the schema.

Perhaps some bug in the schema generation code?

**Comment by domoritz** [comment] 2019-12-01 19:42
The schema generator has to generate definitions even for properties that are not exported. yes, the names are not nice but for now, this is the expected behavior. If these definitions are causing problems, let me know and I can look into it (probably for VL 4.1, though).

**Comment by domoritz** [comment] 2019-12-01 19:42
Closing as expected.

**Closed by domoritz** 2019-12-01 19:42 UTC
Labels: Bug :bug:

**Comment by jakevdp** [comment] 2019-12-01 23:04
This is really unfortunate. Altair generates its class structure from the names in the schema, which means that there are 18 variations on classes named ``alt.ConditionalAxisPropertyalias72493180067988681037249318000208413defalias98199591560396088981995915010466undefined870796116undefined870796116null`` in the top-level namespace. Removing them is not really an option, because these classes are the means by which Altair validates chart specifications. I suspect this will be really confusing for anyone who comes across it.

**Comment by jakevdp** [comment] 2019-12-01 23:07
I might be able to rework the internals to separate "classes which are required for validation" from "classes which we expect the user to have access to". Is there any way of knowing which definitions are "exported" and which are not?

**Comment by domoritz** [comment] 2019-12-01 23:14
Not right now, no. I honestly don't really know why we need to have these bad names for aliases but I haven't put time into it since these names haven't caused any problems in the editor or the docs. I have a backlog of other things to work on right now, unfortunately.
