### ISSUE TITLE
color specified with domain/range and shape, both using the same field, should combine legends but don't

### ISSUE THREAD

**Issue by jowens** [vega/vega-lite#6359] opened 2020-04-19 15:55 UTC
![visualization](https://user-images.githubusercontent.com/976970/79692663-4ca79380-821b-11ea-9570-dfdd649b2edc.png)

I expect that I should have one unified legend here, not two.

```json
{
  "config": {"view": {"continuousWidth": 400, "continuousHeight": 300}},
  "data": {"name": "data-25e7579ea736366057c63175b3358b6a"},
  "mark": "line",
  "encoding": {
    "color": {
      "type": "nominal",
      "field": "schedule",
      "scale": {
        "domain": ["a", "b"],
        "range": ["#e41a1c", "#ff7f00"]
      }
    },
    "shape": {
      "type": "nominal",
      "field": "schedule"
    },
    "x": {
      "type": "ordinal",
      "field": "x"
    },
    "y": {
      "type": "quantitative",
      "field": "y"
    }
  },
  "$schema": "https://vega.github.io/schema/vega-lite/v4.8.1.json",
  "datasets": {
    "data-25e7579ea736366057c63175b3358b6a": [
      {
        "schedule": "a",
        "x": 1,
        "y": 38.15
      },
      {
        "schedule": "a",
        "x": 2,
        "y": 29.3
      },
      {
        "schedule": "b",
        "x": 1,
        "y": 14.39
      },
      {
        "schedule": "b",
        "x": 2,
        "y": 40.35
      }
    ]
  }
}
```
(same JSON: https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjMSA3ZApgO6bYwIAuy8ArrDQM4DqyAJhQBakAsADLwBooceFVr0GACQJoOFUgGZ+AX2UDwUVgEMKW0jnhaAtgVKRtugLQAmAKwEA7LYcBOAlocKAbN6+9n0D4AjE4ARgoKtgAcoV56ahqQRloATgDWZgA21KbqEJAE8HCs1OhYoBD5cJmwKfoalVAUAJ4ADqZYkPCwRtRamZB5jVAoBJmsZgzQHASsNJm5DZWQU-0d2EuN5j1a1KQA2pB6QpChkAC6Q8NQKVrwqOuHAMQE3EFaQdCDUE+IiA6IfgXTZgZRLBJbBgcLTterXSAtWGdbq9QwDK7LUbjSbTWbzUzgjGQAAecOGCLa60gtRKaMGIMgWImnVJhKWkGaZK2iKpAEcaHcqLoqLhFvCmWZOeCNBCoAASKYzZJmOQUVoMDAAek1otQWgAdKhkJwaKF9chYJrFQRkjqCHrLNkKAQddx9VF9UF9QArBgIen5CxaBgECgMLmaHRaGz2JyudyeHxePwBYJhCLRWJ6LD7EEVa5Qa1zBZmY4g-KkrBBDFbTlYBQeoK2EGyxr5+FF-GlgMFkmkaw15Z1sDWFz6hQtwft8mdkudM6DiukavlqDDoJuhQuSd51crXHFqkLveVkeLtc8Xjj5vXMGNc4ykDKIA)

Probably related to https://github.com/vega/vega-lite/issues/5996.

**Comment by domoritz** [comment] 2020-04-19 16:00
Duplicate of #5996. Here the issue seems to be lines. For point marks, we merge  the legends.

**Closed by domoritz** 2020-04-19 16:00 UTC
Labels: Bug :bug:

**Comment by jowens** [comment] 2020-04-19 16:08
I don't see that.

![visualization](https://user-images.githubusercontent.com/976970/79693046-4e725680-821d-11ea-8200-45300e42d361.png)


```
{
  "config": {"view": {"continuousWidth": 400, "continuousHeight": 300}},
  "data": {"name": "data-25e7579ea736366057c63175b3358b6a"},
  "mark": "point",
  "encoding": {
    "color": {
      "type": "nominal",
      "field": "schedule",
      "scale": {
        "domain": ["a", "b"],
        "range": ["#e41a1c", "#ff7f00"]
      }
    },
    "shape": {
      "type": "nominal",
      "field": "schedule"
    },
    "x": {
      "type": "ordinal",
      "field": "x"
    },
    "y": {
      "type": "quantitative",
      "field": "y"
    }
  },
  "$schema": "https://vega.github.io/schema/vega-lite/v4.8.1.json",
  "datasets": {
    "data-25e7579ea736366057c63175b3358b6a": [
      {
        "schedule": "a",
        "x": 1,
        "y": 38.15
      },
      {
        "schedule": "a",
        "x": 2,
        "y": 29.3
      },
      {
        "schedule": "b",
        "x": 1,
        "y": 14.39
      },
      {
        "schedule": "b",
        "x": 2,
        "y": 40.35
      }
    ]
  }
}
```

**Comment by domoritz** [comment] 2020-04-19 16:20
Right, there is a second issue that the scale domain/range definition is incompatible and therefore the legend is not merged. [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjMSA3ZApgO6bYwIAuy8ArrDQM4DqyAJhQBakAsADLwBooceFVr0GACQJoOFUgGZ+AX2UDwUVgEMKW0jnhaAtgVKRtugLQAmAKwEA7LYcBOAlocKAbN6+9n0D4AjE4ARgoKtgAcoV56ahqQRloATgDWZgAOsNTy6hCQBPBwrNToWKAQBXAANrAp+hpVUBQAnpmmWJDwsEbUWjWQ+c1QKAQ1rGYM0BwErDQ1pk1gCc2QDBxaHY0jLe2dUD19hoPDa2MTUzNzC0vNq1WQAB47I5Bt2131pSdDywUXSZdF7LB4FVqvNYfA6QACONC0omQuiouFMZ0egLMENBGgekAAJNNZskzHIKJkGBgAPTUtGoLQAOlQyI4NFCjOQsGpxIIyTpBAZlhqyIIdO4jKijKCjIAVgwEH8ChYtAwCBQGJDNDotDZ7E5XO5PD4vH4AsEwhForE9FgANr-bCOgq8+aLMx6DFrF5YIJex4QrAKKVBWyOsFVSq7KCu24epXR56kaz+8HJlyMhTh-1R3bra5umGhBN5n1gP3OqCB8sShQubOO3NvWPurrF1NQMspyuQat8TNh3bKZYAXTxIGUQA)

**Comment by jowens** [comment] 2020-04-19 16:23
OK, anything I can do about it? All I'm trying to do is have a consistent color-label pairing (across a large number of plots).

**Comment by domoritz** [comment] 2020-04-19 16:47
We need to fix the issue in Vega-Lite. For now, the best workaround is to patch the generated Vega, I think.

**Comment by jowens** [comment] 2020-04-19 18:17
OK. Thank you!
