### ISSUE TITLE
Make default selection events work on mobile

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#4661] opened 2019-03-05 23:11 UTC
Currently, our default selection events are only for desktop applications.

**Comment by domoritz** [comment] 2019-03-06 00:50
Duplicate of https://github.com/vega/vega-lite/issues/4208

**Comment by kanitw** [comment] 2019-03-06 18:56
Well, #4208 asks for this support, which I suspect is already here. (One likely just needs to define the right event.). Here I'm saying that we should support them by default, which is relevant, but different.

**Comment by domoritz** [comment] 2019-03-06 23:37
No, we only care about the default otherwise we could close the other issue. 

Either way, please refine either this or the other issue and close the one you don't refine. We don't need two issues for this.

**Comment by kanitw** [comment] 2019-03-07 00:08
> No, we only care about the default otherwise we could close the other issue.

Yes, you closed the wrong issue.

**Comment by domoritz** [comment] 2019-03-09 02:16
> Yes, you closed the wrong issue.

:-P

**Comment by domoritz** [comment] 2019-03-11 22:14
@mattijn showed how you can add touch interactions to VL right now in https://github.com/vega/vega-lite/issues/4208#issuecomment-471757641 but we should see how we can support this by default.

**Comment by kanitw** [comment] 2019-03-31 23:41
@domoritz said that [Falcon](https://github.com/uwdata/falcon) has some example events that work on mobile too.

**Comment by luciodale** [comment] 2019-05-01 10:57
Is there any progress on this feature? :)

**Comment by domoritz** [comment] 2019-05-01 17:47
Not yet but we would be thrilled about PRs along those lines.

**Comment by donghaoren** [comment] 2019-10-16 17:25
@domoritz, I'd love to give this a try, could you point me to the Falcon code that handles mobile events?

**Comment by domoritz** [comment] 2019-10-16 17:37
It's all in https://github.com/uwdata/falcon/blob/master/src/views/histogram.ts.  You can try Falcon on your phone or iPad as well: https://uwdata.github.io/falcon/flights/.

**Comment by keckelt** [comment] 2020-01-29 21:34
Suggestion from my side:
* Single selection: tap
* Multi selection: tap to select, tap again to deselect, i.e. with [toggle set to true](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATZAgBOjQnh4qckAIJh26XWCTW8YAO7NEYRI2qIJno0uphlN24qG3QlTTBYZDFkeF9-QPgJeABrOjAACgBJJVhCRl1kCPYATzAAFXR2GPRWAHJYMEYlPGRddDjjSLwSmLoASjUNSE10PEwcUAgISAp0MVYdbDAAbQ1psGBICagzNSh2ZYAmAA4AX1VN7eXIACF9yEOcAFZni6udyABhB6ewaQAzBd1tMtp8ACK-ZYATgAjO8wTcAKJQnAneGXRGmABiqLAzyB6g2ECxUAA4njYdCEddTAAJPEnADsNM+WTxzyOZxBAF0NMCZlEYp1lMsptNIELYngxZAeoRkDdUKwxEYHmhDCUbkplIrLnLuNRqDEbnhdItIAKJYhgm1ZfLFaZYM1jXqoBqetrdQ9RaZUNxWFFbbpLfyiVAMLoUmKQXKSgqblYQ2HhsglPBuJoXTGNpAAB6ygBmjGimhumH1Dq9qGa80t4ZmWsmkGLpcTDyrpgAjqwwkZxkYqPXYxmxNwQ83W2Iy6YK1BO1AdTWlHWrTNi2IxAB5QgdZhNzYgmYZ8LMYzLNbE0FH4lynQyyY3q+QccXp9Xq5SkUmKBfmVrj8Ni2P9z1MG0QmHQDnwAQhiPwWAyUZxgyAAdSVomlAB9WA8HHZA0P6QZ3w2PkoLAADnzmBZHTAWF325K8eQbCUqItHAAAY6ABEEGPIkBuSAA)
* Interval: the ones from Falcon (I came here to see if the falcon brush is planned to become default 🙂 )

**Comment by domoritz** [comment] 2023-10-04 19:57
Done in https://github.com/vega/vega-lite/pull/9089

**Closed by domoritz** 2023-10-04 19:57 UTC
Labels: P2, Area - Interaction
