### ISSUE TITLE
boxplot doesn't works with column encoding 

### ISSUE THREAD

**Issue by iliatimofeev** [vega/vega-lite#4156] opened 2018-09-13 14:23 UTC
`boxplot` doesn't works with `column` encoding and `facet`. 
Result `Error: Undefined data set name: "data_1"`
[see editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjKCFIDdkBTAd020hOQBMAXAC3IBYAGFgGinqLXtvIDMbAL7twuSACci0flmAxYk+EUkAlAIbVkAVwDO5AIwth40eMjUNtDeQXwNAWyLlL1jQFpEAIw0BWAA4AJkQAgE4wgDZDSI1IgKJgoO8WIiIBIgB2DQFoDMhzPEcNSQBrcgpaAE8ABxcMSG9YAA8agBtYfkKoIng4bXh0eXE8OA7JO0hqutd4WEdkBzbITkgUIjbqV3p50iVSgH1qBBdu0dg2nUd4Sen6qDmFpZWodc3XPSI9PWQEA52dBMzlBmrdavdII9Fhplqs3lssJAds4SPsjicCmJcFAqmCZoiAI46DTwWjIGxk-AuOHEd6Iz7fX7wA5k5wHRwFMxYqAAEj00G4xW2tFoNT0GAA9BKqagNAA6VDk+g6bxy34S-mCjTSoiyjxtclEaVBOWROUsOUAKz0CBWFisNk+tAMw2xbhsXl8gRC4SiMTiCSSKTSGWyuXyWAA2iNcApkXsyuiVOREDDPqsGT8-qyiOzyEEM18s8yARMsEETNzsXHdqjE8dk1hU2101BM0yWcg2RysBw20WO6WjJlgRAayi0Q37s3W5B29mu7me2AmJFC4y-kOsAFRxR43XDlOU2miOvi53u+Q+3OB5vYIDyGFd+OE4eMU2T2eOzm81hDGEvzvB8-0iZ8kVrSd3zAGdT37DdmR-ZcBEAkt7zLMBDCCMD90gxtoM-ODz0Qq8UP+NDyB3KtY3Aid6ygmDSOIrAmAAwjB3Iv9KxjMcaNfJNpwIm94IvJdmALNigPQkcqJ4nC6LwhiJIQxdfzAARMlIrcML8bCIPkgSW1goSiJU5cK00jiwGk7i9z0t8FME+dlMvLBImQpSyOAsBKJsl8D3449DMY0zyGiCyvOMXTaPs+5aEkHQjKckTVPicKpKivijw-IKPKYsBIlY4z2Ii6zsVkuyAuy2ckryoI-DSoxDAy-ysrAOKEuClyMLqhq-x8srbOiyr8JyoqFy6zDeu05rcIM6rb2c0Teym-8Zv0wL5uEvKmACKaRxjABdMwQGEIA)

**Comment by ijlyttle** [comment] 2018-09-16 21:54
I know this is likely overkill, but just to note that the same problem exists for `row`.

**Comment by domoritz** [comment] 2018-09-22 06:33
The issue seems to not be in the boxplot logic.

**Comment by domoritz** [comment] 2018-09-22 06:53
Here is a normalized spec that shows the issue:

```json
{
  "data": {
    "values": [
      {
        "homework_done": false,
        "session_time_m": 2,
        "session_hour": 1
      },
      {
        "homework_done": false,
        "session_time_m": 0,
        "session_hour": 2
      }
    ]
  },
  "$schema": "https://vega.github.io/schema/vega-lite/v3.0.0.json",
  "facet": {
    "column": {
      "type": "nominal",
      "field": "session_hour"
    }
  },
  "spec": {
    "layer": [
      {
        "transform": [
          {
            "aggregate": [
              {
                "op": "q1",
                "field": "session_time_m",
                "as": "lower_box_session_time_m"
              },
              {
                "op": "q3",
                "field": "session_time_m",
                "as": "upper_box_session_time_m"
              },
              {
                "op": "median",
                "field": "session_time_m",
                "as": "mid_box_session_time_m"
              },
              {
                "op": "min",
                "field": "session_time_m",
                "as": "min_session_time_m"
              },
              {
                "op": "max",
                "field": "session_time_m",
                "as": "max_session_time_m"
              }
            ],
            "groupby": [
              "homework_done"
            ]
          },
          {
            "calculate": "datum.upper_box_session_time_m - datum.lower_box_session_time_m",
            "as": "iqr_session_time_m"
          },
          {
            "calculate": "min(datum.upper_box_session_time_m + datum.iqr_session_time_m * 1.5, datum.max_session_time_m)",
            "as": "upper_whisker_session_time_m"
          },
          {
            "calculate": "max(datum.lower_box_session_time_m - datum.iqr_session_time_m * 1.5, datum.min_session_time_m)",
            "as": "lower_whisker_session_time_m"
          }
        ],
        "layer": [
          {
            "mark": {
              "type": "rule",
              "style": "boxplot-rule"
            },
            "encoding": {
              "y": {
                "field": "lower_whisker_session_time_m",
                "type": "quantitative",
                "title": "session_time_m"
              },
              "y2": {
                "field": "lower_box_session_time_m",
                "type": "quantitative"
              },
              "x": {
                "field": "homework_done",
                "type": "nominal",
                "title": "homework_done"
              }
            }
          },
          {
            "mark": {
              "type": "rule",
              "style": "boxplot-rule"
            },
            "encoding": {
              "y": {
                "field": "upper_box_session_time_m",
                "type": "quantitative",
                "title": "session_time_m"
              },
              "y2": {
                "field": "upper_whisker_session_time_m",
                "type": "quantitative"
              },
              "x": {
                "field": "homework_done",
                "type": "nominal",
                "title": "homework_done"
              }
            }
          },
          {
            "mark": {
              "type": "bar",
              "size": 14,
              "style": "boxplot-box"
            },
            "encoding": {
              "y": {
                "field": "lower_box_session_time_m",
                "type": "quantitative",
                "title": "session_time_m"
              },
              "y2": {
                "field": "upper_box_session_time_m",
                "type": "quantitative"
              },
              "x": {
                "field": "homework_done",
                "type": "nominal",
                "title": "homework_done"
              }
            }
          },
          {
            "mark": {
              "color": "white",
              "type": "tick",
              "size": 14,
              "orient": "horizontal",
              "style": "boxplot-median"
            },
            "encoding": {
              "y": {
                "field": "mid_box_session_time_m",
                "type": "quantitative",
                "title": "session_time_m"
              },
              "x": {
                "field": "homework_done",
                "type": "nominal",
                "title": "homework_done"
              }
            }
          }
        ]
      },
      {
        "transform": [
          {
            "window": [
              {
                "op": "q1",
                "field": "session_time_m",
                "as": "lower_box_session_time_m"
              },
              {
                "op": "q3",
                "field": "session_time_m",
                "as": "upper_box_session_time_m"
              }
            ],
            "frame": [
              null,
              null
            ],
            "groupby": [
              "homework_done"
            ]
          },
          {
            "filter": "(datum.session_time_m < datum.lower_box_session_time_m - 1.5 * (datum.upper_box_session_time_m - datum.lower_box_session_time_m)) || (datum.session_time_m > datum.upper_box_session_time_m + 1.5 * (datum.upper_box_session_time_m - datum.lower_box_session_time_m))"
          }
        ],
        "mark": {
          "type": "point",
          "style": "boxplot-outliers"
        },
        "encoding": {
          "y": {
            "field": "session_time_m",
            "type": "quantitative"
          },
          "x": {
            "field": "homework_done",
            "type": "nominal",
            "title": "homework_done"
          }
        }
      }
    ]
  }
}
```

**Comment by domoritz** [comment] 2018-09-22 07:00
Here is a small example 

```json
{
  "data": {
    "values": [
      {
        "homework_done": false,
        "session_time_m": 2,
        "session_hour": 1
      },
      {
        "homework_done": false,
        "session_time_m": 0,
        "session_hour": 2
      }
    ]
  },
  "$schema": "https://vega.github.io/schema/vega-lite/v3.0.0.json",
  "facet": {
    "column": {
      "type": "nominal",
      "field": "session_hour"
    }
  },
  "spec": {
    "layer": [
      {
        "transform": [
          {
            "aggregate": [
              {
                "op": "median",
                "field": "session_time_m",
                "as": "mid_box_session_time_m"
              }
            ],
            "groupby": [
              "homework_done"
            ]
          }
        ],
        "layer": [
          {
            "mark": {
              "type": "tick"
            },
            "encoding": {
              "y": {
                "field": "mid_box_session_time_m",
                "type": "quantitative"
              },
              "x": {
                "field": "homework_done",
                "type": "nominal"
              }
            }
          }
        ]
      },
      {
        "transform": [
          {
            "window": [
            ],
            "groupby": [
              "homework_done"
            ]
          }
        ],
        "mark": {
          "type": "point"
        },
        "encoding": {
          "y": {
            "field": "session_time_m",
            "type": "quantitative"
          },
          "x": {
            "field": "homework_done",
            "type": "nominal"
          }
        }
      }
    ]
  }
}
```

**Comment by domoritz** [comment] 2018-09-22 07:01
Hmm, this doesn't look fun.

<img width="486" alt="screen shot 2018-09-21 at 23 45 17" src="https://user-images.githubusercontent.com/589034/45914480-94c1c280-bdfa-11e8-9a90-1c5965299cb5.png">

**Comment by domoritz** [comment] 2018-09-22 07:13
Hmm, weird. We have a `data_1` after facet but somehow Vega doesn't find it. I thought that worked.

**Comment by domoritz** [comment] 2018-09-26 01:54
🎉 

<img width="831" alt="screen shot 2018-09-25 at 18 53 27" src="https://user-images.githubusercontent.com/589034/46052682-524aff00-c0f4-11e8-83a1-f3891e26a62f.png">

So, the issue seems to be that we didn't correctly treat window aggregates as aggregates. The chart still looks a bit funny, no?

**Comment by domoritz** [comment] 2018-09-26 02:03
Here is another example that doesn't work

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A vertical 1D box plot showing median, min, and max in the US population distribution of age groups in 2000.",
  "data": {"url": "data/population.json"},
  "mark": "boxplot",
  "encoding": {
    "y": {
      "field": "people",
      "type": "quantitative",
      "axis": {"title": "population"}
    },
    "column": {
      "field": "sex",
      "type": "ordinal"
    }
  }
}
```

**Comment by domoritz** [comment] 2018-09-26 02:06
Hmm, why is people in the domain here?

```json
  "scales": [
    {
      "name": "y",
      "type": "linear",
      "domain": {
        "fields": [
          {"data": "data_1", "field": "lower_whisker_people"},
          {"data": "data_1", "field": "lower_box_people"},
          {"data": "data_1", "field": "upper_box_people"},
          {"data": "data_1", "field": "upper_whisker_people"},
          {"data": "data_1", "field": "mid_box_people"},
          {"data": "data_3", "field": "people"}
        ]
      },
      "range": [{"signal": "child_height"}, 0],
      "nice": true,
      "zero": true
    }
  ],
```

**Comment by domoritz** [comment] 2018-09-26 02:14
Oh, it's for the outliers. But we should use `source_0` instead of `data_3`. `data_3` is in a facet so we can't access it but it also doesn't have a field `people` so I'm confused why the scale tries to use it in its domain.

**Comment by domoritz** [comment] 2018-09-26 02:18
Ahh, `people` is for outliers. We need to use a window to calculate an aggregate and then filter with it. The right thing for the scale is to be derived from a clone of the dataflow that is hoisted to the top. We do this for normal aggregates so let's see why this isn't happening for window aggregates.

**Comment by domoritz** [comment] 2018-09-26 02:42
Here is a small spec that shows the error

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"url": "data/population.json", "format": {"type": "json"}},
  "facet": {"column": {"field": "sex", "type": "ordinal"}},
  "spec": {
    "layer": [
      {
        "transform": [
          {
            "aggregate": [
              {"op": "min", "field": "people", "as": "min_people"},
              {"op": "max", "field": "people", "as": "max_people"}
            ],
            "groupby": []
          }
        ],
        "layer": [
          {
            "mark": {"type": "rule", "style": "boxplot-rule"},
            "encoding": {
              "y": {
                "field": "min_people",
                "type": "quantitative"
              },
              "y2": {"field": "max_people", "type": "quantitative"}
            }
          }
        ]
      },
      {
        "transform": [
          {
            "window": [
              {"op": "q1", "field": "people", "as": "lower_box_people"}
            ],
            "groupby": []
          }
        ],
        "mark": {"type": "point", "style": "boxplot-outliers"},
        "encoding": {"y": {"field": "people", "type": "quantitative"}}
      }
    ]
  }
}
```

**Comment by domoritz** [comment] 2018-09-26 03:07
@invokesus had a hunch that the bug may be caused by https://github.com/vega/vega-lite/pull/4029. However, going back to dad69556d, doesn't seem to fix the issue with https://github.com/vega/vega-lite/issues/4156#issuecomment-424560258 but it does fix https://github.com/vega/vega-lite/issues/4156#issuecomment-423722449. So maybe https://github.com/vega/vega-lite/pull/4175 resolves the issue.

**Comment by domoritz** [comment] 2018-09-26 03:15
This example works before the transform merging but not after:

```
{
  "data": {
    "values": [
      {
        "homework_done": false,
        "session_time_m": 2,
        "session_hour": 1
      },
      {
        "homework_done": false,
        "session_time_m": 0,
        "session_hour": 2
      }
    ]
  },
  "$schema": "https://vega.github.io/schema/vega-lite/v3.0.0.json",
  "facet": {
    "column": {
      "type": "nominal",
      "field": "session_hour"
    }
  },
  "spec": {
    "layer": [
      {
        "transform": [
          {
            "aggregate": [
              {
                "op": "median",
                "field": "session_time_m",
                "as": "mid_box_session_time_m"
              }
            ],
            "groupby": []
          }
        ],
        "mark": {
          "type": "tick"
        },
        "encoding": {
          "y": {
            "field": "mid_box_session_time_m",
            "type": "quantitative"
          }
        }
      },
      {
        "transform": [
          {
            "window": [],
            "groupby": []
          }
        ],
        "mark": {
          "type": "point"
        },
        "encoding": {
          "y": {
            "field": "session_time_m",
            "type": "quantitative"
          }
        }
      }
    ]
  }
}
```

**Comment by domoritz** [comment] 2018-09-26 03:34
Wow, so with dad69556d the dataflow looks like

<img width="907" alt="screen shot 2018-09-25 at 20 21 23" src="https://user-images.githubusercontent.com/589034/46055685-fbe4bd00-c101-11e8-8f0d-d1c127157096.png">

and with the latest dom/window-dataflow

<img width="912" alt="screen shot 2018-09-25 at 20 30 20" src="https://user-images.githubusercontent.com/589034/46055705-15860480-c102-11e8-9577-f814b7c74cdc.png">

So something is very wrong here. I'm going to wait for @invokesus to fix https://github.com/vega/vega-lite/pull/4175 and see whether this resolves this problem. 

https://github.com/vega/vega-lite/pull/4177 still seems like a good idea so I'll leave it open.

**Comment by domoritz** [comment] 2018-09-27 07:13
https://github.com/vega/vega-lite/pull/4177 and https://github.com/vega/vega-lite/pull/4175 will fix this. 

Phew, this was one of the hardest debugging sessions I've done. Took me three days with some really weird behavior in between. However, it exposed a few separate bugs that are all fixed now and we have tests and helper tools to make sure we can catch these class of bugs much easier now.

**Closed as completed** 2018-09-27 07:24 UTC
Labels: Bug :bug:
