### ISSUE TITLE
Tooltip off by one day

### ISSUE THREAD

**Issue by SyntaxRules** [vega/vega-lite#4149] opened 2018-09-04 22:01 UTC
When adding a tooltip to ranged bar marks, the tooltip shows the end date as (date-1). You can see this in the below image and schema. Task B's end is 2018-01-08 but the tooltip show 2018-01-07. 

![image](https://user-images.githubusercontent.com/4117657/45059965-3f945b80-b05b-11e8-9e03-1cd1d8d82bbc.png)

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A simple bar chart with ranged data (aka Gantt Chart).",
  "data": {
    "values": [
      {"task": "A","start": "2018-01-01", "end": "2018-01-03"},
      {"task": "B","start": "2018-01-02", "end": "2018-01-08"},
      {"task": "C","start": "2018-01-05", "end": "2018-01-10"}
    ]
  },
  "mark": "bar",
  "encoding": {
    "y": {"field": "task", "type": "ordinal"},
    "x": {"field": "start", "type": "temporal"},
    "x2": {"field": "end", "type": "temporal"}
  }
}

```

Please let me know if this is better filed in the vega-tooltip repo. Thanks!

**Comment by domoritz** [comment] 2018-09-05 18:47
Thank you for reporting the issue. 

The problem is date parsing in JavaScript. See https://vega.github.io/vega-lite/docs/timeunit.html#utc for details and read about date parsing in browsers. I wish I had a good fix for this but this is a known issue for multiple years (not with Vega but with browsers in general). 

<img width="446" alt="screen shot 2018-09-05 at 11 42 12" src="https://user-images.githubusercontent.com/589034/45114039-c6e7da80-b100-11e8-8e17-4256adebef4a.png">

Here is a working spec. You can also change your date formats to be iso conformant. 

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A simple bar chart with ranged data (aka Gantt Chart).",
  "data": {
    "values": [
      {"task": "A","start": "2018-01-01", "end": "2018-01-03"},
      {"task": "B","start": "2018-01-02", "end": "2018-01-08"},
      {"task": "C","start": "2018-01-05", "end": "2018-01-10"}
    ]
  },
  "mark": "bar",
  "encoding": {
    "y": {"field": "task", "type": "ordinal"},
    "x": {"field": "start", "type": "temporal", "scale": {"type": "utc"}},
    "x2": {"field": "end", "type": "temporal"}
  }
}
```

**Closed by domoritz** 2018-09-05 18:47 UTC

**Comment by SyntaxRules** [comment] 2018-09-05 20:54
Thanks for the quick reply. Your suggested solution did not immediately solve the problem for me- but put me on a path to figuring it out.

To make the end date show up correctly, I had to add the `"scale": {"type": "utc"}` to the `x2` field. However this is not valid vega-lite (`x2` cannot have a scale). So instead I read through the provided link and added `"timeUnit": "utcyearmonthdate"` to each of the fields. The solution that worked for me is:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A simple bar chart with ranged data (aka Gantt Chart).",
  "data": {
    "values": [
      {"task": "A","start": "2018-01-01", "end": "2018-01-03"},
      {"task": "B","start": "2018-01-02", "end": "2018-01-08"},
      {"task": "C","start": "2018-01-05", "end": "2018-01-10"}
    ]
  },
  "mark": "bar",
  "encoding": {
    "y": {"field": "task", "type": "ordinal"},
    "x": {"field": "start", "type": "temporal", "timeUnit": "utcyearmonthdate"},
    "x2": {"field": "end", "type": "temporal", "timeUnit": "utcyearmonthdate"}
  }
}
```

**Comment by domoritz** [comment] 2018-09-05 20:55
I'm glad it worked. Notice that when you set the scale type of `x`, it will also automatically be set on `x2`.
