### ISSUE TITLE
Tooltip content: "data" shows reactive geometry data when used in a line chart.

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#6260] opened 2020-04-04 13:27 UTC
If you modify the [Multi Series Line Chart With Tooltip](https://vega.github.io/vega-lite/examples/interactive_multi_line_pivot_tooltip.html) example to use ``"tooltip": {"content": "data"}``, the result is unexpected: rather than showing the transformed data, it appears to show the layer's pathgroup ([editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATdHkw5gkVgCcx2LTvR883eAGtYdeLAqQAvuoiQA7o00sz0gAMgR64yIzU+GYAzMGhkMhK8NyajErUZgYAHpmQAGaMyGKaZpDaeMhqUHgAnoSVOJAVqITcRuimru4akGLoNchGZgDaGhCgEJNQicmp6ZljU1DJYm25BUUljbA1qOzcpqrVdQ1QStyoaR1uoUtQNeuFxaWERozwlUdNJ6UAjqzoJR4Zg6RhUNyLCDdO69fqDEaQyYGDBGWylCRKSrQu5gAx4dpKWB5NqoEYGApiCpDfSQWBFZDwYHKUqIbhUIZdAC6XxRaMarTSeAhd05i2x40RTQJRJJZMghDB3CF212+0OUAoHVYp3lbw+VUg1CM3FYhHYDxwwzKOkqnNc3MlvNytXqpSMrDEn2q3AOwMIuWSQMSyvMujc4smCSSKTSGX0iM83EI6HgzAtuITkcDqSZKhpmrE2rMgTo0S+dM9jJ4edwbPhEZhBaLOECmdciIbUArDNzCxxtfZff7x1d21jnrUmc8G2KsBG1oqkAdw7OyHQRmQsBD+O1txxkGZjVQJrpdaGe5haEItVK50xk5XkHgnvXpWPrFPrCFbY7Yo0ovbIA)):
<img width="704" alt="Screen Shot 2020-04-04 at 6 26 23 AM" src="https://user-images.githubusercontent.com/781659/78451935-428f6d80-763d-11ea-81d6-b7344adff614.png">

**Comment by domoritz** [comment] 2020-04-04 18:22
The tooltip is actually coming from the voronoi that's added by the nearest transform. I don't think the issue is the pivot transform.

**Comment by domoritz** [comment] 2020-04-04 18:26
[Simpler example](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATdHkw5gkVgCcx2LTvR883eAGtYdeLAqQAvuoiQA7o00sz0gAMgR64yIzU+GYAzMGhkMhK8NyajErUZgYAHpmQAGaMyGKaZpDaeMhqUHgAnoSVOJAVqITcRuimru4aTe1KsHltqGYA2gYFYhVGpeWsqHSwNajs3GJgALybYADkAIK7AAoAMttuALrxYug1yNM4IxoQoBAvUBhGtqUSSpWhrwlJFJpDL6SA1XIFIolRqEIyMeC-ap1BpQACOrHQSjwzB0jCoblcjzA3Vez1eb3QH1ytXqpSMrDEiKa3FW2MIuWSWMSeBmFgJfxeAOSqXSmSJ-24hHQ8GY4P04vJkE5qWxylyFA6rBRgTo0VUUFgRWQ8FVKkaiG4VGmJPJ-w1Yi1ZkCCoghNtNv+hsZJp4ZrAZNtkAtVrFtv+NJRkFgwMZahdgshxVgozKOkqF3jnh+lOQsB5ODw9OQAsDasaqG4rENltucbDgrQhFqpSUyl+mag8EZlNKFaryErPPjbvJI9dGjOIFcQA)

**Comment by domoritz** [comment] 2020-04-04 18:32
The issue seems to be that we have a tooltip encoding on the voronoi layer. However, the Voronoi layer has the reactive geometry data (which is what we are seeing here).

If we remove the tooltip from the Voronoi layer, we have the issue that the Voronoi layer is interactive and therefore swallows the events needed for tooltip. 

Vega spec without the tooltip on the [Voronoi layer](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KO3TwA1tQBO3VjIAm2KAHdEzZAqWRC6PXsYzqh0YoiQjjPS0MAWAAy+XXGRGanxDAGZ-QMhYPABPABtzHEh4ZASEi1c9dDxMHABtJQhgSBl0VGTcbipNAH1Y7k1zAF9AkuKIKHLKwxidTTS63yyu11ZNTJScvL48bnVYOnhYClGxyAAzJow8Q1L4wirU1YUoa01YKtKZ49vINqg9dMZUM00++Qf2rsg8TXQMlg200qEMBQOcSOfU2jASeGQH3kUGQAA9CB9prlWKg6LA4qh2NwEmAALzksAAcgAgtSAAoAGUpDwAup02p1QGNXD07rl0MN1r9pBM0n0RYNkIKfq5-oDgTtwZ0xlzuRtDsdYfDEUK1ZA0Ri+gAKRiwAAiuWQRpmOIKAB1ILcHSyAJRgAA+7rAJtgADV0AkPNbsah7Y7Lc63QAyKNgU0AMXsZiNAGobaGHU7IK6XS7IMqui0C2yxkWICzorAQuUErAlSqC2UKsddMxdVAKAHWNcOXrZPW1WBSsgqDI8HWUqgdFcp1QzpBWIR7ilTQAVRdJI1aHSEI25sAAfjA28Xe7AOFbezL3JLhZ+qo2vL6iBqOplUEXy47CQAyulkPAeA8DIABKyDSAkVBGg6L61A08zNA6yIOq2sgOnm7L3o2T4pLBiJ1HgG7mO+kD9oUBYdIOvwjsgY4TmARRUQ2THcv0orHAg3DQu+VF-FCxxTqwVyvkiFGDpAGCaGoOFQAk6BxPhACMdQUE0sjcIw+YsRA15URWYnjEulp9OmYAxnGCKoHudCSWoNnoFJGpgAAhBSlInoQlKHkOl44A6ckKfUilIWAsLpHoJBgHh9SEYQSR1GFCQRcinYJN2kUFCalnWaavpqTIGneemdCmTg6YumGWYsiyLTnmAMisBk7YbCCYo4P83Zib2g7DqO47gqUEptVAnHcVAGp9IJwmsFeFYfkZCJ9A1TW6V0t46feTa9LhIkEURCWMOFdbIpAqXdgNfHQikACi86JQYWKLS0NVYXqMmQNFdRTnYmxxO2pFyORVEPuJNF0fsMTVgGz67bFSTfAZ81fhJ3A-XE0EfbtjSIWcn1w8gyIdcgGFUat5bsko+muLZ9GMV0IM8s2fQBfhvhfQ5ajHY2E0pIGMjEY2sSJFUBSQHz5hU6x0iaHsOClPdJkhpVEbZgjer2AiAKAYwc44JsAZXCRmzaGCcvhnk4oDEMIzdRstHwKj1xiQuC1OyxMT-NwajXKdXbHAAxN48AAOwABzoKHatMZAqIQwgAbHLHJ0K49rQ8b8f1m-H8MpH9yeHUlfQYowYq2+JzywvzD1DojrhVtQNZ9LlAZBumysIpGZmxgmSYIqmbeZirrpd3Gfot3owaERmViaCXyCd+ZPcyMmaZKw6xdpJGWlMWThYFqtZcM90TO8-JSns1JXN6jzUCaI1At6kLOcMZAd-w5LGwa4iqhAbrYBE0bE2EMZj5CePyQUZdXD20dvsZ2n5jJy0Rh7bQ3sADqHgvBmzOlURSvhIGsXmMSIChA45QymGAqeUdeKxBQT7bBfR2ByXUFQ8SXFVDMEzgxWuQ4-jgVllAI0FBfz-m1rIVcfCMafWxvPM45U8wnXoTgXwdBwj4LVKURRYA8GIw-uJWOWd4AJz6EnKAKcKFpyQZwjRftDB4PTq4OIAAmCGZjSgeWfMEUIV5d46X3phTk2ET6yTPkFFS+UNL-RvlYXIiB-pfy1r-KoADGzG24KbHhIDmYhLqMpGmLCoEyAds8WBvF4GLUQe7LU5DrFpWOHKIEFxaJXnsSNT2aCMGxKwTYpRKjRBqOFG0uh3TxoAgaQ5Jp+TWK5XCZpLptTDBEx8WAXe+C-ijIVKCAc6ikFRNUtoAqmkWkxwhgaTEFCcQlRDHQVEHovQ2yOVY-U6IznmwucVOItytGTI2FWAAXiLQaZC+juE8LEx4gKG7Q1wp4sIz0urFgpuWSshiki0wCW9IJxySJRKAr0Eieg0noHsCU8S900UsRuPyS27FpSmILtXc2FiKXm1ASy2lWx6WKyemJdad5GyjOoCLAIPD66NxSCCrwcLSyvVYu9PO3N+LM3sMgBy-0CUYGJWbTJKQhpShGPncKRdZ6lxIgKgFkNIXkI+jC5pWjdE8jngsu+BNGz-O0E6zqpZKbRHQKicCWya6PxRYnf6TRDpjgYdwAgaT-paA8D+YNfR5V6jjdXZJ18S5qAAMI6AjVnIFKQ0hwiNBKxApA-B5lWeqolgNQoGxdXqOS7B0j0X1rWBtrEMComuqiBEeatEkTeDIHtfb+EBG5pm1t9aSK-PsM8fRWj-HMSlom3OobZ4TN5sgTYewSKpoTUYlISdGypo9R29Umac26H4RCsVUAi0JCNCgEI+By2+Erfiwlmq63tpIk2lthg22G0bF2kdm6B0gfsGB-t46M2LEA9O11c60S2KXfTQWq6oDHr7Bu-tkAiTRrBHu2e1cgPnt+EBPAz9GX-X-QkeMaVYCdP-s6v96Bm0JAAPK1DkiQ9qrGJ3qCvf229UL73BEfaWt9H6kP6BQ0otDlEV2HqgMm1iYbwNi23buk9JGEO-onVR44G8H6sTo9xxEvGz3Ysvbmm9Fq72pAk0+m10nJmQFnXJhdvhEVgDZC0IAA). 

I don't know what the solution is here but I believe this is not a high-priority issue since you can define your own tooltip manually.

**Comment by kanitw** [comment] 2020-04-14 14:59
The solution is to make voronoi layer [output `datum.datum`](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KO3TwA1tQBO3VjIAm2KAHdEzZAqWRC6PXsYzqh0YoiQjjPS0MAWAAy+XXGRGanxDAGZ-QMhYPABPABtzHEh4ZASEi1c9dDxMHABtJQhgSBl0VGTcbipNAH1Y7k1zAF9AkuKIKHLKwxidTTS63yyu11ZNTJScvL48bnVYOnhYClGxyAAzJow8Q1L4wirU1YUoa01YKtKZ49vINqg9dMZUM00++Qf2rsg8TXQMlg200qEMBQOcSOfU2jASeGQH3kUGQAA9CB9prlWKg6LA4qh2NwEmAALzksAAcgAgtSAAoAGUpDwAup02p1QGNXD07rl0MN1r9pBM0n0RYNkIKfq5-oDgTtwZ0xlzuRtDsdYfDEUK1ZA0Ri+gAKRiwAAiuWQRpmOIKAB1ILcHSyAJRgAA+7rAJtgADV0AkPNbsah7Y7Lc63QAyKNgU0AMXsZiNAGobaGHU7IK6XS7IMqui0C2yxkWICzorAQuUErAlSqC2UKsddMxdVAKAHWNcOXrZPW1WBSsgqDI8HWUqgdFcp1QzpBWIR7ilTQAVRdJI1aHSEI25sAAfjA28Xe7AOFbezL3JLhZ+qo2vL6iBqOplUEXy47CQAyulkPAeA8DIABKyDSAkVBGg6L61A08zNA6yIOq2sgOnm7L3o2T4pLBiJ1HgG7mO+kD9oUBYdIOvwjsgY4TmARRUQ2THcv0orHAg3DQu+VF-FCxxTqwVyvkiFGDpAGCaGoOFQAk6BxPhACMdQUE0sjcIw+YsRA15URWYnjEulp9OmYAxnGCKoHudCSWoNnoFJGpgAAhBSlInoQlKHkOl44A6ckKfUilIWAsLpHoJBgHh9SEYQSR1GFCQRcinYJN2kUFCalnWaavpqTIGneemdCmTg6YumGWYsiyLTnmAMisBk7YbCCYo4P83Zib2g7DqO47gqUEptVAnHcVAGp9IJwmsFeFYfkZCJ9A1TW6V0t46feTa9LhIkEURCWMOFdbIpAqXdgNfHQikACi86JQYWKLS0NVYXqMmQNFdRTnYmxxO2pFyORVEPuJNF0fsMTVgGz67bFSTfAZ81fhJ3A-XE0EfbtjSIWcn1w8gyIdcgGFUat5bsko+muLZ9GMV0IM8s2fQBfhvhfQ5ajHY2E0pIGMjEY2sSJFUBSQHz5hU6x0iaHsOClPdJkhpVEbZgjer2AiAKAYwc44JsAZXCRmzaGCcvhnk4oDEMIzdRstHwKj1xiQuC1OyxMT-NwajXKdXbHAAxN48AAOwABzoKHatMZAqIQwgAbHLHJ0K49rQ8b8f1m-H8MpH9yeHUlfQYowYq2+JzywvzD1DojrhVtQNZ9LlAZBumysIpGZmxgmSYIqmbeZirrpd3Gfot3owaERmViaCXyCd+ZPcyMmaZKw6xdpJGWlMWThYFqtZcM90TO8-JSns1JXN6jzUCaI1At6kLOcMZAd-w5LGwa4iqhAbrYBE0bE2EMZj5CePyQUZdXD20dvsZ2n5jJy0Rn8bgxIgKEDjlDKYYCp5R14rEbQ3sIZnWOOwOS6hcHiS4qoZgmcGK1yHH8cCssoBGgoL+f82tZCriYRjT62N55nHKnmE6xDDC+DoOESBPVfZpSqL4XeYwP7iVjlneACc+hJygCnbBackG0NKKInA8j06uDiAAJghto0oHlnzBFCFeBRYBd4H1eqxd6LMgoqXyhpf6N8rC5EQP9L+Wtf5VAAY2Y23BTYMJAczM+niaYUKgTIB2zxYG8XgYtRB7stRYIMX7PocogQXFoleExI1PbewAOoeC8GbQxYBxHhFEFIjY+CvY+waX8AExSHKlKSaxXK3jNL1IKe1O+yBWm-HmKgxg6Cs6YMVlPEqIYHhdX3iRIpCpQQDjVEfdU-E+iqW0AVTS5SY4QwNJibBOIVnLNRB6L0Ntzn6P1Oia55tbnFTiI8xpAy2mMAAF4i0GoslI7hPCBMeKChu0NcJ2LCM9dZap1pOMppWNRSRaacmwifKASduaHJSEBXoJE9BRPQPYdJ4l7rYpYjcfklt2LSi0QXau5tdH0vNqA7lLKthsqWa0MSqKNqNh6dQEWAQGH10buC2pULUWH1xdtKAedCVXVkvYZADl-rkowFSs2sSUhDSlCMfO4Ui6z1LiRcVILIawqwR9BFZTGlKJ5HPQw4S9TAu0J6iZFNyzRHQKicCuya6P0xYnf6TRDpjj6ESAgUT-paA8D+SNfQ1V6hTdXL1rEgLqAAMI6DjQsh1fQ0hwiNBClgpA-B5ikY6ClBrQoGwJo2OS7B0j0X1rWNteoMComuqiBEJbGkkTeDIIdI7mEBG5iXTmhge2G0bIC+wzwVGNMwjiiN6jc7Rtnv03myBNh7BItmtNu78XJtnjmiZmz51Ft0MwmFsqoAVoSEaFAIR8C1t8PWslTbAYtt7SRDtXbF2tvHcGqdh6x2NgnTB0ds7r7zu7ZBlda60RiK3cxKW6aUgEr7Ae0dkAE3zDBGem9EGQNzrwM-Dl-0wMJHjGlWAgTxndlA+gTtCQADytQ5LzP-neudhbi3Pvta+1IwQP3VsQL+-9GH9BYaMTh+mgt8Oqv3bG5hYtj2nsbNm6jy6UN0eOBvB+rEmP8cRIJv1nHRNqEfaOl9cK30yc-c6hTAzICruUxu3wAawBshaEAA) instead of `datum`.

**Comment by kanitw** [comment] 2020-04-14 15:36
Will be fixed in https://github.com/vega/vega-lite/pull/6339

**Closed by kanitw** 2020-04-14 15:36 UTC
Labels: Area - Interaction, Bug :bug:, P3
