### ISSUE TITLE
make facet plot responsive

### ISSUE THREAD

**Issue by YevhDr** [vega/vega-lite#5785] opened 2020-01-22 16:00 UTC
Hello! I'm looking for the way to create responsive facet plot. Now "width": "container"  that I set in the config influences to every column I have. Is it possible to set total width of my facet plot? I want it to be 100% of the parent container, no matter how many columns does it have. May be something like 1fr in css. I will be grateful for any help.

**Comment by domoritz** [comment] 2020-01-22 16:32
Responsive sizing is currently only available for single views and layered.m charts.

**Comment by domoritz** [comment] 2020-01-22 17:20
Duplicate of https://github.com/vega/vega-lite/issues/5309

**Closed by domoritz** 2020-01-22 17:20 UTC
