### ISSUE TITLE
Mouseover color-encoding does not work/casues errors inside interval selection

### ISSUE THREAD

**Issue by keckelt** [vega/vega-lite#5728] opened 2020-01-08 10:23 UTC
Hi
I have a Histogram (binned quantitative) with interval selection and a hover selection (mouseover; spec below) to highlight the hovered bar.
When I set an interval and then hover over a bin inside, the hover color is not applied and there is an error every time my mouse enters the interval.

To me, it looks like the mouseover is not passed through the interval to the bins "behind" it

Spec:
https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATdHkw5gkVgCcx2LTvSlU3Co2Sx5ilQF91ESBiMBrM5HbojNQ1IZCV4bk1GJWozUAh3AA9YjXiodiizPCNWZDdUqAAzOzFNXwBJAFkAEQAhAH0AJR0omLzUyDwAT0JkXwBHVnQlPGZmqkgUsFdJyE7k-Kh0amojYTxenEhw1mGghY7ujagBoZHdEfHJ6fbwsW5A-Un3CnQxHN8AYgBWAE5f372+S2ykiI2UZgA2k94nEFvEOvY8PM4e0hqUcFCUQtgFBYMgxMh4GCVJs8QSichSlNoQsALo0+LXLGQF5vI6QD4AMU5AGEAMzSAAMExRTOxDPcZMJxN8iBsyECbThLNe7023wATDzBTyeSK4c5ofTUoaIEzIFKiTwSWBYZL8dLKcj2l0er4ousjKzAe00IQur4lMpekr3J4fPpIEUxKZ1dz+UK1IVGDGAPKEdDwZhzHCCug-VS4rLcLzsrm8gXC02MpWQOVUB626EHN2kloEn3wv0BzZBpQh5vgzbWVh4+WK5vwAkBXwjsesJFXDSGw1AA

**Comment by domoritz** [comment] 2020-01-21 19:01
Yeah, the mouse events are not passed through the brush. @arvind is this expected?

**Comment by Symmetronic** [comment] 2020-05-15 13:17
I encountered similar problems with highlight and select interactions. It would be great, if these could be combined with an interval selection.

**Comment by kanitw** [comment] 2020-05-23 16:41
Yes this is a current limitation (and a duplicate of https://github.com/vega/vega-lite/issues/3154).

**Comment by kanitw** [comment] 2020-05-23 16:41
@keckelt  Nice color scheme in your example btw. :)

**Closed by kanitw** 2020-05-23 16:41 UTC
Labels: Area - Interaction, Bug :bug:, P3
