### ISSUE TITLE
Padding differs if you use filter

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#950] opened 2016-01-15 20:51 UTC
<img width="614" alt="screen shot 2016-01-15 at 12 51 22" src="https://cloud.githubusercontent.com/assets/589034/12364981/be87778c-bb86-11e5-88de-a0b90bcd24ff.png">

**Comment by domoritz** [comment] 2016-01-15 20:53
I'm not saying it's bad or wrong but it's surprising nonetheless.

**Comment by kanitw** [comment] 2016-01-15 21:13
This is caused by a Vega issue that I reported this morning.  :)
I'm closing this because this shouldn't be fix at VL level.

**Closed by kanitw** 2016-01-15 21:13 UTC
