### ISSUE TITLE
Merge axis disabling

### ISSUE THREAD

**Issue by jheer** [vega/vega-lite#5407] opened 2019-09-24 12:52 UTC
See this [simple boxplot spec with `axis: null`](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgYATgGtsYYJDwBPQsn2R23AB6Ex3PJAC+6iJAAm6PJhyHWWsQt8IhJyKloGZjZOHiFaEU9vWGQ8WFJE9FJUbgpGZFh5RRUXDUhkJXhud0Ylan1QCDdreo1GqAAzPLF3CwBJAFkAEQAhAH0AJS8autc2qBMzCwBHVnQlPGYpqjVWxsh0a0ZYfSVWMTFdpw0rpyA). The axis should not be included, yet it remains. Similar behavior occurs with `errorbar` and `errorband` marks.

**Comment by kanitw** [comment] 2019-09-26 23:46
There are two root causes to this:

1) The composite mark code doesn't preserve `axis` when it's null. This will be fixed in https://github.com/vega/vega-lite/pull/5411. 

2) To disable axis for layered charts, currently we have to add `axis:null` to all layers.  (This is bad.)  To solve this, we need to re-model how we generate axis component by generating "hidden" axis component so that the explicit hiding command gets merged across layers.  https://github.com/vega/vega-lite/pull/5411 hasn't handled this yet.

**Comment by kanitw** [comment] 2020-03-15 20:29
This is no longer problematic as of VL 4.7

![image](https://user-images.githubusercontent.com/111269/76710021-fb0e6500-66c0-11ea-9be2-89c860032173.png)

**Closed by kanitw** 2020-03-15 20:29 UTC
Labels: Area - View Composition, Bug :bug:, P3
