### ISSUE TITLE
Including a field in a tooltip breaks aggregating that field

### ISSUE THREAD

**Issue by jowens** [vega/vega-lite#5992] opened 2020-02-29 20:42 UTC
This is the standard cars example but adding a `color` encoding (`Origin`). I wanted to aggregate (mean) on the `y` encoding (`Miles_per_Gallon`). If I include this encoding in the tooltip, the aggregation disappears. The below two pictures show the difference if I change the tooltip between `Miles_per_Gallon` to `Miles_per_Gallo`.

I think my desirable behavior would be if I include a field that is aggregated, the tooltip would show `mean(field)` instead of `field`.

Hopefully I didn't miss an existing issue that looks at this (I didn't see anything in the vl docs either).

https://gist.github.com/jowens/da4845936b35ee7ade554ca93e6741ab , with first few lines below.

```json
{
  "config": {"view": {"continuousWidth": 400, "continuousHeight": 300}},
  "data": {"name": "data-f02450ab61490a1363517a0190416235"},
  "mark": "point",
  "encoding": {
    "color": {"type": "nominal", "field": "Origin"},
    "x": {"type": "temporal", "field": "Year"},
    "y": {
      "type": "quantitative",
      "aggregate": "mean",
      "field": "Miles_per_Gallon"
    },
    "tooltip": [
      {"type": "quantitative", "field": "MxNxK"},
      {"type": "nominal", "field": "metric"},
      {"type": "quantitative", "field": "Miles_per_Gallon"},
      {"type": "nominal", "field": "schedule"}
    ]
  },
  "$schema": "https://vega.github.io/schema/vega-lite/v4.0.2.json",
  "datasets": {
    "data-f02450ab61490a1363517a0190416235": [
```

<img width="1148" alt="Vega_Editor" src="https://user-images.githubusercontent.com/976970/75614689-39682980-5af0-11ea-801e-efadeab52042.png">
<img width="1120" alt="Vega_Editor" src="https://user-images.githubusercontent.com/976970/75614692-3ff6a100-5af0-11ea-9436-6565e3bd9b5e.png">

**Comment by jakevdp** [comment] 2020-03-01 00:51
This is working as intended, I believe: the way you specify that you'd like to group by a particular field before aggregating is to put that field in the encoding. When you put ``Miles_per_gallon`` in the tooltip encoding, you are saying that you want to group by this field.

If you'd like to display mean of Miles per gallon instead, you can put that in the specification ([vega editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjMSA3ZApgO6bYwIAuy8ArrDQM4DqyAJhQBakAsADLwBooceFVr0GACQJoOFUgGZ+AX2UDwUVgEMKW0jhoAnADalI23QHpoWwwwB0AKwYJIajZAC2tgNZmADrDU8uoQkATwcKzU6FigEGFwxrCG+pAUAJ7+BGbwsJ7UWqZCkCgExqxmAPKGaNRuoQmQAB5pmdlmFASegYZFkCVlFWYAmgS2DRphGfpTTe05WJAAjjRaosi6VLg5jQlQWqiohgSoOotQnuPwA3NhQ5VLALLIxgQMAPrZhh8A4kXJG5zdz7dKwWDGKj+UgAbTuZAWZlW6yoW2QOwGUAeZiezQAcs0ANKTfYQHCIpZ5ArwfqDQjDJZXCi1aAk0nxUlhClQZEbNEYvak0r0x5QF5vT7fP4A1yC0GHY6nc5mK7rSDwkHs9JZC6QKmFYpYkVmBjQDgEVg0N5uOYAXQ0yhAyiAA):
```json
{
  "config": {"view": {"continuousWidth": 400, "continuousHeight": 300}},
  "data": {"url": "data/cars.json"},
  "mark": "point",
  "encoding": {
    "color": {"type": "nominal", "field": "Origin"},
    "x": {"type": "temporal", "field": "Year"},
    "y": {
      "type": "quantitative",
      "aggregate": "mean",
      "field": "Miles_per_Gallon"
    },
    "tooltip": [
      {"type": "quantitative", "field": "MxNxK"},
      {"type": "nominal", "field": "metric"},
      {"type": "quantitative", "field": "Miles_per_Gallon", "aggregate": "mean"},
      {"type": "nominal", "field": "schedule"}
    ]
  }
}
```
![visualization - 2020-02-29T165055 286](https://user-images.githubusercontent.com/781659/75617422-b8228e00-5b13-11ea-9bf3-0950b655c6c5.png)

**Comment by domoritz** [comment] 2020-03-01 02:16
Yep, you need to specify an aggregation. We could add a default aggregation (min) but that may be more surprising than the current behavior.

Closing but feel free to leave comments.

**Closed by domoritz** 2020-03-01 02:16 UTC
Labels: Bug :bug:

**Comment by jowens** [comment] 2020-03-01 19:34
This came up (in a different plot) when I had a field in a tooltip that was also an encoding and I decided I wanted to show an aggregation of that field and changed it in the encoding but didn't even think about the tooltip. That was hard to debug (which is why I bring this up), and slightly unexpected tbh, though your logic is sound. I could envision special-casing "tooltip" as something that you _don't_ group-by (the tooltip would show the aggregation) because tooltip is kind of a special encoding that doesn't affect the visualization, but on balance, I think the simple policy you're following is the right one.

That being said, I would think that it would not be a common case for a visualization to display an aggregated field AND to put the un-aggregated field in a tooltip AND to expect a group-by behavior for that field, so just for debugging purposes, perhaps that might merit a warning.

**Comment by jowens** [comment] 2020-05-09 22:17
OK, ran into this again today. An example might be helpful!

I have a table of fighters and their best placings for each of their fighting styles.

```python
import altair as alt
import pandas as pd

df = pd.DataFrame(
    [
        ["liukang", 1, "tiger"],
        ["liukang", 10, "crane"],
        ["liukang", 3, "shaolin"],
        ["johnnycage", 6, "tiger"],
        ["johnnycage", 5, "crane"],
        ["johnnycage", 4, "shaolin"],
        ["raiden", 8, "tiger"],
        ["raiden", 12, "crane"],
        ["raiden", 2, "shaolin"],
    ],
    columns=["Fighter", "Place", "Fighting Style"],
)
```

Let's see their best placings!

```python
alt.Chart(df, mark="point").encode(y="Fighter", x="min(Place)")`
```

![visualization (1)](https://user-images.githubusercontent.com/976970/81486165-d8538500-9207-11ea-987e-1227f3bcb6ed.png)


OK, let's add a tooltip too.

```python
alt.Chart(df, mark="point").encode(
    y="Fighter", x="min(Place)", tooltip=["Fighter", "min(Place)"]
)
```

![visualization (2)](https://user-images.githubusercontent.com/976970/81486174-df7a9300-9207-11ea-9401-12deaa82aa36.png)

And now, what fighting style gave them their best placing?

```
alt.Chart(df, mark="point").encode(
    y="Fighter", x="min(Place)", tooltip=["Fighter", "min(Place)", "Fighting Style"]
)
```

![visualization (3)](https://user-images.githubusercontent.com/976970/81486182-e73a3780-9207-11ea-8c25-daad39bb9246.png)

I know this violates the grammar. And yet I would like a way to add `Fighting Style` to the tooltip (so I can answer what seems to me to be a reasonable question of what fighting style resulted in the best placing) without affecting the contents of the chart.

**Comment by jowens** [comment] 2020-05-09 22:19
```json
{
  "config": {"view": {"continuousWidth": 400, "continuousHeight": 300}},
  "data": {"name": "data-d21dbc441f28680fbcd5fe46997fb8a4"},
  "mark": "point",
  "encoding": {
    "tooltip": [
      {"type": "nominal", "field": "Fighter"},
      {"type": "quantitative", "aggregate": "min", "field": "Place"},
      {"type": "nominal", "field": "Fighting Style"}
    ],
    "x": {"type": "quantitative", "aggregate": "min", "field": "Place"},
    "y": {"type": "nominal", "field": "Fighter"}
  },
  "$schema": "https://vega.github.io/schema/vega-lite/v4.8.1.json",
  "datasets": {
    "data-d21dbc441f28680fbcd5fe46997fb8a4": [
      {"Fighter": "liukang", "Place": 1, "Fighting Style": "tiger"},
      {"Fighter": "liukang", "Place": 10, "Fighting Style": "crane"},
      {"Fighter": "liukang", "Place": 3, "Fighting Style": "shaolin"},
      {"Fighter": "johnnycage", "Place": 6, "Fighting Style": "tiger"},
      {"Fighter": "johnnycage", "Place": 5, "Fighting Style": "crane"},
      {"Fighter": "johnnycage", "Place": 4, "Fighting Style": "shaolin"},
      {"Fighter": "raiden", "Place": 8, "Fighting Style": "tiger"},
      {"Fighter": "raiden", "Place": 12, "Fighting Style": "crane"},
      {"Fighter": "raiden", "Place": 2, "Fighting Style": "shaolin"}
    ]
  }
}
```

**Comment by domoritz** [comment] 2020-05-10 18:37
In the last example, I think you want to show a nominal field based on the aggregate of another field. That can be done with argmin/argmax.

```json
{
  "config": {"view": {"continuousWidth": 400, "continuousHeight": 300}},
  "data": {"name": "data-d21dbc441f28680fbcd5fe46997fb8a4"},
  "mark": "point",
  "encoding": {
    "tooltip": [
      {"type": "nominal", "field": "Fighter"},
      {"type": "quantitative", "aggregate": "min", "field": "Place"},
      {
        "type": "nominal",
        "field": "Fighting Style",
        "aggregate": {"argmin": "Place"}
      }
    ],
    "x": {"type": "quantitative", "aggregate": "min", "field": "Place"},
    "y": {"type": "nominal", "field": "Fighter"}
  },
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "datasets": {
    "data-d21dbc441f28680fbcd5fe46997fb8a4": [
      {"Fighter": "liukang", "Place": 1, "Fighting Style": "tiger"},
      {"Fighter": "liukang", "Place": 10, "Fighting Style": "crane"},
      {"Fighter": "liukang", "Place": 3, "Fighting Style": "shaolin"},
      {"Fighter": "johnnycage", "Place": 6, "Fighting Style": "tiger"},
      {"Fighter": "johnnycage", "Place": 5, "Fighting Style": "crane"},
      {"Fighter": "johnnycage", "Place": 4, "Fighting Style": "shaolin"},
      {"Fighter": "raiden", "Place": 8, "Fighting Style": "tiger"},
      {"Fighter": "raiden", "Place": 12, "Fighting Style": "crane"},
      {"Fighter": "raiden", "Place": 2, "Fighting Style": "shaolin"}
    ]
  }
}
```

The question in general is whether we can make a reasonable default for what aggregation function to choose. I agree that it would be nice if tooltips were not automatically added to the groupby. 

There does seem to be a bug with the generated expression in the example above. I'm looking into it.

**Comment by domoritz** [comment] 2020-05-10 18:43
Ahh, cool, found the fix. The issue was that we didn't support fields with spaces well.

![image](https://user-images.githubusercontent.com/589034/81507614-69336a80-92b3-11ea-9da9-c12999e8ee43.png)

I'll send a fix right now.
