### ISSUE TITLE
Sort array ignored in faceting order

### ISSUE THREAD

**Issue by willium** [vega/vega-lite#7699] opened 2021-09-14 14:37 UTC
![image](https://user-images.githubusercontent.com/356976/133277928-f3e74d73-5b4f-401a-bbfb-714b6b8f5664.png)

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "data": {"url": "data/movies.json"},
  "mark": "line",
  "encoding": {
    "x": {
      "field": "Release Date",
      "type": "temporal",
      "timeUnit": "day"
    },
    "y": {
      "field": "Worldwide Gross",
      "type": "quantitative",
      "aggregate": "sum"
    },
    "row": {"field": "MPAA Rating", "type": "ordinal", "sort": ["G", "PG", "PG-13", "R", "NC-17", "null", "Not Rated", "Open"] }
  }
}
```
[See in Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICCNsRpwIUmfIC+S5NoDW+4bLiKQcWVDbKassjRQAA8gkAAzc0FlfQAlOEE4JAg4AAIAETV3JUwATxx3dExEHDZtJD0cmgQ4AFVZOn1VXJA7EBbNCKiY9AB1MuiAdxplNIBxbTYICA88gv0ARwYkWUw6NRpSDyQyMm0+Yv0IBgRWpUnBsMiEnpAAWQAFAEEn1NiNgNn8wpAyv1kKh4ZNpMGgANogMYeB5QpQw-gARgAzB5Yh4AHIAYURAHYPLIGIJKiB0WxMG8sjElAB5AryAC6NiZQA)

**Comment by kanitw** [comment] 2021-09-18 08:21
Thanks for reporting!

This sounds like a duplicate of #5366?

**Comment by willium** [comment] 2021-09-18 15:44
Yeah, nice catch. Shouldn't be too hard to fix I imagine

**Closed** 2021-09-18 15:44 UTC
Labels: Bug :bug:
