### ISSUE TITLE
Buggy Height/Margin between vconcat'd plots.

### ISSUE THREAD

**Issue by ayush29feb** [vega/vega-lite#2924] opened 2017-08-25 14:08 UTC
```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"url": "data/sp500.csv"},
  "vconcat": [{
    "width": 480,
    "mark": "area",
    "encoding": {
      "x": {
        "field": "date",
        "type": "temporal",
        "scale": {"domain": {"selection": "brush"}},
        "axis": {"title": "", "labelAngle": 0}
      },
      "y": {"field": "price","type": "quantitative"}
    }
  }, {
    "width": 480,
    "height": 60,
    "mark": "area",
    "selection": {
      "brush": {"type": "interval", "encodings": ["x"]}
    },
    "encoding": {
      "x": {
        "field": "date",
        "type": "temporal",
        "axis": {"format": "%Y", "labelAngle": 0}
      },
      "y": {
        "field": "price",
        "type": "quantitative",
        "axis": {"tickCount": 3, "grid": false}
      }
    }
  }, {
    "width": 480,
    "height": 60,
    "mark": "area",
    "selection": {
      "brush": {"type": "interval", "encodings": ["x"]}
    },
    "encoding": {
      "x": {
        "field": "date",
        "type": "temporal",
        "axis": {"format": "%Y", "labelAngle": 0}
      },
      "y": {
        "field": "price",
        "type": "quantitative",
        "axis": {"tickCount": 3, "grid": false}
      }
    }
  }]
}
```

![image](https://user-images.githubusercontent.com/8674376/29717363-bd09345c-8963-11e7-80cf-f5adcf76fac8.png)

There is an odd margin between the 2nd plot and the 3rd plot. Looks like a bug to me, not sure where exactly things are going wrong.

**Comment by domoritz** [comment] 2017-08-25 16:48
I think the issue is that we set `align: 'all'` for the layout. Looks like an easy but important fix.

**Comment by kanitw** [comment] 2017-08-25 19:21
Thanks for reporting.  Fixed in https://github.com/vega/vega-lite/pull/2926

**Closed by kanitw** 2017-08-25 19:21 UTC
