### ISSUE TITLE
"Dot" in field name breaks the code

### ISSUE THREAD

**Issue by vivekratnavel** [vega/vega-lite#486] opened 2015-07-09 01:18 UTC
For example, the following spec doesn't work

```
{
  "data": {
    "values": [
      {
        "x.a": "A",
        "y": 28
      },
      {
        "x.a": "B",
        "y": 55
      },
      {
        "x.a": "C",
        "y": 43
      },
      {
        "x.a": "D",
        "y": 91
      },
      {
        "x.a": "E",
        "y": 81
      },
      {
        "x.a": "F",
        "y": 53
      },
      {
        "x.a": "G",
        "y": 19
      },
      {
        "x.a": "H",
        "y": 87
      },
      {
        "x.a": "I",
        "y": 52
      }
    ]
  },
  "marktype": "bar",
  "encoding": {
    "y": {
      "type": "Q",
      "name": "y"
    },
    "x": {
      "type": "O",
      "name": "x.a"
    }
  }
}
```

It throws the following error:
<img width="473" alt="screen shot 2015-07-08 at 6 17 10 pm" src="https://cloud.githubusercontent.com/assets/1051198/8585934/9ccfbb92-259d-11e5-9a87-f9d625ce8caa.png">

**Comment by kanitw** [comment] 2015-07-09 01:57
Unfortunately, this would also break how Vega refer to values so we don't plan to fix this anytime soon.

**Comment by kanitw** [comment] 2015-07-09 02:45
I would suggest using other symbol as delimiter for your data.

**Comment by kanitw** [comment] 2015-07-10 04:38
Actually, I was wrong I think dot in the field name is supported in Vega2 by adding a backslash as mentioned in https://github.com/vega/vega/issues/266#issuecomment-120088993.  

However, I haven’t got a chance to test with vega 1.  (Current Vega-lite is still on vega1 but we plan to migrate within 1-3 months.)

**Comment by kanitw** [comment] 2015-10-02 13:01
As mentioned earlier, https://github.com/vega/vega/wiki/Marks#value-references.  Using backslash in from of the dot works — so I’m closing this.

**Closed by kanitw** 2015-10-02 13:01 UTC
Labels: wontfix

**Comment by pratapvardhan** [comment] 2016-04-08 13:47
I'm afraid using backslash doesn't work @kanitw.

**Comment by domoritz** [comment] 2016-04-09 19:57
@pratapvardhan We haven't tested special escaping, spaces, or dots in field names. We collect issues in https://github.com/vega/vega-lite/issues/778.

**Comment by nbmorgan** [comment] 2019-10-23 17:12
Alternatively, how can I change the displayed legend to show the dot and not included it in the actual field?

**Comment by domoritz** [comment] 2019-10-23 17:47
You can define your own legend title.

**Comment by nbmorgan** [comment] 2019-10-24 00:31
It not the legend title where the issue crops up it's the field names. If I use a decimal point/period in the field name for a stacked chart it breaks.  I am currently subbing middle dot until I can fix it.  See my Legend below

![dot_legend](https://user-images.githubusercontent.com/1404206/67443669-9be97000-f5ba-11e9-952f-776b11c91905.png)

**Comment by domoritz** [comment] 2019-10-24 06:27
Can you give me a minimal example to reproduce this issue in a new issue?

**Comment by nbmorgan** [comment] 2019-10-24 17:22
``` python
import altair as alt
from vega_datasets import data

source = data.iowa_electricity()

#If you comment out this line the graph works
source = source.replace({'Fossil Fuels': 'Fossil Fuels > 1.0', 'Nuclear Energy': 'Nuclear Energy > 2.0', 'Renewables':'Renewables > 3.0'})

source = source.pivot( index='year', columns='source', values='net_generation')
source.reset_index(level=0, inplace=True)
source.head(2)

sources = source.columns.tolist()
sources.remove('year')
alt.Chart(source).transform_fold(
        sources,
        as_=['Source', 'net_generation']
    ).mark_area(interpolate='step').encode(
        x="year:T",
        y="net_generation:Q",
        color="Source:O"
    )
```

**Comment by domoritz** [comment] 2019-10-24 17:23
Could you make a small JSON example and file a new issue?

**Comment by nbmorgan** [comment] 2019-10-24 17:28
Do you know how I can recover the JSON generated by Altair? It's tough debugging issues between Altair and Vega.   

My question really is that "." has special meaning to both Altair and Vega-Lite and Just being able to map Legend Values to Pretty Non-DataScience names for making presentations would be useful. Is there a way to do that in Vega-Lite?  I cannot find an example.

**Comment by domoritz** [comment] 2019-10-24 22:49
Yes. You can either use the action menu to open the spec/export the spec (the circle with the three ...) or call `chart.to_json()` to get the json spec. You can then load the spec into https://vega.github.io/editor/#/ and remove parts that are not relevant for the bug. 

Thank you for helping us get to the bottom of this issue. We appreciate your effort!

**Comment by nbmorgan** [comment] 2019-10-24 23:55
Can one of you review this then I will open a new issue:

```JSON
{
  "config": {"view": {"width": 400, "height": 300}, "mark": {"tooltip": null}},
  "data": {"name": "data-98c925ee1df2c87b0d9c6b8530a5a3dd"},
  "mark": {"type": "area", "interpolate": "step"},
  "encoding": {
    "color": {"type": "ordinal", "field": "Source"},
    "x": {"type": "temporal", "field": "year"},
    "y": {"type": "quantitative", "field": "net_generation"}
  },
  "transform": [
    {
      "fold": [
        "Fossil Fuels > 1.0",
        "Nuclear Energy > 2.0",
        "Renewables > 3.0"
      ],
      "as": ["Source", "net_generation"]
    }
  ],
  "$schema": "https://vega.github.io/schema/vega-lite/v3.4.0.json",
  "datasets": {
    "data-98c925ee1df2c87b0d9c6b8530a5a3dd": [
      {
        "year": "2001-01-01T00:00:00",
        "Fossil Fuels > 1.0": 35361,
        "Nuclear Energy > 2.0": 3853,
        "Renewables > 3.0": 1437
      },
      {
        "year": "2002-01-01T00:00:00",
        "Fossil Fuels > 1.0": 35991,
        "Nuclear Energy > 2.0": 4574,
        "Renewables > 3.0": 1963
      },
      {
        "year": "2003-01-01T00:00:00",
        "Fossil Fuels > 1.0": 36234,
        "Nuclear Energy > 2.0": 3988,
        "Renewables > 3.0": 1885
      },
      {
        "year": "2004-01-01T00:00:00",
        "Fossil Fuels > 1.0": 36205,
        "Nuclear Energy > 2.0": 4929,
        "Renewables > 3.0": 2102
      },
      {
        "year": "2005-01-01T00:00:00",
        "Fossil Fuels > 1.0": 36883,
        "Nuclear Energy > 2.0": 4538,
        "Renewables > 3.0": 2724
      },
      {
        "year": "2006-01-01T00:00:00",
        "Fossil Fuels > 1.0": 37014,
        "Nuclear Energy > 2.0": 5095,
        "Renewables > 3.0": 3364
      },
      {
        "year": "2007-01-01T00:00:00",
        "Fossil Fuels > 1.0": 41389,
        "Nuclear Energy > 2.0": 4519,
        "Renewables > 3.0": 3870
      },
      {
        "year": "2008-01-01T00:00:00",
        "Fossil Fuels > 1.0": 42734,
        "Nuclear Energy > 2.0": 5282,
        "Renewables > 3.0": 5070
      },
      {
        "year": "2009-01-01T00:00:00",
        "Fossil Fuels > 1.0": 38620,
        "Nuclear Energy > 2.0": 4679,
        "Renewables > 3.0": 8560
      },
      {
        "year": "2010-01-01T00:00:00",
        "Fossil Fuels > 1.0": 42750,
        "Nuclear Energy > 2.0": 4451,
        "Renewables > 3.0": 10308
      },
      {
        "year": "2011-01-01T00:00:00",
        "Fossil Fuels > 1.0": 39361,
        "Nuclear Energy > 2.0": 5215,
        "Renewables > 3.0": 11795
      },
      {
        "year": "2012-01-01T00:00:00",
        "Fossil Fuels > 1.0": 37379,
        "Nuclear Energy > 2.0": 4347,
        "Renewables > 3.0": 14949
      },
      {
        "year": "2013-01-01T00:00:00",
        "Fossil Fuels > 1.0": 34873,
        "Nuclear Energy > 2.0": 5321,
        "Renewables > 3.0": 16476
      },
      {
        "year": "2014-01-01T00:00:00",
        "Fossil Fuels > 1.0": 35250,
        "Nuclear Energy > 2.0": 4152,
        "Renewables > 3.0": 17452
      },
      {
        "year": "2015-01-01T00:00:00",
        "Fossil Fuels > 1.0": 32319,
        "Nuclear Energy > 2.0": 5243,
        "Renewables > 3.0": 19091
      },
      {
        "year": "2016-01-01T00:00:00",
        "Fossil Fuels > 1.0": 28437,
        "Nuclear Energy > 2.0": 4703,
        "Renewables > 3.0": 21241
      },
      {
        "year": "2017-01-01T00:00:00",
        "Fossil Fuels > 1.0": 29329,
        "Nuclear Energy > 2.0": 5214,
        "Renewables > 3.0": 21933
      }
    ]
  }
}
```

**Comment by nbmorgan** [comment] 2019-10-25 00:00
Changing just the "." to "-" causes the vega editor to render the chart.  Therefore I think this is a Vega issue.

```json
{
  "config": {"view": {"width": 400, "height": 300}, "mark": {"tooltip": null}},
  "data": {"name": "data-98c925ee1df2c87b0d9c6b8530a5a3dd"},
  "mark": {"type": "area", "interpolate": "step"},
  "encoding": {
    "color": {"type": "ordinal", "field": "Source"},
    "x": {"type": "temporal", "field": "year"},
    "y": {"type": "quantitative", "field": "net_generation"}
  },
  "transform": [
    {
      "fold": [
        "Fossil Fuels > 1-0",
        "Nuclear Energy > 2-0",
        "Renewables > 3-0"
      ],
      "as": ["Source", "net_generation"]
    }
  ],
  "$schema": "https://vega.github.io/schema/vega-lite/v3.4-0.json",
  "datasets": {
    "data-98c925ee1df2c87b0d9c6b8530a5a3dd": [
      {
        "year": "2001-01-01T00:00:00",
        "Fossil Fuels > 1-0": 35361,
        "Nuclear Energy > 2-0": 3853,
        "Renewables > 3-0": 1437
      },
      {
        "year": "2002-01-01T00:00:00",
        "Fossil Fuels > 1-0": 35991,
        "Nuclear Energy > 2-0": 4574,
        "Renewables > 3-0": 1963
      },
      {
        "year": "2003-01-01T00:00:00",
        "Fossil Fuels > 1-0": 36234,
        "Nuclear Energy > 2-0": 3988,
        "Renewables > 3-0": 1885
      },
      {
        "year": "2004-01-01T00:00:00",
        "Fossil Fuels > 1-0": 36205,
        "Nuclear Energy > 2-0": 4929,
        "Renewables > 3-0": 2102
      },
      {
        "year": "2005-01-01T00:00:00",
        "Fossil Fuels > 1-0": 36883,
        "Nuclear Energy > 2-0": 4538,
        "Renewables > 3-0": 2724
      },
      {
        "year": "2006-01-01T00:00:00",
        "Fossil Fuels > 1-0": 37014,
        "Nuclear Energy > 2-0": 5095,
        "Renewables > 3-0": 3364
      },
      {
        "year": "2007-01-01T00:00:00",
        "Fossil Fuels > 1-0": 41389,
        "Nuclear Energy > 2-0": 4519,
        "Renewables > 3-0": 3870
      },
      {
        "year": "2008-01-01T00:00:00",
        "Fossil Fuels > 1-0": 42734,
        "Nuclear Energy > 2-0": 5282,
        "Renewables > 3-0": 5070
      },
      {
        "year": "2009-01-01T00:00:00",
        "Fossil Fuels > 1-0": 38620,
        "Nuclear Energy > 2-0": 4679,
        "Renewables > 3-0": 8560
      },
      {
        "year": "2010-01-01T00:00:00",
        "Fossil Fuels > 1-0": 42750,
        "Nuclear Energy > 2-0": 4451,
        "Renewables > 3-0": 10308
      },
      {
        "year": "2011-01-01T00:00:00",
        "Fossil Fuels > 1-0": 39361,
        "Nuclear Energy > 2-0": 5215,
        "Renewables > 3-0": 11795
      },
      {
        "year": "2012-01-01T00:00:00",
        "Fossil Fuels > 1-0": 37379,
        "Nuclear Energy > 2-0": 4347,
        "Renewables > 3-0": 14949
      },
      {
        "year": "2013-01-01T00:00:00",
        "Fossil Fuels > 1-0": 34873,
        "Nuclear Energy > 2-0": 5321,
        "Renewables > 3-0": 16476
      },
      {
        "year": "2014-01-01T00:00:00",
        "Fossil Fuels > 1-0": 35250,
        "Nuclear Energy > 2-0": 4152,
        "Renewables > 3-0": 17452
      },
      {
        "year": "2015-01-01T00:00:00",
        "Fossil Fuels > 1-0": 32319,
        "Nuclear Energy > 2-0": 5243,
        "Renewables > 3-0": 19091
      },
      {
        "year": "2016-01-01T00:00:00",
        "Fossil Fuels > 1-0": 28437,
        "Nuclear Energy > 2-0": 4703,
        "Renewables > 3-0": 21241
      },
      {
        "year": "2017-01-01T00:00:00",
        "Fossil Fuels > 1-0": 29329,
        "Nuclear Energy > 2-0": 5214,
        "Renewables > 3-0": 21933
      }
    ]
  }
}
```

**Comment by nbmorgan** [comment] 2019-10-25 00:14
Actually maybe it's an Altair issue??? If I escape in just transform block it work.  if I escape in the data block it fails again.

```json
  "transform": [
    {
      "fold": [
        "Fossil Fuels > 1\\.0",
        "Nuclear Energy > 2\\.0",
        "Renewables > 3\\.0"
      ],
      "as": ["Source", "net_generation"]
    }
```

**Comment by domoritz** [comment] 2019-10-25 00:24
Thanks for debugging! Do you think Vega-Lite should automatically escape the . here? I don't think so since you might want to reference a nested field.

**Comment by domoritz** [comment] 2019-10-25 00:24
Unless you disagree, I would file this as working as intended.

**Comment by nbmorgan** [comment] 2019-10-25 06:38
Vega is a target for a lot of autogenerated code. I think it should escape the dot or somehow allow for the option.  This is a tough one.

**Comment by domoritz** [comment] 2019-10-25 19:12
The dot is used to access nested data so I disagree that it should be escaped automatically.
