### ISSUE TITLE
faceting row/column, is there a way to specify the space between(negative or positive)?

### ISSUE THREAD

**Issue by afonit** [vega/vega-lite#3437] opened 2018-03-02 13:44 UTC
Looking to do some custom views/effects, I was reading through:
https://vega.github.io/vega-lite/docs/facet.html#facet-field-definition

And I am not seeing a means to specify the gap between the facts - weather there is a way to make them overlap by some amount or to spread them out more.

Is there a method to do this - did I look in the wrong place?

I was just playing around with the parameters to see what I can tweak.  I noticed these plots (joy plots):
https://bokeh.pydata.org/en/latest/docs/gallery/joyplot.html
Just tinkering around to see if I can reproduce that by hiding the axes and grids and making them overlap a bit.

**Comment by domoritz** [comment] 2018-03-02 17:54
We will add ways to specify the layout of composition soon but it's not possible right now. There may be a hacky way like in https://vega.github.io/vega-lite/examples/area_horizon.html.

**Comment by domoritz** [comment] 2018-03-02 17:56
Duplicate of #3270

**Closed by domoritz** 2018-03-02 17:56 UTC
