### ISSUE TITLE
Non-interactive marks can hijack interactions

### ISSUE THREAD

**Issue by jheer** [vega/vega-lite#4885] opened 2019-04-17 06:17 UTC
Observed behavior:
- Open [this example spec in the online editor](https://vega.github.io/editor/#/url/vega-lite/N4KABBYEQDYIYE8CmAnKAuMBtck+j0MigFs4UBrDMAouiKAFwQAclqoBzJAewGcAFnDZQANLnpEoAMwCWMGBwDEAEzViJkvFD6MUPCu0xQl0sxq1Td+wwHVZKxgOoBGTfQC+4y9BVxGcNS0PgwAriiKxn4BAPShfAC0LgAMJAB0AFZ8PAB2FiEM0jwoZIxB7gXQzCLGjDwsPFm5+ZXE0kj+4UbQuv5IfFAVWh5DhCOe3nTBkqTkVJjTPkys3VAAxrIoazDso3hee8TRgQuHUuGRvv5wMdIwspwCjIlwmw0ojGlrfABugz4HJZ6OA5PhFErUHCtRaVKBwTicFBITh9SFnEIw1pSeocNY8UI5MqTLEzOADYz6UKMfr-EljdH0AC6xKxXEpLAARgg0XTCFBig9ZHkGXRGSKIIDKpiQrAeAZQiwOALOEKWqzpPoSOVedpjtqdecIhxjjFXih3s8vr9aQbJQaoIZucZZNc1byZLIkDAVOTsOKZb1qW6DdB4IxZIxQip2CyQ6HcirI9GbTqxbzxpU7Rj-do5DBqWgop10oGkGAAIQAXkrYAA5AAFABKtbAADJW2BoqESwFqRXq3WAGoASVrKYB6OZ6J0XqQa3DzVOrRnMBS+pJyxqPSFnB2wYK-LyxhI+L4vB+qH3MpyHSRumoelCSFjsLkXp9PJD-JQguFvKn7pICQLDMBwOS5LsrQZsML5SEgOR4ioO7rjKYYRlG3TSksb7ehwaFJjGObENUqwAI6hCC4a9rIF7jpYWZLDACbocmS50h6754cxBFXkCKwcORlERv4NGQZmsEzHwsgAF6YURhSerhFL4tSAwSXxW5QIJhLCeGtHqZYOhrHAe5sfaKAgtwn5xhAyQGSSKTJMk8mEGmdIMbCOzcDkKjUDkoQKP6HlaN+0aFjQLkcUp0CUqpvGGSRAkUTp1H6ZF2QfMa-RrPBSE5JwdHDOi0FjBJWHEGQlAoRpqwoAFhHLtYBirEoTnJPF2IsHAGygZgyRpAAzAArMV9lXAE1WGRcxrXLc9yPM8CRmhaVp-KN07AqC4JapgUJSpFeYFpNG5njs86yIuPRemuLklQCY34JFTHyoqxjKqqD10DImrHayepmTZUDTUWsTLcUlrfGtcbBayjocC6E2fSFOEfrtLn0DovYNTZDD4RhHWskx+UsWJBpuSSd30UjEXus9FAKlluhCiJzTU7mP0A+6-00zj0DA+NNxgx8fCrYVWIw8ucPOq6bNfSjvp7TjsAiTxsshUTib4+jkDk+LavQGS1k6srVEYQATATjHcebYs+LrE522NUDwYhyGc4ZeOsTzG4o3hKv4-rm5kclVEibRQXU7KxM8e7B6+8YGsk5bX2JcY2mh3ppMhBLX2e0gFuxzK8ehv70YW4HqfQOnumibbdA51IicEQX3vqopvkJ9bZfJ1IldaSHNfh1BxWjCVAHECw+gZHOC5Hq32h9yZHKoHwACqfCBJoWZQAA7g4TjUAAnE5LJQAISAPE81BDSfmjrLkcgFYXUA-J6O+-doTWGH5AUwKPEmzCqoXBecp8yyFemAfygVPBbxAB4IAA)
- Mouse over a circle to make connecting lines appear. Make sure the mouse is placed over one of the line (`rule`) marks.
- Watch the display flicker as the selection updates and lines are continually removed and re-added.

Expected behavior:
- The rule marks are not interactive and do not intercept events.

Perhaps an appropriate solution is to have a policy that any marks not implicated in event processing have `interactive: false` set in the output Vega? One complication might be the Vega 3+ behavior of automatically enabling tooltips, in which case everything is implicated in event processing. I'm already skeptical of having tooltips always-on by default, but this seems to suggest that they might be harmful to interaction design.

Alternatively, we could expose an `interactive` property in VL for manual correction.

**Comment by jheer** [comment] 2019-04-17 06:19
FYI, I flagged this as a bug, but I'm not 100% sure how to classify this.

**Comment by arvind** [comment] 2019-04-17 14:22
Yes, this has been reported previously as #4553 and #4564. I'm going to close this in favor of #4564 which has an ongoing discussion of the best way to address this issue. My preference would be to use `interactive: false` because all the other options come with a whole set of idiosyncratic edge cases when considering multiview composition. However, `interactive: false` is tricky if tooltips are enabled by default. I've never been thrilled about tooltips being enabled by default so I'd be supportive of making them opt-in.

**Closed by arvind** 2019-04-17 14:22 UTC
Labels: Bug :bug:

**Comment by arvind** [comment] 2019-04-17 14:25
(Interestingly, with your example, I'm able to reproduce the flickering behavior in Chrome but not Safari)
