### ISSUE TITLE
Example broken

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#4455] opened 2019-01-13 15:19 UTC
https://vega.github.io/vega-lite/examples/geo_choropleth.html does not render anything.

**Comment by kanitw** [comment] 2019-01-13 15:37
Probably related to https://github.com/vega/vega-lite/issues/4451

**Comment by danmarshall** [comment] 2019-01-15 23:53
Applies to all examples in the image on https://vega.github.io/vega-lite/

**Comment by kanitw** [comment] 2019-01-19 22:46
duplicate of #4451

**Closed by kanitw** 2019-01-19 22:46 UTC
