### ISSUE TITLE
interactive legend

### ISSUE THREAD

**Issue by afonit** [vega/vega-lite#2434] opened 2017-05-31 15:32 UTC
After looking through:
https://www.domoritz.de/talks/VegaLite-OpenVisConf-2017.pdf
and
https://vega.github.io/vega-lite/examples/#interactive-plots
I am not seeing interactive legends and am wondering if that will be a feature.

Sometimes it can be useful when the colors are not enough of a differentiation or if there is slight over plotting - to select an item in the legend to have it get focus or disappear.

I interact with vega-lite through the altair library and currently solve this by filtering out a value then putting it back in or changing through color pallets and other means, but sometimes it would be convenient to be able to select and un-select items in the key.

Not sure if this would be widely useful but though it might be worth posting.

**Comment by domoritz** [comment] 2017-05-31 16:15
We do not support it right now but it's high on the priority list for 2.1. The main issue is figuring out default interactions so that this feature integrates well into the rest of the grammar. 

Duplicate of https://github.com/vega/vega-lite/issues/1657.

**Closed by domoritz** 2017-05-31 16:15 UTC
