### ISSUE TITLE
Binding selection param to axis for interaction

### ISSUE THREAD

**Issue by tonyxiao** [vega/vega-lite#7394] opened 2021-04-17 15:19 UTC
It is already possible to bind selection to a legend (https://vega.github.io/vega-lite/docs/bind.html)

However sometimes it is a lot more convenient to be interaction with axis label instead, especially when the data point represented is so small that it is very difficult to select it otherwise. Here's an illustration of the problem. 

![CleanShot 2021-04-17 at 10 16 07](https://user-images.githubusercontent.com/696842/115117802-f96b3c80-9f65-11eb-97ff-d73f65e25fb5.gif)

Here's what I'm thinking of
```json
"params": [{
    "name": "currency",
    "select": {"type": "point"},
    "bind": "axisLabel"
  }]
```

**Comment by domoritz** [comment] 2021-04-17 15:23
Duplicate of https://github.com/vega/vega-lite/issues/1657. Please add your example to the other thread.

**Closed by domoritz** 2021-04-17 15:23 UTC
Labels: Enhancement :tada:
