### ISSUE TITLE
Axis for ordinal-like timeunits make bad axis labels when type is temporal

### ISSUE THREAD

**Issue by willium** [vega/vega-lite#6589] opened 2020-06-05 21:53 UTC
We all know that this is true, which is why we recommend that users change the type to "ordinal" in these cases. However, I think [excluding nulls in these cases is misleading](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICUJNohSZ8gL5Lk2gNb6mpxSEzaksiADM22hGgA2qDeNIKYcNr6qgCeABSqmAwIlACacKYAlAAEAKTZAEwgVgC6SnCyUGzKNLJkaKAAHg0goXCCyvrpLkqYMThw+n41skh6vTQIcACqsnTRSDHFSkuaIEhkZNp8EfpVDLKYrn0D+gCODJ6YdGo0pMVWVkA), because we have a known domain (in this case: 1-7, corresponding to days in the week).

![image](https://user-images.githubusercontent.com/111269/83951166-7f661500-a7e4-11ea-8e6b-9ef05051965a.png)

I propose that for the ordinal-like timeunits that have text axes labels (quarter, month, day), rather than asking users to make the type ordinal, we normalize such [temporal types (which produce bad labels)](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICUJNohSZ8gL5Lk2gNb6mpxSEzaksiADM22hGgA2qDeNIKYcNr6qgCeABSqmAwIlACacKYAlAAEAKTZAEwgVgC6SnCyUGzKNLJkaKAAHg0goXCCyvrpLkqYMThw+hEIOH5Ier00CHAAqrJ00UgxxUrLmiBIZGTafBH6VQyymK59A-oAjgyemHRqNKTFVlZAA) 

![image](https://user-images.githubusercontent.com/111269/83951184-960c6c00-a7e4-11ea-8c89-30d7a2577a1b.png)

to [ordinal types with the known domain specified](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICUJNohSZ8gL5Lk2gNb6mpxSEzaksiADM22hGgA2qDeNIKYcNr6qgCeABSqmAwIlACacKYAlAAEAKTZAEwgVgC6SnCyUGzKNLJkaKAAHg0goXCCyvrpLkqYMThw+n41skh6vTQIcACqsnTRSDGu0GODmipsyLVBAIwKBQoAzApiCgCsCgBsCgDsJVY2IEvrSGRk2nwR+lUMspiufQG+gAjgxPJg6GoaKRig8gA). 

![image](https://user-images.githubusercontent.com/111269/83951198-a58bb500-a7e4-11ea-937b-b8042d35a249.png)

If users, for some reason, don't want this behavior, they can continue make the type ordinal themselves, bypassing the normalization step.

**Comment by willium** [comment] 2020-06-05 21:54
As a related aside: do we have any documentation on why when you use time unit with temporal, the axis labels are bad in Vega/D3?

**Comment by kanitw** [comment] 2020-06-06 18:29
Thanks so much for mentioning this topic. There are 3 different issues here: 

a) Automatically changing temporal to ordinal for quarter/month/day.

For this one, the problem is doing so will conflate continuous and discrete types because temporal in Vega-Lite is continuous.  Doing so will add more complexity and inconsistency to the system.  

Basically, if a temporal type (which supposes to output continuous) produces discrete scales, the down streams can't check types anymore. So I don't think we should do it. 

b) Allow automatic imputing timeUnit for ordinal scales  -- Yes! But the tricky part is how to turn the automatic imputation on and off. Let's discuss this in https://github.com/vega/vega-lite/issues/6592. 

c) Make tick counts better for the day time units (as in the second screenshot)

I think this is probably a Vega/D3 issue, so please file an issue there.  
(I tried adding `"nice": "day"` to x-scale and it still won't help, so there is definitely something we should fix in Vega or D3.) 



I'll close this issue for now, but let's discuss more in follow up issues.

Feel free to create a new issue for a) if you have a good solution. 



**Note:** This issue is a bit hard to process. If you don't mind, next time please:

1. Add screenshots in addition to links to the specs so it's much easier to follow?  Note that we often have to read the same issues multiple times (as we screen issues and later revisit to fix things, so it is important that issues are easier to process.   (For this issue, I already edited your description for this one, so I can read and think easier.)

2. File separate issues for different tasks to fix. This will make it easier to screen/track/have 1-1 mappings between PRs and issues.

**Closed by kanitw** 2020-06-06 18:29 UTC
Labels: Bug :bug:
