### ISSUE TITLE
x-axis labels can go beyond the axis bound

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2880] opened 2017-08-14 23:43 UTC
In https://github.com/vega/vega-lite/issues/2825, we found a similar issue is problematic for column layout. It seems like this is actually also problematic for legends.

```
{
  "data": {
    "url": "node_modules/vega-datasets/data/population.json"
  },
  "transform": [],
  "mark": "bar",
  "encoding": {
    "color": {
      "field": "sex",
      "type": "nominal"
    },
    "x": {
      "aggregate": "sum",
      "field": "people",
      "type": "quantitative"
    }
  }
}
```

![image](https://user-images.githubusercontent.com/111269/29296259-fcc92894-810d-11e7-89e5-ce3c84686caf.png)

**Comment by jheer** [comment] 2017-09-27 22:14
I've added support for culling labels that exceed the scale bounds (along with a pixel tolerance parameter, so that text might exceed the bounds by 2 pixels, for example). Those changes have been committed to vega-parser and vega-view-transforms, and will be included in the next batch of releases. The syntax for this is to include a `labelBound` property in an axis definition or axis config. If `true`, labels will be culled with a tolerance of 1 pixel. If numeric (and positive), bounds-based culling is enabled and the number value indicates the pixel tolerance.

**Comment by jheer** [comment] 2017-09-27 23:34
I've also added a new `labelFlush` axis and axis config property that accepts either a boolean or number. If `true`, the first and last axis labels (for an x-axis) are updated to use left and right alignment, respectively. Similarly for y-axes but with bottom and top baseline values.

If the value is a non-zero positive number, it acts similarly to `true` but adds an additional offset that pushes the first and last labels outwards by the specified number of pixels. This can help to make the labels visually align better with their ticks. However, using a numeric `labelFlush` may require increased numeric `labelBound` values to prevent culling, as the labels can be pushed out of the axis range bounds.

Both of the above changes have been committed to vega-parser and will be included in the next round of releases.

**Comment by jheer** [comment] 2017-09-29 20:02
Vega 3.0.3 has now been released with support for `labelBound` and `labelFlush`, both as top-level axis properties and axis config properties.

**Comment by jheer** [comment] 2017-09-29 20:03
Oops! I closed this issue thinking I was on a Vega repo. Re-opened as the new changes have yet to be picked up by Vega-Lite.

**Comment by kanitw** [comment] 2017-10-10 17:49
Will be fixed in https://github.com/vega/vega-lite/pull/3072

**Comment by domoritz** [comment] 2017-11-06 19:54
Is this fixed @kanitw?

**Comment by domoritz** [comment] 2017-11-06 19:55
Looks like it is so I'm closing this.

<img width="281" alt="screen shot 2017-11-06 at 11 54 48" src="https://user-images.githubusercontent.com/589034/32460990-540ef38c-c2e9-11e7-852f-889d53948623.png">

**Closed by domoritz** 2017-11-06 19:55 UTC

**Comment by oaubert** [comment] 2020-03-16 19:28
Has there been a regression since the time this bug was closed? I am facing this issue with vega-lite 4.4 / vega 5.9.2. Here is a minimal reproducible example (sensible to min/max values and width, but the ones I use here exhibit the bug). I tried various combinations/positions for labelFlush (in x2 encoding, in axes global config, etc) to no avail.

```
{
    "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
    "data": {
        "values": [
            {
                "begin": -3600000,
                "end": -3585060
            },
            {
                "begin": 2239460,
                "end": 2417821
            }
        ]
    },
    "vconcat": [
        {
            "width": 480,
            "mark": "rect",
            "encoding": {
                "x": {
                    "field": "begin",
                    "type": "temporal",
                    "axis": {
                        "title": "",
                        "labels": true,
                        "labelFlush": true,
                        "format": "%H:%M:%S"
                    }
                },
                "x2": {"field": "end",
                       "type": "temporal"
                      }
            }
        }
    ]
}
```

**Comment by domoritz** [comment] 2020-03-16 19:46
No, this is not a regression and a limitation of the current behavior of label flush in Vega. In your example, the last value does not exactly end at the end of the x-axis.

Here is a smaller example that demonstrates the issue in your data.

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {
    "values": [
      {"begin": 0},
      {"begin": 2417821}
    ]
  },
  "width": 480,
  "mark": "point",
  "encoding": {
    "x": {"field": "begin", "type": "temporal"}
  }
}
```

**Comment by oaubert** [comment] 2020-03-16 23:06
Thanks for the quick reply (and for all you great work on vega-lite, vega-embed, etc). 
I will then try to expand the upper bound of the timeline (through the recent domain.unionWith) to some round value that should be used as the final label.

**Comment by domoritz** [comment] 2020-03-16 23:41
Sounds good. I think Vega could improve the prevent labels going outside the axis area completely but that would be a feature request in Vega.
