### ISSUE TITLE
Bin is not working with specifying domain

### ISSUE THREAD

**Issue by yhoonkim** [vega/vega-lite#2422] opened 2017-05-25 22:36 UTC
When I specified `scale.domain`, `bin` didn't work.
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {
    "values": [
      {"x": 0.3349},
      {"x": 0.1216},
      {"x": 0.8341},
      {"x": 0.3341}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {
      "field": "x",
      "type": "quantitative",
      "scale": {"domain": [0,1]},
      "bin": {"maxbins": 20}
    },
    "y": {
      "field": "*",
      "type": "quantitative",
      "aggregate": "count"
    }
  }
}


```
Rendered:
![image](https://cloud.githubusercontent.com/assets/6269456/26473364/caa9d4a0-415f-11e7-97f1-d2f06ac61b0a.png)

What I expected (Vega-Lite 1 returns):
![vega 69](https://cloud.githubusercontent.com/assets/6269456/26473313/934ce916-415f-11e7-856b-65650963e7d4.png)

**Comment by yhoonkim** [comment] 2017-05-26 00:43
In my guess, the reported Vega-Lite spec should be compiled like this:
```json
{
  "$schema": "http://vega.github.io/schema/vega/v3.0.json",
  "autosize": "pad",
  "padding": 5,
  "data": [
    {
      "name": "source_0",
      "values": [
        {"x": 0.3349},
        {"x": 0.1216},
        {"x": 0.8341},
        {"x": 0.3341}
      ],
      "format": {"type": "json","parse": {"x": "number"}},
      "transform": [
        {
          "type": "filter",
          "expr": "datum[\"x\"] !== null && !isNaN(datum[\"x\"])"
        },
        {
          "type": "extent",
          "field": "x",
          "signal": "bin_maxbins_20_x_extent"
        },
        {
          "type": "bin",
          "field": "x",
          "as": ["bin_maxbins_20_x_start","bin_maxbins_20_x_end"],
          "signal": "bin_maxbins_20_x_bins",
          "maxbins": 20,
          "extent": [0,1] //Currently, vega-lite return this part as {"signal": "bin_maxbins_20_x_extent"}
        },
        {
          "type": "aggregate",
          "groupby": ["bin_maxbins_20_x_start","bin_maxbins_20_x_end"],
          "ops": ["count"],
          "fields": ["*"],
          "as": ["count_*"]
        }
      ]
    }
  ],
  "signals": [
    {"name": "width","update": "200"},
    {"name": "height","update": "200"}
  ],
  "marks": [
    {
      "name": "nested_main_group",
      "type": "group",
      "encode": {
        "update": {
          "width": {"signal": "width"},
          "height": {"signal": "height"},
          "fill": {"value": "transparent"}
        }
      },
      "marks": [
        {
          "name": "marks",
          "type": "rect",
          "role": "bar",
          "from": {"data": "source_0"},
          "encode": {
            "update": {
              "x2": {
                "scale": "x",
                "field": "bin_maxbins_20_x_start",
                "offset": 1
              },
              "x": {"scale": "x","field": "bin_maxbins_20_x_end"},
              "y": {"scale": "y","field": "count_*"},
              "y2": {"scale": "y","value": 0},
              "fill": {"value": "#4c78a8"}
            }
          }
        }
      ]
    }
  ],
  "scales": [
    {
      "name": "x",
      "type": "bin-linear",
      "domain": {
        "signal": "sequence(bin_maxbins_20_x_bins.start, bin_maxbins_20_x_bins.stop + bin_maxbins_20_x_bins.step, bin_maxbins_20_x_bins.step)"
      }, //Currently, vega-lite return this part as [0,1]. 
      "range": [0,200],
      "round": true,
      "nice": true
    },
    {
      "name": "y",
      "type": "linear",
      "domain": {"data": "source_0","field": "count_*"},
      "range": [200,0],
      "round": true,
      "nice": true,
      "zero": true
    }
  ],
  "axes": [
    {
      "scale": "x",
      "format": "s",
      "orient": "bottom",
      "title": "BIN(x)",
      "zindex": 1,
      "encode": {
        "labels": {
          "update": {
            "angle": {"value": 270},
            "align": {"value": "right"},
            "baseline": {"value": "middle"}
          }
        }
      }
    },
    {
      "scale": "y",
      "format": "s",
      "orient": "left",
      "title": "Number of Records",
      "zindex": 1
    },
    {
      "scale": "y",
      "domain": false,
      "format": "s",
      "grid": true,
      "labels": false,
      "orient": "left",
      "ticks": false,
      "zindex": 0,
      "gridScale": "x"
    }
  ]
}
```
Where there are two changes from the Vega spec derived from the reported Vega-Lite:
1) `data[i].transform.extent` has changed as the domain that the user specifies in the Vega-Lite spec. 
2) `scales[0].domain` got the proper `signal` rather than be overridden as `[0,1]` .

**Comment by domoritz** [comment] 2017-05-26 06:22
Good catch. So it sounds like the issue is that we should use the explicit domain as the extent and not the domain. Do you think you can take a stab at this?

**Comment by yhoonkim** [comment] 2017-05-26 21:03
@domoritz  I'd like to try to solve this issue by myself first if you're ok with some delay :) 
(It will be helpful for me to get used to Vega-Lite repo!)

**Comment by domoritz** [comment] 2017-05-26 21:36
Sounds good. Let me know if you have questions.

**Comment by yhoonkim** [comment] 2017-05-29 02:58
@domoritz 
I realized that there is `bin.extent` for setting domain of the bin. So my problem is solved. However, 
it is still a problem when `scale.domain` and `bin.extent` are specified together. 

My suggestion is ignoring `scale.domain` when the field is binned and throwing a warning message.

**Comment by domoritz** [comment] 2017-05-29 19:10
Thanks for looking into it. Yes, that's a great suggestion.

**Comment by kanitw** [comment] 2017-05-30 01:58
See #2429

**Comment by kanitw** [comment] 2017-08-06 21:36
Looks like this is still incorrect and should be fixed as a part of https://github.com/vega/vega-lite/issues/2791.

**Closed by kanitw** 2017-08-06 21:36 UTC
