### ISSUE TITLE
Legend title=None clips the y-axis

### ISSUE THREAD

**Issue by LouisDeconinck** [vega/vega-lite#9180] opened 2023-11-21 13:45 UTC
When setting orient='bottom', title='None' of a legend this will clip the y-axis:
```
chart = alt.Chart(df).mark_area().encode(
    x=alt.X('Year:T'),
    y=alt.Y('Count:Q'),
    color=alt.Color('Gender:N', legend=alt.Legend(orient='bottom', title='None'))
)
```
![image](https://github.com/vega/vega-lite/assets/27673665/4f7091a3-6c2d-4c85-95d1-6e48766c0cc1)

I had this occur when using an Altair chart in Streamlit. There this issue was also flagged a while ago: https://github.com/streamlit/streamlit/issues/5467

The workaround I'm using is: `title=' ', padding=-20`. This achieves a relatively similar result, but is of course not very clean.

**Comment by ChiaLingWeng** [comment] 2024-03-24 15:26
I try to reproduce the issue from the streamlit issue thread.
'''
import altair as alt
from vega_datasets import data

iris = data.iris()

iris_chart = (
    alt.Chart(iris)
    .mark_point()
    .encode(
        x="petalWidth",
        y="petalLength",
        color=alt.Color("species", legend=alt.Legend(title=None, orient="top")),
    )
)

#print(iris_chart.to_json(indent=2))
iris_chart
'''
and vega-lite script[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEzjQATjRyZ289AEEABNCTY46nILaZjMNgHcassoaZtlAT0PIIEQ0lllQwAzYRwcc0NBOGd6PzZgwwjnBicISkUVUxRUUAZ1QTQMbDxCAihlWSkIVWFidUpZOEwCWRwEXgp+ZWyIZogAAWIARkoAJgBOSgAGAh7MJAIaTXTpORAAXyUYqHcnMjRQXat1Q5BgmjhBZSKICKhLiEzoshib3JA2TRjMIsw2HCZHSYaJoWQMQSCLYgTAeCJFWRsBBOJCFaEADzOFyu7xAEQWggA6jRlPQgXC4EUAI4MALA0w0UibJQeLGXa5FfGogAyMTIZKUsPh6BpdLoDKZG2hyHUAGszkLKegcGwnL8pUA)

**Comment by domoritz** [comment] 2024-03-26 21:16
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEzjQATjRyZ289AEEABNCTY46nILaZjMNgHcassoaZtlAT0PIIEQ0lllQwAzYRwcc0NBOGd6PzZgwwjnBicISkUVUxRUUAZ1QTQMbDxCAihlWSkIVWFidUpZOEwCWRwEXgp+ZWyIZogAAWIARkoAJgBOSgAGAh7MJAIaTXTpORAAXyUYqHcnMjRQXat1Q5BgmjhBZSKICKhLiEzoshib3JA2TRjMIsw2HCZHSYaJoWQMQSCLYgTAeCJFWRsBBOJCFaEADzOFyu7xAEQWggA6jRlPQgXC4EUAI4MALA0w0UibJQeLGXa5FfGogAyMTIZKUsPh6BpdLoDKZG2hyHUAGszkLKegcGwnL8pUA). Closing since there doesn't seem to be an issue. 

Thanks for looking into these issues and sending PRs @ChiaLingWeng. Let me know if you would like to become an official maintainer of the project: https://github.com/vega/.github/blob/main/project-docs/MAINTAINERS.md

**Closed by domoritz** 2024-03-26 21:16 UTC
Labels: Bug :bug:
