### ISSUE TITLE
format not respected for timeUnit with type='ordinal'

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#3594] opened 2018-04-03 04:53 UTC
The axis format is not respected in the case of ordinal timeUnit encodings:

```json
{
  "data": {
    "url": "data/seattle-temps.csv"
  },
  "mark": "line",
  "encoding": {
    "x": {
      "type": "ordinal",
      "axis": {"format": "%b"},
      "field": "month"
    },
    "y": {
      "type": "quantitative",
      "aggregate": "mean",
      "field": "temp"
    }
  },
  "transform": [
    {
      "field": "date",
      "timeUnit": "month",
      "as": "month"
    }
  ],
  "$schema": "https://vega.github.io/schema/vega-lite/v2.3.0.json"
}
```
![export](https://user-images.githubusercontent.com/781659/38229926-29073cb2-36c0-11e8-8312-55df5f70f08a.png)

If you switch ``"ordinal"`` to ``"temporal"``, you get the expected result. This is not a problem when using ``timeUnit`` within the encoding itself.

**Comment by domoritz** [comment] 2018-04-03 05:12
The problem is that we don't know that the field is a date. 

Here is a hacky way to fix it. 

```
{
  "data": {
    "url": "data/seattle-temps.csv"
  },
  "mark": "line",
  "encoding": {
    "x": {
      "type": "ordinal",
      "axis": {"format": "%b"},
      "field": "month",
      "timeUnit": "month"
    },
    "y": {
      "type": "quantitative",
      "aggregate": "mean",
      "field": "temp"
    }
  },
  "transform": [
    {
      "field": "date",
      "timeUnit": "month",
      "as": "month"
    }
  ],
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json"
}
```

I don't remember how we were trying to solve this but one way would be to track whether a field is temporal or not or introduce a new type `temporal-ordinal`.

@kanitw might have a suggestion

**Comment by kanitw** [comment] 2018-04-07 20:54
I would strong vote against adding `temporal-ordinal`.  I don't see why we would need it.  

Casting raw temporal value as ordinal doesn't make sense.  Casting temporal value with timeUnit like month to ordinal is reasonable, but that doesn't need a new complex type.  

If we track the `month` is a field that is derived by applying `timeUnit` (#2862), this problem would go away. 

Since this is a duplicate of #2862, I'll close this for now.

**Closed by kanitw** 2018-04-07 20:54 UTC

**Comment by domoritz** [comment] 2018-04-09 04:11
Oh, I missed the time unit transform in the spec Jake posted. Yes, in this case we can track it. However, how do we handle this case if there is no time unit? I think we can ask people to parse fields as dates.
