### ISSUE TITLE
UTC timeunits do not return UTC times in Vega-Lite 4.0

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#5777] opened 2020-01-20 14:34 UTC
In Vega-Lite 4.0, UTC timeunits return the same value as their non-UTC counterparts. This was not the case in Vega-Lite 3.X

Here is a simple spec that demonstrates this:
```json
{
  "data": {"values": [{"t": "2020-01-01T12:00:00-08:00"}]},
  "mark": "point",
  "encoding": {
    "x": {"type": "temporal", "field": "t", "timeUnit": "hours", "title": "hours"},
    "y": {"type": "temporal", "field": "t", "timeUnit": "utchours", "title": "utchours"}
  }
}
```
I viewed this on a computer set to the US/Pacific timezone.

With Vega-Lite 3.4.0 & Vega 5.9.1, I see the expected result: the local hour is 12, and the UTC hour is 20.
![visualization - 2020-01-20T062720 626](https://user-images.githubusercontent.com/781659/72734181-1429e800-3b4e-11ea-924a-5af387309d13.png)

With Vega-Lite 4.0.2 & Vega 5.9.1, the result has changed: the UTC timeUnit is the same as the local timeUnit:
![visualization - 2020-01-20T062714 928](https://user-images.githubusercontent.com/781659/72734075-ee9cde80-3b4d-11ea-9c85-0092bf1c2264.png)

This seems to be the case not just for ``utchours`` but for every UTC timeUnit Vega-Lite supports: each UTC timeUnit returns identical timestamps as its non-UTC counterpart.

**Comment by jheer** [comment] 2020-01-20 16:48
Examining the generated Vega output, I see that the `timeunit` transformations are not using the `timezone` parameter. For UTC values, the parameter `"timezone": "utc"` should be applied. In addition, I see two `time` scales being generated. I would expect to see one `time` scale and one `utc` scale.

**Comment by haldenl** [comment] 2020-01-20 19:38
Thank you for the report and helpful details! I think I know where the issue is—the switch to vega time format was incomplete. Addressing today.

**Comment by haldenl** [comment] 2020-01-21 04:58
I made a PR, #5780 . When utc timeunits are specified, the fix creates compiled vega such that:

1. Transforms that have the 'utc' timezone.
2. Scales that have the 'utc' type.
3. Labels that are formatted with 'utcFormat' instead of 'timeFormat'.

An inconsistency I'm noticing. With the spec Jake provided, (1) and (2) are not necessary as long as (3) is true. What's more, if (1) and (2) are true but not (3), the result is incorrect (still local timezone). Is this okay for normalization's sake?

**Comment by SyntaxRules** [comment] 2020-01-22 18:46
I think I found another manifestation of this same issue, and may be fixed by @haldenl 's PR. I'll post the details here, let me know if this is a separate issue and I'll open up a different one.

Marks on the following chart are on the 1st and 15th of each month, but don't align with the axis marks. The marks are suppose to be in "timeFormat": "utcyearmonthdate" but show off by one.
![image](https://user-images.githubusercontent.com/4117657/72922858-108f9000-3d0b-11ea-9c50-d91a59479a6e.png)
[Here is a link to the spec](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATdHkw5QECJAroxrZLGxgA2hsNhgkTVcgAmAAweR7gIzefkAC+6vYQjs44bp7u-iI+AKxBIaHhLh5env5JdoapkekxmQnZoQ5OadHeAMxZgTkAusEakBgATgDWLq2sYshqzQDujJosVgBs7u7JkCiM1PhWPpPTyErw3JqMStRWBoaQAB67OUYIpn36TtwYW1bWUT4AnHGucYmqUAXe0lmNyfaQdAHRiWfQnfYAM24rQweBcAFIAJoieGoFHOf6hSDQxirOGRdjcAjXfqlIx4Zi9FwAYURpLJxlM5lBNnB9nCOguYB8HxaylGOB8rl5AE9kOhWlYPE8mmTck5OYteah+YglVAxRKpdFZXKyto8FyeVAVUoBWBhRrxZKcAVdXKOYb1XyzWqcFVRdbtR46nL6uD7ZDcWIIlo1GBwZA8CLCFyo2hCNDTOHIxTUMgAKpKZguVh4eCamGqg19AMaOp1IA)

I wait until the PR is ready, then try out the fix.

**Comment by domoritz** [comment] 2020-01-23 04:53
@SyntaxRules After the fix

![image](https://user-images.githubusercontent.com/589034/72957624-1a3fe480-3d59-11ea-80c9-2ec2ff9aee73.png)

This seems right since the dates are parsed as local, right?

<img width="583" alt="Screen Shot 2020-01-22 at 20 53 43" src="https://user-images.githubusercontent.com/589034/72957669-4ce9dd00-3d59-11ea-9f7b-13ffce068570.png">

**Comment by SyntaxRules** [comment] 2020-01-23 22:49
@domoritz Its closer 😄 ! What I'm expecting is the rule mark on "2020-01-01" to match exactly with the axis tick mark on "2020-01-01". In this use case I really do not care about what timezone the user is in, I always want the rule mark to line up.

I pulled up a editor with vega-lite 3.2.1 and this is what I got:
![image](https://user-images.githubusercontent.com/4117657/73030508-0a76dd80-3df7-11ea-8982-8d1b8e7d8f07.png)

This is what I expect; The marks align perfectly with the axis. 3.2.1 is giving me the desired chart.

**Comment by domoritz** [comment] 2020-01-24 04:53
Isn't that incorrect in vl 3.2.1? Your dates are midnight in local time (unless you are in UTC). Your scale and axis are in UTC on the other hand.

**Comment by haldenl** [comment] 2020-01-25 01:30
@SyntaxRules 
It looks like the issue has to do with the inconsistent parsing of the Date object (see [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse)). In the spec, data is given in `year-month-day` format, which is interpreted in UTC. The datetime objects provided as tick values are interpreted in local time. If we switch to the same formatting:

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {
    "values": [
      {"d": "2020-01-01"},
      {"d": "2020-01-15"},
      {"d": "2020-02-01"},
      {"d": "2020-02-15"},
      {"d": "2020-03-01"}
    ]
  },
  "mark": "rule",
  "width": 600,
  "height": 100,
  "encoding": {
    "x": {
      "scale": {"domain": ["2019-12-15", "2020-04-01"]},
      "axis": {
        "format": "%Y-%m-%d",
        "orient": "bottom",
        "title": "CY",
        "values": ["2019-12-01", "2020-01-01", "2020-02-01", "2020-03-01"]
      },
      "field": "d",
      "type": "temporal",
      "timeUnit": "utcyearmonthdate"
    }
  }
}
```

The output is as expected (on the fix branch). I wonder if something changed with datetime usage between 3.2.1 and 4.0. Will investigate.

![image](https://user-images.githubusercontent.com/11954298/73114431-2e0d5700-3ecf-11ea-924a-1ef65285e592.png)

**Closed** 2020-01-29 18:28 UTC
Labels: Bug :bug:, P1
