### ISSUE TITLE
Trellis plot: difference between vega-lite versions 1 and 2

### ISSUE THREAD

**Issue by jazzido** [vega/vega-lite#2425] opened 2017-05-26 17:20 UTC
Hi,

I noticed that vega-lite 2 renders my faceted plot incorrectly. Here's the desired output, produced correctly by vega-lite 1:

![image](https://cloud.githubusercontent.com/assets/27584/26505199/d8464664-4215-11e7-8df6-8ccb8795c77b.png)

vega-lite 2.0.0-beta.3 sorts the facets incorrectly:

![image](https://cloud.githubusercontent.com/assets/27584/26505224/eae52f42-4215-11e7-9ba6-cf4f0ca4da4d.png)

Plot definition: https://gist.github.com/jazzido/0e1616b604f78e4d14f4dad4e05c1b3f

Thanks!

**Comment by domoritz** [comment] 2017-05-26 17:29
Does this happen with master as well? We just merged a related fix a few days ago https://github.com/vega/vega-lite/pull/2412.

**Comment by domoritz** [comment] 2017-05-26 17:31
Looks like it's correct now. I'm closing this issue as it is fixed in master. We will publish a new version soon. 

<img width="662" alt="screen shot 2017-05-26 at 10 30 39" src="https://cloud.githubusercontent.com/assets/589034/26505630/6341d1ce-41fe-11e7-91fc-a1642456d715.png">

**Comment by jazzido** [comment] 2017-05-26 17:31
Thanks!

**Closed by domoritz** 2017-05-26 17:31 UTC

**Comment by domoritz** [comment] 2017-05-26 17:33
Thanks for reporting the issue and having such clear steps to reproduce it.

**Comment by jazzido** [comment] 2017-05-26 17:34
My pleasure. As an open source maintainer myself, I go by "do unto others…" :)
