### ISSUE TITLE
Tooltips on rule marks stop appearing if other marks are added

### ISSUE THREAD

**Issue by aragilar** [vega/vega-lite#6605] opened 2020-06-12 07:31 UTC
It appears adding additional marks to a plot stop tooltips for rules appearing. This is moved from https://github.com/vega/vega/issues/2706, with a more minimal example.

The non-working example is [here](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAHJQCMlAFYQ2AOxAAaEFBUAzGmTShiNOAHcDmlZhrKGbBhAAScPVjQBmAAweNW5VZt2EADqNAAm9GhiXgC+0RqhSJhIEHCYEOYJSfwATB5icJJwYm5ITACcHgCs2gBscNkA7G5l2kgyklDZHdk1lSioANqg2oIMAB5oHrINYpKVZdmLYpUeNWU1NZIagqVwgmggcGNICDiCcOogJkik58pkEai5HnHDoxOo-HIebm65lWIFmVfpUujVtrt9ugjiczhcNNdbnB7o8Ki8ALrxRICbL5bSSEq5bJIEo1QENGTzSpwUKrJBlJhMamhNBDEDKE4XdAAWTIAEk+ZdEXtkQ8YGhGmUpA1Kq92ZyDgMAMoC9FCm4ilHi1A1JqURoyaKYkCZAT0mQeOCeBq9KBwOBeSRIApiJA1bRlKBuQoNbRiJist7jSaUFbZAGSGTNb2VSluMQQph7A4w07nGTqpFaiUxNRBj5TMRNTa5JrzP4yBoNRPJ6HHNNwDMIjV3MVoNFGuIYZxkVyoKLeEA7ACecAAToGTdjzByEFyp1lzZbrbb7Y7nZJXe7Pd64L7-SAu8itKFrPpUKAPqAkGMaOkLyArJhzgcgi3RfQAAQACmUCAAlIeGi6HsLLoMKrYRBomDDjg84AI4MEgfh0IkNCkEBIDDuYN53uYT4vugmEgYIYEgCMwbQbBCFIShSRWBhsQaMgY4ANbmFoghsBO6BkGOcDYRobA4EgUB0NhqBTJUVFwQcwjKBcXYpOcUBWCo5jKXAqncV42TmEw1hkdASDnOkGjHmwp73PeAwgBMGjYcaMGyeg1iYOOxAmYeTGgKaM4Kugpo5HkBRFCU5RVLU9RNC0bTdN0vQoEeygnmeHFsFxPHDMYpFyZClzOfOyhsAg1heV2V4gLh96gAR85vlmYo-n+gFdiRZEQR+4oyTRyFPmhjEOTht41Y+dCESAxE5WRFH2Y+1EHIhfWoQxildix7HoPJil5gu-SgLO85BbicD4oSHjEqS5KUmUzJ0gyTI0phFlWeetVHJg5jtQch0FQt6DFaVHL7F2mBsBlVg4JO30AwqPU-SVZUg7tMNXO+2bw+gS10QNinGpV1X4eN9Xo01v4AVNoEHJ1GPzS5IDY-1q3ecxSBseYwmieJIZbCAEA0AAXly2SYyAY4MC+sTGiYYSPAO0RAA).

The working example is [here](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAHJQCMlAFYQ2AOxAAaEFBUAzGmTShiNOAHcDmlZhrKGbBhAAScPVjQBmAAweNW5VZt2EADqNAAm9GhiXgC+0RqhSJhIEHCYEOYJSfwATB5icJJwYm5ITACcHgCs2gBscNkA7G5l2kgyklDZHdk1lSioANqg2oIMAB5oHrINYpKVZdmLYpUeNWU1NZIagqVwgmggcGNICDiCcOogJkik58pkEai5HnHDoxOo-HIebm65lWIFmVfpUujVtrt9ugjiczhcNNdbnB7o8Ki8ALrxRICbL5bSSEq5bJIEo1QENGTzSpwUKrJBlJhMamhNBDEDKE4XdAAWTIAEk+ZdEXtkQ8YGhGmUpA1Kq92ZyDgMAMoC9FCm4ilHi1A1JqURoyaKYkCZAT0mQeOCeBq9KBwOBeSRIApiJA1bRlKBuQoNbRiJist7jSaUFbZAGSGTNb2VSluMQQph7A4w07nGTqpFaiUxNRBj5TMRNTa5JrzP4yBoNRPJ6HHNNwDMIjV3MVoNFGuIYZxkVyoKLeEA7ACecAAToGTdjzByEFyp1lcvlCsVShVqnVGs1Wu1Ot1eigu8itKFrPpUKAtII2BOLyBdHsWegdkn9hpMMOcPPlGwENYkPsXYfKASBjDQ6R3lYmDnAcQQtqK9AAAQABTKAgACUIBdg+ghPlc8HZu+n7zgAjgwSB+HQiQ0KQWEaMO5igeB5hQTB6B0fexi4QcIzBkRX4HGRFFQdRtGxBoyBjgA1gcwjKBccqmjOCroKaOR4gSSBEiSbrkpSZTMnSDJMjSHHHmwp73CxRyYOYOF4bO8IgB+AnoD+f4coB75sGwghWDgk72QcjmXC536-v+XnDFxeHCq2ET8aR5GUUkVhicawEgExEGgKx85wVmYooWhmHYTFBxxQh4qJYJyUiWlCldpJMl3mwOBIFAdAMagUxbCAEA0AAXly2Q1egY4MDBsTGiYYSPAO0RAA)

**Comment by aragilar** [comment] 2020-06-15 06:20
This appears to be the same as https://github.com/altair-viz/altair/issues/2009 and https://github.com/vega/vega-lite/issues/6003, or at least the workaround suggested seems to work.

**Comment by domoritz** [comment] 2020-06-15 15:59
Closing as duplicate of #6003.

**Closed by domoritz** 2020-06-15 15:59 UTC
Labels: Bug :bug:
