### ISSUE TITLE
log numbers went crazy in a recent checkin sometime in the last week

### ISSUE THREAD

**Issue by jowens** [vega/vega-lite#709] opened 2015-11-07 14:39 UTC
I surely missed a checkin you guys did that will affect my input vl. Kindly clue me in?

```json
{
  "marktype": "bar",
  "data": {
    "values": [
      {"m_teps": 33.5330810546875,"dataset": "ak2010"},
      {
        "m_teps": 21.458358764648438,
        "dataset": "belgium_osm"
      },
      {
        "m_teps": 1023.6077880859375,
        "dataset": "cit-Patents"
      },
      {
        "m_teps": 502.16387939453125,
        "dataset": "coAuthorsDBLP"
      },
      {
        "m_teps": 10.410270690917969,
        "dataset": "delaunay_n13"
      },
      {
        "m_teps": 187.35877990722656,
        "dataset": "delaunay_n21"
      },
      {
        "m_teps": 443.1048889160156,
        "dataset": "delaunay_n24"
      },
      {"m_teps": 55.096927642822266,"dataset": "europe_osm"},
      {
        "m_teps": 3530.5595703125,
        "dataset": "kron_g500-logn21"
      },
      {"m_teps": 79.42512512207031,"dataset": "road_usa"},
      {
        "m_teps": 2050.32421875,
        "dataset": "soc-LiveJournal1"
      }
    ]
  },
  "encoding": {
    "y": {
      "scale": {"type": "log"},
      "type": "Q",
      "name": "m_teps",
      "axis": {"title": "MTEPS"}
    },
    "x": {"type": "O","name": "dataset"}
  }
}
```

<img width="242" alt="vega_scaffold" src="https://cloud.githubusercontent.com/assets/976970/11015631/2f6fbd54-851a-11e5-9a41-9ffd1034805f.png">

**Comment by domoritz** [comment] 2015-11-08 20:03
Yes. The commit for this change is https://github.com/vega/vega-lite/commit/dfbd8347710a4b0a8a6c13c9113984648be84da6. I'll look into it.

**Comment by domoritz** [comment] 2015-11-08 20:57
This behavior is definitely not what we intended and we will change it. We would like to use precision prefixes (`k`, `M`, ...) but not the way they appear in the log scale example you posted. 

I'm not quite sure yet why this is happening. The problem seems to be that vega (through datalib) uses the same precision prefix for all ticks. 

I asked about the intended behavior at https://github.com/vega/datalib/issues/42.

**Comment by domoritz** [comment] 2015-11-15 23:06
Fixed in datalib and thus vega and thus vega-lite. Thanks for reporting!

**Closed by domoritz** 2015-11-15 23:06 UTC

**Comment by jowens** [comment] 2015-11-30 20:56
This now looks good with latest {vega,vega-lite} master, thanks.
