### ISSUE TITLE
Boxplot does not respect sorting

### ISSUE THREAD

**Issue by f4lco** [vega/vega-lite#5028] opened 2019-06-03 13:01 UTC
A simple boxplot does not respect the sorting of the X axis. Possibly, depending on how box plots work internally, this might be a duplicate / reproduction of #5013.

[Example in Vega Online Editor](https://vega.github.io/editor/#/gist/vega-lite/f4lco/8aea9b466dc856fa9626fc8cfa8c651b/8b151225c31dc28990a857932d931e8d5b055499/schema.json)

I generated the JSON specification using the following Python code:

```python
import altair as alt
import pandas as pd
alt.renderers.enable('notebook')

df = pd.DataFrame({
  'A': [1, 2, 3],
  'B': [3, 4, 5],
  'C': [5, 6, 7]
})

m = df.melt(var_name='strategy', value_name='fit')
alt.Chart(m).mark_boxplot().encode(x=alt.X('strategy:N', sort=['C', 'A', 'B']), y='fit')
```

And while the spec indeed contains a custom sorting:

```
"encoding": {
    "x": {
      "field": "strategy",
      "sort": [
        "C",
        "A",
        "B"
      ],
      "type": "nominal"
    },
    "y": {
      "field": "fit",
      "type": "quantitative"
    }
  }
````

The X axis is sorted alphabetically:

![visualization (1)](https://user-images.githubusercontent.com/29141485/58803507-fab04c00-860f-11e9-8a61-69ba60929da4.png)

**Comment by jwoLondon** [comment] 2019-06-03 14:20
See also #4917, which may be related.

**Comment by domoritz** [comment] 2019-06-07 18:42
Duplicate of https://github.com/vega/vega-lite/issues/4932 and potentially also https://github.com/vega/vega-lite/issues/3153, #5013. Learn more in #5048.

**Closed by domoritz** 2019-06-07 18:42 UTC
Labels: Bug :bug:
