### ISSUE TITLE
Issue with image encoding on maps

### ISSUE THREAD

**Issue by xoolive** [vega/vega-lite#7295] opened 2021-03-10 10:53 UTC
This issue is probably related to #6580 and comes after further investigation after this question on StackOverflow: https://stackoverflow.com/questions/66556550/plotting-image-on-maps-with-vega-lite-altair

The code below does not display the images. In the Vega (not lite) editor, it seems:
- `x1` and `x2` channels are artificially added;
- `width` and `height` configurations disappeared (see #6580)

Editing the corresponding code in the Vega editor accordingly seems to fix the issue:

```json
		  "x": {"field": "layer_1_x"},
          "y": {"field": "layer_1_y"},
          "width": {"value": 60},
          "height": {"value": 60},
```

Working [link](https://vega.github.io/editor/?#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhBMkUANZkATmwbiAJmhAB3GHTjSQOJBo01xZNAJk6aG+mgAsABhcz4NMlmtuZETABPABtDdCg4YOCjDSRMFFQAbVBxJAQwkFj4o2IkYIY4CDRkkFT07QBVcUw4ZQAzZSRxBThJWxoFeziEkABFAEYXAScAdiNguLoGDTCBF0oXfqWANmWBAA4AZnX+5fWAJicZYIlaTGmwgE5KS9Hlt2XLzYEly-2ZBmVo9CxcfCIGDgTqZKHZOulzFQ2MoyAQwTQcHBIQQoGwEAgJBACPQGAgmAR8UxlgQqjV6o1mq0APoAdSQOER4koEGIsJe+xwAA8ALSk2oNJotcS0+mM5msyg4SwgAC+UhSaQyAHkmPyKUKjPCsj0BkNhuNJucZr4FnNLiN9vs3C5notjqcpsbUEtKJsRvd+iMdkNLuthiMPl9tL88IQCIDgRpQR0aBCaFCYXCY4jkaj0ZjsYw8QQXDniXSGdSAEJwABeNGUCipKrVgta+3FbLcXO5BcZVJL5cr1dV5Lr4gbLLIkulcoV5XQADkaEjanJArU2roY9rtLqBAJLgbMI6wk51pQRi5VptdocNvtlu8QCdLLu0P0G17lps9k5lv0Ni5Lv1A98MNgoYAkCbAgvCcYJrC8IpvGKJohi4hYji2YjAQXoEG2xZlhWVbTrOyjzoujYEM8HI8phwqdjhVJ4TMBFIAuyhMkOI5WGOpSKtoNbKDgdR5KWmort0a6DBuAjbveqBONcmyXLcP5DC4+4CK+yz2neRphI+lBLEehyfu+m7ujYICfP+Ib-OGIFgTGEGUNCUHJkisFpghSFZvi-QEP06wYaK1Lcbx-HEZ6IwthRPa1EFwSlo2rGyvKHETiAACydA1MEAqUkuWrCeg64vBJmnODJ+6PpeWwbuauzqWcFwPvMz79KM+zrEex6XI8f7BoBlkRqBUbgc5kFJp0MH8K5GbIfivnrBoBBpdgkRZUKIqFsxrIkU8LaLRlK3UhRcVSmxiVlBkADKsA6Egqo5UJ2T5aJAhjMchr1VJB5nmJ-SXIsx7XredVOoMlAvE8ywWs8H5up13U-L1Yb9TZ4LDfZibQcNcHpohma4viAgEBufnrVSl0wNdt0dgxRFDgQThzOF-nCmTFPFtTTFHaOp2ceg3GEUxgmdKuj1DFeRXvfuOmLLslzDK++7vrVkkuiMKmq0MBx+rL5pwwBfyI9Zg22ajDmjQimOTTj00EJcNtwMT7Z8+zG2wlaLiMyTTuMS78UygAuuxZ3aNqVL9EYYifBEwfCTImAUhAdTQggxSgEEiLaGQcBsKIEhGHUM7BBoRRJDeDrFa9O7FX7-heKk-4TIxVIuFSmfZ2IwouAlqeBOn6CtzgbAWJgRg4KowhwFAO65+go-ZxPU9LvnkRF8UpcafVFf3tXIBIMXiQ3uzTdUpyBqN83gQgAHAfc8lIf7OHajKFH6CrrH8eJ8oydJN3vcgK3OeLwLivEugN7ybyrjXMgddtAN1qKHFuWcAFNy7iANOGR+6D2qCPMe892CSBnjgyeeC85AL3mvIGhhwH1W3rvVesDlDwJPq9Ru-QqQXyvv7GQs9x5EMxCnJKGRuG4NzjXUsYRQAQFrnkbQiQ7AOBgFIAABJ4bwmA-YJRAPnYeqAJFSP-IkehR9-7tybkowxrDjESCbuomUnCQDIErHvccGRDHNwcQoIosce4ZBqJyYe-ggihFXr44e28GhojQKAYWmRuihw0a0VETpQCAiyOIzREhtGgFyPkDIFQmDqHOBoxO1Rzo0DEZEkA2SCgPnWHKTRNAogVKqRkJgExFAaJmNAZQCIF4VMkVA6R6AAA6B9K4XFQIokZiiADUiiAAUH9kCYDmVkXEiQRkTDGTMEZ1dJkgBGQASgOTMvZABuRRoDNITKmbMhZSc4grLiGsjZZcLg7KUSMw5xzZkjPOWda5IATlzJoBAAAankewjzzgIHWQInZxyAD8ijVkwpGWdHZiiAUjOmSi2F6LL4HI0SfHR9Tl4wMPs3E+dSL4kqXoXclZ82EaJCX0vR2gQXguCJC3FaLFTwsUUinlcLL6Yr2dioV+KbEyAhVAppeRqnhFaGSDRcgICRAsGk5p2gED2A0EE2xtib4uMPqw9xnjUHePZcgTO4dAlhH3rGJANqwmqC-lEvKMT4hUnvnUhJbAkmmRwKkipnSoDdJwL0kl-ToHDNGbuAFQLFkPKFZs3c7yxUgCOSc35FzXkzATbcpNyyU15rgOmz5mbvlnMUWZAt8yOUQo0FC55pkvj8sFU81FrbggYqxSAHFnbYVmXhUSipdKtDoHMcfDRNLQDjoZXA1hF86lyMcCSrVqB7h1JUT4dd8qwhbrhrogZ-4G1cqbUK4dBKBXIsHSMq9ftRUVoHdCodbbL6ygNQHIAA) with Vega
Not working [link](https://vega.github.io/editor/?#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAZgAY2AacaYsiygAlMiRoRQAWDgF9p3ADYBDAJ6YATigDaoALaK1AazwhCygA6YUJzAA9x3GLysBVAEakipEA94BlOABelsgAjAAcciCYUJB0JEioIErEhKR0waDwmPJ0VslwqeneJubBIACOpIpEBYrEaJaR8tAIBWkZIFk5eS1tRdymFlaV1Sl1cA0gkYS24omDZVAQOiSK8sVducggUIo6jbKcuvpG86VWcHoIltyMIghiKACsXCDY9EzPbJHRsfHG+UKHU2eXGQOKC2GVRqhHGkyavXBiRB22aUFa4IG522IxhcMa3FIanWZyG2yWK126wcWG62yJ61k0gAutw6HVFMZdvsrOzYVNuAASShgO56KxiQhmSjIAD0soaCEUADoMYxSK5lXAILKRWLFArMEqALTyAqYBVPZVsa3KgBWlGgxT5ikomEIlGMLq0oG5ZWcRHUMDU1QM0WK7wM9A5VgAiiE2E8JAB2YqA9pfa0hbMANhzTzCLDCIRzYQATBIFIiM8gAJzK2spnMcHO1lhPbO1suE4kSwhSmXy0hmZqKOjKyOXTBxFUQNQIWWTiwz2WQHQ6aCUWVMUg6Vyy-euHOygMzNTB0PRAD61EUZgsUGVlDQC47ZbMNmNp6DIagYagN53g+T4vsqZjogKvp7GUADyrg-peUARnAUbets8aJkmaZgjWLzWi8tbJmWZYcGw7ZsCEVbon0wTZsqLDJs2ITJsWia1mESbJj2JIgJK0pyrKw6juOk77DOypzguS7TnABprhuUBbjue6ymwqnHre97XgAQpgARwIYV5wQhf7RGWIGvhwH7GppD5Xrp+mGcZ56-v+5nPggYEQXIUE8tsAByWDpGorgqOoSHcJOaEgBhTxPLW2EpDWEhhMqyZsHmLAlhWBZljm3ZJNWRShOZLE5iwpYSDmIQFmwtaUSADJ9gOAlCRAY4TihU7iZJi5dcusmrssClKeqKnJrKLGyrZOl6QZBhXoF07qKFqhqI+Hmyu276fjNAEOfNi1BStYXrRZXlID5OzQVYzlmDAawBMhqExuhCZxU8iU0ZI9YsLWjb1YmbApU8FU5lRGI1iE5nZulFY1VV8WMU83HNfxQ4ju1IldWJskSfOfVRgNcnDZu25jfuISyuE01Aded0PfIAQWdTybJtZe1GfBaj3Y953gZdRzXX5IAALIFDM8gXqZEVvF10WxR2X1IhIv0pdDeWFnFhElhD32hDaZUhCmZZhOlGW1q2qPbHxg6CZjHWiTJs4E9JK7yWTyn7mEsphHQsri-22TS-+gFaRtL5bW21mB5LIfXnt-PeULfpWL4orYIo8Gy1Fr0xe9TypgoOHFSlyrZR9IS1hRGUFWikPFQmyodm2OZEe21UMZb1u8f26P28JnVRrjLtSf1ztDeunsU7KTyz3PnPp4wmfZ-Zp0RwuEgvBzdMAUvK86evSeC75sHc6t4XPdG-JvYm+XK8lqUJrmtZJhVKVVXrSJ0cmoO-4m5YOKv0Ij3W2rUHbY2Hs7fGY8iYTw9opcmu59y1llLWC0nNnIXzOptEibAd7hy5idNaG8LpTGZLIIAA) with Vega-Lite

```json
{
  "config": {"view": {"continuousWidth": 300, "continuousHeight": 400}},
  "layer": [
    {
      "mark": {"type": "text", "font": "Ubuntu", "fontSize": 18},
      "encoding": {
        "latitude": {"field": "latitude", "type": "quantitative"},
        "longitude": {"field": "longitude", "type": "quantitative"},
        "text": {"type": "nominal", "field": "name"}
      }
    },
    {
      "mark": {"type": "image", "height": 60, "width": 60},
      "encoding": {
        "latitude": {"field": "latitude", "type": "quantitative"},
        "longitude": {"field": "longitude", "type": "quantitative"},
        "url": {"type": "nominal", "field": "url"}
      }
    }
  ],
  "data": {"name": "data"},
  "$schema": "https://vega.github.io/schema/vega-lite/v5.0.0.json",
  "datasets": {
    "data": [...]
  }
}
```

**Comment by domoritz** [comment] 2021-03-10 15:03
It looks like we don't handle images correctly with geo coordinates. Thanks for the bug report. 

x and y work correctly [Open the Chart in the Vega Editor](https://vega.github.io/editor/?#/url/vega-lite/N4IgtghgTg1iBcoAuBPADgUwSAlpA5lgDQgAWGO+pSCArAAwkDuOAJkqXfQL4kYB2AYwD2rHP3wJQADykgAZjgwAbVtmUQkOJAFdWxEKkzYAjjoj8tSTTgBuWXiBRzFKtfBDLhE7XoNGsDzMLKxt7EEcdKGU5AOx+YTBxCBiSV1VsKJjuR1ZNCDl+CDBAkDzrCJIAEgBnQXJIbGokNBr4AHp2+3wIADp8bVIdACNenGF2uoaILowegFplbQwu2l76dd6AKxrvEBJyiBqMJBq5Q4QAbVAikuwAVUsMKHkoCxgBfZAWGDZ87AAigBGei0AAsAHYvhorH4uOsgYiAGxI2gADgAzGigUi0QAmMEkLw+XT6BAATl65MhSPo9CR5IxtER5LxJCyTSQLTanR0aC8EFYvR+eAwYj6wig+HaIsw4vaIjAYG8NXaHB0YGG7S1wyR7UeSGer3eAgA+gB1CBoTD8Xo1WzS5l4tDSeYGo1vfgffgWq02u0O3poCSVG7FUoAeWGHpN-C+IouHmBoPB0JspMCDHWDHJELxeLp9CZ9CBRO8AwzCERvQxENpQIh2NB5LR4Ih7OinO5HXafIFQpFJXFvUl0tlYpwM0Vyv4qvVmva9EXest1rNACEMAAvHCwU1RmNegR4gOOuku+arm2mzc7vcHl6e70n+34IMh7gAXRyQA)

long/lat do not [Open the Chart in the Vega Editor](https://vega.github.io/editor/?#/url/vega-lite/N4IgtghgTg1iBcoAuBPADgUwSAlpA5lgDQgAWGO+pSCArAAwkDuOAJkqXfQL4kYB2AYwD2rHP3wJQAGwhIcSAK6ssiEADMcGaa2yz5SlSBKpM2AI6KI-A3JwA3LLxDThEhctWhN23fBdu+B5GJuiqIJbWtvKOIM6KUNJSIKbh-MJg4hBJJD462AlJ3M6schDJ-BBg4aVI5c4AJADOguSQ2NRIaE3wAPS9jvgQAHRBHIoARsM4wr0tbRADGEMAtNIKGAO0w-Q7wwBWTW7GILUQTRhITclnCADaoJXV2ACqNhhQ6lDWMAInLDA2GVsABFACM9FoABYAOwnfTBVQMHZg1EANjRtAAHABmLFgtFYgBMUJIrnchlUAE5hlTYWj6PQ0VScbRUVSiSRCh0kF0ev1FGhXBBWMMAXgMGIRsIoPheuLMFLeiIwGA3E1euMwBNejqJmjem8kB8vj8BAB9ADqEDQmH4wya9jlbKJaAAHisjSbvvxfvwrTa7Q6ncM0BI4kRHlVwgB5Cbes38f44QG3fzgyHQ+F2SlcHYMKkwolExn0Vn0MFkwKIhCo4Y4mEMsEw-GQqlY6EwrmJHl8vq9QXC0Xi6pS4YyuUKyU4RYqtX8DVanX0XpM3rW20WgBCGAAXjhYOa4wnfQIicHnYz3SsN3bzTv94fj58fX7z478KHw9wALrFIA)

We need to update https://github.com/vega/vega-lite/blob/master/src/compile/mark/encode/position-rect.ts. @xoolive do you want to take a look and send a pull request to fix the issue?

**Comment by xoolive** [comment] 2021-03-10 15:12
Thanks for the pointer. I'm pretty Javascript illiterate but this could be the occasion, esp. if you tell me where to look. 

I'll give it a try

**Comment by domoritz** [comment] 2021-03-10 15:38
I think this is a duplicate of https://github.com/vega/vega-lite/issues/6580, though.

**Closed by domoritz** 2021-03-10 15:38 UTC
Labels: Area - Map, Bug :bug:, P3

**Comment by xoolive** [comment] 2021-03-10 15:51
Indeed @domoritz the same fix works there as well.

**Comment by domoritz** [comment] 2021-03-10 16:11
I think https://github.com/vega/vega-lite/pull/7296 fixes it.

**Comment by xoolive** [comment] 2021-03-10 16:42
Thanks, looking forward to try it in next release!
