### ISSUE TITLE
Allow zoom/pan scale binding for geo data

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega-lite#8856] opened 2023-04-21 10:48 UTC
Great to see the ability to use interval selections with geoData with the VL5.7 release. This makes brushing between geographic and non-geographic views a possibility, which is something I've wanted for a long time. Thank you.

Does this make the possibility of a bind scales option for longitude/latitude data a viable prospect? It would be great to allow zooming and panning of geodata (which often benefit from zooming more than many other data types) via an interval selection so that we don't have to rely on [range sliders to control projection parameters](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAdxoATemgBsAFgAMS+DTJY0AZgBMBkDiQAnJAghoA2qFmO4aENCSCvSsR+DF6oAIx61kw0smpooDE4DJjeDrJkASAeCKE2dgDKUH6ZCDFoEdbIAB7lkdYQmHA45QC+LQrunt5QcLIAMo5MaiiBwaFRMXGoCbJJKehpGYpZXeg4dgDCvY12AASA3cDLpfKo-GEAHJVINeGXSg1Nre2dOd29AAowNMtBgiFoE1i8RAiWSqSQ6Uy2Vy6y2sh2u0ArBuATH2jmVTgBOK43LH3RrNVBiNoAXSU6zYkjgUEw7BOoEwAE8cLk4ABHBh+ACi9k0Sh68LgdmBcCq628Ln5AwQQyQCn5nxoxJA7R8RX8wtFQvQvnVbSUgiQDMFrlAw0wKGmPhw8DsoUwdhCKuQdgA1sDGczvBk2BAYEhPUoAGY0QSCVJkJgACisOgUVi0CguWgAlMsGnY2C7ckwDVA3XiM1mAPK2KB0BkAyhmPWmpDm4EMOxh9BYXD4IhQNSyKQQNRwYTEOyUWRwTAEWYIEg0CC03x2TBsfjKNhNtT8OsGiAEZerghiPQIHtyZaBlfIeb0pm5Bc4CkyeRBuB1xu5KBsBjwuw0ODOPUgZ1upaHq5N6vr+pkwahuGUYWGYYhxmEGKJucYSpgWma5HYEbRmECZhDo5yJmEFhoT49oYQA6uomioHolAWDWIBmhaoBkA4NJQAw6qWg8BIuBEiZ6MSf4Ae6V5enAPp+gGZGFiBtoVuhWZURoMCVgxLTCUAA).

It wouldn't need any change to the API as it could use exactly the same API as used for cartesian positioning (which currently generates the error `Cannot read properties of undefined (reading 'on') [Warning] Scale bindings are currently only supported for scales with unbinned, continuous domains.` when used with longitude/latitude projected data)

**Comment by joshuahhh** [comment] 2024-05-28 05:19
Heads-up @joelostblom – There's a way to mark an issue on GitHub as a duplicate, rather than closing it as completed: https://docs.github.com/en/issues/tracking-your-work-with-issues/marking-issues-or-pull-requests-as-a-duplicate. I think it would be better to use that, since it's a bit confusing to see "closed this as completed" in the log here. Thanks!

**Comment by joelostblom** [comment] 2024-05-28 10:49
Oh, I didn't know of that functionality. It's handy to have as a saved reply, thanks!

Duplicate of #3306

**Comment by joelostblom** [comment] 2024-05-28 10:50
Oh, I didn't know of that functionality. It's handy to have as a saved reply, thanks!

**Closed by joelostblom** 2024-05-28 10:50 UTC
Labels: Enhancement :tada:

**Comment by domoritz** [comment] 2024-05-29 01:38
Didn't know either. Will save that as well.
