### ISSUE TITLE
Sort:null doesn't connect line correctly

### ISSUE THREAD

**Issue by christophe-petitjean** [vega/vega-lite#5974] opened 2020-02-24 09:25 UTC
Issue following https://github.com/vega/vega-lite/issues/5951

When I set sort:null on a line chart, the lines seems to be connected by the order of the records instead of being connected by order of the horizontal axis.

```
{
  "data": {
    "values": [
      {"Month": "05. January", "Temperature": 14.7, "Index": 1},
      {"Month": "04. February", "Temperature": 16.4, "Index": 2},
      {"Month": "08. March", "Temperature": 18.7, "Index":3},
      {"Month": "01. April", "Temperature": 20.9, "Index": 4},
      {"Month": "09. May", "Temperature": 23.5, "Index": 5},
      {"Month": "07. June", "Temperature": 25.8, "Index": 6},
      {"Month": "06. July", "Temperature": 26, "Index": 7},
      {"Month": "02. August", "Temperature": 26.3, "Index": 8},
      {"Month": "12. September", "Temperature": 26.4, "Index": 9},
      {"Month": "11. October", "Temperature": 23.3, "Index": 10},
      {"Month": "10. November", "Temperature": 18.2, "Index": 11},
      {"Month": "03. December", "Temperature": 14.6, "Index": 12}
    ]
  },
  "mark": "line",
  "encoding": {
    "x": {"field": "Month", "sort": null, "type": "ordinal"},
    "y": {"field": "Temperature", "type": "quantitative"}
  }
}
```

Result: 
![](https://user-images.githubusercontent.com/354149/75050607-93536880-54cc-11ea-87a9-28ee6ea098e2.png)

**Comment by jakevdp** [comment] 2020-02-24 13:46
I believe this is expected behavior: the sorting of the axis and the sorting of the line connections are adjusted by different means (see https://vega.github.io/vega-lite/docs/line.html#connected-scatter-plot for example).

I don't think there's the equivalent of ``sort:null`` for the order channel, but you can achieve what you want by adding an explicit index to the data, and using this for both the axis sort order and the order encoding ([vega editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4yghSA3WAbArgKYDOKYA2uBhMJALID2AdvABZmQAMArAHRgApWE3ywATgE9IAGigAVQgFsADoTEJ8YwmQCMAFl4B2WZACSTaIQAeugL7Sq1WoxbtUXA2ABihAEZjRSRl5JVV1eE1tVB0ANl49E3NLG1QAJntHDGdmNg5OAA5+OnEAY3YTBRU1DS1dQuMoJOsyAGYM6hp6HLcoTh1+AEFlMQBLXGDISrCaqLBUzl4ATkSLZtQ9do7s1zzFotgpCtDqiNq0lt5uFeSybk2nLp33TkN+AXwmbSOq8MiyVL4+WuazAMXuWUeuWecUE+FwhxCPxm-xiwJSYEM4M6LihvVSg3wAHN8MR4BMpic-mk4i00WR8li0JCepAdPiwABlQjKeBKXxqcnHX5nOZxBKNVboxaM7a41n9MAAeRK8AY-LEgqRp1mqQutIlN2inBlzI4OgWYAAcgwsHyBd9ptq6rxUnTojoTTiWZwLmAACKEEp2jUOyki-S8VEGkFs2yZAC6VE2kHg6iYxAAZgwxIoyORaAB3EYWBgFvO0BjKDglBgfMkmWCkdzFm62eNthyYRTiADWHFwxa+VEghCYNegxcJZHQGEg6NoGZGhFw0A4XomxGzZNQC6XK44Lea9ig8Akqg42YnTDwkHBkCkO8gi+Xq-cFOFXxPZ9mkAAjqIWBGRB4BGW1b07WdLwFR9n33ZtJQmU9z3cS9ixvOMIDjWwgA)):
```json
{
  "data": {
    "values": [
      {"Month": "05. January", "Temperature": 14.7, "Index": 1},
      {"Month": "04. February", "Temperature": 16.4, "Index": 2},
      {"Month": "08. March", "Temperature": 18.7, "Index": 3},
      {"Month": "01. April", "Temperature": 20.9, "Index": 4},
      {"Month": "09. May", "Temperature": 23.5, "Index": 5},
      {"Month": "07. June", "Temperature": 25.8, "Index": 6},
      {"Month": "06. July", "Temperature": 26, "Index": 7},
      {"Month": "02. August", "Temperature": 26.3, "Index": 8},
      {"Month": "12. September", "Temperature": 26.4, "Index": 9},
      {"Month": "11. October", "Temperature": 23.3, "Index": 10},
      {"Month": "10. November", "Temperature": 18.2, "Index": 11},
      {"Month": "03. December", "Temperature": 14.6, "Index": 12}
    ]
  },
  "transform": [{"window": [{"op": "count", "as": "index"}]}],
  "mark": "line",
  "encoding": {
    "x": {"field": "Month", "sort": {"field": "index"}, "type": "ordinal"},
    "y": {"field": "Temperature", "type": "quantitative"},
    "order": {"field": "index", "type": "ordinal"}
  }
}
``` 
![visualization - 2020-02-24T054447 471](https://user-images.githubusercontent.com/781659/75157357-d24e0d80-56c8-11ea-915b-e0d94ca38d42.png)

**Comment by christophe-petitjean** [comment] 2020-02-24 14:57
I don't understand why setting sort:null on x encoding is changing order of line connections. Line should be connected by increasing x (ie by "Month" in the order of the records) and not by an invisible 'order' encoding sorted by "Month".

Maybe I'm not understanding https://vega.github.io/vega-lite/docs/sort.html correctly

**Comment by jakevdp** [comment] 2020-02-24 16:36
By default the line is connected in order of the sorted x-coordinate. If you want to change this, you need to use the ``order`` encoding.

**Comment by christophe-petitjean** [comment] 2020-02-24 16:59
Exactly. I don't want to change the order of connection but the order of x-axis. But the result seems to show that the line are connected in another order

**Comment by jakevdp** [comment] 2020-02-24 17:13
Take a look at the order in which the points are connected when ``sort`` is not specified:
```
{
  "data": {
    "values": [
      {"Month": "05. January", "Temperature": 14.7, "Index": 1},
      {"Month": "04. February", "Temperature": 16.4, "Index": 2},
      {"Month": "08. March", "Temperature": 18.7, "Index": 3},
      {"Month": "01. April", "Temperature": 20.9, "Index": 4},
      {"Month": "09. May", "Temperature": 23.5, "Index": 5},
      {"Month": "07. June", "Temperature": 25.8, "Index": 6},
      {"Month": "06. July", "Temperature": 26, "Index": 7},
      {"Month": "02. August", "Temperature": 26.3, "Index": 8},
      {"Month": "12. September", "Temperature": 26.4, "Index": 9},
      {"Month": "11. October", "Temperature": 23.3, "Index": 10},
      {"Month": "10. November", "Temperature": 18.2, "Index": 11},
      {"Month": "03. December", "Temperature": 14.6, "Index": 12}
    ]
  },
  "transform": [{"window": [{"op": "count", "as": "index"}]}],
  "mark": "line",
  "encoding": {
    "x": {"field": "Month", "type": "ordinal"},
    "y": {"field": "Temperature", "type": "quantitative"}
  }
}
```
![visualization (60)](https://user-images.githubusercontent.com/781659/75174346-47c7d700-56e5-11ea-8d38-d47519ec4334.png)

Note that the end-point of the line is "12. September".

Now add ``sort:null`` to the x-axis and look at the order in which the points are connected:
```json
{
  "data": {
    "values": [
      {"Month": "05. January", "Temperature": 14.7, "Index": 1},
      {"Month": "04. February", "Temperature": 16.4, "Index": 2},
      {"Month": "08. March", "Temperature": 18.7, "Index": 3},
      {"Month": "01. April", "Temperature": 20.9, "Index": 4},
      {"Month": "09. May", "Temperature": 23.5, "Index": 5},
      {"Month": "07. June", "Temperature": 25.8, "Index": 6},
      {"Month": "06. July", "Temperature": 26, "Index": 7},
      {"Month": "02. August", "Temperature": 26.3, "Index": 8},
      {"Month": "12. September", "Temperature": 26.4, "Index": 9},
      {"Month": "11. October", "Temperature": 23.3, "Index": 10},
      {"Month": "10. November", "Temperature": 18.2, "Index": 11},
      {"Month": "03. December", "Temperature": 14.6, "Index": 12}
    ]
  },
  "transform": [{"window": [{"op": "count", "as": "index"}]}],
  "mark": "line",
  "encoding": {
    "x": {"field": "Month", "sort": null, "type": "ordinal"},
    "y": {"field": "Temperature", "type": "quantitative"}
  }
}
```
![visualization (61)](https://user-images.githubusercontent.com/781659/75174476-7d6cc000-56e5-11ea-8eed-13cc5c82e59a.png)

Note that the end-point of the line is still "12. September".

``sort:null`` does not change the order in which the points are connected, it only changes the order of the x-axis. If you want to change the order in which the points are connected, you can use the ``order`` channel.

**Comment by christophe-petitjean** [comment] 2020-02-24 17:25
Ok. I understand what you mean but it's strange that it's the only settings for sort property that does that (doesn't change the connection order).

If you try : 
```
{
  "data": {
    "values": [
      {"Month": "05. January", "Temperature": 14.7, "Index": 1},
      {"Month": "04. February", "Temperature": 16.4, "Index": 2},
      {"Month": "08. March", "Temperature": 18.7, "Index": 3},
      {"Month": "01. April", "Temperature": 20.9, "Index": 4},
      {"Month": "09. May", "Temperature": 23.5, "Index": 5},
      {"Month": "07. June", "Temperature": 25.8, "Index": 6},
      {"Month": "06. July", "Temperature": 26, "Index": 7},
      {"Month": "02. August", "Temperature": 26.3, "Index": 8},
      {"Month": "12. September", "Temperature": 22.4, "Index": 9},
      {"Month": "11. October", "Temperature": 23.3, "Index": 10},
      {"Month": "10. November", "Temperature": 18.2, "Index": 11},
      {"Month": "03. December", "Temperature": 14.6, "Index": 12}
    ]
  },
  "transform": [{"window": [{"op": "count", "as": "index"}]}],
  "mark": "line",
  "encoding": {
    "x": {"field": "Month", "sort": {"field": "Temperature"}, "type": "ordinal"},
    "y": {"field": "Temperature", "type": "quantitative"}
  }
}
```

The result is this 
<img width="296" alt="image" src="https://user-images.githubusercontent.com/354149/75175357-76b86a00-5732-11ea-805e-d893d4113e23.png">
The end-point is now "02. August"

If I try with `sort:descending`, the end-point is "01. April".

I would expect the same behaviour for sort:null and get this chart
<img width="300" alt="image" src="https://user-images.githubusercontent.com/354149/75175551-d6167a00-5732-11ea-9548-90923cf87c48.png">

That I obtain btw by doing `sort:[]`

**Comment by jakevdp** [comment] 2020-02-24 17:27
Thanks - I didn't realize there was a distinction between null sorting and field-based sorting. That does seem inconsistent.

**Comment by kanitw** [comment] 2020-02-24 18:05
Thank you for reporting.

However, I tried in the latest version of [the online editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4yghSA3WAbArgKYDOKYA2uBhMJALID2AdvABZmQAMArAHRgApWE3ywATgE9IAGigAVQgFsADoTEJ8YwmQCMAFl4B2WZACSTaIQAeugL7Sq1WoxbtUXA2ABihAEZjRSRl5JVV1eE1tVB0ANl49E3NLG1QAJntHDGdmNg5OAA5+OnEAY3YTBRU1DS1dQuMoJOsyAGYM6hp6HLcoTh1+AEFlMQBLXGDISrCaqLBUzl4ATkSLZtQ9do7s1zzFotgpCtDqiNq0lt5uFeSybk2nLp33TkN+AXwmbSOq8MiyVL4+WuazAMXuWUeuWecUE+FwhxCPxm-xiwJSYEM4M6LihvVSg3wAHN8MR4BMpic-mk4i00WR8li0JCepAdPiwABlQjKeBKXxqcnHX5nOb4hKNVboxaM7a41n9MAAeRK8AY-LEgqRp1mqQutIlN2inBlzI4OgWYAAcgwsHyBd9ptq6rxUnTojoTTiWZwLmAACKEEp2jUOyki-S8VEGkFs2yZAC6VE2kHg6iYxAAZgwxIoyORaAB3EYWBgFvO0BjKDglBgfMkmWCkdzFm62eNthyYRTiADWHFwxa+VEghCYNegxcJZHQGEg6NoGZGhFw0A4XomxGzZPclmIQYsk4m8Akqg42YnTDwkHBkCkqAXS5XHApwq+UGPp-cAEdRCwRoh4BGW1ryTEA4yAA) and didn't get the same screenshot as you suggested.  The following screenshot seems correct:

![image](https://user-images.githubusercontent.com/111269/75178241-9d53b200-56ec-11ea-80a3-087a46074e35.png)


Since it's unclear to me at this point what's really the problem, I'll close this issue for now.  

If you still find specific behavior incorrect, it would be better to create a new issue (since this issue is kinda long and some prior discussion might be less relevant). Please be specific about what's wrong and suggest the expected behavior.  It will then be easier for us to fix the issue. 

Thank you!

**Comment by christophe-petitjean** [comment] 2020-02-24 18:16
I'm sorry, maybe I'm not clear because English is not my first language, but I can't explain it better than I did in this issue at the beginning. 
Your example works because you set `sort:descending` but the problem is when you set `sort:null`. 
I can create another issue but I don't know what to add.

**Comment by jakevdp** [comment] 2020-02-24 18:21
@kanitw - the question was about the behavior of ``sort:null``, which does not appear to be behaving as expected: [vega editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4yghSA3WAbArgKYDOKYA2uBhMJALID2AdvABZmQAMArAHRgApWE3ywATgE9IAGigAVQgFsADoTEJ8YwmQCMAFl4B2WZACSTaIQAeugL7Sq1WoxbtUXA2ABihAEZjRSRl5JVV1eE1tVB0ANl49E3NLG1QAJntHDGdmNg5OAA5+OnEAY3YTBRU1DS1dQuMoJOsyAGYM6hp6HLcoTh1+AEFlMQBLXGDISrCaqLBUzl4ATkSLZtQ9do7s1zzFotgpCtDqiNq0lt5uFeSybk2nLp33TkN+AXwmbSOq8MiyVL4+WuazAMXuWUeuWecUE+FwhxCPxm-xiwJSYEM4M6LihvVSg3wAHN8MR4BMpic-mk4i00WR8li0JCepAdPiwABlQjKeBKXxqcnHX5nOb4hKNVboxaM7a41n9MAAeRK8AY-LEgqRp1mqQutIlN2inBlzI4OgWYAAcgwsHyBd9ptq6rxUnTojoTTiWZwLmAACKEEp2jUOyki-S8VEGkFs2yZAC6VE2kHg6iYxAAZgwxIoyORaAB3EYWBgFvO0BjKDglBgfMkmWCkdzFm62eNthyYRTiADWHFwxa+VEghCYNegxcJZHQGEg6NoGZGhFw0A4XomxGzZNQIlwuBM8Akqg42YnTDwkHBkCkqAXS5XHApwq+UEPx-cAEdRCwRoh4CNbUvJMQDjIA)

This does not behave the same way as ``sort: "descending"``.

**Comment by kanitw** [comment] 2020-02-24 18:24
No problem at all.  

Would you mind explaining how `sort:null` is currently wrong? (and what should be the expected behavior?)

**Comment by christophe-petitjean** [comment] 2020-02-24 18:32
For me, `sort:null` should be this chart (where x-axis is not sorted and displays Month in the order  in which they were entered) : 

![](https://user-images.githubusercontent.com/354149/75175551-d6167a00-5732-11ea-9548-90923cf87c48.png)

I got this chart with this spec : 
```
{
  "data": {
    "values": [
      {"Month": "05. January", "Temperature": 14.7, "Index": 1},
      {"Month": "04. February", "Temperature": 16.4, "Index": 2},
      {"Month": "08. March", "Temperature": 18.7, "Index": 3},
      {"Month": "01. April", "Temperature": 20.9, "Index": 4},
      {"Month": "09. May", "Temperature": 23.5, "Index": 5},
      {"Month": "07. June", "Temperature": 25.8, "Index": 6},
      {"Month": "06. July", "Temperature": 26, "Index": 7},
      {"Month": "02. August", "Temperature": 26.3, "Index": 8},
      {"Month": "12. September", "Temperature": 22.4, "Index": 9},
      {"Month": "11. October", "Temperature": 23.3, "Index": 10},
      {"Month": "10. November", "Temperature": 18.2, "Index": 11},
      {"Month": "03. December", "Temperature": 14.6, "Index": 12}
    ]
  },
  "transform": [{"window": [{"op": "count", "as": "index"}]}],
  "mark": "line",
  "encoding": {
    "x": {"field": "Month", "sort": [], "type": "ordinal"},
    "y": {"field": "Temperature", "type": "quantitative"}
  }
}
```

`sort:[]` seems to be <=> to `sort:null` but it seems to be a hack for me because `sort:Array` should be used to enter values manually.

Thanks for the time you are taking and sorry to not be clearer

**Comment by domoritz** [comment] 2020-02-24 18:42
Yes, `sort: null` should not sort the data. 

The chart is correct if we remove this line

<img width="347" alt="Screen Shot 2020-02-24 at 10 37 17" src="https://user-images.githubusercontent.com/589034/75181085-5c5e9c00-56f2-11ea-902f-6a20993b733a.png">

**Comment by jakevdp** [comment] 2020-02-24 18:43
To put more succinctly, I believe the issue is this: specifying ``sort`` in the x-encoding also affects the order encoding, except when ``sort`` is null. That inconsistency is confusing.

**Comment by domoritz** [comment] 2020-02-24 18:47
But you agree that the implicit linking makes sense, right?

Then the right fix here is to remove sorting the line mark when `sort: null`.

**Comment by jakevdp** [comment] 2020-02-24 18:58
> Then the right fix here is to remove sorting the line mark when sort: null.

Agreed.

**Comment by christophe-petitjean** [comment] 2020-02-24 19:20
Thank you all!  @jakevdp I understand a little better our incomprehension seeing the compiled Vega

**Comment by kanitw** [comment] 2020-04-19 17:14
fixed in https://github.com/vega/vega-lite/pull/6361

**Closed by kanitw** 2020-04-19 17:14 UTC
Labels: Area - Data & Transform, Bug :bug:, P3
