### ISSUE TITLE
Performance issues with vl maps

### ISSUE THREAD

**Issue by nyurik** [vega/vega-lite#3349] opened 2018-02-02 08:13 UTC
https://vega.github.io/vega-lite/examples/geo_circle.html -- horribly slow (100% cpu) on both Chrome & FF, even after rendering. Takes a long time to even select text on the same page.

**Comment by domoritz** [comment] 2018-02-02 21:15
Duplicate of #3303. General performance issues should be filed against Vega.

**Closed by domoritz** 2018-02-02 21:15 UTC

**Comment by nyurik** [comment] 2018-02-02 22:40
@domoritz I thought this could be an issue with the specific vega code that VL generates for maps.

**Comment by domoritz** [comment] 2018-02-02 23:16
Ahh, I see. There is not specific code that we generate. I think the issue is actually that browsers need some time to process all the data and render the image.

**Comment by jheer** [comment] 2018-02-02 23:27
I recommend using Canvas to render and see how that fares. Some of the VL geo examples generate *very* big SVGs...
