### ISSUE TITLE
Can the infinite facet be more compact?

### ISSUE THREAD

**Issue by bigfacewo** [vega/vega-lite#8229] opened 2022-06-16 06:41 UTC
This is an example of an infinite facet that I am working on:
https://vega.github.io/editor/#/url/vega-lite/N4IgJghgLhIFygK4CcA28QAspQA4Gc4B6IxAOwEtdUB7ZAUwFp8aUBjegOhv30bbL9M9MgHMwiThFQUAnuTb5ObGgFsiNKMOQbkYesnwAmZfgBuIAL4AaEPlwQ2FMfAAMtgGaP6UeKGQ0AO5+IB4U9KhgGIDX+oBICYCdpoDw+iC2ULK49Bhkas7SKVj0EPrIIagQAEYRAKIAHrglcCBkiKjolu229vRsIV4cvgggKqiIqmS94ZEYgN4+gNRK+WkZWTlkebbCRQalFdV1DU0tbR12Dk4ucO4n3SH2js6ibp7eA6DDo+ODYRFRjYAK2nMLdKZRrZVS5I6dDI9T7PEJvMYTb4YQBjfoAwJUBSxBKzyxy60NAqggyAA1hhykT8rczg8LrYRCowPcQjVEVNGmiMcCmti2rZZCEIKJRAxRNAufhRvkvmyQIAAVMAdKqAXIyrO1VZYgA
```
{
  "data": {"url": "https://uniplore-source.oss-cn-chengdu.aliyuncs.com/other/orders2.csv"},
  "spacing": 0,
  "facet": {"row": {"field": "快递方式","type": "nominal",
   "header":{"labelExpr": "null"}
  }},

  "spec": {
    "facet": {"column": {"field": "类别","type": "nominal","header":{"labelExpr": "null"}}},
    "spacing": 0,
    "spec": {
      "spacing": 0,
      "facet": {
        "column": {
          "field": "子类别","type": "nominal"
        }
      },
      "spec": {
        "facet": {
          "column": {
            "field": "细分","type": "nominal"
          }
        },
        "spec": {
          "mark": "bar",
          "spacing": 0,
          "encoding": {
            "x": {
              "field": "细分","type": "nominal"
            },
            "y": {"aggregate": "sum","field":"销售额"}
          }
        }
      }
    }
  }
}
```
![image](https://user-images.githubusercontent.com/31603897/174007265-77e711dd-a6b6-44ea-adec-6f51dac1a972.png)

It has some problems:
1. Too many labels, taking up a lot of space.
2. There is a hole in the middle.

My other main contrast products are:
1. Tableau 
![image](https://user-images.githubusercontent.com/31603897/174007293-ad48a80a-92c2-40bc-8f24-3893cb47abb6.png)

2. [g2](https://antv.vision/old-site/g2/doc/tutorial/start/facet.html)
![image](https://user-images.githubusercontent.com/31603897/174007410-eb3adff9-b5df-4983-b627-cf692453a0ee.png)

4. [muzejs](https://react-muze-demo.cube.dev/)
![image](https://user-images.githubusercontent.com/31603897/174007321-3c8b9aad-fb65-4669-ae3d-fb49cea2baee.png)

Both of them can achieve a compact layout and support unlimited facets. I have tried to adjust the configuration of Vega Lite, but I can't achieve a similar effect.

If Vega Lite can achieve the class effect, it is the best. I wonder if I can consider this function proposal.

**Comment by kanitw** [comment] 2022-06-16 19:51
> If Vega Lite can achieve the class effect, it is the best.
What do you mean "the class effect"?

**Comment by PBI-David** [comment] 2022-06-17 06:29
VL already allows you to achieve those sample outputs with control over all elements. What precisely are you looking for?

[Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEzjQATjRyZ289AEEABBBoIcguIbKblhtgDNDTJOsOwXmCIcxs3bMy6WOHDq9mzqyLJQlspImFSKKnEoqKDESIIMamgA2qApIEgAjIlMaCBMJUpQ5QAeiTjlAAyURQAsIAC+CvnlxaXllYk16ACeDc2UAGxNXT2FfVUVg0sjIABeE+gtTQDMc73o-Upl6EwATMN1WyAtbbPdh4VLpxWX1eXjSo3blLsAHAcFkcXoN3iA1ptvpMxGIgQVjsszvsPuh6tDfkUSo9gc8BsirmMbi0xICcQjQQTURtiZQ2gBOeF9cGvIbU9EgH63On7cnM-EVVafWltADsTKOLJWhJpGO5U3FfMlAouMo5XLuivmCKlZ3Bay+nMmbQ6SsKureMqhRt+9wl5pVKIh1zld1N2v5J0GToNIvdTyQFqYPvK1o1rUZZqQTtZQrRtLEWoDMel1MN4d2cKjKbOcdlNu5DPt0ZV+pdBZaU2xHqOOctadpAOLddV1LDkyrzcdatpU0jNcKLZDRNd0weA5LXqpzvQ7d+uyTuKQHSngp7o-axZXSLXDdHMy3Krzc+5e0Pq9bM5A6uN44D29ZZZHFb+ZInD7BVoTWff3fZtKxc8d2DGV0xhN97z-K8TzufsAzhC88xvW1eQnBDgLzMDbUXBF0NjL99xwvo8M-f9RzFYsSL1UC-Uo0sCJfO0oyoiph2vWjmKg31yP9JcWJAtsALgpcpiPdcX0TYtRMQmjR0zKSxME8jhIRaTgKfdj92rAM1MfWSXybKNdNI6De20kSuPLcM+wUi82Kw+U7wsuyGIzIijnFGSyJfTco08jD9OspyEX8-ClJfM8-Po7zwyYidQpM7iDIgpcEuo8Lw1hYs0tY8Tw0AqKXL3CSUpCyzZxFFS+kBLyr2QwtUIDGqAuK2L3MKZqwtMwji06xKrONdqkD69Krwct1eui7rGOC6rys0xjeIREbcta40lrmorpvyqqjkZWq1nqkkhv2lqxsbH8A1OrrIUq4trv6+MtPuqakozUq+ge0bbueqMvtWure12wp-oE8791mvb5pgv5FQAXW6EAAHcaGUeg0BmJR4BoMgsDQIoxCaJQIBwJAoBoWQyDQfgiiUZB1AAa0GFxEjgKI2GUCmqdSdiefsGg4EEZRyhqJRMFGYJylkfwKYyOYQHGPmBaF8pGjFiW4HKABHBgkFkHR4h0UhEiQWoaAgNBQDCCI4nKABSRJ0kybJUByW5EhacE7g96YfeaopKFmJQA8uBGxboCw0FkBhBEEYmoAyTWeeUfwkAp3IiYDsQEcRqA2EEcJLZAfnBeF9BRZAcXJfQaWEFlwREgsMg2bL6PY9z-OGAQPQreVsuFnDzBI-QAAxMmfFcfREngJBVHUIvBCQJhBf0Snh6aTpEfUNgkaLkuVbORIDeHkAx6gCfDAAIS6TegA)

![image](https://user-images.githubusercontent.com/86846675/174238692-d5c4623f-3bfc-4495-a11c-f89d3c115057.png)

**Comment by bigfacewo** [comment] 2022-06-17 06:41
@PBI-David Your example is different from what I said. Have you tried to use facet nesting?

**Comment by PBI-David** [comment] 2022-06-17 06:44
@bigfacewo no, I'm obviously missing something so I'll defer to the devs.

**Comment by domoritz** [comment] 2022-06-19 04:24
I think this is a duplicate of https://github.com/vega/vega-lite/issues/2761.

**Closed** 2022-06-19 04:24 UTC
Labels: Enhancement :tada:
