### ISSUE TITLE
Area chart with column facet channel has undefined subchart when there is partial data

### ISSUE THREAD

**Issue by rmales** [vega/vega-lite#4446] opened 2019-01-09 12:00 UTC
Hi,

I'm trying to create an area chart with multiple subcharts using the column facet channel. But, I have found that if there is data missing, for any year on the x axis in my case, this seems to cause an subchart titled 'undefined' to be created. I guess I may be able to fix this by imputing the missing data. I'm opening this issue because the undefined subchart was unexpected to me, and seems at least undesirable if not a bug.

Example: https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATdHkw5QECJAroxrZLGxgA2hsNgD9w5DxWAjAE4PAVnVPn8FaQAIIAqgDKanZOkIRBALIAmpF+-lAmZsjuAEweACx5Hm50Rd5uAAwAbJWp-rGBOOUlXl5u0oXeAOzVbp3REAC+tYaOda44nh41-QFBYSkzRnE4kEkLaemm5u7S2W6V0sWVhQAcPgXD9vVWTS3ee5V7h-nlbjNDM6Mx42CTnZezFbzKIbWIJZIgtLGLZZCbldpuXp0E6VTq9crlf6LKCEBpgW4tDwnXr3bxTIrvAFfK4-Sa+bGQPGQADCAAkAHKQurLKBrLkxDLbOGI7LZSp0UV5co+TrZAFLPFvfwffzU5y0rzTUFMtmc+U48HrKGC2G-V7SMp5Eq7To+aQefXXCaUz4MjUeLHaoK6-lXHmrCGOk3uTEI8VEvLZcp5e6O3HuF2qt3uTWOpnAuNBAAqAGkADK+5zBnAHbJ0bx5aRxvFNDHRzonaQNyoncpkk73E6Jpxqozu+leoERQtLIIABWZeoZxd+xU8J2rNzodYxKO80ey0mkjYbZWy3fsvag7s9UPTw8zKwAagBxABCI82mXcyJOp+5NeXK7cJ2yeU6UrSNKorrvuyrRAAuhoKpQMgSjwNwmiMEo1BWF8jLcGYqAqPoMyQAAZowyBiJoQSBACLgAJ6EKakBKNwqDIaYkDRDBRiUWheGEcRpErPGFF4NRtEAI6sOgSh4MwOiMFQLH2GxUAAB6cXU3EkUErgCUJQTcAATkhSjMaxwwYWIekqTEam8QaWk0UE9GMYZYiFpAYg0HB1lKKwYhiKx0GpJAGC6QA1kE6C6cgmAgAMQA

Thanks,
Richard

**Comment by kanitw** [comment] 2019-01-09 23:41
Thanks for reporting! 

It seems like the problem is due to the automatic impute logic that we have for stacked chart (This example has `color`). 

The generated Vega impute transform should include `p` in the `"groupby"` (`"groupby": ["p", "c"]`).  So this is definitely a bug.

**Comment by kanitw** [comment] 2019-01-09 23:45
@domoritz -- not sure where the groupby gets added for AggregateNode, but I guess the same logic should be applied to fix this issue?

**Comment by kanitw** [comment] 2019-01-10 08:13
NVM -- found the solution -- will be fixed in #4447

**Closed by kanitw** 2019-01-10 08:13 UTC
Labels: :bug:  Bug
