### ISSUE TITLE
Broken on Edge (ShadowRoot is not defined)

### ISSUE THREAD

**Issue by nbevans** [vega/vega-lite#6945] opened 2020-10-09 12:43 UTC
My versions:

    <script src="https://cdnjs.cloudflare.com/ajax/libs/vega/5.17.0/vega.min.js" integrity="sha512-BD8IEFO7qsY1BLFX3UHscXuTtgRtaI88B00irdwt/jjngutw3vslrz6KUP1D93+YhT2IFG31SlmWzWrXmFUXwA==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vega-lite/4.16.8/vega-lite.min.js" integrity="sha512-e9hIGAizb73UlvCw7PK4a8Th+M4CAv1ybeFX7fpTcaP74aovD2ObODkKTOH9+xDYYa3mqQPLZk3kYCHuz8DYjQ==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vega-embed/6.12.2/vega-embed.min.js" integrity="sha512-iQV3RO+tQdxg2cG09e/6BXUOPN31N4/gFTBtHX6lIcDXYfhiEDuBLm0Rdfn+eHwyU8Z4GLm5U5FrXBevhM5WiQ==" crossorigin="anonymous"></script>

Microsoft Edge 44.19041.423.0
Microsoft EdgeHTML 18.19041

```
SCRIPT1028: SCRIPT1028: Expected identifier, string or number
vega-lite.min.js (1,7361)



[object Error]: {description: "'ShadowRoot' is not defined", message: "'ShadowRoot' is not defined", number: -2146823279, stack: "ReferenceError: 'ShadowRoot' is not defined at Anonymous function (https://cdnjs.cloudflare.com/ajax/libs/vega-embed/6.12.2/vega-embed.min.js:26:5491) at Anonymous function (https://cdnjs.cloudflare.com/ajax/libs/vega-embed/6.12.2/vega-embed.min.js:26:5381) at Anonymous function (https://cdnjs.cloudflare.com/ajax/libs/vega-embed/6.12.2/vega-embed.min.js:1:2060) at Anonymous function (https://cdnjs.cloudflare.com/ajax/libs/vega-embed/6.12.2/vega-embed.min.js:1:1373) at Anonymous function (https://cdnjs.cloudflare.com/ajax/libs/vega-embed/6.12.2/vega-embed.min.js:1:1083) at Promise (native code) at a (https://cdnjs.cloudflare.com/ajax/libs/vega-embed/6.12.2/vega-embed.min.js:1:844) at Or (https://cdnjs.cloudflare.com/ajax/libs/vega-embed/6.12.2/vega-embed.min.js:26:4686) at Anonymous function (https://cdnjs.cloudflare.com/ajax/libs/vega-embed/6.12.2/vega-embed.min.js:26:3925) at Anonymous function (https://cdnjs.cloudflare.com/ajax/libs/vega-embed/6.12.2/vega-embed.min.js:1:2060)"}
```

**Comment by nbevans** [comment] 2020-10-09 13:03
If I change my scripts to:

```
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vega/5.17.0/vega.min.js" integrity="sha512-BD8IEFO7qsY1BLFX3UHscXuTtgRtaI88B00irdwt/jjngutw3vslrz6KUP1D93+YhT2IFG31SlmWzWrXmFUXwA==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vega-lite/4.15.0/vega-lite.min.js" integrity="sha512-PtoM8Au4G07Vl/huj6XpEu3Tnd7eB2JyVuagr0nohS2rsTg7l1hHOaeb5J00hrHacv/En40Wa6FP0PEYwi1jZw==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vega-embed/6.9.2/vega-embed.min.js" integrity="sha512-N4tQHmeP+ALu/f0pzFmp5Xf4ZiLWv8grKjnDhNUg6zzEXtzU7SHf52sWDmBnge6SS95VTkWnSzruYYXfgzdAFQ==" crossorigin="anonymous"></script>
```

Then it works in Edge. Any newer than 4.15.0 and it breaks. Looks like the breaking change is quite recent.

**Comment by domoritz** [comment] 2020-10-09 15:20
I believe this is a duplicate of https://github.com/vega/vega-embed/issues/517. Please respond to this message if not and I can reopen this issue.

**Closed by domoritz** 2020-10-09 15:20 UTC
Labels: Bug :bug:
