### ISSUE TITLE
Area charts are rendered strangely if tooltip contains string field that contains numbers

### ISSUE THREAD

**Issue by codetalker78** [vega/vega-lite#4001] opened 2018-07-10 09:52 UTC
Please:
- [x] Check for duplicate issues. Please file separate requests as separate issues on GitHub.
- [x] Describe how to reproduce the bug / the goal of the feature request.
- [x] Use the latest versions of Vega and Vega-Lite.
- [x] Provide an example spec in JSON, wrapped by triple backticks like this:

when generating an area chart based on an array of these objects

```json
{
        "date": "2002-02-05",
        "Timepoint": "Exam 3",
        "lesion": "T02",
        "longaxis": 12.5,
        "longaxisDisplayValue": "12.5 mm",
        "shortaxis": 11,
        "status": "Present",
        "valid": true
      }
```
and using either "Timepoint" or "longaxisDisplayValue" as a field in the tooltip, the areas are rendered incorrectly. When not using these fields or explicitly setting type = quantitative (which will result in _NaN_, the areas are rendered correctly. type = nominal does not help.

area rendering should not depend on tooltype content. Displaying strings that contain numbers (and letters) in a tooltip should be possible without affecting the chart

Observable that demonstrates this:
https://beta.observablehq.com/@codetalker78/vega-lite-demo

- [x] If applicable, include error messages and screenshots, GIF videos (e.g. using https://www.cockos.com/licecap/), or working examples (e.g. https://bit.ly/vega-lite-blocks)

**Comment by domoritz** [comment] 2018-07-10 15:57
This looks like a bug. SOmewhere we need to exclude the fields that are used in the tooltip from a group by clause.

**Comment by kanitw** [comment] 2018-07-13 05:47
Will be fixed in #4015

**Comment by cwickham** [comment] 2019-02-14 17:45
It looks like this might still be an issue in 3.0.0-rc12 e.g. in Vega Editor [with tooltips](https://vega.github.io/editor/#/url/vega-lite/N4KABGBECGCuAuB7AzgSwF4FNIC4oAdoATSAGnCgHdUj4ALXMANgAYXyJI7NUBzO+IwCsbDlCLR40RqAicAbtAA2sTMkYBtCnLCydcyBPjY8kAExsAjAFoWNywBYy2-ZAAqqALaZ8iVADtBUwBRAA9oTzAWZ30DJTVURH9GdzsY2KglJN5oUNR1PABmAA4AOksxWMgs-xy85AARfPwlaABPADVlVRSS8rBPT3Sq5DpEACcpesZCwsrXZCl4WAKoAAVxtUxA4ddFJRpGeHHVFwgAX3mIPSqjEygLO1t7JyuDD29fAKCoMIio3Y6aoJJIpNwsMyAuLZXL5RiWMpCN6cGp1fJNZAtdpdFT3SAI0pCAZDZFQUYTKZwvCOUmQRaSFYpDZbHa0-aHPDHU6xS5nXR8zh3FKPGxPRxQzgfHx+HYhcKRaK0+JoUGmcGFCWZGHTIoOUoOJXa9HNVqdbp4wp6hzEzV0saTWGrQrsAVkpaM0zM5DbQRs5QcsBczB83mxG6uIWmEW2QrWBG2qVfWW-eVgSy25WJZJqtKG2qOxhMADspRdGS1+fqGKxZtxKWLpZttPJDp1YCEAE5m+7VpAvT7beySJyTsGeW9w0DIw8rDG48UE15pd8Un9IumlSDs1BwZC82jVmZCqX947q6acT0o8eWE3XXaKQXqV37-Tlr3+6z70OjqOQxP72ncxZxYWN41pRMZR+SA1zTDMtzBUCMyNVYHEsE971RM8TWxc0UjQxtBltFtKSdYpuwZD9Nm9L9y0gH8R25fRQ30ScDCA6NLFFDd70glc5X+PdMIQnMeLorC2zMJgMPElDz1wuso2k28iObe1SPhJgKPfJlqIHP0DmHQM-3HPk2MFSQ8U47jF0+KDV1TITxJEncIWQysqTAQozBkjJqjknDayvKBvMIklX3Up8wDMA1Xx7XSWV9b9-SMoN-zMwDLOFWcuOeWzl2TGDHPglVt1SDVTzbYtKuNTELzw0wGxU8K6JIqKhDMbSPXWPTaL8hjjKYnQWJ0czxCyqM2DMWxppYIR8qTaDYIq4TSsQsS-IkzymGUmrGkCy88R2sLiMitsHDmOLKISmikroga0tMsNMuMbKIRm2x5ogpdFoc-4VuctacyczaUPhHykUwgK6oU4L8Qhu9WrOzyuK6qjEsHFLfyGuQRrkMbDAmmd3pJr7eJ++yBMiAHNpc8r3IPRgHD1MtQY8-aYaCvFmZOtTHzbS00Zu-TksM7Gx2YlwAF0KBYyBPGgcYAGsZEgeA2nwPFFcwaQ5e2ABjRAiACXgZBcSBQjNqoADNUEwJQjMJ163jVpcAFV-FQaC2h18ZPCSeghRd9XNZSYxPF8cZlChGA22ASBrYmBXoIAUgATTAFOACFIHOFw8cgNpVdt+3Ha29RSCgEO8QAR1gaBAi9yRUHkbBK7pKR9ZVnBICwcZEFz+ZIENrJxmLu2HZSTNQXb6uUn8RBPACaOC6QRAlHgVB8E0MyE4nsuENnjW8QmY3-BXic99LqfoZrQ6yCr4-58X5elEH3eS8ntUKZXI-Q9MBeS9z5vzzjoGWFwQDnCAA) and [without tooltips](https://vega.github.io/editor/#/url/vega-lite/N4KABGBECGCuAuB7AzgSwF4FNIC4oAdoATSAGnCgHdUj4ALXMANgAYXyJI7NUBzO+IwCsbDlCLR40RqAicAbtAA2sTMkYBtCnLCydcyBPjY8kAExsAjAFoWNywBYy2-ZAAqqALaZ8iVADtBUwBRAA9oTzAWZ30DJTVURH9GdzsY2KglJN5oUNR1PABmAA4AOksxWMgs-xy85AARfPwlaABPADVlVRSS8rBPT3Sq5DpEACcpesZCwsrXZCl4WAKoAAVxtUxA4ddFJRpGeHHVFwgAX3mIPSqjEygLO1t7JyuDD29fAKCoMIio3Y6aoJJIpNwsMyAuLZXL5RiWMpCN6cGp1fJNZAtdpdFT3SAI0pCAZDZFQUYTKZwvCOUmQRaSFYpDZbHa0-aHPDHU6xS5nXR8zh3FKPGxPRxQzgfHx+HYhcKRaK0+JoUGmcGFCWZGHTIoOUoOJXa9HNVqdbp4wp6hzEzV0saTWGrQrsAVkpaM0zM5DbQRs5QcsBczB83mxG6uIWmEW2QrWBG2qVfWW-eVgSy25WJZJqtKG2qOxhMADspRdGS1+fqGKxZtxKWLpZttPJDp1YCEAE5m+7VpAvT7beySJyTsGeW9w0DIw8rDG48UE15pd8Un9IumlSDs1BwZC82jVmZCqX947q6acT0o8eWE3XXaKQXqV37-Tlr3+6z70OjqOQxP72ncxZxYWN41pRMZR+SA1zTDMtzBUCMyNVYHEsE971RM8TWxc0UjQxtBltFtKSdYpuwZD9Nm9L9y0gH8R25fRQ30ScDCA6NLFFDd70glc5X+PdMIQnMeLorC2zMJgMPElDz1wuso2k28iObe1SPhJgKPfJlqIHP0DmHQM-3HPk2MFSQ8U47jF0+KDV1TITxJEncIWQysqTAQozBkjJqjknDayvKBvMIklX3Up8wDMA1Xx7XSWV9b9-SMoN-zMwDLOFWcuOeWzl2TGDHPglVt1SDVTzbYtKuNTELzw0wGxU8K6JIqKhDMbSPXWPTaL8hjjKYnQWJ0czxCyqM2DMWxppYIR8qTaDYIq4TSsQsS-IkzymGUmrGkCy88R2sLiMitsHDmOLKISmikroga0tMsNMuMbKIRm2x5ogpdFoc-4VuctacyczaUPhHykUwgK6oU4L8Qhu9WrOzyuK6qjEsHFLfyGuQRrkMbDAmmd3pJr7eJ++yBMiAHNpc8r3IPRgHD1MtQY8-aYaCvFmZOtTHzbS00Zu-TksM7Gx2YlwAF0KBYyBPGgcYAGsZEgeA2nwPFFcwaQ5e2ABjRAiACXgZBcSBQjNqoADNUEwJQjMJ163jVpcAFV-FQaC2h18ZPCSeghRd9XNZSYxPF8cZlChGA22ASBrYmBXoIAUgATTAFOACFIHOFw8cgNpVdt+3Ha29RSCgEO8QAR1gaBAi9yRUHkbBK7pKR9ZVnBICwcZEFz+ZIENrJxmLu2HZSTNQXb6uUn8RBPACaO84uEBziAA)

**Comment by domoritz** [comment] 2019-02-16 17:59
Hmm, odd. I'm looking into it right now.

**Comment by domoritz** [comment] 2019-02-16 18:52
@kanitw I'm not quite seeing the right solution here. The problem is that we add the stacking fields to the groupby of the impute transform. However, we also add the tooltip fields to the stacking fields. Should we do that? Can you look at this?

**Comment by kanitw** [comment] 2019-02-24 06:22
Will be fixed in https://github.com/vega/vega-lite/pull/4579

**Closed by kanitw** 2019-02-24 06:22 UTC
Labels: :bug:  Bug, ⚠️ P1 – Important
