### ISSUE TITLE
Grouped density charts have artifacts (again)

### ISSUE THREAD

**Issue by jonmmease** [vega/vega-lite#9078] opened 2023-09-04 14:18 UTC
This was originally reported in https://github.com/hex-inc/vegafusion/issues/381, but it appears to be a Vega-Lite issue.  Given this grouped density Vega-Lite spec:

```json
{
  "config": {"view": {"continuousWidth": 300, "continuousHeight": 300}},
  "data": {
    "url": "https://cdn.jsdelivr.net/npm/vega-datasets@v1.29.0/data/movies.json"
  },
  "mark": {"type": "area"},
  "encoding": {
    "color": {"field": "Major_Genre", "type": "nominal"},
    "x": {"field": "IMDB_Rating", "type": "quantitative"},
    "y": {"field": "density", "type": "quantitative"}
  },
  "transform": [
    {"filter": {"field": "Major_Genre", "oneOf": ["Action", "Drama"]}},
    {
      "density": "IMDB_Rating",
      "groupby": ["Major_Genre"],
      "as": ["IMDB_Rating", "density"]
    }
  ],
  "$schema": "https://vega.github.io/schema/vega-lite/v5.14.1.json"
}
```

The resulting density curves have a lot of artifacts.

![visualization (1)](https://github.com/vega/vega-lite/assets/15064365/cd5171ad-4cb2-4a1f-9e38-89c4cca8a8ff)

A related case was reported in https://github.com/vega/vega-lite/issues/8049, and the suggested fix was to add an explicit `steps` argument to the Vega `kde` transform that Vega-Lite produces. This change was made in https://github.com/vega/vega-lite/pull/8088, but this doesn't seem to take care of the issue universally.

Rather than (or in addition to) `steps` I think what we need is to specify `"resolve": "shared"` in the kde transform so that the generated x-values are in sync across groups. This chart is fixed when manually adding ``"resolve": "shared"`` to the generated Vega spec:

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhBMkUANZkATmwbiAJmhAB3GHTjSQOJBo01xZNAJk6aG+mgDMABhcz4NMlmduZETABPABtDdCg4YOCjDSRMFFQAbVBxJAQwkDEGZQiAfRcjbOj0LFx8IigNcREIDUiaYmVKcThMAnEcBF4KAFpY+IhWiAABYgBGSgAmAE5KFwJ+-gQ2Yho4CBqJIwAzNmVkTDRQIJwM0S2ZE2VBo5AAWSRhPdyAcThxZQyA5QsrAF8-jJMMokOIILt9mhkiAThltjRgpg4MojHAAB44FHoCx1NFsbYACkSAB0QABBKCYdjiUlSUkAERByFJAF0pAACfoMBAk+6PZ5vD5wVkASnZAEIALyS9k9MYgQHHQKnbQKOo7NbBLToACSd3pACFcgAlOK-IwqNQ4JiBKF8p7KV7vT4gNkgJAQO16w0ms2WGLvCB0W1uz5iYKkbQQGBIT5afxIvBoSZuRUw5UZGgIHAMJEayLakB1MHBi2qBjW21Je0C52GN0KOBVkDeo2mqn+mTpehsQvEJDBBiGGT9wdhFxp2FR+KKMtWm1e-Vtv1WN3wgvaYtBoJGMTKQ6oUDrrV2h4Op1C10yPZ1LGJIvrCKac0swHuz3VrfB3IBWOHGRfkEuTvFobr4tsgwHiAABeyJsAqr5usgygKB+0KpOk2gmPQloVkYU7oLhOA7KoCC3Ns8itLcGFwpRSIaLk2EwLkyAWDEcQJJkag5HA+RzhWC7VmetaXq+b7vFAvZhKAFb9NJuj2I4h4gMe2qgER2h2A4MAKm+njeAeR6ampIAaSUcBeD4AIAl2saoVCKRpBkyH2UCGbaLGcAoAmIRhPenkoG6e6GSpxmbnE3K8q2vodmQrIKjI2ykbcizaBRET0YxcTMaxkjieIknqspslxPJexrOIIWjkO2ikPuNBQAOCWhVEtzQAOGSScEez5ie6DCY6goum+dTQD8OBUlsylBmQqTFCApLRe2vyoOypLsgA1OyBIQgcBJcjyi1LjFvyshypKkiKYpbaSADcnKBsGq3rVtO17HtB28oBgRnWtC0gFdm1-fdA0Xp8z0gEDBI0BAABqA72PtEWHTWg11qK7IAPycsjvKg0NwquuyEOkhtn2kvj6OuiKzVom1jWhNodOJWFurHct-pvlWoDtYz6C2izG7oN9wGaM1gSTPTHXaALoVCw+JZAb++7NXU8ItCZM1zdoMPw8EiPky27MrhjABkpvsjDABiFgGASZO40dPoc3F1PsubltwwjGhI5gkWkt9ZsW9bttIvbhuB9TukAoh-gM+sDkgDRTP4e56D6y0sYxGwuUpRxUbcXkBSC31RvOyuzUgpYfnuDzXja+gWmOH8briA1YTAkOMiwaoaAUcEgxpsn-Opyq6cWF5KIATnSBscpqXoFkPF8SXGhoQr26BD+8QqwBj1ASBrpvlXZB+XXs1NeZlmHICLit+3aCd3A3dwY-yhDkPTnaF1PVuWPIA3gsE1aeud5750XoXXixc5al0ppefwewDxP2PqCU+39SpkD2LaFuMgkBogTkkHm8cU7Xh+O8KCTA2DYBzmWewABlYhI8ZAqHsG-LuMIGoKAAMJqEqm1eul8QARARASJuMACAABYXA0xGjPOe-dBgyGCEgJgkQPwKOfu6H4CQNG2TRAAUTREiPhqB3AgAQBYQxxiDxmKpIodRA5FEwRxOiNAE4pBEOlkwgBZCTEgFCNsf8pkfgaAYV4kAzNgmsNQE-IEnCeHqBClrQRwjggEn0lgSR0jVZyMkKgXR-iVFqL7o4zRsYaA6NKXoqx5C3FdksUY2ppi4n2JKQPTR0EXF01MWmXmGRInlSabIKhmAaHMJCW0pxVJMB8zLsuWKRhlGqOCFbQc0Y2GaKWZEAA8nVZRxEYnv00XY7hvCkkCPmqk0RilxFSJkd3LpbjemMJALLQZfiAlBJYdqAp0zZnfUWUU4IuzkT7I2S005iT+EX0uRZNJGS2h3Oap0zQrielulCKfTQaEjKtXCGwbqU9MiBAQJQ4IAAVNOQiaA5EZnEmZGQ4HDVfEAA)
 
![visualization (2)](https://github.com/vega/vega-lite/assets/15064365/3292d2ba-4a6d-4dbf-a0a2-b6cdfa38dec3)

**Comment by joelostblom** [comment] 2023-09-04 16:54
It seems like this was re-introduced sometime after VL 5.8 because it works fine in Altair 5.0.1, but not in 5.1.1 where VL 5.14 is used.

**Comment by joelostblom** [comment] 2023-09-20 19:46
Wohoo, thank you @jonmmease !

**Comment by joelostblom** [comment] 2023-10-19 15:51
@jonmmease @domoritz  Unfortunately, it seems like this bug is back in the current version of Vega-Lite, so I'm reopening this issue: 

![image](https://github.com/vega/vega-lite/assets/4560057/fd3d7c75-8ef8-436d-af82-b854e5a0fd7c)
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAZgAY2AacaYsiygAlMiRoVYcAvpO50AhoTl4QpAE4AbFCDGEADpWQB6Q2DpQAdACtKdTOrhpV5qJkKGougLaG0mBHIBaeUVKV0oAATQARnMAJgBOczZDYLlDTwgMTEorSmgQGRBPOVUAa2VCAE9dTC0SzCVCzChIOhIkVB51CFVleDs6LQBZOUsegH0AcWbVWu4qmq0oCE8SOU1CgA8+rHVB5BAASSGAEQAhcYAlBXaQeerag4BHUjkiOEViXwLuSp2BrS2KCUD5-e6LZ6vd6fBy1aTzVRvSgwHqeFAAbVA8HUhEwvU6-T2w1GE2mUFmdxA0EwAHkYBiQABBMDEfLcE6I4ogAC68NAQJBVS0x3OVxuUCQ3AQqgougARn9kOiQCMxqopjNatzuHJKAyRRdrnxJSABaCeZJeUA)

One concern that complicates fixing this, is that when the axis resolve is "shared" as per @jonmmease  's last fix, the extent of grouped density transforms incorrectly use the min/max of the entire dataset instead of for each group, resulting in long lines where there are no observations at all, instead of stopping the density at the last data point in the group.

This chart is created in altair 5.1.2 which uses VL 5.15.1 and shows the undesired behavior:

![image](https://github.com/vega/vega-lite/assets/4560057/470d6e00-9a60-4b58-95c4-ff1ec5dc9f2f)

If you instead [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAZgAY2AacaYsiygAlMiRoVYcAvpO50AhoTl4QpAE4AbFCDGEADpWQB6Q2DpQAdACtKdTOrhpV5qJkKGougLaG0mBHIBaeUVKV0oAATQARnMAJgBOczZDYLlDOFU4SitKaBAZEE85VQBrZUIAT11MLWLMJW5KQlUIEprkEAAjdTkwMoLMKEg6EiRUEBhe12VIdVJPKEoUKO54OzotSmqwLCXuRnrbVWUezrsAMV5qEQQxLU6IdQ3uU4veAGU4AC92qNiC4iEdTtMjqdTcSrVLRQCCeEhyTQFAAeyjWTy0aARpBqEKq7RAAEdSHIiHBFMRfPluBVUVh0R1bIsyTTGoo+ihJupQrioR0iSTAQoHDVpPsbndkFEOBDVCTKDAIKpPCgANqgRmUZlaaqKdS0BjMbgIFqkXSdGnIFUgLaYHaYJYAXUkDu4ABJKGADkUtDp9EYfH45OYEGTGKROuY4BBDB6vWlfP4AvZCJgfABWcxRDMxax5SRAA) editor that runs the most recent version of VegaLite, you will see the desired behavior where each density is cut at the min/max values of each group:

![image](https://github.com/vega/vega-lite/assets/4560057/3f759c0e-a610-46b6-87a4-e676e2ad2e48)

It would be ideal if there is a fix for the grouped density issues that still allows for grouped densities to be cut at the min and max value of each group.

<details><summary>Altair code</summary>

```py
import altair as alt
from vega_datasets import data

source = data.iris.url

alt.Chart(source, height=100).transform_density(
    'petalWidth',
    groupby=['species']
).mark_area(stroke='black').encode(
    alt.X('value:Q'),
    alt.Y('density:Q').stack(False),
    alt.Facet('species:N', columns=1, title=None).header(labelFontWeight='bold', labelFontSize=12)
)
```

</details>

**Comment by jonmmease** [comment] 2023-10-19 16:26
@joelostblom are you saying that you're still seeing the jagged/sawtooth behavior in Vega-Lite 5.15.1+? Looks like the Vega editor is still on 5.15.0, so it's not surpising that the example you pasted above still has the issue.

Regarding the long tails, I'm not sure the best approach. Maybe we could filter our the zeros in some cases

**Comment by joelostblom** [comment] 2023-10-19 18:05
Oh sorry I completely missed that the Vega editor is not on the latest Vega-Lite version. I can see now that is says 5.15.0 in the grey text the bottom right corner so that makes sense then for why the densities are jagged in the editor.

Then only the second part of my comment regarding the long tails when grouping is still relevant. Filtering zeroes sounds like a a potential solution, but it would have to only filter zeros before and after the last non-zero value. We wouldn't want to filter zeroes between peaks in multi-modal distributions. Do you think this is something that should be fixed on the Vega level for the KDE transform? It seems like that might be appropriate and I can open an issue there instead if that's the case.

**Comment by kanitw** [comment] 2023-10-28 16:04
From the latest [editor](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAZgAY2AacaYsiygAlMiRoVYcAvpO50AhoTl4QpAE4AbFCDGEADpWQB6Q2DpQAdACtKdTOrhpV5qJkKGougLaG0mBHIBaeUVKV0oAATQARnMAJgBOczZDYLlDTwgMTEorSmgQGRBPOVUAa2VCAE9dTC0SzCVCzChIOhIkVB51CFVleDs6LQBZOUsegH0AcWbVWu4qmq0oCE8SOU1CgA8+rHVB5BAASSGAEQAhcYAlBXaQeerag4BHUjkiOEViXwLuSp2BrS2KCUD5-e6LZ6vd6fBy1aTzVRvSgwHqeFAAbVA8HUhEwvU6-T2w1GE2mUFmdxA0EwAHkYBiQABBMDEfLcE6I4ogAC68NAQJBVS0x3OVxuUCQ3AQqgougARn9kOiQCMxqopjNatzuHJKAyRRdrnxJSABaCeZJtSAACSUMCMTBcg46fRGHx+OTmBAfRikOXmOAQQx2h3Fd3+AL2XE+ACs5iiABZ47l8pIgA), this seems fixed.  Feel free to reopen if you can still reproduce.

**Closed by kanitw** 2023-10-28 16:04 UTC
Labels: Bug :bug:, Altair
