### ISSUE TITLE
vega-lite > bate2 > timeFormat converting to epoch

### ISSUE THREAD

**Issue by rapport** [vega/vega-lite#2357] opened 2017-05-10 13:19 UTC
I have several vega-lite charts on the same html page and since switching to vega-lite beta 2 only the first one called is displayed with its data. They are all working individually or when they are the first when displayed together on the same page. My data looks  looks a bit like this on the first chart:

      {
        "user_id": "P01",
        "time": "2017-05-10T09:38:00Z",
        "heartRate": 66,
        "stepCount": 3
      },

But the following charts although reading from the same variable  appear to corrupt the time format and when I export to the editor it appears to have converting "time" to and epoch as below which I think results in the data not being displayed..
      {
        "user_id": "P01",
        "time": 1494409080000,
        "heartRate": 66,
        "stepCount": 3
      },

I am using the time format to convert the ISO date times 
"timeFormat": "%Y-%m-%dT%H:%M:%S.%LZ"

Can anyone suggest a fix? I even tried hacking a epoch timeFormat for all following charts (although the datetimes the raw JSON format are actually ISO) but it doesn't appear to work!

**Comment by domoritz** [comment] 2017-05-10 16:09
Duplicate of https://github.com/vega/vega-lite/issues/2131. 

The fix right now is to make a copy of the data before passing it to Vega/Vega-Lite. We will address this issue soon.

**Closed by domoritz** 2017-05-10 16:09 UTC
