### ISSUE TITLE
Binning shows a "null" label when there is only 1 bin

### ISSUE THREAD

**Issue by epicyclist** [vega/vega-lite#4717] opened 2019-03-12 17:35 UTC
Binning shows a "null" label when there is only one bin.

[Vega Editor example](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgAZ5IgE7wAjACY6AK1jcAdpAA04KBiUBrbFHbolRk5GR743ACaM91K6AgRIAD29IdGpqJWE8ZCtIF1Y9PCMoADNGZDFXaIAqRMg8AE9CKJxIAEdWdHjmdDxGKkgAX2NfKDzvE2bIdg8rPCVWZCbm5NT06Ip0MX77Iah8wui9blQPCch2sHqTRodXaswcH19IccnkWCsAbXWIQ5njiani1TWZzeaAXS2QeqA)

<img width="345" alt="Screen Shot 2019-03-12 at 10 24 49 AM" src="https://user-images.githubusercontent.com/802575/54221817-6ff8fe80-44b1-11e9-92a0-6982c2da53ba.png">

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.0.0-rc12.json",
  "mark": "bar",
  "encoding": {
    "x": {"aggregate": "count", "field": "*", "type": "quantitative"},
    "y": {
      "bin": true,
      "field": "value",
      "type": "nominal"
    }
  },
  "data": {
    "values": [
      {
        "value": "1"
      }
    ]
  }
}
```

It works properly if additional data is added that will result in 2 or more bins:

<img width="372" alt="Screen Shot 2019-03-12 at 10 30 14 AM" src="https://user-images.githubusercontent.com/802575/54222070-e7c72900-44b1-11e9-9655-400a05bf8703.png">

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.0.0-rc12.json",
  "mark": "bar",
  "encoding": {
    "x": {"aggregate": "count", "field": "*", "type": "quantitative"},
    "y": {
      "bin": true,
      "field": "value",
      "type": "nominal"
    }
  },
  "data": {
    "values": [
      {
        "value": "1"
      },
      {
        "value": "2"
      }
    ]
  }
}
```

**Comment by kanitw** [comment] 2019-03-14 23:23
The problem is caused by the extent to the bin transform. 

A workaround is to change the extent signal to account for one value case:

```
if(bin_maxbins_10_value_extent[0] ===bin_maxbins_10_value_extent[1], [bin_maxbins_10_value_extent[0], bin_maxbins_10_value_extent[0]*1.1], bin_maxbins_10_value_extent)
```

**Comment by kanitw** [comment] 2019-03-15 04:31
Instead of writing crazy signals in Vega-Lite, I think we better fix this in Vega.  Will send a PR.

**Comment by domoritz** [comment] 2019-03-15 05:40
Closing in favor of https://github.com/vega/vega/pull/1700.

**Closed by domoritz** 2019-03-15 05:40 UTC
Labels: Bug :bug:
