### ISSUE TITLE
Allow to explicitly set 'value' for encoding with 'rule'

### ISSUE THREAD

**Issue by alexeypetrushin** [vega/vega-lite#5801] opened 2020-01-26 05:55 UTC
Frequently you want to draw a rule (line) on a graph with explicitly specified value. And currently it's very verbose.

There's a nice way to draw aggregate rule like `mean`. But no easy way to draw a rule with explicitly specified value let's say `80`. 

<img width="266" alt="Screen Shot 2020-01-26 at 8 45 28 am" src="https://user-images.githubusercontent.com/94196/73131253-c95e1380-4018-11ea-9847-f60ed47821ac.png">

How it's done currently [playground](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4yghSA3WAbArgKYDOKYA2uBhMJEqpAIKQA0UARmQEwAcAvm1r0oAIVYcyAVkkC0dMpADC4yJ1QAWAMx8qEALpUBVSLlgBPQgCcylaumpQAtrEsBrBexetdGSIQB2AMYA9tAAlv4A5mT2DlAAHjGQAGZhhLjQCkhskPBmAA6ECsGW4f54kEZxmGZJqemZDJw5eYUKAI74sP7wYYi9WEU6ccMYVRixvnCIMT7U2HhEpKiTcQsERRoADHNju+Pzzm4Klvi4RSy7fkGhEdEruzV1aRkKOBsqrZtQnd29-WFBpV9j5RgYdEA) (there's also a way to use `calculate` but it's also verbose)

```
  "layer": [
    ...
    {
      "data": {
        "values": {
          "value": 40
        }
      },
      "mark": "rule",
      "encoding": {
        "y": {"field": "value", "type": "quantitative"}
      }
    }
  ]

```

I propose adding shorter way, by allowing to specify `value` on `x` and `y` encoding if the mark is `rule`.

```
  "layer": [
    ...
    {
      "mark": "rule",
      "encoding": {
        "y": {"field": "value", "type": "quantitative", "value": 40}
      }
    }
  ]

```

**Comment by domoritz** [comment] 2020-01-26 18:03
Duplicate of https://github.com/vega/vega-lite/issues/1601

**Closed by domoritz** 2020-01-26 18:03 UTC
Labels: Feature Request :raising_hand_woman:
