### ISSUE TITLE
Gallery broken in deployment broken because of symlinks

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#840] opened 2015-12-04 23:26 UTC

**Comment by kanitw** [comment] 2015-12-04 23:35
Can you explain how it is broken?  I pulled the latest master and it's working for me.

**Comment by domoritz** [comment] 2015-12-04 23:37
https://vega.github.io/vega-lite/gallery.html

**Comment by kanitw** [comment] 2015-12-04 23:41
Ok, changing the title to "fix deploy script" -- it's still not in a good shape.  I publish by hand today.

**Comment by kanitw** [comment] 2015-12-06 19:42
Duplicate of #781

**Comment by domoritz** [comment] 2015-12-06 19:54
Okay, can you close once you have published by hand?

**Closed** 2015-12-06 21:03 UTC
Labels: Priority/1-Critical
