### ISSUE TITLE
unrecognized parameter definition in nested chart

### ISSUE THREAD

**Issue by mattijn** [vega/vega-lite#7855] opened 2021-12-14 12:50 UTC
As observed in https://github.com/altair-viz/altair/pull/2528#issuecomment-992563926.
This does not work, nested params, ([Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdmCGAuIBcBtUBbWAnA1s08AngA4Cmy4AllmADbkA0IAzpQF7lKikAexWFVhwD6xbLHQgAvlKakYEACaUoAc3wgeGgGaVStRRQCyles1GkswgOKxataCCZEyFAI4BXWFHiV4CSgA3clkQQh09AwoACQgsZlJiCAB3SycQF04QT29ff19g6VCxLAlmZDQQKAksoVJRcUkmACMVQy4QFWIPRCQQUrVGEEwtJABGAAYppnQVZAmmZnhE5ABWUMC7D04AJimpAF1DpkUEWA0PLFoKU-8Aejh4gDoAK2ZHUIASZjAAC1JMBRfvB4MRmEg7ndgqpYE9VH5fh5mk9KBA7j9-pgoaQYQBaWh+UhQ1ZPHZPCavd5QaRAA)):
```json
{
  "concat": [
    {
      "mark": {"type": "circle", "size": {"expr": "size_param"}},
      "encoding": {
        "x": {"field": "Miles_per_Gallon", "type": "quantitative"},
        "y": {"field": "Horsepower", "type": "quantitative"}
      },
      "params": [
        {
          "name": "size_param",
          "bind": {"input": "range", "max": 1000, "min": 0, "step": 5},
          "value": 200
        }
      ]
    }
  ],
  "data": {"url": "data/cars.json"},
  "$schema": "https://vega.github.io/schema/vega-lite/v5.2.0.json"
}
```
![image](https://user-images.githubusercontent.com/5186265/146001746-7d80c9c5-2be1-4f1b-ab1c-192c2b7f3e4f.png)

But this does work, global params ([Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgDghgThC2DOIBcBtUA7OBTZJ4EsAvLAfUhlhABoQAjfdAE2VAbAFcAXXGdAcxw1YEAB7IAjAAZpQhskk14nLGGQBWAL40AbhAA27HEgBM0jQF0aAYwD26KxG6pQwqAGsWITgE8wRkFb4UFZ6gnhERqBYImBQuATEZNBwIBpaIFj2NowMfJ5iSKAAZvhYesxIIACy+KHwZFhQJADi+np21F6+-gCO7BDonPicjvjaOOneniVlFSAAEjZQ8Co2AO6NnT5+uH0DQyND46lpliCMjhCe7FB6uBcjAPQOywB0AFbwHekAJPBWAAssMJcADOJwwPAkI9HuM+BBXnxhgD2LRXvgbI9-kDhLCsPCALR6YZYWFqV7GV6SD5fdCpIA)):
```json
{
  "params": [
    {
      "name": "size_param",
      "bind": {"input": "range", "max": 1000, "min": 0, "step": 5},
      "value": 200
    }
  ],
  "concat": [
    {
      "mark": {"type": "circle", "size": {"expr": "size_param"}},
      "encoding": {
        "x": {"field": "Miles_per_Gallon", "type": "quantitative"},
        "y": {"field": "Horsepower", "type": "quantitative"}
      }
    }
  ],
  "data": {"url": "data/cars.json"},
  "$schema": "https://vega.github.io/schema/vega-lite/v5.2.0.json"
}
```
![image](https://user-images.githubusercontent.com/5186265/146001376-8e25f13d-c5c4-4559-b83c-a0a71576cef9.png)
It might be desired behaviour, but its a bit difficult to grasp

**Comment by ChristopherDavisUCI** [comment] 2021-12-14 13:38
To add to what @mattijn mentioned, I don't see what the fundamental difference is between @mattijn's first example, and this one which does seem to work fine ([Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B20CGAXSAuMBtcEyjz0gFskAnAaw30hQE8AHAU2pgEszoAbFgXwBpchSE0SwAJm3gBzagUJEAHnMgAzNky7jWAWTY8AzgH1mZIwHEkXLgkj8o9ZqwCOAVyTwUbFKjYA3PkEFIjoVdU1tTEgACVgyAyYGWAB3JjI7B0YWKLcPLx8vAMheITwBUohIBnIkYgNqHGCIeSaoeFrsqAAjMlcDAAs7CoVIBJ5oNCipFDS-K0hhiBLggF1S8sIWohQyDwNVOOIGxZp1Lhn0zGAqmqOonr7B3mWFFaCR0kpWJOmh4JExJIZHITpBlFcTpVwlpWABBaDQTRpXy2ey0LIudyeby+IrvVqjZA8FTiWCkKQNAAM-AATABWFYvYIbJqQUIQ1pQjQwqIAETYBgYXCQiOIojQaMcnUguWxBX8LHxrIMRM611J5PgVPsdMplMZJyZZXWuDeuEg4lQSBUrjIXFYlp8AHpkPEAHQAKwMthZkAAJCr+kxSKx+igUAwDOgnU6AtIkG7pN5+q4um62LAnYHg0hY0x4wBaLjeJixulumluyme71akC8IA))

```
{
  "concat": [
    {
      "mark": {"type": "circle"},
      "encoding": {
        "x": {"field": "Miles_per_Gallon", "type": "quantitative"},
        "y": {"field": "Horsepower", "type": "quantitative"}
      },
      "params": [
        {
          "name": "brush",
          "select": "interval"
        }
      ]
    },
    {
      "transform": [
        {"filter": {"param": "brush"}}
      ],
      "mark": "point",
      "encoding": {
        "x": {
          "field": "Acceleration", "type": "quantitative",
          "scale": {"domain": [0,25]}
        },
        "y": {
          "field": "Displacement", "type": "quantitative",
          "scale": {"domain": [0, 500]}
        }
      }
    }
  ],
  "data": {"url": "data/cars.json"},
  "$schema": "https://vega.github.io/schema/vega-lite/v5.2.0.json"
```
The reason this has come up for me is that, on the Altair side, we're not sure exactly where to inject the parameters when working with a multi-view chart.

**Comment by mattijn** [comment] 2021-12-14 18:39
It seems we raised this already in https://github.com/vega/vega-lite/issues/7812..

**Comment by domoritz** [comment] 2021-12-21 19:13
Duplicate of https://github.com/vega/vega-lite/issues/7812

**Closed by domoritz** 2021-12-21 19:13 UTC
Labels: Bug :bug:
