### ISSUE TITLE
Columns not working properly in VL spec (possibly period in name of column?)

### ISSUE THREAD

**Issue by jowens** [vega/vega-lite#1949] opened 2017-02-16 03:58 UTC
Have not seen this behavior before. I am trying to make columns from a field with a period in its name; I've done this successfully for other fields before, so maybe that's the culprit? Anyway, `column` has `"field: [gpuinfo.name]"` and I have two values for `gpuinfo.name`, both of which appear in the final plot but all data points, no matter which GPU I choose, are in the same column.

I sincerely hope I just didn't botch my specification somewhere. (This was generated from Altair.)

![vega](https://cloud.githubusercontent.com/assets/976970/23006815/04502d98-f3b9-11e6-8b5d-ebd1ba3eba0a.png)

```
{
  "mark": "point",
  "data": {
    "values": [
      {
        "engine": "Gunrock",
        "algorithm": "BFS",
        "num_gpus": 1,
        "elapsed": 43.28049087524414,
        "dataset": "soc-LiveJournal1",
        "m_teps": 1563.7744140625,
        "gpuinfo.name": "GPU 1"
      },
      {
        "engine": "Gunrock",
        "algorithm": "BFS",
        "num_gpus": 2,
        "elapsed": 43.28049087524414,
        "dataset": "soc-LiveJournal1",
        "m_teps": 3456.7,
        "gpuinfo.name": "GPU 1"
      },
      {
        "engine": "Gunrock",
        "algorithm": "CC",
        "num_gpus": 1,
        "elapsed": 31.613856554031372,
        "dataset": "soc-LiveJournal1",
        "m_teps": 2710.914794921875,
        "gpuinfo.name": "GPU 2"
      }
    ]
  },
  "encoding": {
    "color": {
      "field": "engine",
      "type": "nominal",
      "legend": {"title": "Engine"}
    },
    "column": {
      "field": "[gpuinfo.name]",
      "type": "nominal",
      "axis": {"orient": "top","title": "GPU"}
    },
    "shape": {
      "field": "engine",
      "type": "nominal",
      "legend": {"title": "Engine"}
    },
    "y": {
      "field": "m_teps",
      "scale": {"type": "log"},
      "type": "quantitative",
      "axis": {"title": "MTEPS"}
    },
    "x": {
      "field": "num_gpus",
      "type": "nominal",
      "axis": {"title": "Number of GPUs"}
    },
    "row": {
      "field": "algorithm",
      "type": "nominal",
      "axis": {"title": "Primitive"}
    }
  }
}
```

**Comment by kanitw** [comment] 2017-02-16 05:52
Still haven't got the solution, but in any case this simpler spec produces the same problem

```
{
  "mark": "point",
  "data": {
    "values": [
      {
        "engine": "Gunrock",
        "algorithm": "BFS",
        "num_gpus": 1,
        "elapsed": 43.28049087524414,
        "dataset": "soc-LiveJournal1",
        "m_teps": 1563.7744140625,
        "gpuinfo.name": "GPU 1"
      },
      {
        "engine": "Gunrock",
        "algorithm": "BFS",
        "num_gpus": 2,
        "elapsed": 43.28049087524414,
        "dataset": "soc-LiveJournal1",
        "m_teps": 3456.7,
        "gpuinfo.name": "GPU 1"
      },
      {
        "engine": "Gunrock",
        "algorithm": "CC",
        "num_gpus": 1,
        "elapsed": 31.613856554031372,
        "dataset": "soc-LiveJournal1",
        "m_teps": 2710.914794921875,
        "gpuinfo.name": "GPU 2"
      }
    ]
  },
  "encoding": {
    "column": {
      "field": "[gpuinfo.name]",
      "type": "nominal",
      "axis": {"orient": "top","title": "GPU"}
    },
    "y": {
      "field": "m_teps",
      "scale": {"type": "log"},
      "type": "quantitative",
      "axis": {"title": "MTEPS"}
    },
    "x": {
      "field": "num_gpus",
      "type": "nominal",
      "axis": {"title": "Number of GPUs"}
    }
  }
}
```

**Comment by jowens** [comment] 2017-02-16 05:55
Relieved to hear this is actually an issue. I try to keep my Github-issues "actual problem" to "my bad programming skills" ratio above one.

**Comment by kanitw** [comment] 2017-02-16 06:08
The problem is that any aggregate field would normally get `<fn>_` prefix. 

In this case, the layout need to know number of unique values but got `distinct_[gpuinfo.name]`instead (but the field is actually named `distinct_gpuinfo.name` thus the output should be `[distinct_gpuinfo.name]`  

Straightforward fix would be to make `field()` method in `fielddef.ts` output `[]` for escaping only if necessary and if so, add it around the prefix as well.  

Alternatively, we could
1) modify the `field()` method so that it outputs escaped names for field with `[]` when there is an aggregate function (e.g., `distinct_gpuinfo_name`)
2) Make the output aggregate transform in `assemble()` in `summary.ts` always explicit specify `as` array.  

In any case, we need to test that this works for

- [ ] nominal fields (which affects layout)
- [ ] aggregated quantitative fields
- [ ] temporal fields with timeUnit

**Comment by kanitw** [comment] 2017-02-16 06:22
#1951 is a start for this, but we still need to make test pass and test all cases in the previous comment.

**Comment by kanitw** [comment] 2017-02-16 06:23
@willium wondering if you can help fix this.  You're the boss of `field()` method anyway :)

**Comment by kanitw** [comment] 2017-02-16 06:32
- [ ] Make this spec pass.  

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a.a": "A","b.b": 28}, {"a.a": "B","b.b": 55}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "[a.a]", "type": "ordinal"},
    "y": {"field": "[b.b]", "type": "quantitative"}
  }
}
```

**Comment by kanitw** [comment] 2017-08-14 18:37
See https://github.com/vega/vega-lite/pull/1951#issuecomment-322118858 for an earlier, unfinished attempt.

**Comment by domoritz** [comment] 2017-08-14 18:41
Related: https://github.com/vega/vega-lite/issues/2625.

**Comment by willium** [comment] 2017-08-14 18:42
Are they related? the dash seems to work.

**Comment by willium** [comment] 2017-08-14 18:51
I've isolated this down to a problem (or edge case) in Vega:
`datum[\"[b.b]\"]` doesn't work, but `datum[\"b\\.b\"]` does. 
The square-bracket escaping doesn't work inside of a key name.

**Comment by willium** [comment] 2017-08-14 18:52
I'm not sure if we'd call this a bug in Vega or an edge case we didn't account for in Vega-Lite... If it's not a bug, we should improve the docs [here](https://vega.github.io/vega/docs/types/#Field).

**Comment by kanitw** [comment] 2017-08-14 20:07
Well if there is a way to handle it, better fix it.

**Comment by willium** [comment] 2017-08-14 22:00
@jheer: In Vega, the escape sequence `datum[\"[b.b]\"]` doesn't seem to work, while `datum[\"b\\.b\"]` does. Is this a bug in Vega escaping the dot notation when used as an argument to datum, or perhaps the expected behavior that's not documented in the Vega docs? (A third, equally possible option is that I'm doing something wrong...)

**Comment by willium** [comment] 2017-08-14 22:02
@kanitw, @domoritz: in the meantime, I'll convert our default escape pattern to `//.` so the above spec will work.

**Comment by jheer** [comment] 2017-08-14 22:49
Hmm, this seems to work: `vega.field("datum[\"[b.b]\"]")({datum: {"[b.b]": 7}})`

But note that the internal brackets are considered part of the key!

**Comment by kanitw** [comment] 2017-12-05 17:33
@domoritz -- I guess this is already supported with proper escaping?  If so, please close the issue.

**Comment by domoritz** [comment] 2017-12-05 17:56
Yes, it works with escaping.

```json
{
  "mark": "point",
  "data": {
    "values": [
      {
        "engine": "Gunrock",
        "algorithm": "BFS",
        "num_gpus": 1,
        "elapsed": 43.28049087524414,
        "dataset": "soc-LiveJournal1",
        "m_teps": 1563.7744140625,
        "gpuinfo.name": "GPU 1"
      },
      {
        "engine": "Gunrock",
        "algorithm": "BFS",
        "num_gpus": 2,
        "elapsed": 43.28049087524414,
        "dataset": "soc-LiveJournal1",
        "m_teps": 3456.7,
        "gpuinfo.name": "GPU 1"
      },
      {
        "engine": "Gunrock",
        "algorithm": "CC",
        "num_gpus": 1,
        "elapsed": 31.613856554031372,
        "dataset": "soc-LiveJournal1",
        "m_teps": 2710.914794921875,
        "gpuinfo.name": "GPU 2"
      }
    ]
  },
  "encoding": {
    "column": {
      "field": "gpuinfo\\.name",
      "type": "nominal",
      "axis": {"orient": "top","title": "GPU"}
    },
    "y": {
      "field": "m_teps",
      "scale": {"type": "log"},
      "type": "quantitative",
      "axis": {"title": "MTEPS"}
    },
    "x": {
      "field": "num_gpus",
      "type": "nominal",
      "axis": {"title": "Number of GPUs"}
    }
  }
}
```

**Closed by domoritz** 2017-12-05 17:56 UTC
Labels: Bug, Help wanted
