### ISSUE TITLE
Rotated axis labels leave a ton of space

### ISSUE THREAD

**Issue by drgould** [vega/vega-lite#6846] opened 2020-09-04 19:27 UTC
It looks like the axis label sizes are computed based on the non-rotated width so it then leaves a ton of space between labels when they're rotated.

Sample spec: https://vega.github.io/editor/#/gist/faa6fccb92bac9686705af2cc055cad8/rotated_label_spacing.json

This can be worked around a bit by specifying a negative `labelSeparation` but that's also dependent on the length of the label and therefore requires setting a `labelLimit` in order to ensure the labels never overlap. Basically there's no reliable way to ensure the rotated labels always have roughly the same spacing without truncating the labels which may not be desired.

**Comment by domoritz** [comment] 2020-09-05 03:51
I think this is a Vega issue. If you agree, I will move it.

**Comment by jwoLondon** [comment] 2020-09-05 07:11
See also https://github.com/vega/vega/issues/2709

And perhaps its worth grouping together rotated label placement issues with https://github.com/vega/vega/issues/2233

**Comment by domoritz** [comment] 2020-09-05 17:03
Duplicate of https://github.com/vega/vega/issues/2709

**Closed by domoritz** 2020-09-05 17:03 UTC
Labels: Bug :bug:
