### ISSUE TITLE
Inconsistent order for ordinal axis

### ISSUE THREAD

**Issue by haberdashPI** [vega/vega-lite#4229] opened 2018-10-24 23:37 UTC
I would expect the following to have a consistent order for the x and y axis. Instead the y axis is ordered with the highest number at the bottom of the graph. I know I can fix this by using {"sort": "descending"}, but it is not clear why this is necessary in the first place. It also means that attempting to add a layer to this (e.g. to show the actual numbers within each square) prevents the logical order from being used because https://github.com/vega/vega-parser/issues/92 prevents me from specifying the order.

```javascript
{
  "title": {"fontSize": 18, "text": "Stimulus Rate"},
  "width": 300,
  "mark": "rect",
  "height": 300,
  "config": {"range": {"heatmap": {"scheme": "viridis"}}},
  "encoding": {
    "column": {
      "sort": ["Peripheral", "Cortical", "Object"],
      "field": "level",
      "type": "nominal"
    },
    "x": {
      "axis": {"title": "Magnitude of Adaptation"},
      "field": "c_a",
      "type": "ordinal"
    },
    "color": {
      "field": "stim_rate",
      "type": "quantitative",
      "aggregate": "mean",
      "legend": {"title": "Stimuli / Second"}
    },
    "y": {
      "axis": {"title": "Magnitude of Inhitibtion"},
      "field": "c_m",
      "type": "ordinal"
    }
  },
  "data": {
    "values": [
      {
        "c_m": 0,
        "c_a": 0,
        "stim_rate": 3.181247383842612,
        "level": "Peripheral"
      },
      {
        "c_m": 18,
        "c_a": 0,
        "stim_rate": 4.771871075763918,
        "level": "Peripheral"
      },
      {
        "c_m": 32,
        "c_a": 0,
        "stim_rate": 0.8371703641691084,
        "level": "Peripheral"
      },
      {
        "c_m": 56,
        "c_a": 0,
        "stim_rate": 0.7743825868564252,
        "level": "Peripheral"
      },
      {
        "c_m": 100,
        "c_a": 0,
        "stim_rate": 0.5441607367099205,
        "level": "Peripheral"
      },
      {
        "c_m": 0,
        "c_a": 5,
        "stim_rate": 0.8371703641691084,
        "level": "Peripheral"
      },
      {
        "c_m": 18,
        "c_a": 5,
        "stim_rate": 4.5835077438258685,
        "level": "Peripheral"
      },
      {
        "c_m": 32,
        "c_a": 5,
        "stim_rate": 3.9974884889074924,
        "level": "Peripheral"
      },
      {
        "c_m": 56,
        "c_a": 5,
        "stim_rate": 2.0092088740058602,
        "level": "Peripheral"
      },
      {
        "c_m": 100,
        "c_a": 5,
        "stim_rate": 1.9045625784847215,
        "level": "Peripheral"
      },
      {
        "c_m": 0,
        "c_a": 11,
        "stim_rate": 0.5650899958141482,
        "level": "Peripheral"
      },
      {
        "c_m": 18,
        "c_a": 11,
        "stim_rate": 3.1184596065299286,
        "level": "Peripheral"
      },
      {
        "c_m": 32,
        "c_a": 11,
        "stim_rate": 2.7626622017580575,
        "level": "Peripheral"
      },
      {
        "c_m": 56,
        "c_a": 11,
        "stim_rate": 5.02302218501465,
        "level": "Peripheral"
      },
      {
        "c_m": 100,
        "c_a": 11,
        "stim_rate": 2.448723315194642,
        "level": "Peripheral"
      },
      {
        "c_m": 0,
        "c_a": 25,
        "stim_rate": 0.795311845960653,
        "level": "Peripheral"
      },
      {
        "c_m": 18,
        "c_a": 25,
        "stim_rate": 1.6324822101297614,
        "level": "Peripheral"
      },
      {
        "c_m": 32,
        "c_a": 25,
        "stim_rate": 2.260359983256593,
        "level": "Peripheral"
      },
      {
        "c_m": 56,
        "c_a": 25,
        "stim_rate": 2.9928840519045625,
        "level": "Peripheral"
      },
      {
        "c_m": 100,
        "c_a": 25,
        "stim_rate": 5.274173294265383,
        "level": "Peripheral"
      },
      {
        "c_m": 0,
        "c_a": 56,
        "stim_rate": 0.46044370029300963,
        "level": "Peripheral"
      },
      {
        "c_m": 18,
        "c_a": 56,
        "stim_rate": 0.4185851820845542,
        "level": "Peripheral"
      },
      {
        "c_m": 32,
        "c_a": 56,
        "stim_rate": 0.5860192549183759,
        "level": "Peripheral"
      },
      {
        "c_m": 56,
        "c_a": 56,
        "stim_rate": 0.9208874005860193,
        "level": "Peripheral"
      },
      {
        "c_m": 100,
        "c_a": 56,
        "stim_rate": 1.2557555462536625,
        "level": "Peripheral"
      },
      {
        "c_m": 0,
        "c_a": 0,
        "stim_rate": 1.2766848053578903,
        "level": "Cortical"
      },
      {
        "c_m": 18,
        "c_a": 0,
        "stim_rate": 2.155713687735454,
        "level": "Cortical"
      },
      {
        "c_m": 32,
        "c_a": 0,
        "stim_rate": 2.511511092507325,
        "level": "Cortical"
      },
      {
        "c_m": 56,
        "c_a": 0,
        "stim_rate": 2.1138551695269987,
        "level": "Cortical"
      },
      {
        "c_m": 100,
        "c_a": 0,
        "stim_rate": 0.46044370029300963,
        "level": "Cortical"
      },
      {
        "c_m": 0,
        "c_a": 5,
        "stim_rate": 1.6534114692339892,
        "level": "Cortical"
      },
      {
        "c_m": 18,
        "c_a": 5,
        "stim_rate": 2.574298869820008,
        "level": "Cortical"
      },
      {
        "c_m": 32,
        "c_a": 5,
        "stim_rate": 2.5533696107157806,
        "level": "Cortical"
      },
      {
        "c_m": 56,
        "c_a": 5,
        "stim_rate": 3.2858936793637503,
        "level": "Cortical"
      },
      {
        "c_m": 100,
        "c_a": 5,
        "stim_rate": 2.260359983256593,
        "level": "Cortical"
      },
      {
        "c_m": 0,
        "c_a": 11,
        "stim_rate": 2.616157388028464,
        "level": "Cortical"
      },
      {
        "c_m": 18,
        "c_a": 11,
        "stim_rate": 2.8463792381749684,
        "level": "Cortical"
      },
      {
        "c_m": 32,
        "c_a": 11,
        "stim_rate": 3.4951862704060277,
        "level": "Cortical"
      },
      {
        "c_m": 56,
        "c_a": 11,
        "stim_rate": 4.060276266220176,
        "level": "Cortical"
      },
      {
        "c_m": 100,
        "c_a": 11,
        "stim_rate": 3.390539974884889,
        "level": "Cortical"
      },
      {
        "c_m": 0,
        "c_a": 25,
        "stim_rate": 3.4742570113017996,
        "level": "Cortical"
      },
      {
        "c_m": 18,
        "c_a": 25,
        "stim_rate": 2.260359983256593,
        "level": "Cortical"
      },
      {
        "c_m": 32,
        "c_a": 25,
        "stim_rate": 3.5789033068229386,
        "level": "Cortical"
      },
      {
        "c_m": 56,
        "c_a": 25,
        "stim_rate": 5.378819589786522,
        "level": "Cortical"
      },
      {
        "c_m": 100,
        "c_a": 25,
        "stim_rate": 4.667224780242779,
        "level": "Cortical"
      },
      {
        "c_m": 0,
        "c_a": 56,
        "stim_rate": 1.0046044370029301,
        "level": "Cortical"
      },
      {
        "c_m": 18,
        "c_a": 56,
        "stim_rate": 3.390539974884889,
        "level": "Cortical"
      },
      {
        "c_m": 32,
        "c_a": 56,
        "stim_rate": 3.892842193386354,
        "level": "Cortical"
      },
      {
        "c_m": 56,
        "c_a": 56,
        "stim_rate": 4.75094181665969,
        "level": "Cortical"
      },
      {
        "c_m": 100,
        "c_a": 56,
        "stim_rate": 4.792800334868145,
        "level": "Cortical"
      },
      {"c_m": 0, "c_a": 0, "stim_rate": 2.951025533696107, "level": "Object"},
      {"c_m": 0, "c_a": 5, "stim_rate": 4.20678107994977, "level": "Object"},
      {"c_m": 0, "c_a": 11, "stim_rate": 4.457932189200502, "level": "Object"},
      {"c_m": 0, "c_a": 25, "stim_rate": 4.332356634575136, "level": "Object"},
      {"c_m": 0, "c_a": 56, "stim_rate": 4.646295521138551, "level": "Object"},
      {"c_m": 18, "c_a": 0, "stim_rate": 3.01381331100879, "level": "Object"},
      {"c_m": 18, "c_a": 5, "stim_rate": 4.981163666806195, "level": "Object"},
      {"c_m": 18, "c_a": 11, "stim_rate": 4.834658853076601, "level": "Object"},
      {
        "c_m": 18,
        "c_a": 25,
        "stim_rate": 4.1230640435328585,
        "level": "Object"
      },
      {"c_m": 18, "c_a": 56, "stim_rate": 4.081205525324403, "level": "Object"},
      {"c_m": 32, "c_a": 0, "stim_rate": 3.0347425701130177, "level": "Object"},
      {"c_m": 32, "c_a": 5, "stim_rate": 3.599832565927166, "level": "Object"},
      {"c_m": 32, "c_a": 11, "stim_rate": 4.604437002930096, "level": "Object"},
      {"c_m": 32, "c_a": 25, "stim_rate": 4.667224780242779, "level": "Object"},
      {"c_m": 32, "c_a": 56, "stim_rate": 4.081205525324403, "level": "Object"},
      {"c_m": 56, "c_a": 0, "stim_rate": 2.8673084972791965, "level": "Object"},
      {"c_m": 56, "c_a": 5, "stim_rate": 3.8719129342821264, "level": "Object"},
      {
        "c_m": 56,
        "c_a": 11,
        "stim_rate": 3.4951862704060277,
        "level": "Object"
      },
      {"c_m": 56, "c_a": 25, "stim_rate": 4.541649225617413, "level": "Object"},
      {"c_m": 56, "c_a": 56, "stim_rate": 4.185851820845542, "level": "Object"},
      {
        "c_m": 100,
        "c_a": 0,
        "stim_rate": 2.7208036835496023,
        "level": "Object"
      },
      {"c_m": 100, "c_a": 5, "stim_rate": 4.164922561741315, "level": "Object"},
      {
        "c_m": 100,
        "c_a": 11,
        "stim_rate": 4.269568857262453,
        "level": "Object"
      },
      {
        "c_m": 100,
        "c_a": 25,
        "stim_rate": 4.248639598158225,
        "level": "Object"
      },
      {
        "c_m": 100,
        "c_a": 56,
        "stim_rate": 3.9347007115948096,
        "level": "Object"
      }
    ]
  }
}
```

**Comment by kanitw** [comment] 2019-06-08 05:09
Thanks for filing the issue. 

The order makes sense for normal ordinal data, when you read from top-to-bottom. 
So we won't fix that.  Regarding sort order, we plan to fix it, but the issue is tracked in https://github.com/vega/vega-lite/issues/5013.

**Closed by kanitw** 2019-06-08 05:09 UTC
Labels: wontfix
