### ISSUE TITLE
Layering ordinal field breaks when timeUnit is added

### ISSUE THREAD

**Issue by ayush29feb** [vega/vega-lite#3011] opened 2017-09-13 21:40 UTC
![image](https://user-images.githubusercontent.com/8674376/30401546-8cf884bc-988f-11e7-91d6-327d26462713.png)

v/s

![image](https://user-images.githubusercontent.com/8674376/30401974-fa4a144e-9890-11e7-8175-c77efb70b2e0.png)

Adding `timeUnit`: `yearmonthdatehoursminutes` makes the axis break. It is creating 2 bars for the same value. However if I remove it, it tends to work. I am not using `temporal` field type because I don't care about time seperation. I just need it to display it in order with a formatted date.

```
"layer": [{
          "mark": "bar",
          "selection": {
            "brush": {"type": "interval", "encodings": ["x"]}
          },
          "encoding": {
            "x": {
              "timeUnit": "yearmonthdatehoursminutes",
              "field": "datetime",
              "type": "ordinal",
              "axis": {"title": "Test Run Date", "labelAngle": -70}
            },
            "y": {
              "field": "*",
              "aggregate": "count",
              "type": "quantitative",
              "axis": {"title": "#Websites", "labelAngle": -20}
            },
            "color": {
              "field": "statusCode",
              "type": "nominal",
              "scale": {
                "domain": ["Pass", "Fail", "Broke"],
                "range": ["#2ca02c", "#d62728", "#222222"]
              }
            }
          }
        }, {
          "mark": "rule",
          "encoding": {
            "x": {
              "aggregate": "min",
              "timeUnit": "yearmonthdatehoursminutes",
              "field": "datetime",
              "type": "ordinal"
            },
            "detail": {
              "field": "chromeVersion",
              "type": "nominal"
            }
          }
        }, {
          "mark": "text",
          "encoding": {
            "x": {
              "aggregate": "min",
              "timeUnit": "yearmonthdatehoursminutes",
              "field": "datetime",
              "type": "ordinal"
            },
            "y": {
              "value": 18
            },
            "text": {
              "field": "chromeVersion",
              "type": "ordinal"
            }
          }
        }]
```

**Comment by kanitw** [comment] 2017-09-13 22:11
1)  Could you please (1) make a minimal spec _with data_ that produces the issue?   

Without data that produces the problem, we can't help you debug.  

Notes:
- Using both timeUnit and aggregate on the same field is not officially _supported_.  The behavior is not defined so that might be the root case.  (Why do you need `min` there?)
- Using ordinal with `yearmonthdatehoursminutes` wouldn't be very scalable if you have a lot of data.

**Comment by kanitw** [comment] 2018-05-09 18:50
Since there is no example to reproduce the issue, I'll close this for now as this isn't an ideal way to use ordinal scale anyway.

**Closed by kanitw** 2018-05-09 18:50 UTC
