### ISSUE TITLE
Lookup transform from nested JSON not working

### ISSUE THREAD

**Issue by manzt** [vega/vega-lite#5124] opened 2019-06-28 17:22 UTC
It seems Vega-Lite does support a lookup transform from nested JSON like this Vega [example](https://vega.github.io/vega/examples/reorderable-matrix/).

Expected ([Open in Vega-Editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjMSA3ZApgO6baRHIAmALgBakAsADEwDRS0Fq3WkDMLAL7tIAWwCGAJwDWpHNViwANtWQAHUvACuSpYOHgolcdXFzDESFslLSkHtTUBnDAHpXqZE+oA6T3S0AIy0nAkk4eGoCSJ84UVcJeAAvalcCPkQmADYARj4AVgB2AnEATj4AJgZq0pysykREBor8gA5KQvFC10lxIldoOtacggJoaoqs1vFAvkoc-MXS4yy+SsRRwpzoAkL8rLbXJUVpLTUAfSVkeGknHwArJwRIQwNLCRk7STHeVkNIaJwSjXdBYUAQSxwY6SOSQagATzUBDs8Fgomu4lsIhQBCUlDsqEksDOkDeEMgAA9YQikSi0RisVAcXi7KZJKgCNQAHLiUTIkRPSS8MGQZn4rCQQnEjT6P4QqDw6mI5ES1Ho+CYyDYwgs1W8-lQQXCshiglEkn6V5yqDUXrwJyIWCSUSkADaFmwHssx1gpw0Eqe1h2Wq9TKJLrBocsxlM5nl8ag1lsEoczjcHi8vn8tCCITCESiMTiCXEyVSrQY23y4j4uQYXQqBCYrVaBA6FQ2gwYTWy+QIPT6rkKB1K9VK4k2WSYBRyiHEFSY+UClCyXQIrT4OQqO2WmTKFSOJzO51RlAId0ezyjYDJCcg0gIiol1zPVOtd7FTjdkA1fK1UClEkAF1Q0ED1b09O8fT9VkpA5X5Q0gcQvwlNl4J5P933JRBwzjBMjBMMxI3w8kkzsVMXHcTxvD8ZAAmCUJwgQQtfGLRIUlcCsqxrOsGybFs20KDsxhybtKF7ften6Yd8lHShx0nad8lnedF2XVdig3LcdwaJh90PX1j1Pc8HieeAXhIiD5XvR87BfAg32vUUdUoFCwFdH99UgECEzA+U-LAIDrUgAASJxoE4CRyOoRxKNcXACFQcRaPonxkFgVxwsi8R4sS8QAForiieK+B8UqmFMq9BCAA)):

![image](https://user-images.githubusercontent.com/24403730/60359396-dc502d00-99d0-11e9-914c-9f5067d8d1c2.png)

Outcome ([Open in Vega-Editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjMSA3ZApgO6baRHIAmALgBakAsADEwDRS0Fq3WkDMLAL7tIAWwCGAJwDWpHNViwANtWQAHUvACuSpYOHgolcdXFzDESFslLSkHtTUBnDAHpXqZE+oA6T3S0AIy0nAkk4eGoCSJ84UVcJeAAvalcGAA4ATkoAJkDKQPEmRABGBnEAVgFAnMQCADZoJkC+HJLKaEy+V0lxIldxQKZMivq+McySkpyK9JzxDPqx42zM6BKCaEDAxEyc8vF01yVFaS01AH04wOR4AkofACsnBEhWCyhEWEkJXiwcNSSWBqMLUACediUt2kTkggkMBksEhkdkkm1470s0TglFu6H+Hxgym+ckg4JBdngsFEt3EthEKAISkodlQQPOcMxECgAA9SeSCJTqbT6Z9CMy7KZJKgCLxEdzIBD-mSwRSsJAqTT4HS3mKmSz1S9rNBBfCIPKyb14E4vj9SABtD6gbkKk6wM4aQ2wY2CrkuyCIIGicwu-3GUwh0P+6y2dUOZxuDxeXz+WhBEJhCJRGJxBLiZKpDLZPIFIqlcpVZq1BpNFptDpdHp9AZDEZjCZTGZzBbpJZ8FaUNYbLY7PYHI5uj1Xak3O4PZ6vP1Rz7fX6kwHA0FKqBUygEWFm5fyqOQaQEbeQW57vlL-2M5mwrD2jXiUS+qBs70aAC6H3NH2PbA-ygScOXVKUZQxYDIHER8oAg2UADlX19aDA2pSMT3DMwCWXBUYzseMXHcTxvD8ZAAmCUJwgQbNfFzRIUjSLJcnyQpijKSpqmrRpmladpOm6Xp+kGYZRnGPhJmmWZ5kWZZxFWdZNm2XZ9nEQ5jlOc5p1EWd7ieF54DeYC71XEx1yBEFJHBIU9wPEywEA-0zwvK8CBvByA3FSg4OfbU30gX8o0Pf8IG-LlIAAEicaBOAkQjqEcYjXFwAhUHEcjKJ8ZBYFcGK4vEFK0vEABaKEohSvgfCqpgDNeEBBCAA)):
![image](https://user-images.githubusercontent.com/24403730/60359374-cd697a80-99d0-11e9-9faa-ad8194f9cf55.png)

Dataset:
```json
{
    "nodes": [
        {"name": "foo", "group": 1, "index": 0},
        {"name": "bar", "group": 2, "index": 1},
        {"name": "baz", "group": 2, "index": 2},
        {"name": "foobar", "group": 3, "index": 3}
    ],
    "links": [
        {"source": 0, "target": 0},
        {"source": 1, "target": 1},
        {"source": 2, "target": 2},
        {"source": 3, "target": 3},
        {"source": 1, "target": 3},
        {"source": 2, "target": 3}
    ]
}
```

Examining the compiled Vega, I find that only data "source_0" is created when the same URL is use even though the different features are selected in the Vega-Lite spec.

VL spec:

```
  "data": {
    "url": "data/lookup_combined.json",
    "format": {"property": "links"}
  },
  "transform": [
    {
      "lookup": "source",
      "from": {
        "data": {
          "url": "data/lookup_combined.json",
          "format": {"property": "nodes"}
        },
        "key": "index",
        "fields": ["name", "group"]
      }
    }
    }
  ],
```

Compiled Vega:
```
"data": [
    {
      "name": "source_0",
      "url": "data/lookup_combined.json",
      "format": {"property": "links", "type": "json"}
    },
    {
      "name": "data_0",
      "source": "source_0",
      "transform": [
        {
          "type": "lookup",
          "from": "source_0",
          "key": "index",
          "fields": ["source"],
          "values": ["name", "group"]
        }
      ]
    }
  ],
```

**Comment by manzt** [comment] 2019-06-28 17:25
It seems that VL treats it as the same dataset because of the URL even though different features are selected.

When using distinct URLs for each property, the Vega is compiled to:
```
  "data": [
    {
      "name": "source_1",
      "url": "data/lookup_nodes.json",
      "format": {"type": "json"}
    },
    {
      "name": "source_0",
      "url": "data/lookup_links.json",
      "format": {"type": "json"},
      "transform": [
        {
          "type": "lookup",
          "from": "source_1",
          "key": "index",
          "fields": ["source"],
          "values": ["name", "group"]
        },
        {
          "type": "lookup",
          "from": "source_1",
          "key": "index",
          "fields": ["target"],
          "values": ["name"],
          "as": ["targetName"]
        }
      ]
    }
  ]
```

And the desired result is observed.

**Comment by manzt** [comment] 2019-06-28 17:35
Editing the compiled Vega for the not-working example, I find that I can get the desired results by adding another source to the compiled vega:

```
  "data": [
    {
      "name": "source_0",
      "url": "https://gist.githubusercontent.com/manzt/489d2bdba0f14a530b2fe6c0b321dc93/raw/ab09563639112582a48663da9d9c1ecbbf924aa8/lookup_combined.json",
      "format": {"property": "links", "type": "json"}
    },
    {
      "name": "source_1",
      "url": "https://gist.githubusercontent.com/manzt/489d2bdba0f14a530b2fe6c0b321dc93/raw/ab09563639112582a48663da9d9c1ecbbf924aa8/lookup_combined.json",
      "format": {"property": "nodes", "type": "json"}
    },
    {
      "name": "data_0",
      "source": "source_0",
      "transform": [
        {
          "type": "lookup",
          "from": "source_1",
          "key": "index",
          "fields": ["source"],
          "values": ["name", "group"]
        }
      ]
    }
  ],
```

**Comment by domoritz** [comment] 2019-06-28 17:47
I believe this is a duplicate of https://github.com/vega/vega-lite/issues/5034.

**Closed** 2019-06-28 17:48 UTC
Labels: Bug :bug:
