### ISSUE TITLE
Use "width"/"height" instead of hardcoded values

### ISSUE THREAD

**Issue by nyurik** [vega/vega-lite#2651] opened 2017-07-10 18:58 UTC
VL converts width/height as scales `"domain": [200,0]` instead of `"domain": "width"`. Using the second method would generate much more flexible Vega spec that can be easily resized.

**Comment by domoritz** [comment] 2017-07-10 22:31
Duplicate of #618

**Closed by domoritz** 2017-07-10 22:31 UTC
