### ISSUE TITLE
Selections break when field names are channel names

### ISSUE THREAD

**Issue by jmschrei** [vega/vega-lite#4951] opened 2019-05-14 02:11 UTC
Howdy all

I'm trying to use altair to make an interactive display. When I make the static image on a subset of the data, it works fine. 

![image](https://user-images.githubusercontent.com/3916816/57665856-82c3a880-75b2-11e9-9d84-3ae704e81c5e.png)

When I try to add in the brush, things get wonky and it doesn't even let me use a brush!

![image](https://user-images.githubusercontent.com/3916816/57665870-8eaf6a80-75b2-11e9-9192-3ada27ee8191.png)

An example from the altair site works fine though, including the brush.

![image](https://user-images.githubusercontent.com/3916816/57665878-9969ff80-75b2-11e9-8f1f-f33255a18942.png)

@domoritz suggested I should post the issue and the vega here. I've attached the json file (which is named txt so that GitHub will support it.

I am using altair v3.0.1, vega v2.1.0, jupyter notebook version 5.7.8, Python 3.6

[vega.txt](https://github.com/vega/vega-lite/files/3175551/vega.txt)

**Comment by jakevdp** [comment] 2019-05-14 03:13
A minimal reproduction in the vega editor is [here](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEC2CGBOBrSAuKBjAlvdAbAppADThT4B26A9gCabkDmqYoEEk1uV8zrb7AN1i4AroTSRcmBgAsALg3iwAnsVL8OVcnTmYtvdfyhzlAB3FRyVaPWFqjbSADNM+XDWYdRAZzn4eJA7s3m746Lr6EiEE4dwADHEATJCGEAC+hmmBjgAevJAm5p4AjiKw5LpysLoChERQLm4eEnlZhpCqaMAFZhaQpeWV1Zi1xA2u7p6qGenZkNFhEeT5C7HwCcldPUUS9H7wQriQaW3sNNWwBhqHYt7MANqpLJB5aHH1HczvGD77ngCCx2y-G6rzAAEYPp0IR88CJfP4AUCnqDmIkoWjYb9ERJAacjKi0ABmDHErHwv4SABCyIchLAABZSYzyQieNTaQSXswAKzMvk-Ck4qA0mZsAC6pAyaSAA).

**Comment by jakevdp** [comment] 2019-05-14 03:14
(first reported in https://github.com/altair-viz/altair/issues/1503)

**Comment by domoritz** [comment] 2019-05-14 22:23
Even more minimal example is [here](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEC2CGBOBrSAuKBjAlvdAbAppADThT4B26A9gCabkDmqYoEEkAHs8JAC4CeAB0JpIARwCuscr0y9YsgG6EiUAGaZ8uGs06QAviTZR+3PkJFRJ02fKUr1m7btP7Sh0pADOW-OllU5GY+BP5U8AAMEQBMZgLCuvS8+PCKsLgGHuw0CrDcpOxpuBL4XswA2gVsPFxoEaqQpnUNeBJeyfC6AIIGRsYsemgAjA1NYCMYxe0p3b1VEDXM0aNLLVMds1n9i2gAzCt7a20bogBCc-0DtWAALAe3R9OdZxfbg2AArPdfk8czL25jABddwgfRAA).

**Comment by domoritz** [comment] 2019-05-14 22:32
Ahh, so the problem is that we are generating signals that seem to be colling between `x` and `y` channels and fields.

**Comment by jmschrei** [comment] 2019-05-14 22:56
If I change the names from `x` and `y` to `xcoord` and `ycoord`, it works.

**Comment by domoritz** [comment] 2019-05-14 23:49
@arvind I'm thinking of renaming the signals we usually create for x and y and adding a `_brush` to the name in `index.ts`. Where do I need to then change things to generate the right signals?

**Comment by hannahburkhardt** [comment] 2019-05-15 00:59
Of note: this works correctly in altair 2.4.1, but not in altair 3.0.1 (see my issue on the altair repository)

**Comment by arvind** [comment] 2019-05-15 02:06
Thanks for reporting this, @jmschrei and @hannahburkhardt. The selection code already takes care of renaming conflicting signal names when channel and field names collide, so the fix @domoritz suggests shouldn't be necessary. Instead, it looks like the brush marks generated by `interval.ts` are still hardcoded to use signal names of the format `${name}_x` or `${name}_y` rather than reading off their values from `selCmpt.project`. I should be able to fix this first thing tomorrow.

**Comment by arvind** [comment] 2019-05-15 16:14
Should be fixed with #4960.

**Closed** 2019-05-15 16:36 UTC
Labels: Bug :bug:
