### ISSUE TITLE
vconcat removes grid lines

### ISSUE THREAD

**Issue by SyntaxRules** [vega/vega-lite#4226] opened 2018-10-19 17:06 UTC
I have a simple chart with gridlines:

![image](https://user-images.githubusercontent.com/4117657/47231747-07d34000-d38b-11e8-8088-ab5421360b20.png)
[vega-editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAmOgDY6ABjoArWNwB2kADTgo8TQDNG1bGFAQIkdAA9GsMxctXqAJ0YATM3letku5xd3DwBhbjFuVzNIAGIAMQTEnT1nSDdPAHlCdHhmAE8zAEYAwMgxdHZkMTCIqJxYxUam5MCocsqxAAV0Dw9GDVMcABYS1LxGeABrGsjomKbm0ctIcbwxZABBCWoterxuQhbS1fWNgfWzRSWrE+Q4zTwAdWQTfGiNSIwxSBSwAF8lpB2DlJm5uKwNF56vFEgkjlZ1tRkJDHADfpBYHg8hccE5UtRWJ5kOIKlVHL9UoYHgBlRgAL2QRQArNdllSNE8XtQ3jhChT-qy0oSPMTbuTWlZ2XhaQyigB2fl-X5osbMHHmfnWDRIWb1VCeDwXQVSmWMnDSEaaqXPV54IrKwEURjIADu4tKxjE32hyCZvt9P2cSogKqgHnQeHQsGQeAcuPR4cjIgAHABOOU5JmFQzoOS51MeVPSQxFxRDIbwOQAZlTTNThSZyaZZgA2vy8aUwhpjATXBGeLsoNJ4aVkVCh4oLSJJyJpKmR6lMehXHb6tJJ4URIVFNPCoHAqHnB3Ul2e6w++NNNFpGANgvlmPr4pU6mt9IRFW96yrEuV0+p4oVa7vuQa-AAunooaQImmC4pAGjoKgZphhGohphm8BZjmeZyAWRYluu5aVjWdYNk2kBQciBh9AM7pWAYtR0WyzpiOOkCniY579legqIo+OAaKwXqCgg6DqseyweNwGD9K2-KpMO37LDed7yWAYFKZAfYDMhbYSssMRpi+yBDL096pDEcgeHK8DsL0XhqRpakrHkhDIZAkQ0WJIGWIeyxYm57zSf03kOuiNhMVYtj2JFyztFUcZgDmYjRpp4xTIlyWpc56Tjj4fhpWqyGCV6irGixbG-naInwGJyESVYUkyYOen6ROhTJtOnWKF+alWOuc7Tq+VaKD5zgQa0fk3IwSEAKoaMw0SsHg8B5Mgy6oA8iCJoygoBe5eBoIQkShUGgI2MO8atJAxhVGxj57TNyDzYt9TLat62uJtHLbRGu2avt0SHagx19t8yqQSUkAYK4kxMZA8ASIcOD5f46KA-UwJRJDeiQC6ngsGYyaNCAfxAA)
<details>
  <summary>vega-lite spec</summary>
<pre><code>
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.6.0.json",
  "config": {
    "axis": {
      "grid": true,
      "gridColor": "#FFFFFF",
      "gridOpacity": 1,
      "labelColor": "#000000",
      "labelPadding": 4,
      "tickColor": "#000000",
      "titleAlign": "top",
      "titleAngle": 0,
      "titleFontWeight": "normal"
    },
    "background": "#FFFFFF",
    "legend": {},
    "style": {
      "guide-label": {
        "fontSize": 15,
        "fontWeight": 1
      },
      "guide-title": {
        "fontSize": 17
      }
    },
    "title": {
      "anchor": "middle",
      "fontSize": 24,
      "fontWeight": 1
    },
    "view": {
      "fill": "#e5e5e5"
    }
  },
  "datasets": {
    "data-897ac51fa6a69d92f92044c639591585": [
      {
        "Configuration": "2",
        "end": "2024-02-29",
        "start": "2021-10-01"
      },
      {
        "Configuration": "2 A",
        "end": "2099-12-31",
        "start": "2024-03-01"
      }
    ]
  },
  "data": {"name": "data-897ac51fa6a69d92f92044c639591585"},
  "encoding": {
    "color": {
      "field": "Configuration",
      "legend": null,
      "scale": {
        "domain": [
          "2",
          "2 A"
        ],
        "range": [
          "#8999e4dd",
          "#6d7cbddd"
        ],
        "type": "ordinal"
      },
      "type": "nominal"
    },
    "x": {
      "axis": {
        "labels": false,
        "ticks": false,
        "grid": true,
        "title": null
      },
      "field": "start",
      "scale": {
        "domain": [
          "2018-08-01",
          "2029-09-30"
        ]
      },
      "timeUnit": "utcyearmonthdate",
      "type": "temporal"
    },
    "x2": {
      "field": "end",
      "timeUnit": "utcyearmonthdate",
      "type": "temporal"
    }
  },
  "mark": {
    "clip": true,
    "type": "bar"
  },
  "width": 800
}
</code></pre>
</details><br/>

When I place the chart inside a `vconcat` the gridlines disappear:

![image](https://user-images.githubusercontent.com/4117657/47231875-5d0f5180-d38b-11e8-9627-2c770c194232.png)
[vega-editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAmOgDY6ABjoArWNwB2kADTgo8TQDNG1bGFAQIkdAA9GsMxctXqAJ0YATM3letku5xd3DwBhbjFuVzNIAGIAMQTEnT1nSDdPAHlCdHhmAE8zAEYAwMgxdHZkMTCIqJxYxUam5MCocsqxAAV0Dw9GDVMcABYS1LxGeABrGsjomKbm0ctIcbwxZABBCWoterxuQhbS1fWNgfWzRSWrE+Q4zTwAdWQTfGiNSIwxSBSwAF8lpB2DlJm5uKwNF56vFEgkjlZ1tRkJDHADfpBYHg8hccE5UtRWJ5kOIKlVHL9UoYHgBlRgAL2QRQArNdllSNE8XtQ3jhChT-qy0oSPMTbuTWlZ2XhaQyigB2fl-X5osbMHHmfnWDRIWb1VCeDwXQVSmWMnDSEaaqXPV54IrKwEURjIADu4tKxjE32hyCZvt9P2cSogKqgHnQeHQsGQeAcuPR4cjIgAHABOOU5JmFQzoOS51MeVPSQxFxRDIbwOQAZlTTNThSZyaZZgA2vy8aUwhpjATXBGeLsoNJ4aVkVCh4oLSJJyJpKmR6lMehXHb6tJJ4URIVFNPCoHAqHnB3Ul2e6w++NNNFpGANgvlmPr4pU6mt9IRFW96yrEuV0+p4oVa7vuQa-AAunooaQBQBjahGrZOJAiaYLikAaOgqBmmGEaiGmGbwFmOZ5nIBZFiW67lpWNZ1g2TaQFByIGH0AzulYBi1KxbLOmI46QKeJjnv2V6Coij44BorBeoKCDoOqx7LB43AYP0rb8qkw7fssN53mpYBgZpkB9gMWFthKywxGmL7IEMvT3qkMRyB4crwOwvReLp+m6SseSEFhkCRMxskgZYh7LFivnvEp-RBQ66I2JxVi2PYCXLO0VRxmAOZiNGBnjFMGVZTlXnpOOPh+LlapYRJXqKsa3G8b+drSfAslYfJViKcpg6mWZE6FMm04DYoX66VY65ztOr5VoowXOBBrShTcjCYQAqhozDRKweDwHkyDLqgDyIImjKCuFfl4GghCRDFQaAjYw7xq0kDGFUvGPqdy3IGtG31FtO17a4B0ckdEYnZqZ3RBdqBXX23zKpBJSQBgriTJxkDwBIhw4GV-johD9TAlECN6JALqeCwZjJo0kEQX8QA)

<details>
  <summary>vega-lite spec</summary>
<pre><code>
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.6.0.json",
  "config": {
    "axis": {
      "grid": true,
      "gridColor": "#FFFFFF",
      "gridOpacity": 1,
      "labelColor": "#000000",
      "labelPadding": 4,
      "tickColor": "#000000",
      "titleAlign": "top",
      "titleAngle": 0,
      "titleFontWeight": "normal"
    },
    "background": "#FFFFFF",
    "legend": {},
    "style": {
      "guide-label": {
        "fontSize": 15,
        "fontWeight": 1
      },
      "guide-title": {
        "fontSize": 17
      }
    },
    "title": {
      "anchor": "middle",
      "fontSize": 24,
      "fontWeight": 1
    },
    "view": {
      "fill": "#e5e5e5"
    }
  },
  "datasets": {
    "data-897ac51fa6a69d92f92044c639591585": [
      {
        "Configuration": "2",
        "end": "2024-02-29",
        "start": "2021-10-01"
      },
      {
        "Configuration": "2 A",
        "end": "2099-12-31",
        "start": "2024-03-01"
      }
    ]
  },
  "vconcat": [{
  "data": {"name": "data-897ac51fa6a69d92f92044c639591585"},
  "encoding": {
    "color": {
      "field": "Configuration",
      "legend": null,
      "scale": {
        "domain": [
          "2",
          "2 A"
        ],
        "range": [
          "#8999e4dd",
          "#6d7cbddd"
        ],
        "type": "ordinal"
      },
      "type": "nominal"
    },
    "x": {
      "axis": {
        "labels": false,
        "ticks": false,
        "grid": true,
        "title": null
      },
      "field": "start",
      "scale": {
        "domain": [
          "2018-08-01",
          "2029-09-30"
        ]
      },
      "timeUnit": "utcyearmonthdate",
      "type": "temporal"
    },
    "x2": {
      "field": "end",
      "timeUnit": "utcyearmonthdate",
      "type": "temporal"
    }
  },
  "mark": {
    "clip": true,
    "type": "bar"
  },
  "width": 800
  }]
}
</code></pre>
</details><br/>

When I switch the chart to plot on the y-axis (with `vconcat`, the grid lines reappear):

![image](https://user-images.githubusercontent.com/4117657/47232038-de66e400-d38b-11e8-8b67-ec62db725558.png)
[vega-editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAmOgDY6ABjoArWNwB2kADTgo8TQDNG1bGFAQIkdAA9GsMxctXqAJ0YATM3letku5xd3DwBhbjFuVzNIAGIAMQTEnT1nSDdPAHlCdHhmAE8zAEYAwMgxdHZkMTCIqJxYxUam5MCocsqxAAV0Dw9GDVMcABYS1LxGeABrGsjomKbm0ctIcbwxZABBCWoterxuQhbS1fWNgfWzRSWrE+Q4zTwAdWQTfGiNSIwxSBSwAF8lpB2DlJm5uKwNF56vFEgkjlZ1tRkJDHADfpBYHg8hccE5UtRWJ5kOIKlVHL9UoYHgBlRgAL2QRQArNdllSNE8XtQ3jhChT-qy0oSPMTbuTWlZ2XhaQyigB2fl-X5osbMHHmfnWDRIWb1VCeDwXQVSmWMnDSEaaqXPV54IrKwEURjIADu4tKxjE32hyCZvt9P2cSogKqgHnQeHQsGQeAcuPR4cjIgAHABOOU5JmFQzoOS51MeVPSQxFxRDIbwOQAZlTTNThSZyaZZgA2vy8aUwhpjATXBGeLsoNJ4aVkVCh4oLSJJyJpKmR6lMehXHb6tJJ4URIVFNPCoHAqHnB3Ul2e6w++NNNFpGANgvlmPr4pU6mt9IRFW96yrEuV0+p4oVa7vuQa-AAunooaQBQBjahGrZOJAiaYLikAaOgqBmmGEaiGmGbwFmOZ5nIBZFiW67lpWNZ1g2TaQFByIGH0AzulYBi1KxbLOmI46QKeJjnv2V6Coij44BorBeoKCDoOqx7LB43AYP0rb8qkw7fssN53mpYBgZpkB9gMWFthKywxGmL7IEMvT3qkMRyB4crwOwvReLp+m6SseSEFhkCRMxskgZYh7LFivnvEp-RBQ66IFPGrTWHYcYamZZSkmIKU5pl-heeMUxZbJ0YGek44+H4BliuJkliIqxrcbxv52tJ8CyVh8lWIpymDqZZkToUybToNihfrpVjrnO06vlWijBc4EGtKFNyMJhACqGjMNErB4PAeTIMuqAPIgiaMoK4V+XgaCEJEMVBoCeTDglHoNdEj5nStyDrZt9Tbbt+2uIdHLHRGp2aud0SXag119t8yqQSUkAYK4kycZA8ASIcODlblYw+X5wJRPDeiQC6ngsGY66QRBfxAA)
<details>
  <summary>vega-lite spec</summary>
<pre><code>
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.6.0.json",
  "config": {
    "axis": {
      "grid": true,
      "gridColor": "#FFFFFF",
      "gridOpacity": 1,
      "labelColor": "#000000",
      "labelPadding": 4,
      "tickColor": "#000000",
      "titleAlign": "top",
      "titleAngle": 0,
      "titleFontWeight": "normal"
    },
    "background": "#FFFFFF",
    "legend": {},
    "style": {
      "guide-label": {
        "fontSize": 15,
        "fontWeight": 1
      },
      "guide-title": {
        "fontSize": 17
      }
    },
    "title": {
      "anchor": "middle",
      "fontSize": 24,
      "fontWeight": 1
    },
    "view": {
      "fill": "#e5e5e5"
    }
  },
  "datasets": {
    "data-897ac51fa6a69d92f92044c639591585": [
      {
        "Configuration": "2",
        "end": "2024-02-29",
        "start": "2021-10-01"
      },
      {
        "Configuration": "2 A",
        "end": "2099-12-31",
        "start": "2024-03-01"
      }
    ]
  },
  "vconcat": [{
  "data": {"name": "data-897ac51fa6a69d92f92044c639591585"},
  "encoding": {
    "color": {
      "field": "Configuration",
      "legend": null,
      "scale": {
        "domain": [
          "2",
          "2 A"
        ],
        "range": [
          "#8999e4dd",
          "#6d7cbddd"
        ],
        "type": "ordinal"
      },
      "type": "nominal"
    },
    "y": {
      "axis": {
        "labels": false,
        "ticks": false,
        "grid": true,
        "title": null
      },
      "field": "start",
      "scale": {
        "domain": [
          "2018-08-01",
          "2029-09-30"
        ]
      },
      "timeUnit": "utcyearmonthdate",
      "type": "temporal"
    },
    "y2": {
      "field": "end",
      "timeUnit": "utcyearmonthdate",
      "type": "temporal"
    }
  },
  "mark": {
    "clip": true,
    "type": "bar"
  },
  "width": 20
  }]
}
</code></pre>
</details><br/>

I tried a few other things to get the gridlines to show up, none of these solutions worked:

- Set axis labels and title to `true`
- Remove axis encoding altogether
- Adding values into the axis, so vega-lite knows were they should be.
- Create a minimal example by removing all extra style [vega-editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAmOgDY6ABjoArWNwB2kADTgo8TQDNG1bGFAQIkdAA9GsMxctXqAJ0YATM3letku5xd3DwBhbjFuVzNIAGIAMQTEnT1nSDdPAHlCdHhmAE8zAEYUsABfAMtICkZkAHdHEqtjMTFomOQAVk7OyBLSvXK9SA90PHRYZDwHHCcrEbGRAA4ATgB2HI7Cw3Q5HeWPZelDQ8UAFlP4OQBmZY7lwo7FjrMAbUbzd6swjWNqVldRjwtDhINJkoFKsgNF4QdJFNJTiJ4SJpMtwRCoLAxq48NE4dJCiJCookYVehDBhDZoFIN9fv9AZo8WAAILoiGQKEwqBw5bLInSERXMkVDlY9A4vHwxGKK6k8mBfrOAC6AwqVQMGngo1eTmGo0wM0gGnQqGQ0XmohW63gm22uzk+0Oxzh50uNzuDyekEpUChBg8jA0phmJUgBgiUVDHOMyDE3NpRhMDLwQPZlTweUI5pBGm4qCD6FafVFUBsDRjNXj0XFktLVgQRZzHwxUA8+fQQden0qcMKiyRA8UIp7Vnx-MU-KuigVENVFPrUFTZoAqhpmNFWHh4HlkBLUJoWPNzYvIJns9E8GhCJEi7OyqXIDYwdGabHqyCuemrMvkGuNyCW47nurgHhoR6jCe7xnlmzZntet7Fs4SoPkMGCuAA1hWlTwBIhDeL4-hhuecHsBKCq+pAtSeCwZiLIoigDKqpRAA)

My feeling is that there are problems applying the grid inside a bar chart that is vconcated. Has anyone run into this, or can anyone pinpoint the problem here?

**Comment by kanitw** [comment] 2019-01-20 05:14
@domoritz -- I look at the Vega specs and can't figure out why?  I'm wondering if this a bug in Vega?

**Comment by domoritz** [comment] 2019-01-20 06:15
Odd. Here is a small spec. The gridlines disappear when I put the axis on x but they are there when I put the axis on y. 

```json
{
  "$schema": "https://vega.github.io/schema/vega/v4.json",
  "width": 800,
  "marks": [
    {
      "type": "group",
      "style": "cell",
      "encode": {
        "update": {
          "width": {"signal": "width"},
          "height": {"value": 40}
        }
      },
      "axes": [
        {
          "scale": "concat_0_x",
          "orient": "bottom",
          "grid": true
        }
      ]
    }
  ],
  "scales": [
    {
      "name": "concat_0_x",
      "type": "time",
      "domain": {
        "fields": [
          {"signal": "{data: datetime(\"2018-08-01\")}"},
          {"signal": "{data: datetime(\"2029-09-30\")}"}
        ]
      },
      "range": [0, {"signal": "width"}]
    }
  ]
}
```

**Comment by domoritz** [comment] 2019-01-20 06:16
The gridlines appear when I set the height explicitly.

**Comment by domoritz** [comment] 2019-01-20 06:20
Filed in Vega as https://github.com/vega/vega/issues/1524. If this is by design, Vega-Lite has to generate different code. We can reopen this issue if that is the case.

**Comment by SyntaxRules** [comment] 2019-02-28 17:43
@domoritz Following up with the linked issue. It was closed as the vega you produced just needed a hieght/width signal. Does this mean vega-lite should be generating different code, and we should open a issue there?

**Comment by domoritz** [comment] 2019-03-01 00:12
I reopened the issue here. I'd appreciate a pull requests to fix this issue.

**Comment by kanitw** [comment] 2019-03-02 01:23
Will be fixed in https://github.com/vega/vega-lite/pull/4622

**Closed by kanitw** 2019-03-02 01:23 UTC
Labels: :bug:  Bug
