### ISSUE TITLE
Cannot encode size of geoshape

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#3335] opened 2018-01-31 18:46 UTC
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.1.json",
  "width": 500,
  "height": 300,
  "layer": [
    {
      "data": {
        "url": "https://unpkg.com/world-atlas@1/world/110m.json",
        "format": {
          "type": "topojson",
          "feature": "countries"
        }
      },
      "projection": {
        "type": "orthographic"
      },
      "mark": {
        "type": "geoshape",
        "fill": "mintcream",
        "stroke": "black",
        "strokeWidth": 0.35
      }
    },
    {
      "data": {
        "url": "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_week.geojson",
        "format": {
          "type": "json",
          "property": "features"
        }
      },
      "projection": {
        "type": "orthographic"
      },
      "mark": {
        "type": "geoshape",
        "opacity": 0.25,
        "color": "red"
      },
      "encoding": {
        "size": {"field": "properties.mag", "type": "quantitative"}
      }
    }
  ]
}
```

Maybe there is a better way with points but I can't get it to work yet.

**Comment by domoritz** [comment] 2018-01-31 18:50
Size does not work in Vega

```
{
  "$schema": "https://vega.github.io/schema/vega/v3.0.json",
  "autosize": "pad",
  "padding": 5,
  "width": 500,
  "height": 300,
  "style": "cell",
  "data": [
    {
      "name": "source_0",
      "url": "https://unpkg.com/world-atlas@1/world/110m.json",
      "format": {"type": "topojson","feature": "countries"}
    },
    {
      "name": "source_1",
      "url": "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_week.geojson",
      "format": {
        "type": "json",
        "property": "features",
        "parse": {"properties.mag": "number"}
      }
    }
  ],
  "projections": [
    {
      "name": "projection",
      "size": {"signal": "[width, height]"},
      "fit": {"signal": "[data('source_0'), data('source_1')]"},
      "type": "orthographic"
    }
  ],
  "marks": [
    {
      "name": "layer_0_marks",
      "type": "shape",
      "style": ["geoshape"],
      "from": {"data": "source_0"},
      "encode": {
        "update": {
          "fill": {"value": "mintcream"},
          "stroke": {"value": "black"},
          "strokeWidth": {"value": 0.35}
        }
      },
      "transform": [{"type": "geoshape","projection": "projection"}]
    },
    {
      "name": "layer_1_marks",
      "type": "shape",
      "style": ["geoshape"],
      "from": {"data": "source_1"},
      "encode": {
        "update": {
          "size": {"scale": "size","field": "properties.mag"},
          "fill": {"value": "red"},
          "opacity": {"value": 0.25}
        }
      },
      "transform": [{"type": "geoshape","projection": "projection"}]
    }
  ],
  "scales": [
    {
      "name": "size",
      "type": "linear",
      "domain": {"data": "source_1","field": "properties.mag"},
      "range": [10,100],
      "nice": false,
      "zero": false
    }
  ],
  "legends": [
    {
      "size": "size",
      "title": "properties.mag",
      "encode": {"symbols": {"update": {"fill": {"value": "red"}}}}
    }
  ],
  "config": {"axisY": {"minExtent": 30}}
}
```

**Comment by kanitw** [comment] 2018-02-02 17:20
File an issue in a Vega and link to the vega issue? There is nothing we can do here if Vega doesn't support it.

**Comment by domoritz** [comment] 2018-02-04 21:51
In https://github.com/vega/vega/issues/1134

**Comment by kanitw** [comment] 2018-05-09 01:27
Added in Vega 3.1! The geopath and geoshape transforms now support an Expr-valued pointRadius parameter. To see it in action, see the earthquakes example.

**Comment by kanitw** [comment] 2018-05-24 07:04
This is a duplicate of https://github.com/vega/vega-lite/issues/3396

**Closed by kanitw** 2018-05-24 07:04 UTC
Labels: Bug, Good first issue, Help wanted
